import type {Pack,Skill} from './types';
export const vocabulary = 'book 书 · pen 笔 · bag 包 · cup 杯子 · coat 大衣 · ticket 票 · key 钥匙 · map 地图 · phone 手机 · French 法国人 · German 德国人 · Japanese 日本人 · Korean 韩国人 · Chinese 中国人';
type Form = {title:string;listening:string[];reading:{passages:string[];questions:string[];critical:number[]};speaking:string;writing:string};
// Learner-only content. No listening scripts, answer keys or model responses.
export const forms:Record<Pack,Form> = {
 A:{title:'活动签到',listening:['乙承认杯子是自己的吗？','乙说哪件东西是自己的？','第二段的She指谁？','她的国籍是什么？','第三段乙说Pardon的目的是什么？','最后乙确认包是自己的吗？'],reading:{passages:['便签一由Jules写给Lee：This is Remy. He is Korean. This is my pen.','便签二由Kit写给Lee：Is this your book? This is not my bag. This is your bag.'],questions:['被介绍的人是谁？','他的国籍是什么？','应把笔交给谁？','Kit询问的是哪种物品？','Kit承认包是自己的吗？','包应交给谁？'],critical:[2,4,5]},speaking:'你在活动签到台旁，物品均在近处。S1杯子属于另一位来宾，不属于你；S1b手机确实属于你。S2你不确定桌上的书是否属于评阅者。S3你刚找到自己丢的笔，要主动认领。旁边虚构人物Mira明确使用she，已确认是法国人。',writing:'旁边虚构人物Tavi使用he，已确认是日本人；面前的杯子不是你的；面前的包属于读便签的同伴。'},
 B:{title:'代为保管后的交接',listening:['第一段的手机属于说话者还是听话者？','说话者说钥匙属于自己还是听话者？','第二段He指谁？','他的国籍是什么？','第三段Pardon表达什么需要？','最后乙确认笔是自己的吗？'],reading:{passages:['交接对话：Lou对Pat说：“This is my coat.” Pat对Lou说：“This is your coat. This is not my coat.”','接待牌由Faye放在自己旁边：This is Quinn. She is French. Is this your key?'],questions:['大衣最后应交给谁？','Pat承认大衣是自己的吗？','Pat说your时指谁？','牌上被介绍的是谁？','她的国籍是什么？','牌上询问什么物品的归属？'],critical:[0,1,2]},speaking:'你临时代评阅者保管物品，保管不会改变物主。S1你手里的钥匙是评阅者的；S1b杯子确属你。S2另一部手机物主未确认，请问评阅者是不是他的。S3你把评阅者的笔递还给他，说明归属。身边虚构人物Jori使用he，已确认是德国人。',writing:'交接便签里不能把“保管”写成“拥有”：你手里暂存的地图不属于你；桌上那把钥匙是你自己的。介绍旁边虚构人物Ayla，她使用she，已确认是韩国人。'},
 C:{title:'赠送与借用',listening:['第一段钥匙属于谁？','说话者说书属于自己还是听话者？','第二段She指谁？','她的国籍是什么？','第三段乙为什么说Pardon？','最后乙认领地图了吗？'],reading:{passages:['Vic写给Bo：This is not my cup. This is your cup. Is this your phone?','Bo在介绍旁边的人和自己物品：This is Sage. He is German. This is my map.'],questions:['Vic承认杯子是自己的吗？','该把杯子递给谁？','Vic正在确认什么物品？','He指谁？','他的国籍是什么？','地图属于谁？'],critical:[0,1,5]},speaking:'S1评阅者已经明确把一本书赠送给你，现在书属于你；S1b大衣明确属于评阅者，不属于你。S2桌上杯子的物主不明，请向评阅者确认。S3你拿着的包只是借来的，属于评阅者，需交还并说明归属。旁边虚构人物Cleo使用she，已确认是中国人。',writing:'面前的笔只是借来的，不属于你；面前的书已经送给读便签的同伴，因此现在是他的。旁边虚构人物Niko使用he，已确认是法国人。'},
 D:{title:'纠正错误标签',listening:['乙确认票是自己的吗？','乙确认大衣也是自己的吗？','第二段He指谁？','他的国籍是什么？','第三段Pardon的作用是什么？','最后乙认领杯子了吗？'],reading:{passages:['装箱前，Miro写给Sol的核对纸：Is this your bag? This is not my key. This is your key.','Sol在旁边的人物/物品牌：This is Arin. She is Chinese. This is my book.'],questions:['哪种物品仍在询问物主，不能仅凭此纸认定已经归属？','钥匙应放入Miro还是Sol的箱子？','“钥匙是Miro的”这一标签对吗？','She指谁？','她已确认的国籍是什么？','书应交给谁？'],critical:[1,2,5]},speaking:'你正在纠正装箱标签。S1桌上大衣贴着你的名字，但你已核对物主，确定属于评阅者；S1b旁边的笔已核对确属你。S2票的标签已经掉了，你不知道是否属于评阅者，先问他，不能直接认领。S3钥匙原来是评阅者的，但他刚明确送给你，现在请从你的视角说明归属。旁边虚构人物Esme使用she，已确认是日本人；名字不能作为国籍证据。',writing:'给面前同伴一张更正便签，不复制旧标签：旁边虚构人物Lior使用he，已亲口确认是韩国人；名字本身不能判断国籍。手机虽然贴了你的名字，但实际不属于你；票虽然由你拿着，但你只是代同伴保管，票属于这位读者。'},
 E:{title:'维修物品交还',listening:['乙认领包了吗？','乙说哪件是自己的？','She指谁？','她是什么国籍？','Pardon要对方做什么？','最后乙认领手机了吗？'],reading:{passages:['Rae写给Val：This is not my ticket. This is your ticket. Is this your pen?','Val介绍身边的人：This is Ivo. He is Japanese. This is my phone.'],questions:['票属于Rae吗？','票应给谁？','Rae询问什么物品？','He指谁？','他的国籍是什么？','手机属于谁？'],critical:[0,1,5]},speaking:'维修时临时贴签可能错误，以已核对事实为准。S1手机确属你；S1b书是评阅者的；S2钥匙物主不明，向评阅者问归属；S3已修好的地图属于评阅者，交还说明。人物Oona使用she，是法国人。',writing:'人物Rafi使用he，是中国人；面前的大衣不是你的；杯子已经买下，确实属于你。'},
 F:{title:'借出后归还',listening:['书属于说话者还是听话者？','说话者说哪件东西是自己的？','He指谁？','他的国籍是什么？','Pardon表达什么需要？','最后乙认领钥匙了吗？'],reading:{passages:['Uma写给Wren：This is my bag. This is not my book. This is your book.','Wren介绍旁边的人：This is Zia. She is Korean. Is this your coat?'],questions:['包应给谁？','Uma承认书是自己的吗？','书应给谁？','She指谁？','她的国籍是什么？','Wren正在确认什么物品？'],critical:[0,1,2]},speaking:'S1桌上的笔是另一位来宾借给你的，不是你的；S1b大衣明确属于你；S2地图物主不明，问评阅者；S3评阅者刚把原先向你借的书还给你，书仍然属于你，说明归属。人物Ewan使用he，是日本人。',writing:'人物Una使用she，是德国人；桌上的钥匙不属于你；大衣只是暂存在你这里，属于面前读便签的同伴。'}
};
export const speakingActions = ['按已确认事实分别作完整肯定和否定回应','问评阅者S2是否属于他','从你的视角说明S3归属','介绍身旁虚构人物，并用指代说明已确认国籍','新的问话被噪音盖住，你没有听清，请对方重说'];
export function learnerTask(pack:Pack,skill:Skill){const form=forms[pack];return skill==='listening'?form.listening:skill==='reading'?form.reading:skill==='speaking'?form.speaking:form.writing;}
