import type {Bank,MiniItem,MiniTask} from '../content';
const banks:Bank[]=['guided','independent','repair','delayed-a','delayed-b'];
const make=(base:Omit<MiniTask,'items'|'calibration'|'level'>,rows:Omit<MiniItem,'id'|'bank'>[]):MiniTask=>({...base,level:'NCE1 第13–24课已教微技能；难度未校准',calibration:'uncalibrated',items:rows.map((row,i)=>({...row,id:`${base.id}:${banks[i]}`,bank:banks[i]}))});
// Original materials for extracting facts and conveying meaning, not grammar scores.
export const batch02Tasks:readonly MiniTask[]=[
 make({id:'mini-n1-13',courseId:'nce1-13',groupId:'NCE1-13',lessons:[13,14],skill:'listening',track:'common',title:'听物主与颜色，补登记信息',teaching:'先看登记表要求的物主和物品，再听对应颜色；不要填另一个人的颜色或问句中的猜测。same colour=相同颜色；grey/gray=灰色。第14课也出现两种颜色，本题会明说词数。声音是本机合成，真人听感未验；完整播放只记材料接触，文字稿记帮助。'},[
  {material:'Ava: My coat is white. Ben: My coat is black.',prompt:'登记 Ben 的 coat（外套）颜色：____。只写一个英文颜色词。',hint:'两个人都说 my coat；听 Ben 那一条，不填 Ava 的颜色。',reference:'black',accepted:['black'],audio:new URL('./audio/mini-n1-13-guided.wav',import.meta.url).href},
  {material:'Mia: Her dress is yellow. Her hat is the same colour.',prompt:'这里 her 明确指同一位朋友。登记她的 hat（帽子）颜色：____。只写一个英文颜色词。',hint:'帽子与裙子是 same colour，回想已说的裙子颜色。',reference:'yellow',accepted:['yellow'],audio:new URL('./audio/mini-n1-13-independent.wav',import.meta.url).href},
  {material:'Leo: His shirt is white. His tie is the same colour.',prompt:'这里 his 明确指同一位朋友。登记他的 tie（领带）颜色：____。只写一个英文颜色词。',hint:'先听shirt（衬衫）的颜色，再把same colour关联到领带；两件物品颜色相同。',reference:'white',accepted:['white'],audio:new URL('./audio/mini-n1-13-repair.wav',import.meta.url).href},
  {material:'Nora: Is your umbrella red? Sam: No. My umbrella is blue.',prompt:'登记 Sam 的 umbrella（伞）最后确认的颜色：____。只写一个英文颜色词。',hint:'先听 No，再听本人确认；提问中猜的颜色不能当结论。',reference:'blue',accepted:['blue'],audio:new URL('./audio/mini-n1-13-delayed-a.wav',import.meta.url).href},
  {material:'Tia: My hat is grey and black. Jo: My coat is green.',prompt:'登记 Tia 的 hat 两种颜色：____。按说出的顺序写“颜色 and 颜色”，共3个英文词；grey/gray均可。',hint:'只取 Tia 的帽子，两种颜色都要保留，不取 Jo 的 coat。',reference:'grey and black',accepted:['grey and black','gray and black'],audio:new URL('./audio/mini-n1-13-delayed-b.wav',import.meta.url).href},
 ]),
 make({id:'mini-n1-15',courseId:'nce1-15',groupId:'NCE1-15',lessons:[15,16],skill:'reading',track:'common',title:'读两人旅客留言，筛选一条事实',teaching:'这些是原创旅客留言，标头给出两位共同说话者。We/Our指该标头的一组人；not是否定。先按问题找那一组，再取事实，别把邻组或否定中的信息记过去。tourists=游客；cases=箱子；passports=护照；Norwegian=挪威的；Swedish=瑞典的。阅读提取不评自由口语或完整雅思阅读能力。'},[
  {material:'Ava and Ben: We are tourists. Our cases are brown.\nMia and Leo: Our cases are green.',prompt:'哪一组的 cases（箱子）是 brown？照抄该组标头，写“名字 and 名字”，共3个英文词。',hint:'先找到 brown 的留言，Our指同一标头下的两个人。',reference:'Ava and Ben',accepted:['Ava and Ben']},
  {material:'Nora and Sam: We are not Swedish. We are Norwegian.\nTia and Jo: We are Swedish.',prompt:'Nora 和 Sam 实际说明的国籍是 ____。照抄一个英文国籍词；不要填被否认的国籍。',hint:'区分 not 后的否认与随后肯定说明，不取另一组。',reference:'Norwegian',accepted:['Norwegian']},
  {material:'Ken and Kim: These are not our cases. Our cases are blue.\nDan and Eva: Our cases are red.',prompt:'Ken 和 Kim 自己的 cases 颜色是 ____。只写一个英文颜色词。',hint:'These are not our cases 否认眼前那些；随后 Our cases 才确认自己的一组。',reference:'blue',accepted:['blue']},
  {material:'Amy and Max: We are not teachers. We are tourists.\nIvy and Tom: We are teachers.',prompt:'Amy 和 Max 在留言里确认的身份是 ____。照抄一个英文词，保留多人词尾。',hint:'not teachers是否认；找他们之后确认的复数身份词。',reference:'tourists',accepted:['tourists']},
  {material:'Rae and Kai: Our passports are green. Our tickets are yellow.\nMay and Joe: Our passports are blue.',prompt:'Rae 和 Kai 的哪种物品是 yellow？照抄一个英文复数物品词。',hint:'同一组也有两种物品，按颜色选物品，不把护照或邻组颜色混入。',reference:'tickets',accepted:['tickets']},
 ]),
 make({id:'mini-n1-17',courseId:'nce1-17',groupId:'NCE1-17',lessons:[17,18],skill:'speaking',track:'common',title:'口头向来访者介绍两位同事',teaching:'这是原创工作场景信息传达。照明确事实介绍两位同事、说明两人的共同职业，再说明或否认状态。They are + 复数职业，不用a/an；否定要保留not。只选本机录音在本页回放，不上传、不持久保存声音；仅保留元数据，刷新需重新选择。文字备选不记口语独立证据；内容与口语质量待人工。'},[
  {material:'来访者面前是两位同事 Ava 和 Ben。他们共同的职业是 teachers（教师），现在 busy（忙）。',prompt:'口头说3句：用名字介绍这两人，说明共同职业，再说明当前状态。',hint:'This is Ava and this is Ben. They are teachers. They are busy.',reference:'This is Ava and this is Ben. They are teachers. They are busy.',accepted:[]},
  {material:'两位同事 Mia 和 Leo 现在在你身边。两人共同的职业是 engineers（工程师），他们现在并不 busy。',prompt:'口头说3句：介绍两人，说明职业，纠正“他们现在很忙”的说法。不编造原因。',hint:'介绍名字后，They are + 复数职业；最后用 are not/aren’t busy。',reference:"This is Mia and this is Leo. They are engineers. They aren't busy.",accepted:[]},
  {material:'两位同事 Nora 和 Sam 刚来到来访者面前。他们共同的职业是 keyboard operators（键盘操作员），两人现在并不 tired（累）。',prompt:'换两位同事，口头介绍名字和职业，再纠正“他们现在很累”的说法，共3句。',hint:'职业有两个词；两个人用 operators，最后用 are not/aren’t tired 保留否定。',reference:"This is Nora and this is Sam. They are keyboard operators. They aren't tired.",accepted:[]},
  {material:'两位同事 Tia 和 Jo 在你身边。他们共同的职业是 sales reps（销售代表），两人现在并不 tired。',prompt:'口头介绍名字和共同职业，再说明两人“不累”，共3句。不把否定改成肯定。',hint:'sales reps是复数职业；最后一句需保留 not 或 aren’t。',reference:"This is Tia and this is Jo. They are sales reps. They aren't tired.",accepted:[]},
  {material:'两位同事 Ken 和 Kim 已来到来访者面前。他们共同的职业是 mechanics（机械师），两人现在 busy。',prompt:'口头介绍两位同事，说明共同职业和当前状态，共3句。自然等义表达可留待人工核对。',hint:'只说题设的名字、共同职业与状态；不根据名字猜性别。',reference:'This is Ken and this is Kim. They are mechanics. They are busy.',accepted:[]},
 ]),
 make({id:'mini-n1-19',courseId:'nce1-19',groupId:'NCE1-19',lessons:[19,20],skill:'writing',track:'general-training',title:'写简短留言，说明状态与递物对象',teaching:'这是一条日常留言的微型练习，不是完整GT写作Task 1，也不评Band。先让收件人知道谁处于什么状态，再写清把什么交给谁。I用am，we/they用are，she/he用is；Give后用me/him/her/us/them。a cup=一个杯子；an apple=一个苹果；some coats/cups=一些外套/杯子。只据事实写2–3句，允许自然等义表达，内容与写作质量待人工核对；不做Academic图表描述。'},[
  {material:'你和同事在门口等候，两人现在都 cold（冷）。给拿着外套的伙伴留言，说明你们的状态，再请他给你们两人一些 coats（外套）；“我们”包含你自己。',prompt:'写2句英文留言：说明你们的当前状态；请求把指定物品给正确的接收组。可以加please，不编造其他情况。',hint:'We are cold. Give us some coats, please. 状态主语we与递物接收者us指同一组。',reference:'We are cold. Give us some coats, please.',accepted:[]},
  {material:'你未参加步行。Ava和Ben在休息点，他们两人现在 thirsty（渴）。给负责递杯子的伙伴留言，说明这两位第三人的状态，请伙伴给他们一些 cups（杯子）；接收组不包含你。',prompt:'写2句英文留言，让伙伴知道谁处于什么状态、把什么给谁。不要把自己写进这两人的状态或接收组。',hint:'用They are说明第三人共同状态，再用Give them请求递物；保留多件cups。',reference:'They are thirsty. Give them some cups, please.',accepted:[]},
  {material:'你留在柜台。Mia和Leo在门外，他们两人现在 cold（冷）。给负责物品的伙伴留言，说明这两位第三人的状态，请伙伴给他们一些 coats（外套）；你不在这两人中。',prompt:'换一个情境写2句英文留言：报告两位第三人的共同状态，再请求把指定多件物品给他们。',hint:'先核对第三人范围：They are cold。Give后的同一接收组用them，不改成us。',reference:'They are cold. Give them some coats, please.',accepted:[]},
  {material:'Nora明确使用she。她现在 hungry（饿），你自己不饿。给拿着水果篮的伙伴留言，说明Nora的状态，请伙伴给她一个 apple（苹果）。',prompt:'写2句英文留言：说明这位第三人的状态，再请求把单件物品给她。人物代词按题设，不根据名字猜。',hint:'She is说明她的状态；Give后用her，apple前单件用an。',reference:'She is hungry. Give her an apple, please.',accepted:[]},
  {material:'Sam明确使用he。他现在 hot（热），你现在 cold（冷）。给递杯子的伙伴留言，分别说明Sam和你自己的状态，然后请伙伴给Sam一个 cup（杯子）。',prompt:'写3句英文留言：分别报告两个不同的当前状态；最后明确请求给谁一个杯子。不要把两种状态合并成we。',hint:'Sam用He is hot，你用I am cold；递杯请求用Give him a cup。',reference:'He is hot. I am cold. Give him a cup, please.',accepted:[]},
 ]),
 make({id:'mini-n1-21',courseId:'nce1-21',groupId:'NCE1-21',lessons:[21,22],skill:'listening',track:'common',title:'听递物对话，确认所选单件',teaching:'物品管理员需要登记实际选择：Give…a…只请求单件，Which one?追问哪一件；one代替已明确的单件物品。先找到指定请求者，再听选择或更正，不把提问的猜测记成选择。large/small=大/小；clean/dirty=干净/脏；sharp/blunt=锋利/钝；new/old=新/旧；for后说明另一条分配，for me=给我，is for Jo=是给Jo的；knife=刀，box=盒子，cup=杯子，pen=笔。本机合成声未做人试听校准；完整播放记接触，文字稿记帮助。'},[
  {material:'Ava: Give me a box, please. Ben: Which one? Ava: The small one. Ben: The large one is for Jo.',prompt:'登记Ava请求的box尺寸：____。只写一个英文词large或small。',hint:'听Ava对Which one的回答；Ben之后说的是另一位Jo的大盒子。',reference:'small',accepted:['small'],audio:new URL('./audio/mini-n1-21-guided.wav',import.meta.url).href},
  {material:'Mia: Give me a cup, please. Leo: The dirty one? Mia: No. The clean one, please.',prompt:'登记Mia最后选择的cup状态：____。只写一个英文词clean或dirty。',hint:'先听No，再取同一请求者确认的选择；不要填被否认的建议。',reference:'clean',accepted:['clean'],audio:new URL('./audio/mini-n1-21-independent.wav',import.meta.url).href},
  {material:'Nora: Give me a pen, please. Sam: The old one? Nora: No. The new one, please.',prompt:'登记Nora最后选择的pen是哪种：____。只写一个英文词new或old。',hint:'与前题一样先排除问句中的建议，再取No之后确认的单件选择。',reference:'new',accepted:['new'],audio:new URL('./audio/mini-n1-21-repair.wav',import.meta.url).href},
  {material:'Tia: Give him a knife, please. Jo: Which one? Tia: The blunt one. The sharp one is for me.',prompt:'登记Tia要求交给him的knife是哪种：____。只写一个英文词sharp或blunt；不填Tia自己那把。',hint:'Which one之后先说明交给him的钝刀；最后才说明自己的另一把。',reference:'blunt',accepted:['blunt'],audio:new URL('./audio/mini-n1-21-delayed-a.wav',import.meta.url).href},
  {material:'Ken: Give her a box, please. Kim: Which one? Ken: The large one. Give me the small one.',prompt:'登记Ken要求交给her的box尺寸：____。只写一个英文词large或small；区分两位接收者。',hint:'her的large与后来me的small是两件不同的盒子。',reference:'large',accepted:['large'],audio:new URL('./audio/mini-n1-21-delayed-b.wav',import.meta.url).href},
 ]),
 make({id:'mini-n1-23',courseId:'nce1-23',groupId:'NCE1-23',lessons:[23,24],skill:'reading',track:'common',title:'读分发留言，按位置选对一组',teaching:'这些是原创分发留言，每组同类物品至少两件。some与复数表示多件，Which ones?追问哪一组；The ones on the…选择表面上的一组。for me=给说话者自己的一组。先看请求类别和接收人，再读实际选择，排除未选的一组；不改为单件one。shelf=架子，table=桌子，chair=椅子，desk=书桌，floor=地板；cups=杯子，books=书，boxes=盒子，tickets=票，bags=包。阅读筛选事实不等于会独立说或写完整对话。'},[
  {material:'Ava: Give me some cups, please.\nBen: Which cups?\nAva: The ones on the shelf. Not the ones on the table.\n记录说明：两处各有一组多只杯子。',prompt:'给Ava的cups应从哪个表面位置取？只写一个英文地点词：____。',hint:'The ones on the shelf选择架子上的一组；not之后的table是排除项。',reference:'shelf',accepted:['shelf']},
  {material:'Mia: Give him some books, please.\nLeo: Which ones?\nMia: The ones on the desk. The books on the chair are for me.\n记录说明：him是明确的另一位接收人；两处各有一组多本书。',prompt:'给him的books应从哪个表面位置取？只写一个英文地点词；别取给Mia自己的那组：____。',hint:'同类物品有两个接收者；先确认him的选择，再排除for me的椅子组。',reference:'desk',accepted:['desk']},
  {material:'Nora: Give her some boxes, please.\nSam: Which ones?\nNora: The ones on the table. The boxes on the floor are for me.\n记录说明：her是明确的另一位接收人；两处各有一组多个盒子。',prompt:'给her的boxes应从哪个表面位置取？只写一个英文地点词；别取给Nora自己的那组：____。',hint:'与前题一样区分接收者：her取table组；for me是另一组。',reference:'table',accepted:['table']},
  {material:'Tia: Give us some tickets, please.\nJo: Which tickets?\nTia: Not the ones on the desk. The ones on the chair.\n记录说明：us包含Tia和同伴；两处各有一组多张票。',prompt:'Tia和同伴实际要取的tickets放在哪里？只写一个英文地点词：____。',hint:'先排除Not选项，再取肯定选择的位置；不能把us当作只有Tia。',reference:'chair',accepted:['chair']},
  {material:'Ken: Give them some bags, please.\nKim: Which ones?\nKen: The ones on the floor. Give me the ones on the shelf.\n记录说明：them是两位第三人；两处各有一组多个包。',prompt:'给them的bags应从哪个表面位置取？只写一个英文地点词；不填给Ken的那组：____。',hint:'第一次The ones说明them的floor组，第二个请求才是me的shelf组。',reference:'floor',accepted:['floor']},
 ]),
];
