import assert from 'node:assert/strict';
import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=new URL('../../',import.meta.url),work=new URL('work/mini-batch02/',root);await mkdir(work,{recursive:true});
const versions=(await readdir(new URL('node_modules/.pnpm/',root))).filter(n=>/^esbuild@\d+\.\d+\.\d+$/.test(n)).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}));
const {build}=await import(new URL('node_modules/.pnpm/'+versions[0]+'/node_modules/esbuild/lib/main.js',root));
await build({stdin:{contents:`export * from './mini-task/model';export * from './mini-task/content';export * from './mini-task/adapter';export * from './mini-task/manifest';export * from './mini-task/route';export * from './mini-task/batch-02/manifest';export {batch02Tasks} from './mini-task/batch-02/content';export {initial,validateState} from './app/model';export {emptyProgress} from './map/model';export {courseLoopBindings} from './app/course-loop-progress';export {todayPractice} from './app/today-practice';export {parseRoute,routeHash} from './app/navigation';`,resolveDir:fileURLToPath(root),loader:'ts'},bundle:true,platform:'node',format:'esm',target:'node22',outfile:fileURLToPath(new URL('model.mjs',work)),logLevel:'silent'});
const m=await import(new URL('model.mjs',work)),now=Date.now(),checks=[];const check=(name,fn)=>{fn();checks.push(name);console.log('PASS '+name)};
const state=structuredClone(m.initial),map=m.emptyProgress(),loops={};
for(const b of m.courseLoopBindings){let at=now-10*m.DAY,s=b.model.initialState(at),r=b.model.restore(JSON.stringify(s),now);let safety=0;while(r.view.phase!=='own'){assert(++safety<200);const q=b.model.currentQuestion(r.view);let a;if(q){const last=r.view.attempts.at(-1);a=last?.id===q.id&&last.exposure===r.view.exposures.filter(e=>e.id===q.id).length?{type:'next'}:r.view.draft===q.accepted[0]?{type:'submit'}:{type:'draft',value:q.accepted[0]}}else a={type:'next'};r=b.model.transition(s,a,++at);assert(r.ok,r.message);s=r.state}loops[b.id]=s;state.drafts[b.key]=JSON.stringify(s)}
check('batch02 authored identities, explicit paired lessons and exact existing host routes',()=>{assert([3,6].includes(m.batch02Tasks.length));assert.deepEqual(m.batch02Tasks.map(t=>t.skill),['listening','reading','speaking','writing','listening','reading'].slice(0,m.batch02Tasks.length));assert.equal(new Set(m.miniTasks.map(t=>t.id)).size,m.miniTasks.length);assert.deepEqual(m.batch02LessonBindings.map(b=>b.lesson),Array.from({length:m.batch02Tasks.length*2},(_,i)=>i+13));for(const t of m.batch02Tasks){assert.equal(t.items.length,5);assert.equal(new Set(t.items.map(i=>i.material)).size,5);assert.equal(m.parseRoute(m.routeHash({view:'mini-task',miniTaskId:t.id})).miniTaskId,t.id);assert(m.miniPrerequisite(state,t.courseId,now).eligible)}assert(m.batch02LessonBindings.every(b=>b.coverage==='partial-target'&&b.uncovered.length));assert(!m.miniTasks.some(t=>t.track==='academic'))});
check('real CL prerequisite + Today unique priority/read-only + no parallel course mastery',()=>{assert.equal(m.miniPracticeTasks(m.initial,now).length,0);const before=JSON.stringify({state,map});const tasks=m.todayPractice(state,map,now,true);for(const t of m.batch02Tasks){const entries=tasks.filter(x=>x.id==='mini-task:'+t.groupId);assert.equal(entries.length,1);assert.equal(entries[0].priority,3.5)}assert.equal(JSON.stringify({state,map}),before);assert(m.miniPracticeTasks(state,now,false).length===0)});
const finalSnapshots={};
for(const t of m.miniTasks){check(t.id+' original/help/modality/repair/finiteA-B/refresh isolation',()=>{let at=now-9*m.DAY,s=m.initialMini(t.id,at),r=m.restoreMini(JSON.stringify(s),now,t.id);const send=a=>{const n=m.transitionMini(s,a,++at);assert(n.ok,n.message);s=n.snapshot;r=n;assert.deepEqual(m.restoreMini(JSON.stringify(s),now,t.id).view,r.view)};send({type:'next'});for(const bank of ['guided','independent','repair','delayed-a','delayed-b']){if(bank.startsWith('delayed')){assert(!m.transitionMini(s,{type:'review'},r.view.dueAt-1).ok);at=r.view.dueAt;send({type:'review'})}const q=m.itemFor(t.id,r.view);if(t.skill==='listening')send({type:'audio-ended'});if(t.skill==='speaking')send({type:'speech-captured',durationMs:1500,bytes:2000});else send({type:'draft',value:q.accepted[0]||q.reference});const original=structuredClone(r.view.attempts);send({type:'submit'});assert.deepEqual(r.view.attempts.slice(0,-1),original);assert(!m.transitionMini(s,{type:'submit'},at).ok);assert.equal(r.view.attempts.at(-1).independent,bank!=='guided');if(['speaking','writing'].includes(t.skill)){assert.equal(r.view.attempts.at(-1).matched,null);assert.equal(r.view.attempts.at(-1).status,'awaiting-external-review')}send({type:'correction-draft',value:'revision draft',note:'reason draft'});assert.equal(r.view.correctionDraft,'revision draft');send({type:'next'})}assert.equal(r.view.phase,'exhausted');assert.equal(r.view.attempts.length,5);assert(!m.transitionMini(s,{type:'review'},at).ok);const next=m.withMiniSnapshot(state,s,now);for(const b of m.courseLoopBindings)assert.equal(next.drafts[b.key],state.drafts[b.key]);for(const field of ['cards','scores','completed','attempts','correct','mistakes'])assert.deepEqual(next[field],state[field]);assert(!m.miniPracticeTasks(next,now).some(x=>x.id==='mini-task:'+t.groupId));finalSnapshots[t.id]=s;
let helped=m.initialMini(t.id,now-10),v=m.transitionMini(helped,{type:'next'},now-9);helped=v.snapshot;if(t.skill==='listening')v=m.transitionMini(helped,{type:'text-mode'},now-8);else if(t.skill==='speaking')v=m.transitionMini(helped,{type:'text-mode'},now-8);else v=m.transitionMini(helped,{type:'help'},now-8);assert(v.ok);v=m.transitionMini(v.snapshot,{type:'draft',value:t.items[0].accepted[0]||t.items[0].reference},now-7);v=m.transitionMini(v.snapshot,{type:'submit'},now-6);assert(v.ok);assert.equal(v.view.attempts[0].independent,false);if(['speaking','listening'].includes(t.skill))assert.equal(v.view.attempts[0].modality,'text');for(const bad of [{...s,taskId:'mini-n1-99'},{...s,contentVersion:99},{...s,events:[{type:'award-band',at:now}]}]){const raw=JSON.stringify(bad),p=m.restoreMini(raw,now,t.id);assert(!p.ok);assert.equal(p.raw,raw)}})}
const packet={schemaVersion:1,inputScope:'No hints, references, accepted keys or model supplied. Text only; no human acoustic audit.',items:m.batch02Tasks.flatMap(t=>t.items.map(q=>({id:q.id,skill:t.skill,track:t.track,lessons:t.lessons,material:q.material,prompt:q.prompt})))};
await writeFile(new URL('mini-task/batch-02/blind-packet.json',root),JSON.stringify(packet,null,2)+'\n');await writeFile(new URL('fixtures.json',work),JSON.stringify({state,map,loops,finalSnapshots},null,2)+'\n');await writeFile(new URL('model-results.json',work),JSON.stringify({checks,count:checks.length,syntheticDates:true,naturalDelayVerified:false},null,2)+'\n');console.log('PASS '+checks.length+' first-six + batch02 model/host groups');
