import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {productionHost} from '../batch-01/production-test-binding.mjs';
const root=new URL('../../',import.meta.url),assets=new URL('dist-online/',root),json=async u=>JSON.parse(await readFile(u,'utf8')),sha=x=>createHash('sha256').update(x).digest('hex');
const names=(await readdir(new URL('.',import.meta.url))).filter(n=>/^lesson-nce1-\d+\.mjs$/.test(n)&&(!process.env.NCE_IDS||process.env.NCE_IDS.split(',').map(Number).includes(Number(n.match(/(\d+)\.mjs/)[1])))).sort(),contents=await Promise.all(names.map(n=>import('./'+n)));
assert.ok(contents.length,'no authored modules selected');if(process.env.NCE_IDS)assert.equal(contents.length,new Set(process.env.NCE_IDS.split(',').map(Number)).size);
const [ui,manifest,index,comics,pages,grammar,gindex,pindex,host]=await Promise.all([readFile(new URL('app/course-loop-ui.tsx',root),'utf8'),json(new URL('materials/manifest.json',assets)),json(new URL('language/index.json',assets)),json(new URL('app/data/nce-illustrations.json',root)),json(new URL('app/data/nce-pages.json',root)),json(new URL('app/data/textbook-grammar.json',root)),json(new URL('grammar/index.json',assets)),json(new URL('lesson-pages/index.json',assets)),productionHost()]);
const panel=ui.slice(ui.indexOf('function SourcePanel(')),match=[...panel.matchAll(/const valid=([^;]+);setLanguage\(valid\?result:null\)/g)];assert.equal(match.length,1);const accepts=new Function('result','lesson','first',`return (${match[0][1]});`);
const records=[];
for(const c of contents)test(c.lesson.id+' real transcript LRC, source panel, comic and paired exercise pages',async()=>{
 const {lesson}=c,n=lesson.lessons[0],path=`language/NCE1/${n}.json`,bytes=await readFile(new URL(path,assets)),language=JSON.parse(bytes),lrc=manifest.files.filter(f=>f.book==='NCE1'&&f.lesson===n&&f.textFormat==='lrc'&&f.sha256===language.sourceSha256);assert.equal(lrc.length,1);
 assert.equal(lesson.source.languageSha256,language.sourceSha256);assert.equal(lesson.source.sourceSha256,language.sourceSha256);assert.notEqual(sha(bytes),language.sourceSha256);assert.equal(index.files[`NCE1/${n}.json`].sha256,sha(bytes));
 const original=Buffer.concat(await Promise.all(lrc[0].parts.map(p=>readFile(new URL(p.path.slice(1),assets)))));assert.equal(sha(original),language.sourceSha256);assert.equal(original.length,lrc[0].size);assert.equal(accepts(language,lesson,n),true);
 for(const wrong of [null,{...language,book:'NCE2'},{...language,lesson:n+1},{...language,sourceSha256:sha(bytes)},{...language,sourceSha256:'0'.repeat(64)}])assert.equal(!!accepts(wrong,lesson,n),false);
 const comic=comics.lessons[`NCE1-${n}`],rows=host.splitLesson(language.rows,'NCE1',true).body;assert.equal(comic.sourceSha256,language.sourceSha256);assert.equal(comics.sources.NCE1,pages.NCE1.sourceSha256);assert.deepEqual(host.lessonIllustration('NCE1',n,language.sourceSha256,rows.length),comic);assert.equal(host.lessonIllustration('NCE1',n,sha(bytes),rows.length),null);assert.equal(host.lessonIllustration('NCE1',n,language.sourceSha256,rows.length+1),null);
 const image=await readFile(new URL(`lesson-pages/${comic.pageSha256}.jpg`,assets));assert.equal(sha(image),comic.pageSha256);
 const entry=grammar.entries.find(e=>e.id===`NCE1-${n}`);assert.ok(entry);assert.equal(entry.lastLesson,n+1);const exercisePages=[];for(const p of entry.pages){const page=gindex.pages[`NCE1-${p}`];assert.ok(page);assert.equal(sha(await readFile(new URL(page.src.slice(1),assets))),page.sha256);exercisePages.push({page:p,sha256:page.sha256})}
 const paired=lesson.source.pairedExercise;if(paired){assert.equal(paired.entryId,entry.id);assert.deepEqual(paired.lessons,lesson.lessons);const ps=paired.pages||paired.catalogPages||[paired.page??Number(paired.pageKey.split('-').at(-1))];if(paired.pageKey)assert.ok(ps.includes(Number(paired.pageKey.split('-').at(-1))));for(const p of ps){assert.ok(entry.pages.includes(p));const actual=gindex.pages[`NCE1-${p}`];assert.ok(actual);if(paired.page===p){assert.equal(paired.path,actual.src);assert.equal(paired.sha256,actual.sha256);}}}
 for(const p of lesson.source.grammarPages||[]){assert.ok(entry.pages.includes(Number(p.pageKey.split('-').at(-1))));const actual=gindex.pages[p.pageKey];assert.ok(actual);assert.equal(p.src,actual.src);assert.equal(p.sha256,actual.sha256);assert.equal(sha(await readFile(new URL(p.src.slice(1),assets))),p.sha256);}
 for(const p of lesson.source.comicPages||[]){assert.ok(p.page>=pages.NCE1.starts[String(n)]&&p.page<pages.NCE1.starts[String(n+1)]);const actual=pindex.lessons[`NCE1-${n}`].pages.find(x=>x.page===p.page);assert.ok(actual);assert.equal(p.src,actual.src);assert.equal(p.sha256,actual.sha256);assert.equal(sha(await readFile(new URL(p.src.slice(1),assets))),p.sha256);}
 for(const clip of lesson.source.clips){assert.ok(lesson.teaching.some(t=>t.target===clip.target));assert.ok(clip.start>=language.rows[0].time&&clip.end>clip.start&&clip.start<=lrc[0].lastTimestamp);assert.ok(language.rows.some(r=>Math.abs(r.time-clip.start)<0.001));}
 records.push({id:lesson.id,sourceSha256:language.sourceSha256,languageFileSha256:sha(bytes),pdfSourceSha256:pages.NCE1.sourceSha256,comicPageSha256:comic.pageSha256,grammarEntry:entry,exercisePages,sourcePanel:'actual unchanged guard accepts real source',playback:'not-audited'});
});
test('every cross-course SourcePanel pair rejects',async()=>{const langs=await Promise.all(contents.map(c=>json(new URL(`language/NCE1/${c.lesson.lessons[0]}.json`,assets))));for(let a=0;a<contents.length;a++)for(let b=0;b<contents.length;b++)assert.equal(accepts(langs[b],contents[a].lesson,contents[a].lesson.lessons[0]),a===b)});
if(process.env.NCE_WRITE_SOURCE_EVIDENCE){test('record verified source evidence',async()=>{assert.equal(records.length,contents.length);const {writeFile}=await import('node:fs/promises');await writeFile(new URL('../../docs/parallel-nce1-121-131/source-evidence.json',import.meta.url),JSON.stringify({baseline:'7b7c1283d12f0c6d784478cda8353080598f6980',remoteHeads:'7b7c1283d12f0c6d784478cda8353080598f6980',groups:records,naturalRetention:'unverified',audioPlayback:'not-audited'},null,2)+'\n')})}
for(const c of contents)test(c.lesson.id+' existing original audio parts match manifest (integrity, not hearing)',async()=>{const n=c.lesson.lessons[0],a=manifest.files.filter(f=>f.book==='NCE1'&&f.lesson===n&&f.type==='audio/mpeg');assert.equal(a.length,1);const parts=await Promise.all(a[0].parts.map(p=>readFile(new URL(p.path.slice(1),assets))));for(let i=0;i<parts.length;i++)if(a[0].parts[i].sha256)assert.equal(sha(parts[i]),a[0].parts[i].sha256);const bytes=Buffer.concat(parts);assert.equal(bytes.length,a[0].size);assert.equal(sha(bytes),a[0].sha256)});
