import type {Bank,MiniItem,MiniTask} from '../content';
const banks:Bank[]=['guided','independent','repair','delayed-a','delayed-b'];
const make=(base:Omit<MiniTask,'items'|'calibration'|'level'>,rows:Omit<MiniItem,'id'|'bank'>[]):MiniTask=>({...base,level:'NCE1 第49–60课部分已教微目标；难度未校准',calibration:'uncalibrated',items:rows.map((row,i)=>({...row,id:`${base.id}:${banks[i]}`,bank:banks[i]}))});
export const batch05Tasks:readonly MiniTask[]=[
 make({"id": "mini-n1-49", "courseId": "nce1-49", "groupId": "NCE1-49", "lessons": [49, 50], "skill": "listening", "track": "common", "title": "听喜好交接，为共享水果盘核对条件", "teaching": "like/likes报告喜好；does not like否定指定人的喜好，不能移给另一个人。but后的doesn’t可省略已知重复动作，仍跟着新主语。听共享水果盘要分别核对两人的明确喜好，不把“我喜欢”当成所有人喜欢。pears梨，grapes葡萄，peaches桃，apples苹果，bananas香蕉。这里只核对受控听力事实，不证明已点单或食物适合健康需求。本机既有合成声未人工试听，文字稿算帮助，难度未校准。"},[
  {"material": "Sam likes pears, but Rae does not. Rae likes apples.", "prompt": "登记谁明确喜欢pears，只写A/B/C：A Rae；B Sam；C 两人都喜欢。", "hint": "does not省略like pears，否定的是Rae，不是Sam。", "reference": "B — Sam", "accepted": ["B"], "audio": new URL('./audio/mini-n1-49-guided.wav',import.meta.url).href},
  {"material": "Jo likes apples and pears. Rae likes pears, but she does not like apples. Jo does not like grapes.", "prompt": "水果盘先选两人都明确喜欢的一种，不猜其他需求。只写A/B/C：A apples；B pears；C grapes。", "hint": "分别确认Jo和Rae；只出现一个人的喜欢不够，两人共同支持的是哪项？", "reference": "B — pears", "accepted": ["B"], "audio": new URL('./audio/mini-n1-49-independent.wav',import.meta.url).href},
  {"material": "Sam: Ken likes peaches and grapes. Mia: Does Ken like peaches? Sam: Yes, he does. Mia: I do not. I like grapes. Sam: Ken does not like bananas.", "prompt": "换新交接，为Ken和Mia的共有水果盘选两人都明确喜欢的一种。只写A/B/C：A peaches；B bananas；C grapes。", "hint": "同样分别核对两人，保留but后的否定范围，不沿用上一盘水果。", "reference": "C — grapes", "accepted": ["C"], "audio": new URL('./audio/mini-n1-49-repair.wav',import.meta.url).href},
  {"material": "Ava: Does Leo like apples? Ben: No, he does not. He likes pears. Ava: Does Nora like pears? Ben: I do not know.", "prompt": "给协调员只传已确认的喜好。只写A/B/C：A Leo喜欢pears，Nora是否喜欢pears未确认；B Leo和Nora都喜欢pears；C Leo喜欢apples。", "hint": "No明确否定Leo的apples；I do not know不是Nora不喜欢。", "reference": "A — Leo likes pears; Nora unconfirmed", "accepted": ["A"], "audio": new URL('./audio/mini-n1-49-delayed-a.wav',import.meta.url).href},
  {"material": "Nora: I like grapes. Sam likes pears, but I do not. Rae: Does Sam like grapes? Nora: Yes, he does.", "prompt": "共享盘要用两位已确认都喜欢的水果。只写A/B/C：A Nora和Sam都喜欢pears；B Nora和Sam都喜欢grapes；C Rae和Sam都喜欢grapes。", "hint": "I do not接pears，不接首句grapes；末尾Yes确认Sam的grapes，Rae未报告自己喜好。", "reference": "B — Nora and Sam like grapes", "accepted": ["B"], "audio": new URL('./audio/mini-n1-49-delayed-b.wav',import.meta.url).href},
 ]),
 make({"id": "mini-n1-51", "courseId": "nce1-51", "groupId": "NCE1-51", "lessons": [51, 52], "skill": "reading", "track": "common", "title": "读虚构欢迎卡，核对来源与气候频率", "teaching": "这些都是虚构访客与地区卡，不是今日天气或真实国家气候建议。come/comes from报告卡上明确来源；国籍标签不是来源问题的已知答案。It is often cold用形容词；It sometimes rains用天气动作。always总是，often经常，sometimes有时；不能把经常/有时升级成每天保证。spring春天，summer夏天，winter冬天，May五月，October十月，snow下雪，windy有风。受控阅读事实核对，不评完整雅思阅读或实际旅行规划。"},[
  {"material": "虚构欢迎卡\nRina comes from Italy.\nIn this story, it is often cold in winter. It sometimes rains in May.", "prompt": "哪条卡片摘要保留来源和频率？只写A/B/C：A 来自Italy；冬天经常冷；B 来自Italy；冬天保证每天冷；C 来自May。", "hint": "comes from的地点和often的强度分别保留，月份不是访客来源。", "reference": "A — Italy; often cold in winter", "accepted": ["A"]},
  {"material": "虚构访客资料\nAva comes from Norway. Leo comes from Spain.\nAva的地区介绍：It is sometimes warm in May. It often rains in May.", "prompt": "为Ava核对欢迎短讯，哪条有依据？只写A/B/C：A 来自Spain；五月总是暖；B 来自Norway；五月有时暖，不能保证晴天；C 来自Norway；五月不会下雨。", "hint": "锁定Ava的来源与地区；sometimes/often不支持always或从不下雨。", "reference": "B — Norway; sometimes warm, rain possible", "accepted": ["B"]},
  {"material": "虚构欢迎资料更正\n协调员旧登记：Ben来源France；气候尚未填写。\nBen: I do not come from France. I come from Sweden.\nBen补充的地区卡：It often snows in winter. It is sometimes windy in October.", "prompt": "为Ben核对欢迎短讯，哪条有依据？只写A/B/C：A 来自France；十月总是有风；B 来自Sweden；冬天不会下雪；C 来自Sweden；十月有时有风，不能保证无雪的冬天。", "hint": "同样锁定指定访客与频率；often snows不支持无雪保证。", "reference": "C — Sweden; sometimes windy, winter snow possible", "accepted": ["C"]},
  {"material": "会面资料未填完\nMia: I am French.\n来源／comes from: 未填写，尚未询问。\n虚构场地介绍：It is often warm in spring.", "prompt": "协调员要确认Mia来自哪里。哪条处理忠于资料？只写A/B/C：A 直接填France；B 直接填spring；C 保留来源未知，询问Where does Mia come from?。", "hint": "国籍标签和场地天气不是已经填好的来源回答；对缺项提问。", "reference": "C — ask where Mia comes from", "accepted": ["C"]},
  {"material": "虚构接待记录\nJo comes from Brazil. Rae comes from Norway.\nJo的地区：It is always hot in summer. It sometimes rains in winter.\nRae的地区：It is often cold in winter.", "prompt": "只给Jo写来源与winter摘要，哪条正确？只写A/B/C：A 来自Brazil；winter有时下雨；B 来自Norway；winter经常冷；C 来自Brazil；winter总是热。", "hint": "不要把另一访客的winter或本人的summer移入指定摘要。", "reference": "A — Brazil; sometimes rains in winter", "accepted": ["A"]},
 ]),
 make({"id": "mini-n1-53", "courseId": "nce1-53", "groupId": "NCE1-53", "lessons": [53, 54], "skill": "speaking", "track": "common", "title": "口头澄清日常规律，问清尚未确认的动作", "teaching": "日常规律不是当前画面。单个人肯定动词-s/-es；Does疑问和does not否定后用原形。does not…early只否定“早做”，不证明“晚做”。给接手人报告已有事实、询问缺项，不能替未知规律作答。open/shut打开/关闭，gate大门，read letters读信，wash dishes洗碗，early早，late晚，at night夜间，in the evening傍晚。开放口语自然表达待人工，不按模板给分；本机音频只在本页回放，不上传、不持久保存，刷新重选。文字备选不算独立口语。"},[
  {"material": "管理员Jo明确用she。确认的日常规律：她不早开大门。她是否在夜间关大门还没有问。你向接手人交接。", "prompt": "口头说2句：报告已确认的否定规律，再询问Jo夜间是否关大门。不要把“不早开”改成“晚开”。", "hint": "She does not open the gate early. Does Jo shut the gate at night?", "reference": "She does not open the gate early. Does Jo shut the gate at night?", "accepted": []},
  {"material": "伙伴Ben明确用he。确认的规律：他在夜间不读letters。是否在早上打开box尚未确认，接手人知道他的习惯。", "prompt": "口头向接手人说2句：报告已确认的否定规律，保留时间和物品；再询问早上那项未知规律。不猜改成读别的东西或晚点读。", "hint": "先保留does not read letters at night，再用Does Ben open the box in the morning?问缺项。", "reference": "He does not read letters at night. Does Ben open the box in the morning?", "accepted": []},
  {"material": "接手人误传：Nora（she）每天夜间洗dishes。你已核实：她的夜间规律并不洗dishes。是否在早上关闭window尚未问，接手人可以确认。你需要当面纠正误传并补问缺项。", "prompt": "当面口头说2句澄清：先纠正夜间洗碗的错误规律，再询问早上关窗的缺项。保留日常否定，不把不洗碗说成不会洗碗。", "hint": "同样用does not +原形报告夜间规律，用Does Nora shut the window in the morning?问缺项。", "reference": "She does not wash the dishes at night. Does Nora shut the window in the morning?", "accepted": []},
  {"material": "联络员Sam明确用he。伙伴只知道Sam不在傍晚看television；是否在傍晚读book未确认。你要澄清，不给两项互为相反的错误保证。", "prompt": "口头说2句：保留已确认的否定规律，并询问另一项动作。不要因为不看电视就断言他看书。", "hint": "He does not watch television in the evening. Does Sam read a book in the evening?", "reference": "He does not watch television in the evening. Does Sam read a book in the evening?", "accepted": []},
  {"material": "早间开门安排：Ava明确用she，日常早开door；Leo明确用he，日常不早开door。Leo是否在夜间关door还没问。", "prompt": "口头向协调员说3句：分别报告两人的不同规律，再询问Leo的未知夜间动作。不把“不早”说成“晚”。", "hint": "Ava opens the door early. Leo does not open the door early. Does Leo shut the door at night?", "reference": "Ava opens the door early. Leo does not open the door early. Does Leo shut the door at night?", "accepted": []},
 ]),
 make({"id": "mini-n1-55", "courseId": "nce1-55", "groupId": "NCE1-55", "lessons": [55, 56], "skill": "writing", "track": "general-training", "title": "写作息联络便签，保留频率并问活动缺项", "teaching": "这是GT日常联络起步短讯，不是完整Task1，没有Academic图表或Band。把已确认作息告诉协调员，并用What does…do…?或What do…do…?问未知活动。always总是，usually通常，often经常，sometimes有时；不能把usually说成always。主语决定动词-s/-es，不由物品数量决定。at noon中午，at night夜间，in the afternoon下午；every day每天不加in/at。不同自然表达待人工核对，不自动评分。"},[
  {"material": "协调员问起Jo（she）的作息。已核实：她usually在中午吃lunch。她下午做什么还未问，协调员可以确认。", "prompt": "写2句英文联络短讯：转达已知作息与频率，再问她下午通常做什么。不给未知活动编答案。", "hint": "She usually eats her lunch at noon. What does she do in the afternoon?", "reference": "She usually eats her lunch at noon. What does she do in the afternoon?", "accepted": []},
  {"material": "收件处协调员需要一条作息信息和一个待问问题。Ben（he）often在早上洗cups；Ben夜间做什么尚未确认。不是他此刻的画面。", "prompt": "写2句英文便签：报告已核实的早间习惯，保留often和cups；询问他夜间做什么。不要升级为每天保证或现在正在洗。", "hint": "He often washes cups in the morning. What does he do at night?", "reference": "He often washes cups in the morning. What does he do at night?", "accepted": []},
  {"material": "协调员旧便签：Nora（she）always在早上洗cups。Nora的新确认：她often在早上读letters；夜间活动还未问。你需要更新旧便签，并请协调员补问夜间作息。这是日常规律，不是当前画面。", "prompt": "写2句替换错误便签的短讯：用新确认更新早间动作和频率，再问夜间活动。不保留旧的洗杯子或always保证。", "hint": "同样保留指定人物、频率、物品与时段；问句用What does she do at night?。", "reference": "She often reads letters in the morning. What does she do at night?", "accepted": []},
  {"material": "清理组是Ava和Rae（they），两人usually在下午清理table。协调员还没问两人在中午做什么。人数和一张桌子不要混淆。", "prompt": "写2句联络便签：报告已知的两人作息与通常频率，再问两人中午做什么。无需写精确时钟。", "hint": "They usually clean the table in the afternoon. What do they do at noon?", "reference": "They usually clean the table in the afternoon. What do they do at noon?", "accepted": []},
  {"material": "家庭作息确认：Jo（she）always在傍晚洗dishes；Sam（he）sometimes在傍晚看television。Jo下午活动未确认。协调员要两条已知信息和一个待问问题。", "prompt": "写3句英文短讯：分别保留两人频率与活动，再问Jo下午做什么。不把sometimes说成总是。", "hint": "Jo always washes the dishes in the evening. Sam sometimes watches television in the evening. What does Jo do in the afternoon?", "reference": "Jo always washes the dishes in the evening. Sam sometimes watches television in the evening. What does Jo do in the afternoon?", "accepted": []},
 ]),
 make({"id": "mini-n1-57", "courseId": "nce1-57", "groupId": "NCE1-57", "lessons": [57, 58], "skill": "listening", "track": "common", "title": "听现场更新，定位此刻而非照搬平常", "teaching": "usually/every day说平常规律；明确now/at the moment的进行时说此刻画面。today单独出现不保证动作正在发生，本题另有明确现场证据。not doing表示现在没在做，不证明不会或永远不做。by car乘车，on foot步行，garden花园，living room起居室，park公园；washing/reading/drinking是正在洗/读/喝。只核对受控当前事实，不评完整听力；本机合成声未人工试听，文字稿记帮助。"},[
  {"material": "Jo usually drinks tea in the living room. At the moment, she is drinking tea in the garden.", "prompt": "同伴此刻找Jo，应登记哪处已确认位置？只写A/B/C：A living room；B garden；C 未说明。", "hint": "usually不是此刻；at the moment明确garden的当前画面。", "reference": "B — garden", "accepted": ["B"], "audio": new URL('./audio/mini-n1-57-guided.wav',import.meta.url).href},
  {"material": "Rae: What are the students doing now? Jo: They usually go to school by car. But now they are going on foot. The teachers are going by bus.", "prompt": "给学生组的此刻交通联络表选一项，排除平常方式和另一组：A by car；B by bus；C on foot。只写A/B/C。", "hint": "明确now指学生此刻on foot；bus是teachers，car是学生平常。", "reference": "C — on foot", "accepted": ["C"], "audio": new URL('./audio/mini-n1-57-independent.wav',import.meta.url).href},
  {"material": "Sam: What are the visitors doing now? Nora: They usually go to the park by bus. But now they are going on foot. The guides are going by car.", "prompt": "新口播为访客组登记此刻方式，不是平常或另一组。只写A/B/C：A on foot；B by car；C by bus。", "hint": "同样根据指定组与now；guides的car不能移给visitors。", "reference": "A — on foot", "accepted": ["A"], "audio": new URL('./audio/mini-n1-57-repair.wav',import.meta.url).href},
  {"material": "Ben usually reads letters at night. Jo: Is he reading letters now? Rae: No. At the moment, he is washing the cups.", "prompt": "现场交接哪条只报告已知事实？只写A/B/C：A Ben现在读信；B Ben不会读信；C Ben现在洗杯子，没有在读信。", "hint": "No否定的是当下reading，不是读信能力或长期习惯。", "reference": "C — washing cups now, not reading letters", "accepted": ["C"], "audio": new URL('./audio/mini-n1-57-delayed-a.wav',import.meta.url).href},
  {"material": "Ava: Nora usually plays in the garden. Sam: What is she doing now? Ava: I do not know. Leo is reading in the garden now.", "prompt": "同伴要找Nora当前活动。只写A/B/C：A 已知她正在garden玩；B 当前活动未确认，需要继续询问；C 她现在正在读书。", "hint": "habit不是现场证据；I do not know保留未知，Leo的当前动作不属于Nora。", "reference": "B — Nora current activity unknown", "accepted": ["B"], "audio": new URL('./audio/mini-n1-57-delayed-b.wav',import.meta.url).href},
 ]),
 make({"id": "mini-n1-59", "courseId": "nce1-59", "groupId": "NCE1-59", "lessons": [59, 60], "skill": "reading", "track": "common", "title": "读补给库存，核对整组条件与替代边界", "teaching": "Do you have any…?询问未知库存，We do not have any…报告已核实没有，We have some…报告有。可数物一批用cups/boxes/pencils复数；未分份milk/soap/glue/ink/writing paper不可数原形。some不说明足够数量，库存也不证明已购买。替代必须按题设许可，不自作主张；本题先核类别，精确数量仍需另核。size尺寸，small小，large大。受控阅读信息决策，不评完整雅思阅读或实际采购完成。"},[
  {"material": "店铺回复\nWe don’t have any grapes, but we have some bananas.\n顾客只问grapes库存，未答应替换。", "prompt": "哪条回传忠于回复？只写A/B/C：A grapes有货；B grapes无货，bananas有货但尚未同意替换；C 顾客已买bananas。", "hint": "but后是现有替代，不是顾客已接受或购买。", "reference": "B — no grapes; bananas available, substitution unaccepted", "accepted": ["B"]},
  {"material": "补给要求：cups或plates任一种，再加soap；尺寸不限，具体数量还要点清。\n店铺卡：We don’t have any cups. We have some plates and some soap. We have some ink.", "prompt": "哪组已满足类别条件，可以继续核对数量？只写A/B/C：A cups+soap；B plates+ink；C plates+soap。不能说数量已足够或已购买。", "hint": "两项要求同时核对：允许plates替代cups，但必需soap不能换成ink。", "reference": "C — plates and soap; quantity still unconfirmed", "accepted": ["C"]},
  {"material": "整理要求：boxes或bags任一种，再加glue；尺寸不限，具体数量还要点清。\n店铺卡：We don’t have any boxes. We have some bags and some glue. We have some writing paper.", "prompt": "新任务哪组满足类别条件，可继续核对数量？只写A/B/C：A bags+glue；B boxes+glue；C bags+writing paper。不要声称已购或足量。", "hint": "同样核对允许替代的一项和不能缺的另一项，writing paper不能代替glue。", "reference": "A — bags and glue; quantity still unconfirmed", "accepted": ["A"]},
  {"material": "需要small box；未同意large替代。\n店铺回复：We don’t have any small boxes. We only have large ones. Do you want one?\n顾客回复：No, thank you.", "prompt": "回传结果哪条准确？只写A/B/C：A small box有货；B 接受large box；C small box无货，large替代已拒绝，未确认购买。", "hint": "only说明仅有large；No是拒绝替代，不是购买确认。", "reference": "C — small unavailable; large substitute declined", "accepted": ["C"]},
  {"material": "一次只从一个店铺领货，需pencils和writing paper两类；数量另核。\n店A：We have some pencils. We don’t have any writing paper.\n店B：We have some pencils and some writing paper.", "prompt": "哪个店的已知库存支持两类一起继续核数量？只写A/B/C：A 店A；B 店B；C 两店都支持。不把两店库存拼成一个店，也不猜精确数量。", "hint": "分别核每一家是否同时有两项，不能拿店B纸补进店A的回答。", "reference": "B — shop B; both categories, quantity still unconfirmed", "accepted": ["B"]},
 ]),
];
