// Native Chrome against actual final packages; synthetic owned profile only.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdir,readdir,rename} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=new URL('../../',import.meta.url),run=new URL(`work/mini-batch05/newuser-${Date.now()}/`,root),origin='http://127.0.0.1:5202';
await mkdir(new URL('downloads/',run),{recursive:true});const profile=fileURLToPath(new URL('chrome-profile/',run));
const chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--autoplay-policy=no-user-gesture-required','--mute-audio','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});
const checks=[],errors=[],requests=[];let page,browser,missing;
class CDP{
 constructor(socket){this.socket=socket;this.seq=0;this.navSeq=0;this.pending=new Map();socket.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=this.pending.get(m.id);if(p){this.pending.delete(m.id);clearTimeout(p.timer);if(m.error)p.reject(Error(JSON.stringify(m.error)));else p.resolve(m.result)}}if(m.method==='Page.frameNavigated'&&!m.params.frame.parentId)this.navSeq++;if(m.method==='Page.javascriptDialogOpening')void this.send('Page.handleJavaScriptDialog',{accept:true});if(m.method==='Runtime.exceptionThrown')errors.push(m.params);if(m.method==='Network.requestWillBeSent')requests.push(m.params.request.url)})}
 static async connect(url){const socket=new WebSocket(url);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true})});return new CDP(socket)}
 send(method,params={}){const id=++this.seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('CDP timeout '+method)),12000);this.pending.set(id,{resolve,reject,timer});this.socket.send(JSON.stringify({id,method,params}))})}
 async eval(fn,arg){const r=await this.send('Runtime.evaluate',{expression:`(${fn.toString()})(${JSON.stringify(arg)})`,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
 async wait(fn,arg,label){for(let i=0;i<120;i++){if((await this.send('Runtime.evaluate',{expression:`!!((${fn.toString()})(${JSON.stringify(arg)}))`,returnByValue:true})).result.value)return;await new Promise(r=>setTimeout(r,100))}throw Error('Timeout '+label)}
 async click(text){await this.wait(text=>{const b=[...document.querySelectorAll('button,a[href]')].find(b=>b.textContent===text);return b&&!b.disabled},text,text);const point=await this.eval(text=>{const b=[...document.querySelectorAll('button,a[href]')].find(b=>b.textContent===text);b.scrollIntoView({block:'center'});const r=b.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}},text);await this.send('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',clickCount:1});await this.send('Input.dispatchMouseEvent',{type:'mouseReleased',...point,button:'left',clickCount:1})}
}
try{
 let active;for(let i=0;i<100;i++){try{active=(await readFile(profile+'/DevToolsActivePort','utf8')).trim().split('\n');break}catch{await new Promise(r=>setTimeout(r,100))}}assert(active);browser=await CDP.connect(`ws://127.0.0.1:${active[0]}${active[1]}`);await browser.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:fileURLToPath(new URL('downloads/',run)),eventsEnabled:true});const {targetId}=await browser.send('Target.createTarget',{url:origin+'/map/'});const list=await fetch(`http://127.0.0.1:${active[0]}/json/list`).then(r=>r.json());page=await CDP.connect(list.find(t=>t.id===targetId).webSocketDebuggerUrl);await page.send('Page.enable');await page.send('Runtime.enable');await page.send('Network.enable');await page.send('Network.setCacheDisabled',{cacheDisabled:true});await page.wait(()=>document.readyState==='complete'&&document.querySelector('main'),null,'normal map');
 await page.send('Page.navigate',{url:origin+'/#/today'});await page.wait(()=>document.querySelector('.today-start'),null,'empty new-user Today');
 const before=await page.eval(()=>({href:document.querySelector('.today-start').getAttribute('href'),text:document.querySelector('.today-start').textContent,miniLinks:[...document.querySelectorAll('a[href]')].filter(a=>a.getAttribute('href').includes('/mini-task/')).length,raw:localStorage.getItem('english-studio-v1')}));
 assert(before.href.startsWith('/map/#/learn/'));assert.equal(before.miniLinks,0);assert(!before.href.includes('placement'));if(before.raw)assert(!Object.keys(JSON.parse(before.raw).drafts).some(k=>k.startsWith('english-mini-task-v1:')));
 await page.click(before.text);await page.wait(()=>location.hash.startsWith('#/learn/')&&document.querySelector('main'),null,'actual warmup/course landing');const after=await page.eval(()=>({href:location.href,text:document.querySelector('main').innerText}));assert(!after.href.includes('placement'));assert(after.text.length>10);
 const receipt={before:{...before,raw:undefined},after:{href:after.href,visibleTextLength:after.text.length},checks:['empty Today leads to actual main course/warmup','no premature mini-task links/snapshots','no forced placement start'],profile:'fresh synthetic task-owned',task19ProfileRead:false};await writeFile(new URL('receipt.json',run),JSON.stringify(receipt,null,2)+'\n');console.log('PASS new-user actual empty Today/course landing. Evidence '+fileURLToPath(run));
}finally{if(browser)try{await browser.send('Browser.close')}catch{}page?.socket.close();browser?.socket.close();chrome.kill()}
