import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createCourseLoopModel} from '../course-loop/model.mjs';
import {registeredCourseIds} from '../course-loop/registry.mjs';
const ids=[25,27,29,31,33,35],contents=await Promise.all(ids.map(n=>import(`../course-loop/parallel-nce1-025-035/lesson-nce1-${String(n).padStart(3,'0')}.mjs`)));
const NOW=1791028800000,DAY=86400000;
function runner(c){const model=createCourseLoopModel(c);let at=NOW,state=model.initialState(at);return {model,get state(){return state},get now(){return at},get view(){return model.inspect(state,at).view},setAt(n){at=n},send(action){const r=model.transition(state,action,++at);assert.ok(r.ok,r.message);state=r.state;return r.view},reject(action){const raw=JSON.stringify(state),r=model.transition(state,action,++at);assert.equal(r.ok,false);assert.equal(JSON.stringify(r.state),raw);return r},answer(value){const q=model.currentQuestion(this.view);this.send({type:'draft',value:value??q.accepted[0]});this.send({type:'submit'})},bank(){const phase=this.view.phase;while(this.view.phase===phase){this.answer();this.send({type:'next'})}},toIndependent(){this.bank();this.send({type:'next'});this.bank()},finish(){this.toIndependent();this.bank();this.send({type:'next'});this.bank();this.send({type:'own-draft',value:'Fictional dialogue awaiting a human reader.'});this.send({type:'finish'})}}}
test('unchanged production factory bytes and registry excluded all six candidates',async()=>{
 assert.deepEqual(await readFile(new URL('../course-loop/model.mjs',import.meta.url)),execFileSync('git',['show','d9c7c48a7d419c230be06bf81cc956d63b124649:studio/course-loop/model.mjs']));
 assert.deepEqual(registeredCourseIds,['nce1-1','nce1-3','nce1-5','nce1-7','nce1-9','nce1-11']);
 for(const c of contents)assert.ok(!registeredCourseIds.includes(c.lesson.id));
});
for(const c of contents){
 const id=c.lesson.id;
 test(`${id}: first attempt, targeted teaching and local meaning boundaries use actual factory`,()=>{const r=runner(c),q=c.questionsFor('diagnostic')[0];r.answer(q.counterexamples[0].answer);assert.equal(r.view.attempts[0].correct,false);assert.equal(r.view.attempts[0].answer,q.counterexamples[0].answer);r.send({type:'next'});r.bank();assert.equal(r.model.teachingFor(r.view)[0].target,q.target);for(const item of c.questions){for(const value of item.accepted){assert.ok(c.matches(item,value));if(item.form!=='choice'){const altered=item.form==='question'?value.replace(/\?$/,'.'):value.replace(/\.$/,'')+'?';assert.equal(c.matches(item,altered),false,`${item.id}: ${altered}`)}}for(const b of item.counterexamples)assert.equal(c.matches(item,b.answer),false,item.id+': '+b.answer)}});
 test(`${id}: help/source cannot become fresh evidence; preserve original on correction/retry`,()=>{const r=runner(c);r.toIndependent();const q=r.model.currentQuestion(r.view),bad=q.counterexamples[0].answer;r.send({type:'source',source:'comic'});r.answer(bad);r.send({type:'next'});r.bank();r.reject({type:'next'});r.reject({type:'correct',id:q.id,answer:q.accepted[0],note:''});r.send({type:'correct',id:q.id,answer:q.accepted[0],note:'Correct specified referent and meaning; original remains.'});assert.equal(r.view.attempts.find(a=>a.id===q.id).answer,bad);r.send({type:'next'});const repair=r.model.currentQuestion(r.view);r.answer(repair.counterexamples[0].answer);r.reject({type:'next'});r.send({type:'retry'});r.answer();assert.equal(r.view.attempts.at(-1).fresh,false);assert.equal(r.view.attempts.at(-1).hinted,true);assert.ok(r.view.learning.some(x=>x.id===`${id}:comic`))});
 test(`${id}: exact raw drafts/events restore and foreign course raw rejected`,()=>{const r=runner(c);r.toIndependent();r.send({type:'help'});r.send({type:'draft',value:'  unchanged learner draft?  '});const raw=JSON.stringify(r.state),restored=r.model.restore(raw,r.now);assert.ok(restored.ok);assert.deepEqual(restored.state,r.state);assert.deepEqual(restored.view,r.view);const foreign=JSON.stringify({...r.state,lessonId:'nce1-1'}),f=r.model.restore(foreign,r.now);assert.equal(f.ok,false);assert.equal(f.raw,foreign)});
 test(`${id}: synthetic 24h + 7d/1d gates, two distinct banks, finite exhaustion`,()=>{const r=runner(c);r.finish();const original=structuredClone(r.view.attempts),due=r.view.dueAt;assert.equal(due,r.now+DAY);assert.equal(r.model.transition(r.state,{type:'review'},due-1).ok,false);r.setAt(due);r.send({type:'review'});assert.equal(r.view.phase,'review-a');r.bank();assert.equal(r.view.reviewResults[0].independent,true);assert.equal(r.view.dueAt,r.now+7*DAY);r.send({type:'next'});r.setAt(r.view.dueAt);r.send({type:'review'});assert.equal(r.view.phase,'review-b');r.send({type:'help'});r.bank();assert.equal(r.view.reviewResults[1].independent,false);assert.equal(r.view.dueAt,r.now+DAY);r.send({type:'next'});r.setAt(r.view.dueAt);r.reject({type:'review'});assert.equal(r.model.recommendation(r.view,r.now).kind,'needs-new-material');assert.deepEqual(r.view.attempts.slice(0,original.length),original);const receipt=r.model.receipt(r.view,r.now);assert.equal(receipt.openExpression,'awaiting-human-review');assert.equal(receipt.mastery,'not-assessed');assert.equal(receipt.band,null);assert.equal(receipt.listening,'not-tested');assert.equal(receipt.pronunciation,'not-tested')});
}
test('all six independent envelope and content versions are isolated',()=>{const models=contents.map(c=>createCourseLoopModel(c));for(const receiver of models){for(const sender of models){const raw=JSON.stringify(sender.initialState(NOW)),r=receiver.restore(raw,NOW);assert.equal(r.ok,JSON.parse(raw).lessonId===receiver.initialState(NOW).lessonId);if(!r.ok)assert.equal(r.raw,raw)}const raw=JSON.stringify({...receiver.initialState(NOW),contentVersion:99}),r=receiver.restore(raw,NOW);assert.equal(r.ok,false);assert.equal(r.raw,raw)}assert.equal(new Set(contents.flatMap(c=>c.questions.map(q=>q.id))).size,108)});
