// Real production component QA on an isolated localhost/profile; no clock changes or record injection.
import {spawn} from 'node:child_process';
import {mkdir,mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {contents,root} from './test-binding.mjs';
const work=fileURLToPath(new URL('work/nce1-037-047/',root));await mkdir(work,{recursive:true});const proof=await mkdtemp(join(work,'browser-')),profile=join(proof,'profile');
const wait=ms=>new Promise(r=>setTimeout(r,ms)),errors=[],checks=[];let browser,tab;
async function until(fn,label){for(let i=0;i<220;i++){try{if(await fn())return}catch{}await wait(40)}throw Error('Timeout '+label)}
async function connect(url){const ws=new WebSocket(url),pending=new Map();let seq=0;await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.j(Error(JSON.stringify(m.error))):p.r(m.result)}}};return {close:()=>ws.close(),send:(method,params={})=>new Promise((r,j)=>{let id=++seq;pending.set(id,{r,j});ws.send(JSON.stringify({id,method,params}))})}}
async function ev(code){const r=await tab.send('Runtime.evaluate',{expression:code,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result.value}
const sel=(s,t)=>`[...document.querySelectorAll(${JSON.stringify(s)})].find(e=>${t?`e.textContent.trim()===${JSON.stringify(t)}`:'true'})`;
async function click(s,t){const e=sel(s,t);await until(()=>ev(`!!(${e})&&!(${e}).disabled`),'enabled '+(t||s));await ev(`(${e}).scrollIntoView({block:'center'})`);await wait(80);const point=await ev(`(()=>{const r=(${e}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await tab.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await tab.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point})}
async function type(s,value){for(let i=0;i<5;i++){await click(s);await wait(110);if(await ev(`document.activeElement===document.querySelector(${JSON.stringify(s)})`))break}await tab.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:4,commands:['selectAll']});await tab.send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:4});await tab.send('Input.insertText',{text:value});await until(()=>ev(`document.querySelector(${JSON.stringify(s)})?.value===${JSON.stringify(value)}`),'input value');await wait(100)}
async function phase(p){await until(()=>ev(`document.querySelector('.course-loop')?.dataset.phase===${JSON.stringify(p)}`),'phase '+p)}
const chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
try{
 await until(async()=>{try{return !!await readFile(join(profile,'DevToolsActivePort'),'utf8')}catch{return false}},'debug endpoint');const [port,path]=(await readFile(join(profile,'DevToolsActivePort'),'utf8')).trim().split('\n');browser=await connect(`ws://127.0.0.1:${port}${path}`);const {targetId}=await browser.send('Target.createTarget',{url:'about:blank'});const tabs=await fetch(`http://127.0.0.1:${port}/json/list`).then(r=>r.json());tab=await connect(tabs.find(x=>x.id===targetId).webSocketDebuggerUrl);await tab.send('Runtime.enable');await tab.send('Page.enable');await tab.send('Emulation.setDeviceMetricsOverride',{width:1100,height:900,deviceScaleFactor:1,mobile:false});
 for(const n of [37,41,47]){const c=contents.find(c=>c.lesson.id===`nce1-${n}`);await tab.send('Page.navigate',{url:`http://127.0.0.1:4397/?course=nce1-${n}`});await phase('diagnostic');await until(()=>ev(`document.querySelector('.course-loop-card input')&&!document.querySelector('.course-loop-card input').disabled`),'first task');
 await click('button','看原文');await until(()=>ev(`document.querySelectorAll('.course-loop-text p[lang="en"]').length>0`),'guarded text');const textRows=await ev(`document.querySelectorAll('.course-loop-text p[lang="en"]').length`);
 await click('button','看本课漫画');await until(()=>ev(`[...document.querySelectorAll('.sentence-illustration img')].some(e=>e.complete&&e.naturalWidth>0)`),'comic image');
 await click('button','听本课原声');await until(()=>ev(`document.body.innerText.includes(${JSON.stringify(c.lesson.source.clips[0].label)})`),'clip labels');await click('button',c.lesson.source.clips[0].label);await until(()=>ev(`[...document.querySelectorAll('audio')].some(a=>a.src.startsWith('blob:')&&a.readyState>=1&&a.currentTime>0)`),'real original audio seek');const audio=await ev(`[...document.querySelectorAll('audio')].filter(a=>a.src.startsWith('blob:')).map(a=>({duration:a.duration,time:a.currentTime,readyState:a.readyState}))`);await click('button[aria-label="停止或取消原声"]');await click('button','收起教材');
 await type('.course-loop-card input',c.questionsFor('diagnostic')[0].accepted.at(-1));await click('button','提交本题');await until(()=>ev(`document.querySelector('.course-loop-original')?.textContent.includes(${JSON.stringify(c.questionsFor('diagnostic')[0].accepted.at(-1))})`),'original saved');await tab.send('Page.reload',{ignoreCache:true});await phase('diagnostic');await until(()=>ev(`document.querySelector('.course-loop-original')?.textContent.includes(${JSON.stringify(c.questionsFor('diagnostic')[0].accepted.at(-1))})`),'original restored');
 const shot=await tab.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(join(proof,`nce1-${n}.png`),Buffer.from(shot.data,'base64'));
 checks.push({course:c.lesson.id,sourceGuard:'real SourcePanel loaded',textRows,comic:true,originalAudio:audio,audibility:'not asserted',savedOriginalRestored:true});
 if(n!==47)continue;
 await click('button','下一题');for(const [i,q] of c.questionsFor('diagnostic').slice(1).entries()){await type('.course-loop-card input',q.accepted.at(-1));await click('button','提交本题');await click('button',i===0?'下一题':'看针对性讲解')}
 await phase('learn');await click('button','跟着换一句');for(const [i,q] of c.questionsFor('guided').entries()){await type('.course-loop-card input',q.accepted.at(-1));await click('button','提交本题');await click('button',i<2?'下一题':'收起示范，自己试')}
 await phase('independent');for(const [i,q] of c.questionsFor('independent').entries()){await type('.course-loop-card input',i===0?q.counterexamples[0].answer:q.accepted.at(-1));await click('button','提交本题');await click('button',i<2?'下一题':'看首答与反馈')}
 await phase('feedback');await type('.course-loop-card article input',c.questionsFor('independent')[0].accepted.at(-1));await type('.course-loop-card article textarea','QA：通常喜欢与这次想要是不同意思。');await click('button','保留这条订正');await until(()=>ev(`document.body.innerText.includes('首答保留')`),'correction retained');await click('button','换三个情境，再试一次');
 for(const [i,q] of c.questionsFor('repair').entries()){await type('.course-loop-card input',q.accepted.at(-1));await click('button','提交本题');await click('button',i<2?'下一题':'换成自己的问答')}
 await phase('own');await type('.course-loop-card textarea','QA fictional dialogue: Do you like pears? Do you want a glass of water? I do not like cooked onions.');await click('button','保留本次记录，安排复习');await phase('waiting');assert.equal(await ev(`[...document.querySelectorAll('button')].some(e=>e.textContent==='开始到期的新题')`),false);assert.ok(await ev(`document.body.innerText.includes('待人工核对')`));const final=await tab.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(join(proof,'nce1-47-waiting.png'),Buffer.from(final.data,'base64'));checks.push({course:'nce1-47',fullNativePipeline:true,wrongOriginalAndCorrectionPreserved:true,openExpression:'awaiting-human-review',naturalDelayedReview:'not run; no due control',clockChanged:false});
 }
 assert.equal(errors.length,0);await writeFile(join(proof,'result.json'),JSON.stringify({checks,errors,productionSource:'unchanged CourseLoopWorkspace, SourcePanel, host writer; test registry in memory only',qaOrigin:'http://127.0.0.1:4397',proof},null,2));console.log(JSON.stringify({checks:checks.length,proof,errors:errors.length}));
}finally{tab?.close();browser?.close();chrome.kill()}
