/** Test-only temporary registration. Bundles unchanged production UI and host;
 * no production registry, writer, UI or route file is edited. */
import {mkdir,readFile,readdir,stat} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {join,resolve,extname} from 'node:path';import {createServer} from 'node:http';import {createReadStream} from 'node:fs';
const root=fileURLToPath(new URL('../../',import.meta.url)),here=fileURLToPath(new URL('.',import.meta.url));
export async function startPreview(){
 const out=join(root,'work/parallel-nce1-133-143-preview');await mkdir(out,{recursive:true});
 const names=(await readdir(here)).filter(n=>/^lesson-nce1-\d+\.mjs$/.test(n)&&(!process.env.NCE_CONTENT_IDS||process.env.NCE_CONTENT_IDS.split(',').map(Number).includes(Number(n.match(/(\d+)\.mjs/)[1])))).sort(),nums=names.map(n=>Number(n.match(/(\d+)\.mjs/)[1]));
 const versions=(await readdir(join(root,'node_modules/.pnpm'))).filter(n=>/^esbuild@\d+\.\d+\.\d+$/.test(n)).sort();const {build}=await import(fileURLToPath(new URL('../../node_modules/.pnpm/'+versions.at(-1)+'/node_modules/esbuild/lib/main.js',import.meta.url)));
 const registry=names.map((n,i)=>`import * as c${i} from '${join(here,n)}';`).join('\n')+`\nimport {createCourseLoopModel} from '${join(root,'course-loop/model.mjs')}';export const registeredCourses=[${names.map((n,i)=>'c'+i)}].map(c=>({id:c.lesson.id,lesson:c.lesson,byId:c.byId,key:'nce-course-loop-v1:'+c.lesson.source.groupId,inputsKey:'nce-course-loop-inputs-v1:'+c.lesson.source.groupId,model:createCourseLoopModel(c)}));export const registeredCourseIds=registeredCourses.map(c=>c.id);export const isRegisteredCourse=id=>registeredCourseIds.includes(id);export function getCourseBinding(id='nce1-${nums[0]}'){const c=registeredCourses.find(c=>c.id===id);if(!c)throw Error('Unregistered QA course; preserve raw');return c}`;
 await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';import {CourseLoopWorkspace} from './app/course-loop-ui';import {emptyProgress} from './map/model';import {AudioSpace} from './map/media';const id=new URLSearchParams(location.search).get('course')||'nce1-${nums[0]}';document.querySelector('#qa').textContent='隔离QA预览 · 临时测试注册 · 不代表生产发布或自然间隔验收';createRoot(document.querySelector('#root')).render(React.createElement(AudioSpace,{controls:false},React.createElement(CourseLoopWorkspace,{courseId:id,map:{...emptyProgress(),lastNode:'nce1-133'},continueRoute:()=>{},onLeaveGuard:()=>{}})));`,resolveDir:root,loader:'tsx'},bundle:true,platform:'browser',format:'esm',target:'es2022',jsx:'automatic',define:{'process.env.NODE_ENV':'"development"','__STUDIO_ONLINE__':'true'},outfile:join(out,'preview.js'),plugins:[{name:'test-only-registration',setup(b){b.onResolve({filter:/course-loop\/registry\.mjs$|^\.\/registry\.mjs$/},()=>({path:'qa-registry',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:registry,loader:'js',resolveDir:here}))}}],logLevel:'silent'});
 const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/preview.css"><style>body{margin:0;padding:20px;background:#f5f3ed;color:#26362f;font-family:system-ui}nav{display:flex;gap:10px;flex-wrap:wrap}#root{max-width:940px;margin:auto}</style><nav>${nums.map(n=>`<a href="/?course=nce1-${n}">${n}–${n+1}</a>`).join('')}</nav><p id="qa"></p><div id="root"></div><script type="module" src="/preview.js"></script></html>`;
 const server=createServer(async(req,res)=>{try{const p=new URL(req.url,'http://local').pathname;if(p==='/'){res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html);return}let file;if(/^\/preview\.(js|css)$/.test(p))file=join(out,p.slice(1));else if(/^\/(language|materials|lesson-pages|illustrations|comics)\//.test(p)){file=resolve(root,'dist-online',p.slice(1));if(!file.startsWith(resolve(root,'dist-online')+'/'))throw Error('Invalid path')}else {res.writeHead(404).end();return}const info=await stat(file);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.json':'application/json','.jpg':'image/jpeg','.bin':'application/octet-stream','.webp':'image/webp'}[extname(file)]||'application/octet-stream'));res.setHeader('Content-Length',info.size);res.setHeader('Cache-Control','no-store');createReadStream(file).pipe(res)}catch{res.writeHead(404).end('Resource unavailable')}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));return {server,origin:`http://127.0.0.1:${server.address().port}`,numbers:nums};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const p=await startPreview();console.log(p.origin)}
