/** Actual final online/offline packages, native fields/files/audio, one existing
 * IDB writer. Fresh temporary profile, synthetic fixtures, unchanged clock. */
import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {mkdtemp,mkdir,readFile,readdir,writeFile,rename,rm,stat} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {createServer} from 'node:http';
import {createHash} from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const studio=fileURLToPath(new URL('../../../',import.meta.url)),out=path.resolve(process.env.R13_QA_OUT||path.join(studio,'../../stage-r13-evidence/native'));
const temporary=await mkdtemp(path.join(os.tmpdir(),'stage-r13-native-')),downloads=path.join(temporary,'downloads'),profile=path.join(temporary,'fresh-synthetic-profile');
const checks=[],exceptions=[],requests=[],external=[],artifacts=[],sockets=[],driverRetries=[],dialogs=[];
const hash=b=>createHash('sha256').update(b).digest('hex'),delay=ms=>new Promise(r=>setTimeout(r,ms)),target='#/stage-assessment?task=stage-nce1-7-12',key='stage-assessment-v1:NCE1-7-12',firstKey='stage-assessment-v1:NCE1-1-6';
let chrome,server,browser,page,origin,debugPort,version;
class CDP{
 constructor(ws){this.ws=ws;this.seq=0;this.pending=new Map();this.loads=0;ws.addEventListener('message',e=>{const m=JSON.parse(String(e.data));if(m.id){const p=this.pending.get(m.id);if(p){this.pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}}if(m.method==='Page.loadEventFired')this.loads++;if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params.exceptionDetails);if(m.method==='Page.javascriptDialogOpening'){dialogs.push(m.params);void this.send('Page.handleJavaScriptDialog',{accept:false});}if(m.method==='Network.requestWillBeSent'&&/^https?:/.test(m.params.request.url)&&!m.params.request.url.startsWith(origin+'/'))external.push(m.params.request.url);});}
 static async connect(url){const ws=new WebSocket(url);await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true});});const c=new CDP(ws);sockets.push(c);return c;}
 send(method,params={}){const id=++this.seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(Error('CDP timeout '+method));},15000);this.pending.set(id,{resolve,reject,timer});this.ws.send(JSON.stringify({id,method,params}));});}
 async eval(fn,arg){const r=await this.send('Runtime.evaluate',{expression:`(${fn.toString()})(${JSON.stringify(arg)})`,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
 async wait(fn,arg,label,limit=200){for(let n=0;n<limit;n++){try{if(await this.eval(fn,arg))return;}catch(e){if(!/Execution context was destroyed|Cannot find context|Inspected target navigated/.test(String(e)))throw e;driverRetries.push({label,error:String(e)});}await delay(40);}throw Error('Timeout '+label);}
 async click(selector,text){if(this.targetId)await browser.send('Target.activateTarget',{targetId:this.targetId});const query=({selector,text})=>[...document.querySelectorAll(selector)].some(b=>(text===undefined||b.textContent.trim()===text||b.getAttribute('aria-label')===text)&&!b.disabled&&b.getClientRects().length);await this.wait(query,{selector,text},'click '+(text||selector));await this.eval(({selector,text})=>{const b=[...document.querySelectorAll(selector)].find(b=>(text===undefined||b.textContent.trim()===text||b.getAttribute('aria-label')===text)&&!b.disabled&&b.getClientRects().length);b.scrollIntoView({block:'center',behavior:'instant'});},{selector,text});await delay(90);await this.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:10,y:500,button:'none'});await this.wait(({selector,text})=>{const b=[...document.querySelectorAll(selector)].find(b=>(text===undefined||b.textContent.trim()===text||b.getAttribute('aria-label')===text)&&!b.disabled&&b.getClientRects().length);if(!b)return false;const r=b.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return !!hit&&(hit===b||b.contains(hit));},{selector,text},'native hit target clear of transient toast');const p=await this.eval(({selector,text})=>{const b=[...document.querySelectorAll(selector)].find(b=>(text===undefined||b.textContent.trim()===text||b.getAttribute('aria-label')===text)&&!b.disabled&&b.getClientRects().length),r=b.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};},{selector,text});await this.send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await this.send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});await delay(90);}
 async type(selector,text){for(let n=0;n<5;n++){await this.click(selector);await delay(70);if(await this.eval(sel=>document.activeElement===document.querySelector(sel),selector))break;if(n===4)throw Error('Native focus did not settle '+selector);driverRetries.push({label:'native focus',selector,n});}await this.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:process.platform==='darwin'?4:2,commands:['selectAll']});await this.send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:process.platform==='darwin'?4:2});await this.send('Input.insertText',{text});await this.wait(({selector,text})=>document.querySelector(selector)?.value===text,{selector,text},'native text');}
}
const apiSource=`
import * as store from './app/offline-store';import {initial,validateState} from './app/model';import {createStageModel} from './stage-assessment/model';import {firstStageDefinition} from './stage-assessment/protocol';import {nextStageDefinition} from './stage-assessment/next-nce1-007-012/definition';import {workspaceDraft} from './stage-assessment/next-nce1-007-012/workspace-notes';import * as capability from './app/capability-review-backup';import * as demo from './public/demos/yesterday/model.mjs';import * as review from './public/demos/yesterday/review-adapter.mjs';
const first=createStageModel(firstStageDefinition),next=createStageModel(nextStageDefinition);
function raw(model){let r=model.emptyRecord('synthetic-r13-native-restore-only',true),at=Date.now()-90000,n=0;const send=c=>r=model.append(r,{id:'synthetic-native-'+(++n),at:++at,command:c},at);send({type:'learning',skills:['reading'],kind:'complete',note:'synthetic fixture only; no real natural delay or external reviewer'});send({type:'open',skill:'reading',phase:'T1',unseen:true});const id=model.project(r).attempts.at(-1).id;send({type:'draft',id,answers:['immutable synthetic original','','','','','']});send({type:'submit',id});send({type:'review',id,review:{reviewer:{role:'teacher',qualified:true,calibrated:true,external:true,basis:'unit restore fixture only; not production evidence'},targetElicited:true,disputed:false,secondReview:false,basis:'unit fixture only',judgments:Array(6).fill('correct'),criticalReversed:false}});return JSON.stringify(r);}
const bare=()=>({...structuredClone(initial),drafts:{unrelated:'synthetic unrelated original'},scores:{sentinel:7}});
const fixture=()=>({...bare(),drafts:{...bare().drafts,[firstStageDefinition.draftKey]:raw(first),[nextStageDefinition.draftKey]:raw(next)}});
function observation(raw,model){const r=JSON.parse(raw),v=model.project(r),i=model.interval(v,'reading','T2',Date.now());return {raw,events:r.events,attempts:v.attempts,anchor:i.anchor,dueAt:i.dueAt,verification:i.verification,ready:i.ready};}
function cap(){const at=Date.now()-10000;let d=demo.initialState(at);d=demo.showQuestion(d,'new-omar');d=demo.submit(d,'new-omar',1,at+1);d=demo.showQuestion(d,'new-may');d=demo.submit(d,'new-may',2,at+2);d=demo.finishDemo(d,'Synthetic rollback fixture only.',at+3);const p=review.ensurePlan(review.emptySnapshot(),demo.completedDemo(d),at+3).snapshot;localStorage.setItem(demo.storageKey,JSON.stringify(d));localStorage.setItem(review.STORAGE_KEY,JSON.stringify(p));const b=capability.captureCapabilityReviewBackup();if(!b.ok)throw Error(b.message);return b.backup;}
window.qa={store,first,next,raw,bare,fixture,validateState,observation,workspaceDraft,cap,reviewKey:review.STORAGE_KEY,demoKey:demo.storageKey,pair:()=>({demo:localStorage.getItem(demo.storageKey),review:localStorage.getItem(review.STORAGE_KEY)})};
`;
async function check(name,run){try{const detail=await run();checks.push({name,ok:true,detail});console.log('PASS '+name);}catch(e){checks.push({name,ok:false,error:String(e)});throw e;}}
async function go(url,inject=true){const loads=page.loads,current=await page.eval(()=>location.href),dest=url.startsWith('file:')?url:origin+url;if(current===dest)await page.send('Page.reload');else{const r=await page.send('Page.navigate',{url:dest});if(!r.loaderId)await page.send('Page.reload');}for(let n=0;n<200&&page.loads===loads;n++)await delay(40);assert.ok(page.loads>loads,'actual document load');if(inject){await page.eval(()=>import('/qa-api.js'));await page.wait(()=>!!window.qa,null,'QA isolated helper');}}
const state=()=>page.eval(()=>qa.store.readState()),snapshot=()=>page.eval(async()=>({main:await qa.store.readStateSnapshot(),pair:qa.pair()}));
const button=(text,selector='button')=>page.click(selector,text);
async function ready(){await page.wait(()=>document.querySelector('[data-stage-host]')?.getAttribute('data-stage-scope')==='NCE1-7-12'&&!!document.querySelector('.stage-learning-workspace')&&!document.querySelector('[data-stage-draft=writing] textarea')?.disabled,null,'new stage workspace');}
async function saved(slot,text){await page.wait(async({slot,text})=>{const s=await qa.store.readState(),read=qa.next.readRecord(s.drafts['stage-assessment-v1:NCE1-7-12']);return qa.workspaceDraft(read,slot)?.answers[0]===text;},{slot,text},'confirmed '+slot+' workspace');await page.wait(slot=>!document.querySelector('[data-stage-draft='+slot+'] [role=status]')?.textContent.includes('正在'),slot,'workspace readback ready');}
async function shot(name){const {data}=await page.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});const b=Buffer.from(data,'base64');await writeFile(path.join(out,name+'.png'),b);artifacts.push({file:name+'.png',bytes:b.length,sha256:hash(b)});}
async function download(name,action){const before=new Set(await readdir(downloads));await action();let f;for(let n=0;n<200;n++){f=(await readdir(downloads)).find(p=>!before.has(p)&&!p.endsWith('.crdownload'));if(f)break;await delay(40);}assert.ok(f,'native downloaded '+name);const dest=path.join(out,name+'.json');await rename(path.join(downloads,f),dest);const b=await readFile(dest);artifacts.push({file:name+'.json',bytes:b.length,sha256:hash(b),nativeDownload:true});return {file:dest,value:JSON.parse(b),raw:b};}
async function closeDialog(){if(await page.eval(()=>!!document.querySelector('[role=dialog]'))){await page.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await page.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await page.wait(()=>!document.querySelector('[role=dialog]'),null,'close dialog');}}
async function file(name,state,capability){assert.equal(await page.eval(s=>qa.validateState(s),state),true,'Synthetic whole-State fixture must validate before native upload');const f=path.join(out,name+'.json');await writeFile(f,JSON.stringify({format:'english-studio-progress',version:capability===undefined?1:2,savedAt:new Date().toISOString(),state,...(capability===undefined?{}:{capability})}));return f;}
async function restore(f,beforeConfirm){await button('进度备份与恢复');await page.wait(()=>!!document.querySelector('.progress-save-dialog input[type=file]'),null,'shared dialog file input mounted');const {root}=await page.send('DOM.getDocument'),{nodeId}=await page.send('DOM.querySelector',{nodeId:root.nodeId,selector:'[role=dialog] input[type=file]'});assert.ok(nodeId);await page.send('DOM.setFileInputFiles',{nodeId,files:[f]});await page.wait(()=>document.body.innerText.includes('恢复这份学习进度？'),null,'native restore preview');if(beforeConfirm)await beforeConfirm();await button('确认替换并恢复');await page.wait(()=>![...document.querySelectorAll('[role=dialog] button')].some(b=>b.textContent.includes('正在恢复')),null,'restore handler finished');await delay(200);}
async function select(index,position){if(process.platform==='darwin'){const actual='.stage-select label:nth-child('+index+') select';driverRetries.push({kind:'Mac headless native select popup unverified; QA DOM change for scope/phase only',index,position});await page.wait(actual=>!!document.querySelector(actual)&&!document.querySelector(actual).disabled,actual,'scope selector ready');await page.eval(({actual,position})=>{const s=document.querySelector(actual);s.value=s.options[position].value;s.dispatchEvent(new Event('change',{bubbles:true}));},{actual,position});await page.wait(({actual,position})=>document.querySelector(actual)?.selectedIndex===position,{actual,position},'selected scope committed');return;}const selector='.stage-select select:nth-of-type('+index+')';const actual='.stage-select label:nth-child('+index+') select';await page.click(actual);await page.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'Home',code:'Home',windowsVirtualKeyCode:36});await page.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Home',code:'Home',windowsVirtualKeyCode:36});for(let i=0;i<position;i++){await page.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'ArrowDown',code:'ArrowDown',windowsVirtualKeyCode:40});await page.send('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowDown',code:'ArrowDown',windowsVirtualKeyCode:40});}await page.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await page.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});if(!await page.eval(({actual,position})=>document.querySelector(actual)?.selectedIndex===position,{actual,position})){await page.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await page.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});driverRetries.push({kind:'Mac headless native select popup did not commit; QA uses DOM change for scope/phase selection only',index,position});await page.eval(({actual,position})=>{const s=document.querySelector(actual);s.value=s.options[position].value;s.dispatchEvent(new Event('change',{bubbles:true}));},{actual,position});}await page.wait(({actual,position})=>document.querySelector(actual)?.selectedIndex===position,{actual,position},'selected UI scope/phase committed');}
async function start(skill,position){await select(1,position);await select(2,1);await page.click('.stage-check input');await button('开始'+skill+' · 学后未见题');await page.wait(()=>!!document.querySelector('#stage-current'),null,'durably opened '+skill);}
async function ended(){await page.wait(()=>!!document.querySelector('[data-stage-correction] textarea')&&!document.querySelector('[data-stage-correction] textarea').disabled,null,'ended and correction loaded');}
async function failWrites(){await page.eval(()=>{window.__originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='state')throw new DOMException('Synthetic R13 storage failure','QuotaExceededError');return __originalPut.apply(this,args);};});}
async function allowWrites(){await page.eval(()=>{IDBObjectStore.prototype.put=__originalPut;delete window.__originalPut;});}
try{
 await mkdir(out,{recursive:true});await mkdir(downloads);
 const packages=path.join(studio,'node_modules/.pnpm'),builders=(await readdir(packages)).filter(n=>/^esbuild@\d+\.\d+\.\d+$/.test(n)).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}));const {build}=await import(path.join(packages,builders[0],'node_modules/esbuild/lib/main.js'));await build({stdin:{contents:apiSource,resolveDir:studio,loader:'ts'},bundle:true,platform:'browser',format:'esm',target:'chrome120',outfile:path.join(temporary,'qa-api.js'),logLevel:'silent'});const api=await readFile(path.join(temporary,'qa-api.js'));
 const packageRoot=path.join(studio,'dist-online');server=createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');const pathname=new URL(req.url,'http://local').pathname;if(pathname==='/qa-api.js'){res.setHeader('Content-Type','text/javascript');res.end(api);return;}if(pathname==='/seed'){res.setHeader('Content-Type','text/html');res.end('<script type="module" src="/qa-api.js"></script>');return;}let p=path.resolve(packageRoot,pathname==='/'?'index.html':pathname.slice(1));try{assert.ok(p.startsWith(packageRoot+'/'));if((await stat(p)).isDirectory())p=path.join(p,'index.html');const s=await stat(p);requests.push({pathname,bytes:s.size});res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.wav':'audio/wav','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg'})[path.extname(p)]||'application/octet-stream');res.setHeader('Content-Length',s.size);const stream=createReadStream(p);stream.on('error',()=>res.destroy());stream.pipe(res);}catch{res.statusCode=404;res.end('Missing local package asset');}});await new Promise((r,j)=>{server.once('error',j);server.listen(0,'127.0.0.1',r);});origin='http://127.0.0.1:'+server.address().port;
 chrome=spawn(process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-sync','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});let launchError;chrome.once('error',e=>launchError=e);let endpoint;for(let n=0;n<200;n++){if(launchError)throw launchError;try{endpoint=(await readFile(profile+'/DevToolsActivePort','utf8')).trim().split('\n');break;}catch{await delay(40);}}assert.ok(endpoint);debugPort=endpoint[0];browser=await CDP.connect(`ws://127.0.0.1:${debugPort}${endpoint[1]}`);version=await browser.send('Browser.getVersion');await browser.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads,eventsEnabled:true});const {targetId}=await browser.send('Target.createTarget',{url:origin+'/seed'}),tabs=await fetch('http://127.0.0.1:'+debugPort+'/json/list').then(r=>r.json());page=await CDP.connect(tabs.find(t=>t.id===targetId).webSocketDebuggerUrl);page.targetId=targetId;for(const method of ['Page.enable','Runtime.enable','Network.enable','DOM.enable'])await page.send(method);await page.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await page.wait(()=>!!window.qa,null,'synthetic helper seed');
 let firstRaw;await page.eval(()=>{const s=qa.bare();s.drafts['stage-assessment-v1:NCE1-1-6']=qa.raw(qa.first);return qa.store.writeState(s);});firstRaw=(await state()).drafts[firstKey];
 if(!process.env.R13_MATRIX_ONLY){await go('/#/today');
 await check('actual Today entry opens lessons 7-12 through final StudyApp accepted route',async()=>{await page.wait(()=>!!document.querySelector('a[href="/#/stage-assessment?task=stage-nce1-7-12"]'),null,'next stage entry');await page.click('a[href="/#/stage-assessment?task=stage-nce1-7-12"]');await ready();await page.eval(()=>import('/qa-api.js'));assert.equal(await page.eval(()=>location.hash),target);assert.equal(await page.eval(()=>document.querySelectorAll('[data-mini-host],[data-placement-host]').length),0);});
 await check('native learning current draft saves, reloads and leaves first-stage raw untouched',async()=>{await page.click('[data-stage-learning] details:nth-of-type(4)>summary');await page.type('[data-stage-draft=writing] textarea','Synthetic practice current draft before refresh.');await saved('writing','Synthetic practice current draft before refresh.');const raw=(await state()).drafts[key];await go('/'+target);await ready();assert.equal(await page.eval(()=>document.querySelector('[data-stage-draft=writing] textarea').value),'Synthetic practice current draft before refresh.');assert.equal((await state()).drafts[key],raw);assert.equal((await state()).drafts[firstKey],firstRaw);});
 await check('native current draft failure retains text, blocks all module departures and retries through one writer',async()=>{await page.click('[data-stage-learning] details:nth-of-type(4)>summary');const before=(await state()).drafts[key];await failWrites();await page.type('[data-stage-draft=writing] textarea','Synthetic pending practice must survive failed storage.');await page.wait(()=>document.querySelector('[data-stage-draft=writing] [role=alert]')?.textContent.includes('Synthetic R13'),null,'failure surfaced');for(const dest of ['#/stage-assessment','#/placement','#/mini-task/mini-n1-01','#/nce/NCE3/1?tab=grammar']){await page.eval(h=>location.hash=h,dest);await page.wait(h=>location.hash===h,target,'guard restores current new-stage hash');assert.equal(await page.eval(()=>document.querySelector('[data-stage-draft=writing] textarea').value),'Synthetic pending practice must survive failed storage.');assert.equal(await page.eval(()=>document.querySelectorAll('[data-mini-host],[data-placement-host],.course-video textarea').length),0);}assert.equal((await state()).drafts[key],before);const pending=await download('pending-practice',()=>button('下载未确认当前稿','[data-stage-draft=writing] button'));assert.equal(pending.value.counted,false);assert.equal(pending.value.pending.answers[0],'Synthetic pending practice must survive failed storage.');await shot('failed-practice-retained-390');await allowWrites();await button('重试保存当前稿','[data-stage-draft=writing] button');await saved('writing','Synthetic pending practice must survive failed storage.');});
 await check('320 and 390 actual new workspaces fit viewport and keep semantic claims honest',async()=>{for(const width of [320,390]){await page.send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:false});const layout=await page.eval(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,text:document.body.innerText}));assert.ok(layout.scroll<=layout.width+1,JSON.stringify(layout));assert.match(layout.text,/不证明独立四技能掌握/);await shot('learning-'+width);}return {physicalPhone:false};});
 await check('native reading and speaking learning workspaces save actual new-context drafts',async()=>{for(const [index,slot,text] of [[2,'reading','Synthetic factual reading note: Juno is tired; unknown white umbrella owner.'],[3,'speaking','Synthetic speaking excerpt only; no real listener, actual hearing pending.']]){await page.click('[data-stage-learning] details:nth-of-type('+index+')>summary');await page.type('[data-stage-draft='+slot+'] textarea',text);await saved(slot,text);}const read=await page.eval(async()=>qa.next.readRecord((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12']));assert.equal(read.view.attempts.length,0);assert.ok(read.view.learning.every(e=>e.kind==='practice'));});
 await check('actual practice audio reaches ended as synthetic media without human delivery or scoring',async()=>{await page.click('[data-stage-learning] details:nth-of-type(1)>summary');await page.eval(()=>{const a=document.querySelector('[data-stage-learning] audio');window.__audioEnded=false;a.addEventListener('ended',()=>window.__audioEnded=true,{once:true});});await page.click('[data-stage-learning] audio');await page.eval(()=>document.querySelector('[data-stage-learning] audio').play());await page.wait(()=>window.__audioEnded,null,'real practice audio ended',800);const sound=await page.eval(()=>{const a=document.querySelector('[data-stage-learning] audio');return {duration:a.duration,ended:a.ended,src:a.currentSrc};});assert.ok(sound.ended&&sound.duration>15);assert.ok(sound.src.startsWith(origin+'/assets/'));assert.equal((await page.eval(async()=>qa.next.readRecord((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12']))).view.attempts.length,0);return {sound,humanHeardVerified:false};});
 await button('现在记录学习完成声明');await start('写作',3);
 let writingId,writingDeadline,writingFirst;
 await check('actual seven-minute writing first draft refresh preserves deadline and unrelated state',async()=>{await page.type('textarea[aria-label="写作首答"]','Synthetic writing first answer; no automatic manual grade.');await page.wait(async()=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.at(-1).answers[0]==='Synthetic writing first answer; no automatic manual grade.',null,'writing first confirmed');const before=await page.eval(async()=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.at(-1));writingId=before.id;writingDeadline=before.deadline;assert.equal(before.deadline-before.openedAt,420000);await go('/'+target);await page.wait(()=>document.querySelector('textarea[aria-label="写作首答"]')?.value==='Synthetic writing first answer; no automatic manual grade.',null,'writing refresh');const after=await page.eval(async()=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.at(-1));assert.deepEqual(after,before);assert.equal((await state()).drafts[firstKey],firstRaw);await shot('writing-timer-refresh-390');});
 await check('native first-answer failure download and retry preserve original timer',async()=>{const raw=(await state()).drafts[key];await failWrites();await page.type('textarea[aria-label="写作首答"]','Synthetic pending timed answer retained.');await page.wait(()=>document.querySelector('.stage-error')?.textContent.includes('Synthetic R13'),null,'timed save failure');assert.equal((await state()).drafts[key],raw);await page.eval(h=>location.hash=h,'#/placement');await page.wait(h=>location.hash===h,target,'timed guard');const pending=await download('pending-timed-first',()=>button('下载未确认输入'));assert.equal(pending.value.counted,false);assert.equal(pending.value.pendingInput[0],'Synthetic pending timed answer retained.');await allowWrites();await button('保存首答草稿');await page.wait(async()=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.at(-1).answers[0]==='Synthetic pending timed answer retained.',null,'timed retry');assert.equal((await page.eval(async()=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.at(-1))).deadline,writingDeadline);});
 await button('锁定已保存首答，待外评');await ended();writingFirst=(await page.eval(async()=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.at(-1))).first;
 await check('native correction current draft and reason survive real document refresh',async()=>{await page.type('[data-stage-correction] textarea','Synthetic correction new current draft.');await page.type('input[aria-label="新阶段订正理由"]','Synthetic reason: clarify occupation and owner.');await page.wait(async id=>{const read=qa.next.readRecord((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12']),draft=qa.workspaceDraft(read,'correction',id);return draft?.answers[0]==='Synthetic correction new current draft.'&&draft.note==='Synthetic reason: clarify occupation and owner.';},writingId,'correction current persisted');const raw=(await state()).drafts[key];await go('/'+target);await ended();assert.equal(await page.eval(()=>document.querySelector('[data-stage-correction] textarea').value),'Synthetic correction new current draft.');assert.equal(await page.eval(()=>document.querySelector('input[aria-label="新阶段订正理由"]').value),'Synthetic reason: clarify occupation and owner.');assert.equal((await state()).drafts[key],raw);await shot('correction-refreshed-390');});
 await check('native correction failure retains pending new draft and separate revision preserves immutable first',async()=>{const raw=(await state()).drafts[key];await failWrites();await page.type('[data-stage-correction] textarea','Synthetic failed correction draft must survive.');await page.wait(()=>document.querySelector('[data-stage-correction] [role=alert]')?.textContent.includes('Synthetic R13'),null,'correction fail');await button('另存已确认订正，不覆盖首答');assert.equal((await state()).drafts[key],raw);const pending=await download('pending-correction',()=>button('下载未确认当前稿','[data-stage-correction] button'));assert.equal(pending.value.counted,false);assert.equal(pending.value.pending.answers[0],'Synthetic failed correction draft must survive.');await allowWrites();await button('重试保存当前稿','[data-stage-correction] button');await page.wait(async id=>qa.workspaceDraft(qa.next.readRecord((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12']),'correction',id)?.answers[0]==='Synthetic failed correction draft must survive.',writingId,'correction retry');await button('另存已确认订正，不覆盖首答');await page.wait(async id=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.find(a=>a.id===id)?.revisions.length===1,writingId,'separate revision');const attempt=await page.eval(async id=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.find(a=>a.id===id),writingId);assert.deepEqual(attempt.first,writingFirst);assert.equal(attempt.deadline,writingDeadline);assert.equal(attempt.reviews.length,0);});
 await check('actual reading six-question task stores first answers and four-minute timer without an auto grade',async()=>{await start('阅读',1);for(let i=1;i<=6;i++)await page.type('.stage-answer:nth-of-type('+i+') input','Synthetic read fact '+i);await button('锁定已保存首答，待外评');await ended();const a=await page.eval(async()=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.at(-1));assert.equal(a.skill,'reading');assert.equal(a.deadline-a.openedAt,240000);assert.equal(a.first.length,6);assert.equal(a.reviews.length,0);});
 await check('actual speaking excerpt remains pending actual qualified listener and four-minute timer',async()=>{await start('口语',2);await page.type('textarea[aria-label="口语原始摘录（可选）"]','Synthetic excerpt only. Actual listener and pronunciation not tested.');await button('锁定已保存首答，待外评');await ended();const a=await page.eval(async()=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.at(-1));assert.equal(a.skill,'speaking');assert.equal(a.deadline-a.openedAt,240000);assert.equal(a.reviews.length,0);assert.equal(a.delivery,undefined);});
 await check('assessment synthetic audio requires durable reference help before sound and cannot create human evidence',async()=>{await start('听力',0);const raw=(await state()).drafts[key];await failWrites();await page.click('[data-stage-audio]');await page.wait(()=>document.querySelector('.stage-audio-boundary [role=status]')?.textContent.includes('尚未确认'),null,'audio durable failure');assert.equal(await page.eval(()=>document.querySelector('.stage-audio-boundary audio').getAttribute('src')),null);assert.equal((await state()).drafts[key],raw);await allowWrites();await page.eval(()=>{window.__assessmentEnded=false;document.querySelector('.stage-audio-boundary audio').addEventListener('ended',()=>window.__assessmentEnded=true,{once:true});});await page.click('[data-stage-audio]');await page.wait(()=>window.__assessmentEnded,null,'actual assessment learning sound ended',800);const a=await page.eval(async()=>qa.next.project(JSON.parse((await qa.store.readState()).drafts['stage-assessment-v1:NCE1-7-12'])).attempts.at(-1));assert.equal(a.deadline-a.openedAt,180000);assert.ok(a.help.includes('reference'));assert.equal(a.delivery,undefined);assert.equal(a.reviews.length,0);await button('锁定已保存首答，待外评');await ended();assert.match(await page.eval(()=>document.body.innerText),/无效条件/);return {humanDeliveryVerified:false};});
 await check('full native four-skill backup keeps first stage, new current drafts and corrections together',async()=>{const before=await state();const backup=await download('native-four-skill-progress',()=>button('保存进度','.progress-save-actions button'));assert.equal(backup.value.state.drafts[key],before.drafts[key]);assert.equal(backup.value.state.drafts[firstKey],firstRaw);assert.equal(backup.value.state.drafts.unrelated,'synthetic unrelated original');});
 }
 // Both actual shared ProgressSave and StageHost ProgressSave; synthetic review
 // records exist only to test exact first/anchor/due preservation, not learning.
 for(const route of ['/#/progress','/'+target]){
  const label=route.includes('progress')?'shared':'stage-host';
  await page.eval(()=>{localStorage.clear();return qa.store.writeState(qa.fixture());});await go(route);await page.wait(()=>!!document.querySelector('.progress-save-button:not(:disabled)'),null,label+' save ready');const original=await snapshot(),originalState=await state(),source={};for(const k of [firstKey,key])source[k]=await page.eval(({k,next})=>qa.store.readState().then(s=>qa.observation(s.drafts[k],next?qa.next:qa.first)),{k,next:k===key});
  await check(label+' native same-source whole-file restore preserves both exact raws and due',async()=>{const backup=await download(label+'-roundtrip',()=>button('保存进度','.progress-save-actions button'));await restore(backup.file);await page.wait(()=>document.querySelector('.progress-save-receipt')?.textContent.includes('已恢复'),null,'restore success');assert.deepEqual(await snapshot(),original);await closeDialog();});
  for(const kind of ['missing-both','missing-next','older-next'])await check(label+' '+kind+' retains both current stages',async()=>{const incoming=structuredClone(originalState);incoming.scores={replacement:2};if(kind==='missing-both'){delete incoming.drafts[firstKey];delete incoming.drafts[key];}if(kind==='missing-next')delete incoming.drafts[key];if(kind==='older-next'){const r=JSON.parse(incoming.drafts[key]);r.events.pop();incoming.drafts[key]=JSON.stringify(r);}await restore(await file(label+'-'+kind,incoming));await page.wait(()=>document.querySelector('.progress-save-receipt')?.textContent.includes('已恢复'),null,'legacy restore');const s=await state();assert.equal(s.drafts[key],originalState.drafts[key]);assert.equal(s.drafts[firstKey],originalState.drafts[firstKey]);await closeDialog();});
  for(const kind of ['fork','future','schema','workspace-schema','equal-future','equal-schema','live-unknown-missing'])await check(label+' '+kind+' refuses whole write and keeps all raw state',async()=>{const incoming=structuredClone(originalState),r=JSON.parse(incoming.drafts[key]);if(kind==='fork')r.events[2].command.answers[0]='forked synthetic answer';if(kind.includes('future'))r.events.at(-1).at=Date.now()+86400000;if(kind.includes('schema'))r.version=99;if(kind==='workspace-schema'){r.version=1;r.events[0].command.note='stage-workspace-007-012:v9:{}';}if(kind==='live-unknown-missing')r.version=99;incoming.drafts[key]=JSON.stringify(r);if(kind.startsWith('equal-')||kind==='live-unknown-missing')await page.eval(s=>qa.store.writeState(s),incoming);else await page.eval(s=>qa.store.writeState(s),originalState);await go(route);const before=await snapshot();const restoreState=kind==='live-unknown-missing'?{...originalState,drafts:{unrelated:'replacement'}}:incoming;await restore(await file(label+'-'+kind,restoreState));assert.deepEqual(await snapshot(),before);assert.equal(await page.eval(()=>!!document.querySelector('.progress-save-receipt')?.textContent.includes('已恢复')),false);await closeDialog();});
  await check(label+' new-source restore adds provenance only and keeps original first/anchor/due',async()=>{await page.eval(()=>qa.store.writeState(qa.bare()));await go(route);await restore(await file(label+'-new-source',originalState));await page.wait(()=>document.querySelector('.progress-save-receipt')?.textContent.includes('已恢复'),null,'new source success');for(const k of [firstKey,key]){const imported=await page.eval(({k,next})=>qa.store.readState().then(s=>qa.observation(s.drafts[k],next?qa.next:qa.first)),{k,next:k===key});assert.deepEqual(imported.events.slice(0,-1),source[k].events);assert.equal(imported.events.at(-1).command.type,'restore');assert.deepEqual(imported.attempts,source[k].attempts);assert.equal(imported.anchor,source[k].anchor);assert.equal(imported.dueAt,source[k].dueAt);assert.equal(imported.verification,'restored-time-unverified');assert.equal(imported.ready,false);}await closeDialog();});
  await check(label+' actual post-main capability failure rolls back exact whole raw and both stages',async()=>{const payload=await page.eval(()=>qa.cap());await page.eval(s=>{localStorage.clear();return qa.store.writeState(s);},originalState);await go(route);const before=await snapshot(),incoming={...originalState,scores:{replacement:99}};const inject=()=>page.eval(()=>{window.__originalSet=Storage.prototype.setItem;window.__failedCapability=false;window.__puts=0;window.__countPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...a){if(this.name==='state')window.__puts++;return __countPut.apply(this,a);};Storage.prototype.setItem=function(k,v){if(k===qa.demoKey&&!window.__failedCapability){window.__failedCapability=true;throw Error('Synthetic post-main capability failure');}return __originalSet.call(this,k,v);};});await restore(await file(label+'-rollback-input',incoming,payload),inject);await page.wait(()=>window.__failedCapability,null,'capability failure after main commit');assert.deepEqual(await snapshot(),before);assert.ok(await page.eval(()=>window.__puts>=2),'main commit plus rollback actual IDB writes');await page.eval(()=>{Storage.prototype.setItem=__originalSet;IDBObjectStore.prototype.put=__countPut;});await closeDialog();});
 }
 await check('portable final single HTML loads lessons 7-12, saves and reloads an actual current draft',async()=>{const fileUrl=pathToFileURL(path.join(studio,'dist/index.html')).href+target;await go(fileUrl,false);await page.wait(()=>!!document.querySelector('[data-stage-draft=writing] textarea')&&!document.querySelector('[data-stage-draft=writing] textarea').disabled,null,'file portable stage');await page.click('[data-stage-learning] details:nth-of-type(4)>summary');await page.type('[data-stage-draft=writing] textarea','Synthetic portable current draft.');await page.wait(()=>document.querySelector('[data-stage-draft=writing] [role=status]')?.textContent.includes('已确认保存'),null,'portable save');await go(fileUrl,false);await page.wait(()=>document.querySelector('[data-stage-draft=writing] textarea')?.value==='Synthetic portable current draft.',null,'portable true reload');for(const width of [320,390]){await page.send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:false});assert.ok(await page.eval(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('portable-'+width);}assert.equal(await page.eval(()=>document.querySelector('[data-stage-learning] audio').getAttribute('src')?.startsWith('data:audio/wav;base64,')),true);});
 await check('portable Today entry returns to actual new draft and data audio reaches ended without external request',async()=>{await button('查看今天安排');await page.wait(()=>location.hash==='#/today'&&!!document.querySelector('a[href="#/stage-assessment?task=stage-nce1-7-12"]'),null,'portable Today stage entry');await page.click('a[href="#/stage-assessment?task=stage-nce1-7-12"]');await page.wait(()=>document.querySelector('[data-stage-draft=writing] textarea')?.value==='Synthetic portable current draft.',null,'portable entry resumes draft');await page.click('[data-stage-learning] details:nth-of-type(1)>summary');await page.eval(()=>{window.__portableAudioEnded=false;const a=document.querySelector('[data-stage-learning] audio');a.addEventListener('ended',()=>window.__portableAudioEnded=true,{once:true});});await page.click('[data-stage-learning] audio');await page.eval(()=>document.querySelector('[data-stage-learning] audio').play());await page.wait(()=>window.__portableAudioEnded,null,'portable data audio ended',800);assert.ok(await page.eval(()=>document.querySelector('[data-stage-learning] audio').duration>15));return {humanHeardVerified:false};});
 assert.equal(exceptions.length,0,'actual main application exceptions');assert.equal(external.length,0,'application makes no external network request in this run');
}catch(e){console.error(e);process.exitCode=1;if(page){await shot('failure').catch(()=>{});await writeFile(path.join(out,'failure-dom.txt'),await page.eval(()=>document.body.innerText).catch(()=>''));}}
finally{const binding={};for(const p of ['dist-online/index.html','dist/index.html','dist-online/version.json','dist-online/map/index.html']){const b=await readFile(path.join(studio,p));binding[p]={bytes:b.length,sha256:hash(b)};}const report={qaScope:process.env.R13_MATRIX_ONLY?'restore-and-portable':'full',sourceHead:execFileSync('git',['rev-parse','HEAD'],{cwd:studio,encoding:'utf8'}).trim(),sourceBase:'d717bad909d889fd305d667bd1d8530883aaf23a',scope:'actual final StudyApp online/portable packages; native fields/files/audio; original full-State CAS IDB writer; fresh synthetic profile; unchanged Date.now',checks,passed:checks.filter(c=>c.ok).length,failed:checks.filter(c=>!c.ok).length,driverExitedWithError:!!process.exitCode,RuntimeExceptions:exceptions,externalRequests:external,requests,artifacts,dialogs,driverRetries,packageBinding:binding,browser:version,unverified:['published origin','natural24h/7d retention','human acoustic quality','human listener or qualified manual review','four-skill mastery','difficulty equivalence','physical phone','Mac native select popup; scope/phase selection uses QA DOM change fallback']};await mkdir(out,{recursive:true});await writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');for(const s of sockets)s.ws.close();if(chrome){const exited=new Promise(r=>chrome.exitCode!==null?r():chrome.once('exit',r));chrome.kill('SIGTERM');await exited;}if(server)await new Promise(r=>server.close(r));await rm(temporary,{recursive:true,force:true,maxRetries:5,retryDelay:100});console.log(JSON.stringify({proof:out,passed:report.passed,failed:report.failed,exceptions:exceptions.length,driverExitedWithError:report.driverExitedWithError}));}
