import type {LanguageRow} from './language';
import type {NceBookId} from './model';
export type Option={en:string;zh:string};
export type Frame={id:string;name:string;match:RegExp;form:string;zh:string;slots:{label:string;options:Option[]}[];tip:string;transfer:string};
const choices=(label:string,items:string[])=>({label,options:items.map(s=>{const [en,zh]=s.split('|');return {en,zh}})});
export const frames:Frame[]=[
 {id:'ownership',name:'物品与归属',match:/\b(?:your|my|his|her) (?:handbag|bag|coat|umbrella|pen|book|car|shirt|dress)\b/i,form:'Is this your {0}? Yes, it is. This is my {0}.',zh:'这是你的{0}吗？是的。这是我的{0}。',slots:[choices('换一种物品',['bag|包','book|书','pen|钢笔'])],tip:'先问 Is this your…? 回答时把 your 换成 my。物品先用单数。',transfer:'拿起身边另一件东西，重新问答；这次不看屏幕。'},
 {id:'request',name:'提出请求',match:/\b(?:please|could you|can you|would you)\b/i,form:'Could you {0}, please? Thank you.',zh:'请你{0}好吗？谢谢。',slots:[choices('请对方做什么',['open the window|打开窗户','help me|帮我','say that again|再说一遍'])],tip:'Could you 后面直接接动作原形；把整个请求作为一组读。',transfer:'想一个今天会用到的请求，把动作换成自己的。'},
 {id:'place',name:'地点与环境',match:/\b(?:there is|there are|where|in the room)\b/i,form:'There is a {0} near my home. I go there {1}.',zh:'我家附近有一个{0}。我{1}去那里。',slots:[choices('家附近的地方',['park|公园','shop|商店','library|图书馆']),choices('多久去一次',['every week|每周','on Sundays|星期日','twice a month|一个月两次'])],tip:'There is 后面用单数。先说地点，再补一个去那里的频率。',transfer:'换一个真实的地方，补充你在那里做什么。'},
 {id:'identity',name:'身份与现状',match:/\b(?:am|are you|is he|is she|name|nationality|job)\b/i,form:'I am {0}. I {1}.',zh:'我是{0}。我{1}。',slots:[choices('你的身份',['a student|一名学生','a teacher|一名教师','an engineer|一名工程师']),choices('补一个生活细节',['study English every day|每天学英语','work in a small team|在一个小团队工作','enjoy reading|喜欢阅读'])],tip:'职业前通常有 a / an。先说身份，再补一个真实细节。',transfer:'不用示范中的职业，说出自己的身份和一件日常的事。'},
 {id:'feeling',name:'状态与感受',match:/\b(?:tired|thirsty|hungry|happy|ill|feel|cold|hot)\b/i,form:'I feel {0} today. I need {1}.',zh:'我今天感到{0}。我需要{1}。',slots:[choices('现在的状态',['tired|累','hungry|饿','thirsty|渴']),choices('你需要什么',['some rest|休息一下','some food|一些食物','some water|一些水'])],tip:'两句意思要配得上：渴了通常需要水。先说状态，再说需要。',transfer:'换成你今天的实际状态；原因可以先用中文想。'},
 {id:'ability',name:'能力与进步',match:/\b(?:can|cannot|can't|could)\b/i,form:'I can {0}, but I cannot {1} yet.',zh:'我会{0}，但还不会{1}。',slots:[choices('已经会做的事',['swim|游泳','cook|做饭','ride a bike|骑自行车']),choices('还在学习的事',['drive a car|开车','play the piano|弹钢琴','speak French|说法语'])],tip:'can / cannot 后用动作原形，yet 表示“还”。',transfer:'说一个你能做的事，再说一个你正在学的事。'},
 {id:'future',name:'计划与愿望',match:/\b(?:going to|will|shall|tomorrow)\b/i,form:'Tomorrow, I am going to {0}. I will go with {1}.',zh:'明天我打算{0}。我会和{1}一起去。',slots:[choices('打算做什么',['visit a museum|参观博物馆','go to the park|去公园','go shopping|购物']),choices('和谁一起',['a friend|一个朋友','my family|家人','my sister|姐姐或妹妹'])],tip:'am going to 后接动作原形；先计划，再补同行的人。',transfer:'把明天换成下周，讲一个不同的真实计划。'},
 {id:'past',name:'过去的经历',match:/\b(?:was|were|went|did|had|yesterday|ago)\b/i,form:'Last weekend, I {0}. I felt {1}.',zh:'上周末我{0}。我感到{1}。',slots:[choices('发生了什么',['visited a friend|拜访了一个朋友','went to a park|去了公园','cooked dinner|做了晚饭']),choices('你的感受',['happy|开心','relaxed|放松','tired|疲惫'])],tip:'过去的事使用过去式：go → went，feel → felt。先后两句时态一致。',transfer:'换成昨天的一件事，再补充当时和谁在一起。'},
 {id:'preference',name:'喜好与原因',match:/\b(?:like|love|enjoy|prefer|want)\b/i,form:'I enjoy {0} because {1}.',zh:'我喜欢{0}，因为{1}。',slots:[choices('喜欢的活动',['reading|阅读','swimming|游泳','cooking|做饭']),choices('一个原因',['it helps me relax|它帮助我放松','I can learn something new|我能学到新东西','it is fun|它很有趣'])],tip:'enjoy 后面的动作使用 -ing。because 后面写完整的原因。',transfer:'换一个活动，给出自己的原因，不照抄示范。'},
 {id:'habit',name:'日常与频率',match:/\b(?:usually|often|every|always|sometimes|do you)\b/i,form:'I usually {0} {1}.',zh:'我通常{1}{0}。',slots:[choices('经常做什么',['read a book|读书','go for a walk|散步','listen to music|听音乐']),choices('什么时候',['after dinner|晚饭后','in the morning|早上','before bed|睡觉前'])],tip:'usually 通常放在动作前；频率和时间让回答更具体。',transfer:'加第二句：为什么这样做？可以用 It helps me relax. 起步。'},
];
// These functions are selected from evidence in the current lesson, not by book alone.
frames.splice(2,0,
 {id:'progressive',name:'正在进行的动作',match:/\b(?:am|is|are|'m|'re|'s)\s+\w+ing\b/i,form:'I am {0} now. Please {1}.',zh:'我现在正在{0}。请{1}。',slots:[choices('正在做什么',['reading|阅读','cooking|做饭','working|工作']),choices('希望对方做什么',['wait a moment|等一下','be quiet|安静一点','help me|帮帮我'])],tip:'正在发生的动作：am / is / are + 动词 -ing。两句话要符合你设定的情境。',transfer:'家人打电话来，告诉他你现在正在做什么，再提出一个请求。'},
 {id:'perfect',name:'已经完成的事',match:/\b(?:have|has|'ve|'s)\s+(?:just |already |never |ever )?(?:been|seen|done|had|made|taken|\w+ed)\b/i,form:'I have {0}. Now I can {1}.',zh:'我已经{0}。现在我可以{1}。',slots:[choices('已经做完什么',['finished my work|完成了工作','cleaned my room|打扫了房间','packed my bag|收拾好了包']),choices('接下来能做什么',['take a break|休息一下','go outside|出去','leave home|出门'])],tip:'have / has + 过去分词连接已完成的事和现在的情况。',transfer:'出门前向朋友汇报一件已经准备好的事，再说接下来可以做什么。'},
 {id:'conditional',name:'条件与结果',match:/\bif\b/i,form:'If it {0}, I will {1}.',zh:'如果天气{0}，我就会{1}。',slots:[choices('天气条件',['rains|下雨','snows|下雪','gets cold|变冷']),choices('你会做什么',['stay at home|待在家里','take a coat|带一件外套','call my friend|给朋友打电话'])],tip:'这里练真实的未来条件：if 从句用一般现在时，结果可用 will + 动词原形。',transfer:'为明天的出行准备一个备用方案，说清条件和结果。'},
 {id:'reason',name:'原因与结果',match:/\b(?:because|therefore|so that|as a result)\b/i,form:'I {0} because {1}.',zh:'我{0}，因为{1}。',slots:[choices('你的选择',['walk to work|步行上班','study at home|在家学习','take the bus|乘公共汽车']),choices('原因',['it saves money|这样省钱','it is convenient|这样方便','it helps me concentrate|这样帮助我集中注意力'])],tip:'because 后面接完整的原因：谁或什么 + 动作或状态。检查原因是否真的支持前面的选择。',transfer:'解释今天做的一个选择，并补一个让别人能理解的原因。'},
 {id:'contrast',name:'两面与转折',match:/\b(?:although|however|even though|nevertheless)\b/i,form:'Although {0}, I {1}.',zh:'虽然{0}，我还是{1}。',slots:[choices('一个困难',['I was tired|我很累','it was raining|正在下雨','the task was difficult|任务很难']),choices('实际做了什么',['finished my work|完成了工作','kept going|继续坚持','asked for help|寻求了帮助'])],tip:'Although 表示“虽然”。先讲困难，再讲实际发生的另一面；主句不再加 but。',transfer:'讲一次遇到困难仍然完成某件事的经历，说清两面。'},
 {id:'comparison',name:'比较与选择',match:/\b(?:better|worse|cheaper|larger|bigger|smaller|more \w+|most \w+|\w+er than)\b/i,form:'This {0} is cheaper than that one. I prefer it because {1}.',zh:'这个{0}比那个便宜。我更喜欢它，因为{1}。',slots:[choices('比较什么',['bag|包','coat|外套','phone|手机']),choices('你的理由',['it is useful|它实用','it is lighter|它更轻','I like the colour|我喜欢它的颜色'])],tip:'比较级 + than。先明确比较哪两样东西，再说明选择理由。',transfer:'朋友在两件物品之间犹豫，比较它们，再给出你的选择和理由。'},
 {id:'passive',name:'介绍事物的来历',match:/\b(?:is|are|was|were)\s+(?:\w+ly\s+)?(?:built|made|found|known|called|owned|taken|\w+ed)\b/i,form:'This {0} was {1}. People still use it today.',zh:'这个{0}{1}。今天人们仍在使用它。',slots:[choices('介绍什么',['bridge|桥','building|建筑','station|车站']),choices('它的来历',['built in 1990|建于1990年','repaired last year|去年修缮过','opened many years ago|多年前就启用了'])],tip:'事物是动作的接受者：was / were + 过去分词。示范中的日期是假设情境，讲真实地点时使用已知事实。',transfer:'介绍家附近一处设施：它是什么、何时修建或修缮、现在有什么用途。'},
 {id:'relative',name:'补充说明人或物',match:/\b(?:who|which|that)\s+(?:is|are|was|were|has|have|can|\w+s)\b/i,form:'I know a person who {0}. This helps me {1}.',zh:'我认识一位{0}的人。这帮助我{1}。',slots:[choices('这个人做什么',['teaches English|教英语','works in a library|在图书馆工作','lives nearby|住在附近']),choices('带来的帮助',['learn new things|学到新东西','find useful information|找到有用的信息','feel less lonely|感到不那么孤单'])],tip:'先说人，再用 who 补充这个人的特点。例子里 a person 是单数，后面的动作注意单数形式。',transfer:'介绍一位帮助过你的人，用一句补充说明让别人知道他有什么特点。'},
);
export const sentenceFor=(frame:Frame,selected:number[],chinese=false)=>(chinese?frame.zh:frame.form).replace(/\{(\d+)\}/g,(_,i)=>{const options=frame.slots[Number(i)].options;return options[selected[Number(i)]||0]?.[chinese?'zh':'en']||options[0][chinese?'zh':'en']});
export function guideFor(rows:LanguageRow[],book:NceBookId){
 const source=rows.find(r=>frames.some(f=>f.match.test(r.en))&&r.en.length>12)||rows.find(r=>r.en.length>12)||rows[0];
 const frame=frames.find(f=>f.match.test(source?.en||''))||frames.find(f=>f.id==='identity')!;
 const start=rows.indexOf(source),parts:LanguageRow[]=[];
 for(let i=start;i>=0&&i<rows.length&&parts.length<5;i++){parts.push(rows[i]);if(/[.!?]["'”’]?\s*$/.test(rows[i].en))break;}
 const excerpt={en:parts.map(r=>r.en).join(' '),zh:parts.map(r=>r.zh).join('')};
 const level=book==='NCE1'?'sentence':book==='NCE2'?'story':'opinion';
 const prompts=level==='sentence'?['换成人物或物品','补一个自己的细节']:level==='story'?['本课这句话里发生了什么？','前后有什么原因或结果？','你遇到过什么类似情境？']:['本课这句话在说明什么？','原文的什么细节支持它？','换到生活中，什么时候适用或不适用？'];
 return {source,frame,level,excerpt,prompts,goal:`用“${frame.name}”${level==='sentence'?'说两句自己的话':level==='story'?'讲一件自己的事':'解释一个具体情境'}`};
}
export type GuideDraft={step:number;selected:number[];meaning:string;keywords:string;answer:string;repair:string;retry:string;saved:boolean;category:string;checkedAnswer:string;checkedRetry:string;checkRound:number;checkChoice:string;checkMarked:boolean;transfer:string;checkedTransfer:string;checkpointAt:number;checkpointCorrect:boolean;previousTransfer:string;form:string;source:string};
export function readGuide(raw?:string):GuideDraft{
 let d:any={};try{d=JSON.parse(raw||'{}')||{}}catch{}
 const text=(key:string)=>typeof d[key]==='string'?d[key].slice(0,5000):'';
 return {step:Number.isInteger(d.step)?Math.max(0,Math.min(4,d.step)):0,selected:Array.isArray(d.selected)?d.selected.slice(0,4).map((x:any)=>Number.isInteger(x)&&x>=0&&x<3?x:0):[],meaning:text('meaning'),keywords:text('keywords'),answer:text('answer'),repair:text('repair'),retry:text('retry'),saved:d.saved===true,category:text('category'),checkedAnswer:text('checkedAnswer'),checkedRetry:text('checkedRetry'),checkRound:Number.isInteger(d.checkRound)?Math.max(0,Math.min(10000,d.checkRound)):0,checkChoice:text('checkChoice'),checkMarked:d.checkMarked===true,transfer:text('transfer'),checkedTransfer:text('checkedTransfer'),checkpointAt:Number.isFinite(d.checkpointAt)&&d.checkpointAt>0?d.checkpointAt:0,checkpointCorrect:d.checkpointCorrect===true,previousTransfer:text('previousTransfer'),form:text('form'),source:text('source')};
}

export function transferCheck(frame:Frame,lesson:number,round:number){
 const selected=frame.slots.map((_,i)=>(lesson+round+i+1)%3),sentence=sentenceFor(frame,selected),translation=sentenceFor(frame,selected,true);
 const patterns:Record<string,[RegExp,string[]]>={
  ownership:[/^Is\b/,['Are','Do']],request:[/\b(?:open|help|say)\b/,['helping','to help']],place:[/\bis\b/,['are','am']],identity:[/\bam\b/,['is','are']],feeling:[/\bfeel\b/,['feels','feeling']],ability:[/\b(?:swim|cook|ride)\b/,['swimming','cooks']],future:[/\b(?:visit|go)\b/,['visiting','goes']],past:[/\b(?:visited|went|cooked)\b/,['go','visiting']],preference:[/\b(?:reading|swimming|cooking)\b/,['read','swim']],habit:[/\b(?:read|go|listen)\b/,['reads','going']],
  progressive:[/\b(?:reading|cooking|working)\b/,['read','works']],perfect:[/\b(?:finished|cleaned|packed)\b/,['finish','cleaning']],conditional:[/\b(?:rains|snows|gets)\b/,['rain','snowing']],reason:[/\bbecause\b/,['because of','despite']],contrast:[/^Although\b/,['Because','If']],comparison:[/\bcheaper\b/,['cheap','cheapest']],passive:[/\b(?:built|repaired|opened)\b/,['build','repairing']],relative:[/\bwho\b/,['which','where']]
 };
 const [pattern,other]=patterns[frame.id]||patterns.identity,match=sentence.match(pattern);
 if(!match)throw Error('Missing practice target: '+frame.id);
 const answer=match[0],options=[answer,...other],shift=(lesson+round)%3;
 return {id:`${frame.id}-${lesson}-${round}`,prompt:sentence.slice(0,match.index)+'____'+sentence.slice(match.index!+answer.length),translation,answer,options:options.slice(shift).concat(options.slice(0,shift)),explanation:frame.tip,transfer:frame.transfer};
}
