import type {NceBookId,Question} from './model';
import type {BlueprintTask} from './ielts-blueprint';
import {blueprintNodes} from './ielts-blueprint';

export type JourneyStage='starter'|'foundation'|'bridge'|'listening'|'reading'|'writing'|'speaking';
export const journeyStages:{id:JourneyStage;title:string;outcome:string;level:string}[]=[
 {id:'starter',title:'开口起步',outcome:'认懂一句，再换一个词说出来',level:'01'},
 {id:'foundation',title:'日常表达',outcome:'说清日常、正在做什么和经历',level:'02'},
 {id:'bridge',title:'连成一段话',outcome:'讲清顺序、原因和观点',level:'03'},
 {id:'listening',title:'听力',outcome:'跟上信息，识别改口与干扰',level:'04'},
 {id:'reading',title:'阅读',outcome:'找到证据，理解句子关系',level:'04'},
 {id:'writing',title:'写作',outcome:'概括图表，把观点解释清楚',level:'04'},
 {id:'speaking',title:'口语',outcome:'回答问题，再自然地展开',level:'04'},
];
export type MiniLesson={en:string;zh:string;tip:string;prompt:string;options:string[];answer:string;why:string;checks:Question[]};
export type JourneyMission={id:string;stage:JourneyStage;title:string;outcome:string;minutes:number;mini?:MiniLesson;course?:{book:NceBookId;lesson:number;goal:string};legacy?:string;assignment?:BlueprintTask;scoreKey?:string;draftKey?:string};
const q=(prompt:string,answer:string,explanation:string):Question=>({id:'recall',type:'input',prompt,answer,explanation});
function mini(id:string,stage:JourneyStage,title:string,outcome:string,en:string,zh:string,tip:string,prompt:string,options:string[],answer:string,why:string,checks:[string,string,string][],course?:JourneyMission['course'],legacy?:string):JourneyMission{
 return {id,stage,title,outcome,minutes:stage==='starter'?3:5,course,legacy,mini:{en,zh,tip,prompt,options,answer,why,checks:checks.map((x,i)=>({...q(...x),id:`${id}-${i}`}))}};
}
export const journeyMissions:JourneyMission[]=[
 mini('first','starter','这是我的包','认出物品，完成第一句英文。','This is my pen.','这是我的笔。','This is… 是“这是……”。my 是“我的”。只换最后一个词，就能介绍别的物品。','想说“这是我的包”，最后放哪个词？',['pen（笔）','bag（包）','book（书）'],'bag（包）','This is my bag. 只替换物品，句子前面保持不变。',[
  ['This is my ____.（这是我的包。）只填表示“包”的词。','bag','bag 是包；This is my bag.'],['This is my ____.（这是我的书。）book 是书，请填空。','book','This is my book.'],['This is my ____.（这是我的笔。）只填物品。','pen','This is my pen.']],undefined,'starter.first'),
 mini('question','starter','问一句，答一句','把刚才的陈述变成简单问答。','Is this your bag? — Yes, it is.','这是你的包吗？——是的。','提问时 Is 放到 this 前面。your 是“你的”，Yes 表示肯定。','怎样问“这是你的包吗”？',['This is your bag.','Is this your bag?'],'Is this your bag?','把 Is 移到开头，这句话就变成提问。',[
  ['____ this your book?（这是你的书吗？）只填句首一个词。','Is','Is this your book?'],['Is this your pen? — ____, it is.（是的。）只填肯定回答开头。','Yes','Yes, it is.'],['Is this your bag? — No, it is ____.（不，不是。）只填否定词。','not','No, it is not.']],{book:'NCE1',lesson:1,goal:'be-question'},'starter.question'),
 mini('myself','starter','用一句话介绍自己','用 I am… 介绍身份。','I am a student.','我是一名学生。','I 是“我”，am 接在 I 后面。a student 是一名学生。','模拟介绍一名老师，选哪个句子？',['I am a teacher.','You are a teacher.'],'I am a teacher.','I am… 的主语是“我”；teacher 是老师。',[
  ['I ____ a student.（我是一名学生。）填 am / is / are 中的一个。','am','I 和 am 搭配。'],['She ____ a teacher.（她是一名老师。）填 am / is / are 中的一个。','is','She 和 is 搭配。'],['You ____ a student.（你是一名学生。）填 am / is / are 中的一个。','are','You 和 are 搭配。']],{book:'NCE1',lesson:7,goal:'be'},'starter.myself'),
 mini('whose','starter','分清“我的”和“你的”','说清物品属于谁。','This is my book. That is your book.','这是我的书。那是你的书。','my = 我的，your = 你的；先认识这两个词，再换成别人的名字。','对朋友说“这是你的笔”，选哪一个？',['This is my pen.','This is your pen.'],'This is your pen.','your 指对方的；my 指自己的。',[
  ['This is ____ bag.（这是我的包。）填 my 或 your。','my','my 表示我的。'],['Is this ____ pen?（这是你的笔吗？）填 my 或 your。','your','your 表示你的。'],['That is ____ book.（那是我的书。）填 my 或 your。','my','That is my book.']],{book:'NCE1',lesson:11,goal:'possession'}),
 mini('more-than-one','starter','从一个物品到两个','认识最常用的规则复数。','one book → two books','一本书 → 两本书','先练 book、pen、bag 这样的规则变化：多于一个时，词尾加 s。其他变化遇到时再补。','two 后面用哪一个？',['book','books'],'books','two books 表示两本书。',[
  ['two ____（两支笔）。pen 是笔，填它的复数。','pens','pen 的规则复数是 pens。'],['three ____（三个包）。bag 是包，填它的复数。','bags','bag 的规则复数是 bags。'],['two ____（两本书）。book 是书，填它的复数。','books','book 的规则复数是 books。']],{book:'NCE1',lesson:17,goal:'countable'}),
 mini('where','starter','给物品加一个位置','用 in / on 说清放在哪里。','The book is on the desk.','书在桌子上。','on = 在表面上；in = 在里面。先学这两个位置，不一次背很多介词。','想说“笔在包里面”，选哪个词？',['on（在上面）','in（在里面）'],'in（在里面）','The pen is in the bag. 笔在包里面。',[
  ['The book is ____ the desk.（书在桌子表面上。）填 in 或 on。','on','on 表示在表面上。'],['The pen is ____ the bag.（笔在包里面。）填 in 或 on。','in','in 表示在里面。'],['The bag is ____ the chair.（包在椅子上。）填 in 或 on。','on','The bag is on the chair.']],{book:'NCE1',lesson:25,goal:'place'}),
 mini('daily','foundation','说说每天做什么','用简单现在时说习惯。','I work every day. She works every day.','我每天工作。她每天工作。','先说 I work，再换成 she；一般现在时中，she / he / it 后的动词常加 s。','“她每天阅读”是哪句？',['She read every day.','She reads every day.'],'She reads every day.','She reads… 中的 reads 表示她的日常习惯。',[
  ['She ____ every day.（她每天工作。）用 work 的合适形式。','works','She works every day.'],['I ____ every day.（我每天阅读。）用 read 的合适形式。','read','I 后面这里用 read。'],['He ____ every day.（他每天步行。）用 walk 的合适形式。','walks','He walks every day.']],{book:'NCE1',lesson:49,goal:'present-simple'}),
 mini('daily-question','foundation','问问别人的日常','借助 Do / Does 提问。','Do you like tea? Does she like tea?','你喜欢茶吗？她喜欢茶吗？','you 配 do；she 配 does。Does 已带出人称变化，后面保留 like。','“她喜欢茶吗？”选哪个？',['Does she likes tea?','Does she like tea?'],'Does she like tea?','用了 Does，后面的动词就保留原形 like。',[
  ['____ you like coffee?（你喜欢咖啡吗？）填 Do 或 Does。','Do','Do you like coffee?'],['____ he work here?（他在这里工作吗？）填 Do 或 Does。','Does','Does he work here?'],['Does she ____ tea?（她喜欢茶吗？）用 like 的合适形式。','like','Does she like tea?']],{book:'NCE1',lesson:49,goal:'present-simple'}),
 mini('not','foundation','说清“不是”和“不做”','用否定表达真实意思。','I do not like coffee.','我不喜欢咖啡。','一般动词前加 do not；she / he / it 用 does not。am / is / are 后直接加 not。','哪句表示“她不喜欢咖啡”？',['She does not like coffee.','She not like coffee.'],'She does not like coffee.','does not 放在 like 前面。',[
  ['I do ____ like tea.（我不喜欢茶。）填一个否定词。','not','I do not like tea.'],['She ____ not work here.（她不在这里工作。）填 do 或 does。','does','She does not work here.'],['I am ____ a teacher.（我不是老师。）填一个否定词。','not','I am not a teacher.']],{book:'NCE1',lesson:49,goal:'present-simple'}),
 mini('can','foundation','说说自己会做什么','用 can + 动词表达能力。','I can swim. Can you swim?','我会游泳。你会游泳吗？','can 后用动词原形。提问时把 can 移到开头。','哪句表示“她会游泳”？',['She can swim.','She can swims.'],'She can swim.','can 后面用 swim，不加 s。',[
  ['She can ____.（她会阅读。）用 read 的合适形式。','read','can 后面用动词原形 read。'],['____ you swim?（你会游泳吗？）填表示能力的词。','Can','Can you swim?'],['I can ____ English.（我会说英语。）用 speak 的合适形式。','speak','I can speak English.']],{book:'NCE1',lesson:45,goal:'can'}),
 mini('now','foundation','说说此刻正在做什么','区分现在进行与日常习惯。','I am reading now.','我现在正在阅读。','am / is / are + 动词 ing，表示正在发生的事。先保留 I am，只换最后的动作。','“她现在正在工作”选哪个？',['She is working now.','She works every day.'],'She is working now.','is working 表示此刻正在工作。',[
  ['I am ____ now.（我现在正在阅读。）用 read 的 ing 形式。','reading','I am reading now.'],['She ____ working now.（她现在正在工作。）填 am / is / are。','is','She is working now.'],['They ____ reading now.（他们现在正在阅读。）填 am / is / are。','are','They are reading now.']],{book:'NCE1',lesson:31,goal:'present-continuous'}),
 mini('yesterday','foundation','讲一件昨天的小事','从现在的动作过渡到过去。','I worked yesterday.','我昨天工作了。','yesterday 是昨天。先学规则变化 work → worked，再按用到的任务认识不规则变化。','哪一句明确在说昨天？',['I work every day.','I worked yesterday.'],'I worked yesterday.','worked 和 yesterday 一起把事情放到过去。',[
  ['I ____ yesterday.（我昨天步行了。）用 walk 的过去式。','walked','walk → walked。'],['She ____ yesterday.（她昨天工作了。）用 work 的过去式。','worked','过去式 worked 不随人称变成 works。'],['We ____ the park yesterday.（我们昨天参观了公园。）用 visit 的过去式。','visited','visit → visited。']],{book:'NCE1',lesson:71,goal:'past-simple'}),
 mini('tomorrow','foundation','说说明天的计划','把熟悉的动作放进未来。','I am going to read tomorrow.','我打算明天阅读。','am / is / are going to + 动词原形，先说一个具体计划。tomorrow 是明天。','“她打算工作”选哪个？',['She is going to work.','She is going to worked.'],'She is going to work.','going to 后面用 work。',[
  ['I am going to ____ tomorrow.（我打算明天阅读。）用 read 的合适形式。','read','I am going to read tomorrow.'],['She ____ going to work.（她打算工作。）填 am / is / are。','is','She is going to work.'],['We ____ going to visit the park.（我们打算参观公园。）填 am / is / are。','are','We are going to visit the park.']],{book:'NCE1',lesson:37,goal:'going-to'}),
 mini('experience','bridge','区分经历和昨天的事','先辨认有没有明确过去时间。','I have visited London. I visited London last year.','我去过伦敦。我去年去了伦敦。','第一句说经历；第二句带 last year，明确说过去的时间。先用时间线理解，再补更多用法。','“我去年去过伦敦”这里选哪个？',['I have visited London last year.','I visited London last year.'],'I visited London last year.','明确的过去时间 last year 与一般过去时配合。',[
  ['I ____ London yesterday.（我昨天参观了伦敦。）用 visit 的合适形式。','visited','yesterday 指明确过去时间，用 visited。'],['I have ____ London.（我去过伦敦。）用 visit 的过去分词。','visited','规则动词 visit 的过去分词也是 visited。'],['She ____ visited London.（她去过伦敦。）填 have 或 has。','has','She has visited London.']],{book:'NCE2',lesson:5,goal:'past-or-perfect'}),
 mini('compare','bridge','比较两样东西','先比较一个共同维度。','This room is larger than that one.','这个房间比那个大。','比较两个事物时，large → larger，than 连接比较对象；先说大小，再逐渐换维度。','哪句在比较两个房间？',['This room is larger than that one.','This room is large.'],'This room is larger than that one.','larger than 明确表示“比……大”。',[
  ['This room is ____ than that one.（这个房间更小。）用 small 的比较级。','smaller','small → smaller。'],['This bag is larger ____ that one.（这个包比那个大。）填连接比较对象的词。','than','larger than…'],['This room is ____ than that one.（这个房间更大。）用 large 的比较级。','larger','large → larger。']],{book:'NCE2',lesson:8,goal:'comparison'}),
 mini('reason','bridge','给一句话补一个原因','用 because 把两句意思接起来。','I read because it is fun.','我阅读，因为这很有趣。','先说观点或事情，再用 because 给原因。不要一开始就追求很长的句子。','哪句给出了阅读的原因？',['I read books.','I read because it is fun.'],'I read because it is fun.','because 后面补充为什么阅读。',[
  ['I walk ____ it is good for me.（我步行，因为这对我有好处。）填“因为”。','because','because 引出原因。'],['I stay home ____ it is raining.（我留在家里，因为正在下雨。）填“因为”。','because','I stay home because it is raining.'],['I like this room ____ it is quiet.（我喜欢这个房间，因为它安静。）填“因为”。','because','一个观点加一个原因，已经是一小段表达的基础。']],{book:'NCE2',lesson:49,goal:'complex-sentences'}),
 mini('sequence','bridge','把一件事按顺序讲清楚','用 First / Then 连接两个动作。','First, I made tea. Then, I read a book.','先泡茶，然后读了一本书。','先把每个动作说清楚，再用顺序词连接。made 是 make 的过去式。','哪一个表示“然后”？',['First','Then'],'Then','First 是首先，Then 是然后。',[
  ['First, I had breakfast. ____, I went to work.（然后去上班。）填 Then 或 Because。','Then','Then 标出下一件事。'],['____, I opened the book. Then, I read.（首先打开书。）填 First 或 Then。','First','First 标出第一步。'],['First, we walked. ____, we had lunch.（然后吃午饭。）填 Then 或 But。','Then','Then 让听者跟上事情的顺序。']]),
 mini('contrast','bridge','补一个不同的情况','用 but 说清转折。','The room is small, but it is quiet.','房间小，但是很安静。','先陈述事实，再补一个不同角度。but 后面不用把前面的话重新说一遍。','哪句同时说出缺点和优点？',['The room is small and small.','The room is small, but it is quiet.'],'The room is small, but it is quiet.','but 连接“小”和“安静”这两个不同角度。',[
  ['The bag is old, ____ it is useful.（包旧，但是有用。）填 but 或 because。','but','but 表示转折。'],['I like tea, ____ I do not like coffee.（我喜欢茶，但是不喜欢咖啡。）填 but 或 because。','but','but 对照两种不同喜好。'],['The trip was long, ____ it was interesting.（旅程长，但是有趣。）填 but 或 because。','but','保留两句的主干，再用 but 连接。']],{book:'NCE2',lesson:49,goal:'complex-sentences'}),
 mini('long-sentence','bridge','长句里先找到主干','把补充说明先放在一边。','The book that I bought yesterday is useful.','我昨天买的那本书很有用。','先看 The book is useful. 中间 that I bought yesterday 只是说明是哪本书。','这句话的核心意思是什么？',['那本书很有用。','我今天要买一本书。'],'那本书很有用。','抓住 The book + is + useful，再把补充信息接回来。',[
  ['The bag that she bought is red. 这句话说包是什么颜色？只填英文颜色。','red','主干是 The bag is red.'],['The teacher who lives here is kind. 这句话说老师怎样？只填 kind 或 here。','kind','主干是 The teacher is kind.'],['The room that we saw is small. 这句话说房间怎样？只填英文形容词。','small','主干是 The room is small.']],{book:'NCE1',lesson:121,goal:'relative'}),
 mini('paragraph','bridge','用证据理解一小段','区分作者说了什么和自己的猜测。','Lina walks to work. It takes ten minutes. She likes the fresh air.','Lina 步行上班。花十分钟。她喜欢清新的空气。','先抓三件事：怎么去、花多久、为什么喜欢。没有说的内容，不替作者补上。','Lina 上班要多久？',['十分钟','三十分钟'],'十分钟','It takes ten minutes. 就是答案依据。',[
  ['Ben reads after dinner. He reads for twenty minutes. 他读多久？只填英文数字词。','twenty','证据是 for twenty minutes。'],['Mia travels by bus. The journey takes ten minutes. 她乘什么？只填英文交通工具。','bus','证据是 by bus。'],['Leo likes the park because it is quiet. 他喜欢公园的什么特点？只填英文形容词。','quiet','because 后面直接给出原因。']]),
 mini('hear-correction','listening','听到改口，更新答案','从字面理解过渡到听力干扰。','We meet at six—sorry, at seven.','我们六点见——抱歉，是七点。','先看改口的意思，再听示范。正式听力里，最先听到的信息不一定是最后答案。','最后约在几点？',['six','seven'],'seven','sorry 后面的 seven 修正了 six。',[
  ['“The room is 12—sorry, 20.” 最后确认的房间号是多少？填数字。','20','改口后最终确认 20。'],['“Tuesday? No, Wednesday.” 最后确认哪一天？填英文。','Wednesday','No 后面的 Wednesday 才是最终选择。'],['“At nine—actually, at ten.” 最后确认几点？填英文数字词。','ten','actually 提示信息更新。']]),
 mini('read-evidence','reading','分清“没说”和“说错了”','为判断题找到原文依据。','The museum opens at nine.','博物馆九点开门。','原文说了开门时间，没有说门票价格。Not Given 是未提供依据，不是“我不知道”。','题干：门票免费。根据这句原文，应选？',['True','False','Not Given'],'Not Given','原文没有提供票价，不能从开门时间推断免费。',[
  ['原文：The shop closes at six. 题干：The shop closes at seven. 填 True / False / Not Given。','False','六点与七点矛盾，所以 False。'],['原文：The library opens on Monday. 题干：It opens on Monday. 填 True / False / Not Given。','True','两句信息相同。'],['原文：The café is near the station. 题干：The coffee is cheap. 填 True / False / Not Given。','Not Given','位置不能证明价格。']]),
 mini('write-reason','writing','让一个观点站得住','先连好观点和理由，再写整篇。','Libraries are useful because people can study there for free.','图书馆有用，因为人们可以在那里免费学习。','先回答题目，再写与观点直接相关的理由。下一步才补具体例子。','哪一个理由支持“图书馆有用”？',['People can study there for free.','I had tea yesterday.'],'People can study there for free.','免费学习与图书馆的价值直接相关。',[
  ['观点：Public parks are useful. 理由：People can exercise there. 用一个词连接：Parks are useful ____ people can exercise there.','because','because 把观点和理由连起来。'],['观点：Buses can reduce traffic. 例子：One bus carries many people. 填 example 或 however：For ____, one bus can carry many people.','example','For example 引出支持观点的例子。'],['观点：Reading helps us learn. 理由：Books give us information. 填 because 或 although：Reading helps us learn ____ books give us information.','because','先明确原因和观点之间的关系。']],{book:'NCE2',lesson:49,goal:'complex-sentences'}),
 mini('write-overview','writing','先找图表的主要变化','Academic Task 1 从整体概括开始。','Library visits rose from 100 to 200. Museum visits stayed at 80.','图书馆访问量从 100 升到 200。博物馆访问量保持 80。','先选最重要的变化，不急着把每个数字重新抄一遍。','哪一句最适合概括？',['Library visits rose, while museum visits were unchanged.','The numbers are 100, 200 and 80.'],'Library visits rose, while museum visits were unchanged.','整体概括要说出变化和对比。',[
  ['Visits rose from 50 to 100. 访问量是上升还是下降？填 rose 或 fell。','rose','50 到 100 是上升。'],['Visits stayed at 80 in both years. 两年数值是否改变？填 changed 或 unchanged。','unchanged','stayed at 表示保持不变。'],['A rose, ____ B fell.（A 上升，而 B 下降。）填 while 或 because。','while','while 在这里连接相反趋势。']]),
 mini('speak-detail','speaking','先回答，再补一个细节','口语不从背整篇答案开始。','I like reading. I usually read before bed.','我喜欢阅读。我通常在睡前阅读。','回答喜好后，补时间、地点或一个真实小例子。这里只练组织方式，发音要另外回听。','别人问你喜欢阅读吗，哪个回答更完整？',['Yes. I usually read before bed.','Before bed.'],'Yes. I usually read before bed.','先回答问题，再补 before bed 这个细节。',[
  ['Do you like walking? 先直接肯定回答，只填 Yes 或 When。','Yes','先直接回答，再加一个理由或细节。'],['I like reading ____ it helps me relax. 填 because 或 but。','because','用 because 把喜好和原因联系起来。'],['I usually walk ____ dinner.（我通常晚饭后散步。）填 after 或 because。','after','after dinner 补充具体时间。']]),
 ...blueprintNodes.filter(n=>['listening','reading','writing','speaking'].includes(n.id)).flatMap(n=>n.tasks.map(t=>({
  id:`${n.id}-${t.id}`,stage:n.id as JourneyStage,title:t.title,outcome:t.work,minutes:t.id==='full'||t.id==='feedback'?60:15,assignment:t,legacy:`${n.id}.${t.id}`,
  ...(t.id==='locate'?{scoreKey:'ielts-listening'}:t.id==='evidence'?{scoreKey:'ielts-reading'}:t.id==='task-one'?{draftKey:'ielts-w1'}:t.id==='task-two'?{draftKey:'ielts-w3'}:{}),
 }))),
];
export const missionById=(id?:string)=>journeyMissions.find(m=>m.id===id);
