export type Question={id:string,type:'choice'|'input',prompt:string,options?:string[],answer:string,accepted?:string[],explanation:string};
export type Word={word:string,ipa?:string,meaning:string,example:string};
export type Lesson={id:number,title:string,subtitle:string,level:string,theme:string,goal:string,dialogue:{speaker:string,en:string,zh:string}[],vocab:Word[],grammar:{title:string,rule:string,formula:string,examples:{en:string,zh:string}[],pitfall:string},patterns:{en:string,zh:string}[],exercises:Question[]};
export type NceBookId="NCE1"|"NCE2"|"NCE3"|"NCE4";
export type NceEntry={title:string,text:string,notes:string,steps:string[]};
export const bookCounts:Record<NceBookId,number>={NCE1:144,NCE2:96,NCE3:60,NCE4:48};
export const nceSteps=["listen","words","retell","practice"];
export function validNceKey(k:string){const [book,no]=k.split("-");return Object.hasOwn(bookCounts,book)&&/^[1-9]\d*$/.test(no||"")&&Number(no)<=(bookCounts as Record<string,number>)[book]&&k===`${book}-${Number(no)}`;}
export type State={nce?:Record<string,NceEntry>,nceLast?:{book:NceBookId,lesson:number},nceEdition?:"standard"|"85",personalWords?:Word[],version:1,lastLesson:number,completed:number[],scores:Record<string,number>,mistakes:Record<string,Question>,cards:Record<string,{box:number,due:number}>,days:string[],attempts:number,correct:number,drafts:Record<string,string>,custom:{id:string,title:string,text:string}[]};
export const initial:State={version:1,lastLesson:1,completed:[],scores:{},mistakes:{},cards:{},days:[],attempts:0,correct:0,drafts:{},custom:[]};
export const normal=(s:string)=>s.toLowerCase().trim().replace(/[’‘]/g,"'").replace(/[.,!?;:]/g,'').replace(/\s+/g,' ');
export const isCorrect=(q:Question,a:string)=>[q.answer,...(q.accepted||[])].some(x=>normal(x)===normal(a));
export const day=()=>new Date().toLocaleDateString('en-CA');
export const wordCount=(s:string)=>(s.match(/(?:[A-Za-z]+(?:['’-][A-Za-z]+)*|\d+(?:[.,]\d+)*(?:%|[A-Za-z]+)?)/g)||[]).length;
export function validateState(v:any):v is State {
 const record=(x:any)=>x&&typeof x==='object'&&!Array.isArray(x)&&Object.keys(x).length<10000&&!Object.keys(x).some(k=>['__proto__','constructor','prototype'].includes(k));
 const nceOk=v?.nce===undefined||(record(v.nce)&&Object.keys(v.nce).length<=348&&Object.entries(v.nce).every(([k,e]:any)=>validNceKey(k)&&e&&typeof e.title==='string'&&e.title.length<=120&&typeof e.text==='string'&&e.text.length<=50000&&typeof e.notes==='string'&&e.notes.length<=12000&&Array.isArray(e.steps)&&e.steps.length<=4&&new Set(e.steps).size===e.steps.length&&e.steps.every((s:any)=>nceSteps.includes(s))));
 const lastOk=v?.nceLast===undefined||(v.nceLast&&Number.isInteger(v.nceLast.lesson)&&validNceKey(`${v.nceLast.book}-${v.nceLast.lesson}`));
 const wordsOk=v?.personalWords===undefined||(Array.isArray(v.personalWords)&&v.personalWords.length<=2000&&v.personalWords.every((w:any)=>w&&typeof w.word==='string'&&w.word.trim().length>0&&w.word.length<=100&&typeof w.meaning==='string'&&w.meaning.length<=300&&typeof w.example==='string'&&w.example.length<=1000&&(w.ipa===undefined||typeof w.ipa==='string'&&w.ipa.length<=100)));
 return nceOk&&lastOk&&wordsOk&&[undefined,'standard','85'].includes(v?.nceEdition)&&v?.version===1&&Number.isInteger(v.lastLesson)&&v.lastLesson>=1&&v.lastLesson<=36&&Array.isArray(v.completed)&&v.completed.length<=36&&v.completed.every((x:any)=>Number.isInteger(x)&&x>=1&&x<=36)&&record(v.scores)&&Object.values(v.scores).every(x=>typeof x==='number'&&x>=0&&x<=100)&&record(v.mistakes)&&Object.entries(v.mistakes).every(([k,q]:any)=>q?.id===k&&typeof q.prompt==='string'&&typeof q.answer==='string'&&typeof q.explanation==='string'&&['choice','input'].includes(q.type)&&(q.type!=='choice'||Array.isArray(q.options)&&q.options.every((s:any)=>typeof s==='string'))&&(!q.accepted||Array.isArray(q.accepted)&&q.accepted.every((s:any)=>typeof s==='string')))&&record(v.cards)&&Object.values(v.cards).every((x:any)=>Number.isInteger(x.box)&&x.box>=0&&x.box<=5&&Number.isFinite(x.due))&&Array.isArray(v.days)&&v.days.every((x:any)=>typeof x==='string')&&Number.isInteger(v.attempts)&&v.attempts>=0&&Number.isInteger(v.correct)&&v.correct>=0&&v.correct<=v.attempts&&record(v.drafts)&&Object.values(v.drafts).every(x=>typeof x==='string')&&Array.isArray(v.custom)&&v.custom.length<=100&&v.custom.every((x:any)=>typeof x.id==='string'&&typeof x.title==='string'&&typeof x.text==='string'&&x.text.length<=50000);
}
