'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,ChevronLeft,ChevronRight,ExternalLink,Headphones,Layers,NotebookPen,Play,Plus,Search,Square,Upload,Volume2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {toast} from 'sonner';
import {State,NceBookId,NceEntry,Word,Question,bookCounts,normal} from './model';
import {speak,Recorder,WordCard,Quiz} from './learning';
import {LocalMaterials} from './offline-tools';
import {readAudio,saveAudio,audioMime} from './offline-store';
import {parseLessonText} from './nce-utils';
import {ONLINE} from './runtime-mode';
import companionData from './data/book-companion.json';
const books=[
 {id:'NCE1',number:'01',name:'第一册',en:'First Things First',theme:'从开口说，到说清楚',description:'日常对话 · 发音与基础句型',color:'cobalt',focus:'打好基本功'},
 {id:'NCE2',number:'02',name:'第二册',en:'Practice & Progress',theme:'把经历，讲成一个故事',description:'时态系统 · 叙事与段落表达',color:'teal',focus:'建立表达体系'},
 {id:'NCE3',number:'03',name:'第三册',en:'Developing Skills',theme:'读懂细节，也读懂言外之意',description:'长难句 · 语篇与准确表达',color:'violet',focus:'提升理解深度'},
 {id:'NCE4',number:'04',name:'第四册',en:'Fluency in English',theme:'有观点，也有论证',description:'抽象议题 · 批判阅读与写作',color:'ochre',focus:'走向成熟表达'}
] as const;
type Companion={goals:string[],routine:string[],grammar:{id:string,title:string,rule:string,formula:string,examples:{en:string,zh:string}[],pitfall:string,exercise:Question}[]};
const companion=companionData as Record<NceBookId,Companion>;
const steps=[['listen','听读跟练'],['words','词句整理'],['retell','独立复述'],['practice','完成练习']] as const;
const blank:NceEntry={title:'',text:'',notes:'',steps:[]};

export function nceCompleted(state:State){return Object.values(state.nce||{}).filter(e=>e.steps.length===4).length;}
type Props={state:State,update:(fn:(state:State)=>State)=>void,addWord:(w:Word)=>void,onAnswer:(q:Question,ok:boolean)=>void,openCourse:(id:number)=>void,goIELTS:()=>void,goCloud?:()=>void,startAt?:{book:NceBookId,lesson:number}|null};
export default function NceStudio({state,update,addWord,onAnswer,openCourse,goIELTS,goCloud,startAt}:Props){
 const [mode,setMode]=useState<'home'|'book'|'lesson'>(startAt?'lesson':'home'),[bookId,setBookId]=useState<NceBookId>(startAt?.book||state.nceLast?.book||'NCE1'),[lessonNo,setLessonNo]=useState(startAt?.lesson||state.nceLast?.lesson||1),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[jump,setJump]=useState(''),[tab,setTab]=useState('listen');
 const book=books.find(b=>b.id===bookId)!,count=bookCounts[bookId],key=`${bookId}-${lessonNo}`,entry=state.nce?.[key]||blank;
 const completed=(id:NceBookId)=>Object.entries(state.nce||{}).filter(([k,e])=>k.startsWith(id+'-')&&e.steps.length===4).length;
 function openBook(id:NceBookId){window.speechSynthesis?.cancel();setBookId(id);setFilter('all');setSearch('');setMode('book');window.scrollTo({top:0})}
 function openLesson(id:NceBookId,no:number){window.speechSynthesis?.cancel();setBookId(id);setLessonNo(no);setTab('listen');setMode('lesson');update(s=>({...s,nceLast:{book:id,lesson:no}}));window.scrollTo({top:0})}
 function patch(data:Partial<NceEntry>){update(s=>({...s,nce:{...s.nce,[key]:{...(s.nce?.[key]||blank),...data}}}))}
 const last=state.nceLast||{book:'NCE1' as const,lesson:1};
 const visible=Array.from({length:count},(_,i)=>i+1).filter(n=>{const e=state.nce?.[`${bookId}-${n}`];return(filter==='all'||filter==='done'&&e?.steps.length===4||filter==='active'&&!!e&&(e.steps.length>0||!!e.text||!!e.notes)&&e.steps.length<4)&&(`${n} ${e?.title||''}`).toLowerCase().includes(search.toLowerCase())});
 return <div className="nce-studio">
 {mode==='home'?<>
  <div className="page-heading"><div><div className="eyebrow">NEW CONCEPT · YOUR STUDY STUDIO</div><h1>四册英语，一步一步学透。</h1><p>从日常表达，到阅读、思考和写作。让每一课都留下真正的进步。</p></div><div className="row wrap">{ONLINE&&<button className="btn" onClick={goCloud}><BookOpen size={17}/>教材与音频</button>}<LocalMaterials state={state} update={update}/></div></div>
  <section className="nce-hero"><div><span className="overline">YOUR NEXT CHAPTER</span><h2>读过，听过，<br/>更要能自己说出来。</h2><p>听读教材 → 整理词句 → 跟读复述 → 检查掌握</p><button className="btn white" onClick={()=>openLesson(last.book,last.lesson)}><Play size={16}/>{state.nceLast?'继续':'开始'}{books.find(b=>b.id===last.book)?.name} · 第 {last.lesson} 课 <ArrowRight size={17}/></button></div><div className="nce-hero-meter"><strong>{nceCompleted(state)}<span> / 348</span></strong><p>已完成全部四项训练的课次</p><Progress value={nceCompleted(state)/348*100}/><small>学习记录保存在本机，可导出备份</small></div></section>
  <div className="section-top section-space"><div><h2>选择你的这一册</h2><p className="muted">随时从适合自己的阶段开始。</p></div><span className="small muted">{ONLINE?"在线学习 · 网站教材":"断网可用 · 资料留在本机"}</span></div>
  <div className="nce-book-grid">{books.map(b=><button key={b.id} className={'nce-book '+b.color} onClick={()=>openBook(b.id)}><div className="nce-cover"><span className="nce-cover-label">NEW CONCEPT<br/>ENGLISH</span><strong>{b.number}</strong><span className="nce-cover-foot">{b.en}<ArrowUpRight size={19}/></span></div><div className="nce-book-body"><div className="section-top"><h3>{b.name}</h3><span>{bookCounts[b.id]} 课</span></div><h4>{b.theme}</h4><p>{b.description}</p><Progress value={completed(b.id)/bookCounts[b.id]*100}/><div className="section-top small"><span>{completed(b.id)} 课已完成</span><ArrowRight size={17}/></div></div></button>)}</div>
  <div className="nce-bottom-grid"><section className="panel"><div className="row"><Headphones className="accent"/><h3>{ONLINE?"原书和音频，直接在网站学习":"课文和音频，一起留在本机"}</h3></div><p className="muted small">{ONLINE?"从「教材与音频」在线读原书、听课文。PDF 和 MP3 接入后直接由网站提供，不需要连接网盘。当前尚未上传四册教材。":"选择教材文件夹，核对课号后导入 TXT、LRC 和音频。已导入资料断网可用；到「学习档案」导出完整资料包，即可一起搬到其他电脑。本站不预装四册教材文件。"}</p><details className="offline-resource-help"><summary>教材资料从哪里获取？</summary><p>外研社官方说明：智慧版可通过书后二维码在「外研 U 学」激活，获得配套听读与练习。暂未核实有可自由下载的四册全文与 MP3 包，也未核实 App 资源可导出。已有本地音频、TXT 或 LRC 可直接导入。资料核对：2026-09-26。</p><small>官方说明：www.fltrp.com/ebook/jcjyyjzx/2023_jcjyjxzy/files/basic-html/page62.html</small></details></section><section className="panel nce-ielts"><div className="eyebrow">BEYOND THE BOOKS</div><h3>把阅读积累，用到雅思任务里。</h3><p className="muted small">额外练习限时听读、口语组织和写作。学完教材并不自动等于取得某个雅思分数。</p><button className="text-btn" onClick={goIELTS}>进入雅思训练 <ArrowRight size={16}/></button></section></div>
 </>:<>
  <button className="text-btn nce-back" onClick={()=>mode==='lesson'?openBook(bookId):setMode('home')}><ArrowLeft size={16}/>{mode==='lesson'?`返回${book.name}目录`:'返回四册总览'}</button>
  <div className="nce-book-heading"><div><div className="eyebrow">BOOK {book.number} · {book.en.toUpperCase()}</div><h1>{book.name}{mode==='lesson'?` · 第 ${lessonNo} 课`:`：${book.theme}`}</h1><p className="muted">{mode==='lesson'?(entry.title||'给这一课，留下属于你的表达。'):book.description}</p></div><LocalMaterials state={state} update={update} book={bookId} label={`导入${book.name}资料`}/></div>
  <div className="nce-source-line"><span>{ONLINE?"本课记录保存在当前浏览器。教材与音频可读 PDF、听音频，再带入本课练习。":"本地模式 · 文本、音频与学习记录保存在当前浏览器；不连接外部点读服务。"}</span></div>
 {mode==='book'?<>
  <div className="nce-book-intro"><section className="panel"><div className="section-top"><h3>这一阶段，重点练什么</h3><span className="pill">{book.focus}</span></div><ul>{companion[bookId].goals.map(g=><li key={g}>{g}</li>)}</ul><div className="row wrap"><button className="btn secondary" onClick={()=>openLesson(bookId,state.nceLast?.book===bookId?state.nceLast.lesson:1)}>开始本册学习 <ArrowRight size={16}/></button><button className="text-btn" onClick={()=>document.getElementById('book-grammar')?.scrollIntoView({behavior:'smooth'})}>查看本册语法补强</button></div></section><section className="panel"><span className="eyebrow">BOOK PROGRESS</span><div className="big-stat">{completed(bookId)}<span>/ {count} 课</span></div><Progress value={completed(bookId)/count*100}/><p className="muted small">每课完成听读、词句、复述、练习四项后计入。这里记录纸质教材课号，导入合并课次时请核对文件对应关系。</p></section></div>
  <div className="filter-bar"><div className="nce-filters">{[['all','全部课次'],['active','学习中'],['done','已完成']].map(([v,label])=><button className={filter===v?'active':''} key={v} onClick={()=>setFilter(v)}>{label}</button>)}</div><label className="search"><Search size={17}/><input aria-label="搜索本册课号或笔记标题" placeholder="搜索课号或自定义标题" value={search} onChange={e=>setSearch(e.target.value)}/></label><form className="nce-jump" onSubmit={e=>{e.preventDefault();const n=Number(jump);if(Number.isInteger(n)&&n>=1&&n<=count)openLesson(bookId,n);else toast.error(`请输入 1–${count} 的课号`)}}><input type="number" min="1" max={count} aria-label="跳转课号" placeholder="课号" value={jump} onChange={e=>setJump(e.target.value)}/><button className="btn secondary" type="submit">前往</button></form></div>
  <div className="nce-lesson-grid">{visible.map(n=>{const e=state.nce?.[`${bookId}-${n}`];return <button key={n} className={'nce-lesson '+(e?.steps.length===4?'done':'')} onClick={()=>openLesson(bookId,n)}><span className="section-top"><b>{String(n).padStart(3,'0')}</b>{e?.steps.length===4?<Check size={17}/>:<ChevronRight size={16}/>}</span><strong>{e?.title||`第 ${n} 课`}</strong><span className="nce-mini-steps">{steps.map(([id,label])=><i key={id} className={e?.steps.includes(id)?'checked':''} aria-label={label+(e?.steps.includes(id)?'已完成':'未完成')}/>)}</span><small>{e?.steps.length===4?'已完成':e?.steps.length?`${e.steps.length} / 4 项训练` :e?.text?'已导入课文':'开始学习'}</small></button>})}</div>{visible.length===0&&<div className="empty">没有符合条件的课次，试试其他筛选。</div>}
  <BookGrammar key={bookId} bookId={bookId} onAnswer={onAnswer} update={update}/>
 </>:<>
  <div className="nce-checks">{steps.map(([id,label],i)=><label key={id} className={entry.steps.includes(id)?'checked':''}><Checkbox checked={entry.steps.includes(id)} onCheckedChange={checked=>{patch({steps:checked?[...entry.steps,id]:entry.steps.filter(s=>s!==id)});update(s=>({...s,days:[...new Set([...s.days,new Date().toLocaleDateString('en-CA')])]}))}}/><span><strong>{label}</strong><small>{companion[bookId].routine[i]}</small></span></label>)}</div>
  <Tabs value={tab} onValueChange={v=>{window.speechSynthesis?.cancel();setTab(v)}}><TabsList className="lesson-tabs"><TabsTrigger value="listen">听读与课文</TabsTrigger><TabsTrigger value="words">我的词句</TabsTrigger><TabsTrigger value="notes">复述与笔记</TabsTrigger><TabsTrigger value="grammar">语法补强</TabsTrigger></TabsList>
  <TabsContent value="listen"><ImportedLesson key={key} entry={entry} patch={patch} lessonKey={key}/></TabsContent>
  <TabsContent value="words"><WordCollector state={state} addWord={addWord}/></TabsContent>
  <TabsContent value="notes"><div className="two-col section-space"><section className="panel"><h3>合上书，用自己的话讲一遍</h3><p className="muted">先写 3 个关键词，再说出这课的主要内容。最后选一个句型，替换成你自己的经历或观点。</p><Recorder/><button className="text-btn" onClick={()=>openCourse(bookId==='NCE1'?1:bookId==='NCE2'?13:25)}>做一组原创表达练习 <ArrowRight size={16}/></button></section><section className="panel"><label className="field">课文标题（自定义）<input maxLength={120} value={entry.title} onChange={e=>patch({title:e.target.value})} placeholder="给这一课起一个容易找到的标题"/></label><label className="field">我的复述 / 句型 / 疑问<textarea rows={9} maxLength={12000} value={entry.notes} onChange={e=>patch({notes:e.target.value})} placeholder={"关键词：\n我的复述：\n想学会的句型：\n还没弄懂的地方："}/></label><p className="muted small">自动保存在本机，随学习备份一起导出。</p></section></div></TabsContent>
  <TabsContent value="grammar"><BookGrammar bookId={bookId} onAnswer={onAnswer} update={update}/></TabsContent></Tabs>
  <div className="nce-lesson-footer"><button className="btn secondary" disabled={lessonNo<=1} onClick={()=>openLesson(bookId,lessonNo-1)}><ChevronLeft size={16}/>上一课</button><span className="muted small">{lessonNo} / {count} · {entry.steps.length} 项已完成</span><button className="btn" disabled={lessonNo>=count} onClick={()=>openLesson(bookId,lessonNo+1)}>下一课<ChevronRight size={16}/></button></div>
 </>}
 </>}
 </div>
}
function ImportedLesson({entry,patch,lessonKey}:{entry:NceEntry,patch:(e:Partial<NceEntry>)=>void,lessonKey:string}){
 const [editing,setEditing]=useState(!entry.text),[showTranslation,setShowTranslation]=useState(true),[rate,setRate]=useState('0.85'),[active,setActive]=useState(-1),[audioUrl,setAudioUrl]=useState(''),[audioName,setAudioName]=useState(''),[audioBusy,setAudioBusy]=useState(false),[isPlaying,setIsPlaying]=useState(false),[dictation,setDictation]=useState(false),[line,setLine]=useState(0),[answer,setAnswer]=useState(''),[checked,setChecked]=useState(false);const input=useRef<HTMLInputElement>(null),audioInput=useRef<HTMLInputElement>(null),seq=useRef(0),player=useRef<HTMLAudioElement>(null),endAt=useRef<number|null>(null);const rows=parseLessonText(entry.text);
 useEffect(()=>{let canceled=false;const load=()=>{readAudio(lessonKey).then(a=>{if(!canceled){setAudioUrl(a?URL.createObjectURL(a.blob):'');setAudioName(a?.name||'')}}).catch(()=>{})};load();window.addEventListener('english-studio-media-updated',load);return()=>{canceled=true;window.removeEventListener('english-studio-media-updated',load)}},[lessonKey]);
 useEffect(()=>{if(player.current)player.current.playbackRate=Number(rate)},[rate,audioUrl]);
 async function importAudio(f?:File){if(!f)return;if(f.size<1){toast.error('音频文件为空，请重新选择');return}if(f.size>200*1024**2){toast.error('单份音频最多 200 MB');return}if(!/\.(mp3|m4a|wav|ogg|webm|flac|aac)$/i.test(f.name)){toast.error('请选择 MP3、M4A、WAV、OGG、WebM、FLAC 或 AAC 音频');return}setAudioBusy(true);try{await saveAudio({key:lessonKey,name:f.name,type:audioMime(f.name),blob:f});stop();setAudioUrl(URL.createObjectURL(f));setAudioName(f.name);toast.success('音频已保存到本机，刷新后仍可使用')}catch{toast.error('保存音频失败。请检查可用空间，或使用本地启动器打开。')}finally{setAudioBusy(false);if(audioInput.current)audioInput.current.value=''}}
 function playLine(i:number){stop();setActive(i);if(audioUrl&&rows[i].time!==undefined&&player.current){const t=rows[i].time!;endAt.current=rows.slice(i+1).find(r=>r.time!==undefined&&r.time>t)?.time??null;player.current.currentTime=t;player.current.play().catch(()=>{setActive(-1);toast.error('音频无法播放，请检查文件格式')})}else speak(rows[i].en,Number(rate),()=>setActive(-1))}
 function timeUpdate(){const p=player.current;if(!p)return;if(endAt.current!==null&&p.currentTime>=endAt.current){p.pause();endAt.current=null;setActive(-1);return}if(!p.paused){let i=-1;rows.forEach((r,j)=>{if(r.time!==undefined&&r.time<=p.currentTime)i=j});setActive(i)}}
 useEffect(()=>()=>{seq.current++;window.speechSynthesis?.cancel()},[]);useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);
 function stop(){seq.current++;window.speechSynthesis?.cancel();player.current?.pause();setIsPlaying(false);endAt.current=null;setActive(-1)}
 function play(){if(audioUrl&&player.current){stop();player.current.currentTime=0;setActive(0);player.current.play().catch(()=>{setActive(-1);toast.error('音频无法播放，请检查文件格式')});return}const token=++seq.current;function next(i:number){if(token!==seq.current)return;if(i>=rows.length){setActive(-1);return}setActive(i);speak(rows[i].en,Number(rate),ok=>ok?next(i+1):setActive(-1))}next(0)}
 async function importFile(file?:File){if(!file)return;if(file.size>200000||!(/\.(txt|lrc)$/i.test(file.name))){toast.error('请选择小于 200 KB 的 TXT 或 LRC 文件');return}const text=await file.text();if(text.length>50000){toast.error('单课最多 50,000 字符，请拆分后导入');return}patch({text});setEditing(false);setLine(0);setChecked(false);setAnswer('');toast.success('课文已放进本课');if(input.current)input.current.value=''}
 return <div className="lesson-grid"><section className="panel"><div className="section-top"><h3>本课听读</h3><button className="text-btn" onClick={()=>{stop();setEditing(!editing);setLine(0);setChecked(false);setAnswer('')}}>{editing&&entry.text?'返回听读':entry.text?'编辑课文':'粘贴课文'}</button></div><p className="muted small nce-copy-note">导入自己的 TXT / LRC 和本课音频，即可在这里离线听读。</p>{editing?<><label className="field">本课文本<textarea aria-label="本课文本" rows={10} maxLength={50000} value={entry.text} onChange={e=>patch({text:e.target.value})} placeholder={"粘贴你自己的课文，每行一句。\n也支持：英文 | 中文\n以及带时间戳的 LRC 文本。"}/></label><div className="row wrap"><button className="btn" disabled={!entry.text.trim()} onClick={()=>setEditing(false)}>开始跟读 <Play size={15}/></button><button className="btn secondary" onClick={()=>input.current?.click()}><Upload size={16}/>导入 TXT / LRC</button></div><p className="muted small nce-copy-note">仅保存在当前浏览器；最多 50,000 字符。不会联网获取课文。</p></>:rows.length?<><div className="audio-controls"><button className="btn" onClick={active>=0||isPlaying?stop:play}>{active>=0||isPlaying?<Square size={16}/>:<Play size={16}/>} {active>=0||isPlaying?'停止播放':'播放全文'}</button><select aria-label="课文朗读速度" value={rate} onChange={e=>{stop();setRate(e.target.value)}}><option value="0.7">0.7× 慢速</option><option value="0.85">0.85× 清晰</option><option value="1">1× 自然</option></select><label className="switch-label"><Switch checked={showTranslation} onCheckedChange={setShowTranslation}/>中文</label></div><p className="muted small">{audioUrl?'已有本地音频；带时间戳的 LRC 可点击句子定位播放，请使用同一版本的音频和字幕（不处理 LRC offset 偏移）。':'当前使用离线系统语音；需要设备已安装英文语音包。'}</p><div className="nce-text-lines">{rows.map((r,i)=><div key={i} className={'nce-text-line '+(active===i?'active':'')}><span>{i+1}</span><div><p lang="en">{r.en}</p>{showTranslation&&r.zh&&<small>{r.zh}</small>}</div><button className="icon-btn" aria-label={`朗读导入课文第 ${i+1} 句`} onClick={()=>playLine(i)}><Volume2 size={18}/></button></div>)}</div><Recorder/></>:<div className="empty"><BookOpen size={35}/><h3>这一课，还没有导入文本</h3><button className="btn" onClick={()=>setEditing(true)}>粘贴自己的课文</button></div>}<input ref={input} type="file" hidden accept=".txt,.lrc,text/plain" onChange={e=>importFile(e.target.files?.[0])}/></section>
 <aside className="study-aside"><section className="panel"><Headphones className="accent"/><h3 className="nce-copy-note">本课本地音频</h3><p className="muted small">音频保存在本机资料库，刷新后仍可播放。支持常见音频格式，实际解码取决于浏览器。</p><button className="btn secondary full nce-copy-note" disabled={audioBusy} onClick={()=>audioInput.current?.click()}>{audioBusy?'正在保存…':audioUrl?'更换本课音频':'导入本课音频'}</button><input ref={audioInput} hidden type="file" accept="audio/*,.mp3,.m4a,.wav,.ogg,.webm,.flac,.aac" onChange={e=>importAudio(e.target.files?.[0])}/>{audioUrl&&<><p className="muted small nce-audio-name">{audioName}</p><audio ref={player} aria-label="本课本地音频播放器" src={audioUrl} controls onTimeUpdate={timeUpdate} onPlay={()=>setIsPlaying(true)} onPause={()=>{setIsPlaying(false);setActive(-1)}} onEnded={()=>setActive(-1)} onError={()=>toast.error('音频不能解码，请换用兼容的 MP3 或 WAV 文件')}/><p className="muted small">需要搬家时，导出「完整资料包（含音频）」。</p></>}</section>{rows.length>0&&!editing&&<section className="panel"><button className="text-btn" onClick={()=>{stop();setDictation(!dictation)}}><NotebookPen size={17}/>{dictation?'收起听写':'逐句听写'}</button>{dictation&&<><div className="section-top"><strong>第 {line+1} / {rows.length} 句</strong><button className="icon-btn" aria-label="朗读当前听写句" onClick={()=>playLine(line)}><Volume2 size={19}/></button></div><label className="field">听写答案<textarea value={answer} onChange={e=>{setAnswer(e.target.value);setChecked(false)}}/></label><button className="btn secondary" disabled={!answer.trim()} onClick={()=>setChecked(true)}>对照原句</button>{checked&&<div className="feedback"><strong>{normal(answer)===normal(rows[line].en)?'完全正确':'对照原句，再听一次'}</strong><p>{rows[line].en}</p></div>}<div className="row spread"><button className="icon-btn" aria-label="上一句" disabled={line<=0} onClick={()=>{setLine(line-1);setAnswer('');setChecked(false)}}><ChevronLeft/></button><button className="icon-btn" aria-label="下一句" disabled={line>=rows.length-1} onClick={()=>{setLine(line+1);setAnswer('');setChecked(false)}}><ChevronRight/></button></div></>}</section>}</aside></div>
}
function WordCollector({state,addWord}:{state:State,addWord:(w:Word)=>void}){const [word,setWord]=useState(''),[meaning,setMeaning]=useState(''),[example,setExample]=useState('');return <div className="section-space"><section className="panel"><div className="section-top"><div><h3>把课本里的生词，变成自己的词</h3><p className="muted small">保存后直接进入「单词复习」，按间隔安排复习。</p></div><Layers className="accent"/></div><form className="nce-word-form" onSubmit={e=>{e.preventDefault();if(!word.trim()||!meaning.trim())return;if(['__proto__','constructor','prototype'].includes(word.trim().toLowerCase())){toast.error('请将这个词连同常用短语一起加入');return}if((state.personalWords?.length||0)>=2000&&!state.personalWords?.some(w=>w.word.toLowerCase()===word.trim().toLowerCase())){toast.error('个人词库最多 2,000 个词，请先导出备份');return}addWord({word:word.trim(),meaning:meaning.trim(),example:example.trim()});setWord('');setMeaning('');setExample('')}}><label className="field">单词 / 短语<input required value={word} maxLength={100} onChange={e=>setWord(e.target.value)} placeholder="例如：take responsibility for"/></label><label className="field">中文释义<input required value={meaning} maxLength={300} onChange={e=>setMeaning(e.target.value)} placeholder="例如：对……负责"/></label><label className="field">自己的例句<input value={example} maxLength={1000} onChange={e=>setExample(e.target.value)} placeholder="用自己的经历造一句话"/></label><button className="btn" type="submit"><Plus size={16}/>保存并加入复习</button></form></section><div className="section-top section-space"><h3>四册共用的个人生词本</h3><span className="muted small">{state.personalWords?.length||0} 个词条</span></div><div className="word-grid">{(state.personalWords||[]).map(w=><WordCard key={w.word.toLowerCase()} word={w} enrolled={!!state.cards[w.word.toLowerCase()]} onAdd={()=>addWord(w)}/>)}</div></div>}
function BookGrammar({bookId,onAnswer,update}:{bookId:NceBookId,onAnswer:(q:Question,ok:boolean)=>void,update:Props['update']}){const [practice,setPractice]=useState(false);const data=companion[bookId];return <section id="book-grammar" className="section-space"><div className="section-top"><div><div className="eyebrow">ORIGINAL COMPANION</div><h2>本阶段语法补强</h2><p className="muted">6 个原创重点，帮助你把结构用起来；不与教材课次一一对应。</p></div><button className="btn secondary" onClick={()=>setPractice(!practice)}>{practice?'返回语法讲解':'做 6 题巩固'}<ArrowRight size={16}/></button></div>{practice?<section className="panel narrow"><Quiz key={bookId} title="阶段语法自测" questions={data.grammar.map(g=>g.exercise)} onAnswer={onAnswer} onFinish={score=>update(s=>({...s,scores:{...s.scores,['nce-'+bookId]:score}}))}/></section>:<div className="grammar-list">{data.grammar.map((g,i)=><details key={g.id} className="panel grammar-detail"><summary><span className="number-tag">{i+1}</span><strong>{g.title}</strong><Plus size={17}/></summary><div className="grammar-content"><p>{g.rule}</p><div className="formula">{g.formula}</div>{g.examples.map((e,j)=><div className="example-line" key={j}><span lang="en">{e.en}</span><span className="muted">{e.zh}</span><button className="icon-btn" aria-label={`朗读${g.title}例句 ${j+1}`} onClick={()=>speak(e.en)}><Volume2 size={17}/></button></div>)}<div className="note"><strong>注意这里</strong><p>{g.pitfall}</p></div></div></details>)}</div>}</section>}
