'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,ChevronLeft,ChevronRight,Headphones,Layers,Play,Search,Square,Volume2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {toast} from 'sonner';
import {State,NceBookId,NceEntry,Word,Question,bookCounts,normal} from './model';
import {speak,Recorder,WordCard} from './learning';
import {LessonGrammarLinks} from './textbook-grammar-ui';
import {ChineseRecall} from './chinese-recall-ui';
import {readAudio} from './offline-store';
import {parseLessonText} from './nce-utils';
import {ONLINE} from './runtime-mode';
import {WordText} from './word-lookup';
import {loadLessonLanguage,translatedRows,rowsToText,type LessonLanguage} from './language';
import {navigate} from './navigation';
import {PlaybackSpeed,usePlaybackRate} from './playback-speed';
import {useRoute} from './use-route';
import SiteMaterials from './site-materials';
import companionData from './data/book-companion.json';
import {studyUnit,unitTrained,trainedUnits,stageChecks} from './study-path';
import {UnitReview} from './study-path-ui';
import {LessonPractice} from './lesson-practice-ui';
import {GuidedExpression} from './expression-guide-ui';
import {splitLesson} from './lesson-structure';
import {LessonQuestion,LessonPages,TextbookVocabulary} from './lesson-context';
import {ReadingLayout} from './sentence-illustration-ui';
import {sentenceAtTime} from './sentence-illustration';
import {LessonGoals,ListeningNext,LearningTeaching,LearningPractice} from './learning-plan-ui';
import {learningSummary} from './learning-plan';
const books=[
 {id:'NCE1',number:'01',name:'第一册',en:'First Things First',theme:'从开口说，到说清楚',description:'日常对话 · 发音与基础句型',color:'cobalt',focus:'打好基本功'},
 {id:'NCE2',number:'02',name:'第二册',en:'Practice & Progress',theme:'把经历，讲成一个故事',description:'时态系统 · 叙事与段落表达',color:'teal',focus:'建立表达体系'},
 {id:'NCE3',number:'03',name:'第三册',en:'Developing Skills',theme:'读懂细节，也读懂言外之意',description:'长难句 · 语篇与准确表达',color:'violet',focus:'提升理解深度'},
 {id:'NCE4',number:'04',name:'第四册',en:'Fluency in English',theme:'有观点，也有论证',description:'抽象议题 · 批判阅读与写作',color:'ochre',focus:'走向成熟表达'}
] as const;
type Companion={goals:string[],routine:string[]};
const companion=companionData as Record<NceBookId,Companion>;
const steps=[['listen','理解与听读'],['words','整理词句'],['retell','自己的表达'],['practice','配套练习']] as const;
const blank:NceEntry={title:'',text:'',notes:'',steps:[]};

export function nceCompleted(state:State){return (Object.keys(bookCounts) as NceBookId[]).reduce((sum,book)=>sum+Array.from({length:book==='NCE1'?72:bookCounts[book]},(_,i)=>book==='NCE1'?i*2+1:i+1).filter(n=>unitTrained(state,book,n)||learningSummary(state,book,n).practiced).length,0);}
type Props={state:State,update:(fn:(state:State)=>State)=>void,addWord:(w:Word)=>void,onAnswer:(q:Question,ok:boolean)=>void,goIELTS:()=>void,goCloud?:(book?:NceBookId,lesson?:number)=>void,startAt?:{book:NceBookId,lesson:number}|null};
export default function NceStudio({state,update,addWord,onAnswer,goIELTS,goCloud,startAt}:Props){
 const route=useRoute(),mode=route.book?(route.lesson?'lesson':'book'):'home',bookId=route.book||state.nceLast?.book||'NCE1',lessonNo=route.lesson||state.nceLast?.lesson||1,tab=!route.tab||route.tab==='materials'?'listen':route.tab==='words'?'grammar':route.tab==='notes'?'practice':route.tab;
 const [jump,setJump]=useState(''),[originalOpen,setOriginalOpen]=useState(false);const filter=route.filter||'all',search=route.query||'';
 const setFilter=(filter:string)=>navigate({...route,filter},{replace:true,keepScroll:true});
 const setSearch=(query:string)=>navigate({...route,query},{replace:true,keepScroll:true});
 const setTab=(tab:string,scrollTarget?:string)=>navigate({...route,tab:tab==='materials'?'listen':tab,step:undefined,mode:undefined,goal:undefined,practice:undefined},{keepScroll:true,scrollTarget:scrollTarget||((document.getElementById('lesson-content')?.getBoundingClientRect().top??0)<0?'lesson-content':undefined)});
 const [loadedLanguage,setLanguage]=useState<LessonLanguage|null>(null);
 const recallLesson=bookId==='NCE1'?lessonNo-(lessonNo%2===0?1:0):lessonNo;
 const language=loadedLanguage?.book===bookId&&loadedLanguage.lesson===recallLesson?loadedLanguage:null;
 useEffect(()=>{let alive=true;setLanguage(null);void loadLessonLanguage(bookId,recallLesson).then(data=>{if(alive)setLanguage(data)});return()=>{alive=false}},[bookId,recallLesson]);
 const materialTarget=useMemo(()=>({book:bookId,lesson:lessonNo}),[bookId,lessonNo]);
 const exerciseTarget=useMemo(()=>({book:bookId,lesson:bookId==='NCE1'&&lessonNo%2===1?lessonNo+1:lessonNo}),[bookId,lessonNo]);
 const studyText=language?rowsToText(language.rows):'';
 const exerciseLesson=bookId==='NCE1'&&lessonNo%2===0;
 const lessonSteps=steps.map(([id,label])=>[id,exerciseLesson&&id==='listen'?'句型跟练':exerciseLesson&&id==='retell'?'句型运用':label]);
 useEffect(()=>{if(mode==='lesson'&&(state.nceLast?.book!==bookId||state.nceLast.lesson!==lessonNo))update(s=>({...s,nceLast:{book:bookId,lesson:lessonNo}}))},[mode,bookId,lessonNo,state.nceLast,update]);
 const book=books.find(b=>b.id===bookId)!,count=bookCounts[bookId],key=`${bookId}-${lessonNo}`,entry=state.nce?.[key]||blank;
 useEffect(()=>setOriginalOpen(false),[key]);
 const unit=studyUnit(bookId,lessonNo);
 const recallText=state.nce?.[unit.key]?.text||studyText;
 const recallRows=useMemo(()=>parseLessonText(recallText),[recallText]);
 const trusted=!!language&&JSON.stringify(recallRows.map(r=>r.en))===JSON.stringify(language.rows.map(r=>r.en));
 const bodyRows=splitLesson(recallRows,bookId,trusted).body;
 const completed=(id:NceBookId)=>Array.from({length:units(id)},(_,i)=>id==='NCE1'?i*2+1:i+1).filter(n=>unitTrained(state,id,n)||learningSummary(state,id,n).practiced).length;
 const units=(id:NceBookId)=>id==='NCE1'?72:bookCounts[id];
 function openBook(id:NceBookId){navigate({view:'nce',book:id})}
 function openLesson(id:NceBookId,no:number,tab='listen'){navigate({view:'nce',book:id,lesson:no,tab});update(s=>({...s,nceLast:{book:id,lesson:no}}))}
 function patch(data:Partial<NceEntry>){update(s=>({...s,nce:{...s.nce,[key]:{...(s.nce?.[key]||blank),...data}}}))}
 const last=state.nceLast||{book:'NCE1' as const,lesson:1};
 const visible=Array.from({length:count},(_,i)=>i+1).filter(n=>{const e=state.nce?.[`${bookId}-${n}`],done=unitTrained(state,bookId,n)||learningSummary(state,bookId,n).practiced,newActive=Object.keys(learningSummary(state,bookId,n).record.goals).length>0;return(filter==='all'||filter==='done'&&done||filter==='active'&&(newActive||!!e&&(e.steps.length>0||!!e.text||!!e.notes))&&!done)&&(`${n} ${e?.title||''}`).toLowerCase().includes(search.toLowerCase())});
 const visiblePairs=Array.from({length:72},(_,i)=>i*2+1).filter(n=>{const entries=[state.nce?.[`NCE1-${n}`],state.nce?.[`NCE1-${n+1}`]],done=unitTrained(state,'NCE1',n)||learningSummary(state,'NCE1',n).practiced,active=Object.keys(learningSummary(state,'NCE1',n).record.goals).length>0||entries.some(e=>e&&(e.steps.length||e.text||e.notes||e.review));return (filter==='all'||filter==='done'&&done||filter==='active'&&active&&!done)&&`${n} ${n+1} ${entries.map(e=>e?.title||'').join(' ')}`.toLowerCase().includes(search.toLowerCase())});
 const completionRecord=<details className="lesson-completion" key={key}><summary>以前的完成勾选（自报）<span>{entry.steps.length} / 4</span><ChevronRight size={16}/></summary><div className="lesson-completion-checks">{lessonSteps.map(([id,label])=><label key={id}><Checkbox aria-label={`${label}已完成`} checked={entry.steps.includes(id)} onCheckedChange={checked=>{patch({steps:checked?[...new Set([...entry.steps,id])]:entry.steps.filter(s=>s!==id)});update(s=>({...s,days:[...new Set([...s.days,new Date().toLocaleDateString('en-CA')])]}))}}/><span>{label}</span></label>)}</div></details>;
 const lessonNavigation=<div className="nce-lesson-footer"><button className="btn secondary" disabled={lessonNo<=1} onClick={()=>openLesson(bookId,lessonNo-1)}><ChevronLeft size={16}/>上一课</button><label className="lesson-switch"><span>跳转课次</span><select aria-label="切换当前课次" value={lessonNo} onChange={e=>openLesson(bookId,Number(e.target.value))}>{Array.from({length:count},(_,i)=><option key={i+1} value={i+1}>第 {i+1} 课</option>)}</select></label><button className="btn" disabled={lessonNo>=count} onClick={()=>openLesson(bookId,lessonNo+1)}>下一课<ChevronRight size={16}/></button></div>;
 return <div className={"nce-studio"+(mode==='lesson'?' is-lesson':'')+(mode==='lesson'&&tab==='practice'?' is-expression':'')}>
 {mode==='home'?<>
  <div className="page-heading"><div><div className="eyebrow">NEW CONCEPT · YOUR STUDY STUDIO</div><h1>新概念 · 四册课程</h1><p>按册选课，听读、词句、表达和练习都在课内完成。</p></div><div className="row wrap">{ONLINE&&<button className="btn" onClick={()=>goCloud?.()}><BookOpen size={17}/>整册资料与下载</button>}</div></div>
  <section className="panel nce-course-resume"><div><span className="eyebrow">{state.nceLast?'上次学到':'从这里开始'}</span><h2>{books.find(b=>b.id===last.book)?.name} · 第 {last.lesson} 课</h2></div><button className="btn" onClick={()=>openLesson(last.book,last.lesson)}><Play size={16}/>{state.nceLast?'继续学习':'开始学习'}<ArrowRight size={17}/></button></section>
  <div className="section-top section-space"><div><h2>选择你的这一册</h2><p className="muted">随时从适合自己的阶段开始。</p></div><span className="small muted">{ONLINE?"在线学习 · 网站教材":"断网可用 · 资料留在本机"}</span></div>
  <div className="nce-book-grid">{books.map(b=><button key={b.id} className={'nce-book '+b.color} onClick={()=>openBook(b.id)}><div className="nce-cover"><span className="nce-cover-label">NEW CONCEPT<br/>ENGLISH</span><strong>{b.number}</strong><span className="nce-cover-foot">{b.en}<ArrowUpRight size={19}/></span></div><div className="nce-book-body"><div className="section-top"><h3>{b.name}</h3><span>{b.id==='NCE1'?'72 组 · 144 课':`${bookCounts[b.id]} 课`}</span></div><h4>{b.theme}</h4><p>{b.description}</p><Progress value={completed(b.id)/units(b.id)*100}/><div className="section-top small"><span>{completed(b.id)} / {units(b.id)} 组完成训练</span><ArrowRight size={17}/></div></div></button>)}</div>
  <p className="muted small section-space">需要规划下一阶段？<button className="text-btn" onClick={goIELTS}>查看雅思训练与学习路线 <ArrowRight size={16}/></button></p>
 </>:<>
  <button className="text-btn nce-back" onClick={()=>mode==='lesson'?openBook(bookId):navigate({view:'nce'})}><ArrowLeft size={16}/>{mode==='lesson'?`返回${book.name}目录`:'返回四册总览'}</button>
  <div className="nce-book-heading"><div><div className="eyebrow">BOOK {book.number} · {book.en.toUpperCase()}</div><h1>{book.name}{mode==='lesson'?` · 第 ${lessonNo} 课`:`：${book.theme}`}</h1><p className="muted">{mode==='lesson'?(route.mode==='recall'?'看中文，说英文':entry.title||(bookId==='NCE1'?`课文与第 ${unit.last} 课句型配对学习`:'听懂课文，再用自己的话表达。')):book.description}</p></div><div className="row wrap">{ONLINE&&mode==='book'&&<button className="btn secondary" onClick={()=>goCloud?.(bookId,1)}><BookOpen size={17}/>本册资料与下载</button>}</div></div>
  <div className="nce-source-line"><span>{ONLINE?"教材、听读和练习都在本课内；笔记与进度保存在当前浏览器。":"本地模式 · 文本、音频与学习记录保存在当前浏览器；不连接外部点读服务。"}</span></div>
 {mode==='book'?<>
  <div className="nce-book-intro"><section className="panel"><div className="section-top"><h3>这一阶段，重点练什么</h3><span className="pill">{book.focus}</span></div><ul>{companion[bookId].goals.map(g=><li key={g}>{g}</li>)}</ul><p className="stage-check">{stageChecks[bookId]}</p><div className="row wrap"><button className="btn secondary" onClick={()=>openLesson(bookId,state.nceLast?.book===bookId?state.nceLast.lesson:1)}>开始本册学习 <ArrowRight size={16}/></button><button className="text-btn" onClick={()=>navigate({view:'grammar',book:bookId})}>查看本册语法与句型</button></div></section><section className="panel"><span className="eyebrow">BOOK PROGRESS</span><div className="big-stat">{completed(bookId)}<span>/ {units(bookId)} 组</span></div><Progress value={completed(bookId)/units(bookId)*100}/><p className="muted small">{bookId==='NCE1'?'两课组成一组：奇数课听读、词句和表达，加上配套偶数课练习。':'每课作为一组，完成听读、词句、表达和练习。'}这里记录完成训练的数量；能否独立运用，在课内自查。</p></section></div>
  {bookId==='NCE1'&&<p className="notice">第一册共 144 课，按 72 组配对学习：1＋2、3＋4……143＋144。一组可以分几天完成。奇数课听读课文，偶数课换词练句型；录音与字幕对应奇数课。</p>}
  <div className="filter-bar"><div className="nce-filters">{[['all','全部课程'],['active','学习中'],['done','完成训练']].map(([v,label])=><button className={filter===v?'active':''} key={v} onClick={()=>setFilter(v)}>{label}</button>)}</div><label className="search"><Search size={17}/><input aria-label="搜索本册课号或笔记标题" placeholder="搜索课号或自定义标题" value={search} onChange={e=>setSearch(e.target.value)}/></label><form className="nce-jump" onSubmit={e=>{e.preventDefault();const n=Number(jump);if(Number.isInteger(n)&&n>=1&&n<=count)openLesson(bookId,n);else toast.error(`请输入 1–${count} 的课号`)}}><input type="number" min="1" max={count} aria-label="跳转课号" placeholder="课号" value={jump} onChange={e=>setJump(e.target.value)}/><button className="btn secondary" type="submit">前往</button></form></div>
  {bookId==='NCE1'?<div className="nce-pair-grid">{visiblePairs.map(n=>{const done=unitTrained(state,'NCE1',n)||learningSummary(state,'NCE1',n).practiced,review=state.nce?.[`NCE1-${n}`]?.review;return <article className={'nce-pair '+(done?'done':'')} key={n}><div className="section-top"><strong>第 {n}–{n+1} 课</strong><span className="small muted">{done?'训练已完成':'两课一组'}</span></div><div className="pair-lessons">{[n,n+1].map((no,i)=><button key={no} className="nce-lesson" onClick={()=>openLesson(bookId,no)}><span className="section-top"><b>{String(no).padStart(3,'0')}</b><ChevronRight size={16}/></span><strong>{i===0?'课文听读':'句型与练习'}</strong><small>{state.nce?.[`NCE1-${no}`]?.title||(i===0?'理解、听清、自己表达':'讲解、换词与配套回顾')}</small></button>)}</div>{review&&<p className="small muted">{review.dueAt<=Date.now()?'到了复习时间':'已安排复习'} · 自查 {review.checks.length} / 3 项</p>}</article>})}</div>:<div className="nce-lesson-grid">{visible.map(n=>{const e=state.nce?.[`${bookId}-${n}`],done=unitTrained(state,bookId,n)||learningSummary(state,bookId,n).practiced;return <button key={n} className={'nce-lesson '+(done?'done':'')} onClick={()=>openLesson(bookId,n)}><span className="section-top"><b>{String(n).padStart(3,'0')}</b>{done?<Check size={17}/>:<ChevronRight size={16}/>}</span><strong>{e?.title||`第 ${n} 课`}</strong><span className="nce-mini-steps">{steps.map(([id,label])=><i key={id} className={e?.steps.includes(id)?'checked':''} aria-label={label+(e?.steps.includes(id)?'已完成':'未完成')}/>)}</span><small>{done?'训练已完成':e?.steps.length?`${e.steps.length} / 4 项训练`:e?.text?'已保存课文':'开始学习'}</small></button>})}</div>}{(bookId==='NCE1'?visiblePairs:visible).length===0&&<div className="empty">没有符合条件的课次，试试其他筛选。</div>}
  <LessonGrammarLinks book={bookId}/>
 </>:<>
  <div id="lesson-content">
  <LessonGoals book={bookId} lesson={lessonNo} state={state}/><Tabs key={key} value={tab} onValueChange={v=>{window.speechSynthesis?.cancel();setTab(v)}}><TabsList className="lesson-tabs"><TabsTrigger value="listen" aria-label="课文">1 课文</TabsTrigger><TabsTrigger value="grammar" aria-label="讲解">2 讲解</TabsTrigger><TabsTrigger value="practice" aria-label="练习">3 练习</TabsTrigger></TabsList>
  <TabsContent value="listen">{!route.mode&&<div className="learning-understanding"><strong>先听一遍，带着问题理解课文</strong><p className="small muted">先抓住大意，再点不清楚的句子反复听。词语可直接点开查义。</p>{!exerciseLesson&&<details className="learning-listening-question"><summary>{splitLesson(recallRows,bookId,trusted).question.map(r=>r.en).join(' ')||'听后写下我理解的大意'}</summary><LessonQuestion lesson={splitLesson(recallRows,bookId,trusted)} answer={state.drafts[`listen-answer-${key}`]||''} onChange={value=>update(s=>({...s,drafts:{...s.drafts,[`listen-answer-${key}`]:value}}))}/></details>}</div>}{ONLINE&&(!entry.text||exerciseLesson)?<SiteMaterials key={key} embedded viewPdf={()=>{setOriginalOpen(true);setTab('practice')}} practiceMode startAt={materialTarget} visible={tab==='listen'} state={state} restore={s=>update(()=>s)} openLesson={(book,no)=>openLesson(book,no,'listen')}/>:<SavedLesson key={key} entry={{...entry,text:rowsToText(translatedRows(entry.text,language))}} lessonKey={key} trusted={trusted} sourceSha256={trusted?language?.sourceSha256:undefined} questionAnswer={state.drafts[`listen-answer-${key}`]||''} saveQuestion={value=>update(s=>({...s,drafts:{...s.drafts,[`listen-answer-${key}`]:value}}))}/>}<ListeningNext book={bookId} lesson={lessonNo} state={state} update={update}/></TabsContent>
  <TabsContent value="practice"><LearningPractice key={unit.key} book={bookId} lesson={lessonNo} state={state} update={update}/><details className="panel section-space"><summary>再用课文原句做填空（可选）</summary><LessonPractice key={unit.key} rows={recallRows} lessonKey={unit.key} label={unit.label} state={state} update={update} listen={()=>openLesson(bookId,unit.first)} notes={()=>setTab('practice')}/></details><details className="panel section-space legacy-learning" open={route.tab==='notes'}><summary>笔记与以前的表达练习、自查记录</summary><GuidedExpression key={unit.key} book={bookId} lesson={unit.first} rows={bodyRows} state={state} update={update} listen={()=>openLesson(bookId,unit.first)} sourceSha256={trusted&&JSON.stringify(recallRows.map(r=>r.time))===JSON.stringify(language?.rows.map(r=>r.time))?language?.sourceSha256:undefined}/><details className="panel section-space expression-free-notes"><summary>自由笔记与课文标题</summary><label className="field">课文标题（自定义）<input maxLength={120} value={entry.title} onChange={e=>patch({title:e.target.value})} placeholder="给这一课起一个容易找到的标题"/></label><label className="field">我的复述 / 句型 / 疑问<textarea rows={9} maxLength={12000} value={entry.notes} onChange={e=>patch({notes:e.target.value})} placeholder={"关键词或句型：\n换成自己的内容：\n我听不清或说不出的地方：\n下一次先练什么："}/></label><p className="muted small">自动保存在当前浏览器。</p></details><details className="lesson-extra-review"><summary>整课自查与复习记录（可选）</summary><UnitReview key={unit.key} book={bookId} lesson={lessonNo} state={state} update={update} open={(no,tab)=>openLesson(bookId,no,tab)}/></details></details><details className="panel lesson-original" open={originalOpen} onToggle={event=>setOriginalOpen(event.currentTarget.open)}><summary><BookOpen size={19}/><span>{bookId==='NCE1'?`需要时核对第 ${unit.last} 课原书`:'需要时核对本课原书'}</span><ChevronRight size={17}/></summary><p className="muted small">{bookId==='NCE1'?`本组以第 ${unit.first} 课原句理解和表达为主，第 ${unit.last} 课原书用于核对句型与习题。`:'可在原书中核对本课的例句、栏目和习题。'}把需要核对或反复出错的地方记入笔记。</p>{ONLINE&&originalOpen&&<SiteMaterials key={key+'-practice'} embedded pdfOnly startAt={exerciseTarget} visible={tab==='practice'} state={state} restore={s=>update(()=>s)} openLesson={(book,no)=>openLesson(book,no)}/>}</details><p className="muted small lesson-grammar-link">句型反复用错？<button className="text-btn" onClick={()=>setTab('grammar')}>查看本课教材语法<ArrowRight size={14}/></button></p></TabsContent><TabsContent value="grammar"><LearningTeaching book={bookId} lesson={lessonNo}/><details className="panel section-space" open={route.tab==='words'}><summary>本课生词与我的词句</summary><WordCollector key={key} book={bookId} lesson={lessonNo} text={rowsToText(bodyRows)} state={state} addWord={addWord}/></details></TabsContent></Tabs></div>
  {completionRecord}
  {bookId==='NCE1'&&<p className="lesson-pair-link"><button className="text-btn" onClick={()=>openLesson(bookId,exerciseLesson?unit.first:unit.last)}>{exerciseLesson?`回听第 ${unit.first} 课课文`:`配套第 ${unit.last} 课句型练习`} <ArrowRight size={14}/></button></p>}
  {tab!=='practice'&&<p className="small muted section-space"><button className="text-btn" onClick={()=>setTab('practice')}>用本课表达，说一句自己的话 <ArrowRight size={14}/></button></p>}
  {tab==='practice'?<details className="lesson-change"><summary>切换课次</summary>{lessonNavigation}</details>:lessonNavigation}
 </>}
 </>}
 </div>
}
function SavedLesson({entry,lessonKey,trusted,sourceSha256,questionAnswer,saveQuestion}:{entry:NceEntry,lessonKey:string,trusted:boolean,sourceSha256?:string,questionAnswer:string,saveQuestion:(s:string)=>void}){
 const rate=usePlaybackRate(),route=useRoute(),recall=route.mode==='recall',dictation=route.mode==='dictation';
 useEffect(()=>{stop();setChecked(false)},[recall,dictation]);
 const [showTranslation,setShowTranslation]=useState(false),[active,setActive]=useState(-1),[audioUrl,setAudioUrl]=useState(''),[audioName,setAudioName]=useState(''),[isPlaying,setIsPlaying]=useState(false),[line,setLine]=useState(0),[answer,setAnswer]=useState(''),[checked,setChecked]=useState(false);const seq=useRef(0),player=useRef<HTMLAudioElement>(null),endAt=useRef<number|null>(null);const [book,no]=lessonKey.split('-');const structure=splitLesson(parseLessonText(entry.text),book as NceBookId,trusted),rows=structure.body;
 useEffect(()=>{let canceled=false;const load=()=>{readAudio(lessonKey).then(a=>{if(!canceled){setAudioUrl(a?URL.createObjectURL(a.blob):'');setAudioName(a?.name||'')}}).catch(()=>{})};load();window.addEventListener('english-studio-media-updated',load);return()=>{canceled=true;window.removeEventListener('english-studio-media-updated',load)}},[lessonKey]);
 useEffect(()=>{if(player.current)player.current.playbackRate=Number(rate)},[rate,audioUrl]);
 function followLine(i:number){i=Math.max(0,i);if(i!==line){setLine(i);setAnswer('');setChecked(false)}}
 function playLine(i:number,last=i){stop();setActive(i);followLine(i);if(audioUrl&&rows[i].time!==undefined&&player.current){const t=rows[i].time!;endAt.current=rows.slice(last+1).find(r=>r.time!==undefined&&r.time>t)?.time??null;player.current.currentTime=t;player.current.play().catch(()=>{setActive(-1);toast.error('音频无法播放，请检查文件格式')})}else speak(rows.slice(i,last+1).map(r=>r.en).join(' '),()=>setActive(-1))}
 function timeUpdate(){const p=player.current;if(!p)return;if(endAt.current!==null&&p.currentTime>=endAt.current){p.pause();endAt.current=null;setActive(-1);return}if(!p.paused){let i=-1;rows.forEach((r,j)=>{if(r.time!==undefined&&r.time<=p.currentTime)i=j});setActive(i);if(i>=0)followLine(i)}}
 useEffect(()=>()=>{seq.current++;window.speechSynthesis?.cancel()},[]);useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);
 function stop(){seq.current++;window.speechSynthesis?.cancel();player.current?.pause();setIsPlaying(false);endAt.current=null;setActive(-1)}
 function play(){if(audioUrl&&player.current){stop();player.current.currentTime=rows[0]?.time||0;setActive(0);followLine(0);player.current.play().catch(()=>{setActive(-1);toast.error('音频无法播放，请检查文件格式')});return}const token=++seq.current;function next(i:number){if(token!==seq.current)return;if(i>=rows.length){setActive(-1);return}setActive(i);followLine(i);speak(rows[i].en,ok=>{if(token===seq.current){ok?next(i+1):setActive(-1)}})}next(0)}
 return <div className={'lesson-grid'+(recall?' recall-active':'')}><section className="panel"><h3>本课听读</h3>{rows.length>0&&<label className="reading-mode">练习方式<select aria-label="练习方式" value={route.mode||'shadow'} onChange={e=>{stop();navigate({...route,tab:'listen',mode:e.target.value==='shadow'?undefined:e.target.value as 'recall'|'dictation'},{keepScroll:true})}}><option value="shadow">听读与跟读</option><option value="dictation">听写</option><option value="recall">看中文说英文</option></select></label>}{rows.length?recall?<ChineseRecall rows={rows} onListen={playLine} onStop={stop} audioLabel={audioUrl?'听原声':'听本机示范'}/>:<>{!dictation&&<LessonQuestion lesson={structure} answer={questionAnswer} onChange={saveQuestion}/>}<div className="audio-controls"><button className="btn" onClick={active>=0||isPlaying?stop:play}>{active>=0||isPlaying?<Square size={16}/>:<Play size={16}/>} {active>=0||isPlaying?'停止播放':'播放全文'}</button><PlaybackSpeed ariaLabel="课文朗读速度"/><label className="switch-label"><Switch checked={!dictation&&showTranslation} disabled={dictation} onCheckedChange={setShowTranslation} aria-label="显示课文中文"/>中文</label></div><p className="muted small">{audioUrl?'已有本地音频；带时间戳的 LRC 可点击句子定位播放，请使用同一版本的音频和字幕（不处理 LRC offset 偏移）。':'当前使用离线系统语音；需要设备已安装英文语音包。'}</p><ReadingLayout book={book as NceBookId} lesson={Number(no)} line={line} rowCount={rows.length} sourceSha256={sourceSha256} activeLine={dictation?-1:active} showIllustration={trusted&&!dictation}>{dictation?<p className="notice" role="status">听写时已收起原文、中文和跟读参考。先写下来，核对后再看答案；切回听读与跟读可返回课文。</p>:<><h3 className="lesson-body-title">课文正文</h3><div className="nce-text-lines">{rows.map((r,i)=><div key={i} className={'nce-text-line '+(line===i?'active':'')} data-reading-line={i} aria-current={line===i?'true':undefined}><span>{i+1}</span><div><p lang="en"><WordText text={r.en} exampleTranslation={r.zh}/></p>{showTranslation&&r.zh&&<small>{r.zh}</small>}</div><button className="icon-btn" aria-label={`朗读已保存课文第 ${i+1} 句`} onClick={()=>playLine(i)}><Volume2 size={18}/></button></div>)}</div><label className="field record-line-select">选择跟读句<select aria-label="选择跟读句" value={line} onChange={e=>{stop();setLine(Number(e.target.value));setAnswer('');setChecked(false)}}>{rows.map((r,i)=><option key={i} value={i}>{i+1}. {r.en.slice(0,80)}</option>)}</select></label><Recorder key={`${lessonKey}-${line}`} referenceText={rows[line]?.en} onListen={()=>playLine(line)} onBeforeRecord={stop}/></>}</ReadingLayout></>:<div className="empty"><BookOpen size={35}/><h3>本机尚未保存本课</h3><p>请在在线版打开对应课次学习。</p></div>}</section>
 <aside className="study-aside">{audioUrl&&<section className="panel"><Headphones className="accent"/><h3 className="nce-copy-note">本课本地音频</h3><p className="muted small nce-audio-name">{audioName}</p><audio ref={player} aria-label="本课本地音频播放器" src={audioUrl} controls onLoadedMetadata={()=>{if(player.current)player.current.playbackRate=Number(rate)}} onTimeUpdate={timeUpdate} onSeeked={()=>followLine(sentenceAtTime(rows,player.current?.currentTime||0))} onPlay={()=>setIsPlaying(true)} onPause={()=>{setIsPlaying(false);setActive(-1)}} onEnded={()=>setActive(-1)} onError={()=>toast.error('当前浏览器无法播放这份已保存音频')}/><PlaybackSpeed ariaLabel="本课本地音频语速"/></section>}{rows.length>0&&dictation&&<section className="panel"><h3>逐句听写</h3>{dictation&&<><div className="section-top"><strong>第 {line+1} / {rows.length} 句</strong><button className="icon-btn" aria-label="朗读当前听写句" onClick={()=>playLine(line)}><Volume2 size={19}/></button></div><PlaybackSpeed label="听写语速" ariaLabel="本课听写语速"/><label className="field">听写答案<textarea value={answer} onChange={e=>{setAnswer(e.target.value);setChecked(false)}}/></label><button className="btn secondary" disabled={!answer.trim()} onClick={()=>setChecked(true)}>对照原句</button>{checked&&<div className="feedback"><strong>{normal(answer)===normal(rows[line].en)?'完全正确':'对照原句，再听一次'}</strong><p>{rows[line].en}</p>{rows[line].zh&&<p className="line-translation">{rows[line].zh}</p>}</div>}<div className="row spread"><button className="icon-btn" aria-label="上一句" disabled={line<=0} onClick={()=>{setLine(line-1);setAnswer('');setChecked(false)}}><ChevronLeft/></button><button className="icon-btn" aria-label="下一句" disabled={line>=rows.length-1} onClick={()=>{setLine(line+1);setAnswer('');setChecked(false)}}><ChevronRight/></button></div></>}</section>}</aside></div>
}
function WordCollector({state,addWord,text,book,lesson}:{state:State,addWord:(w:Word)=>void,text:string;book:NceBookId;lesson:number}){return <div className="section-space"><section className="panel"><div className="section-top"><div><h3>把课本里的生词，变成自己的词</h3><p className="muted small">点选教材词条，查看释义并加入「单词复习」。</p></div><Layers className="accent"/></div><TextbookVocabulary book={book} lesson={lesson} text={text}/></section><div className="section-top section-space"><h3>四册共用的个人生词本</h3><span className="muted small">{state.personalWords?.length||0} 个词条</span></div><div className="word-grid">{(state.personalWords||[]).map(w=><WordCard key={w.word.toLowerCase()} word={w} enrolled={!!state.cards[w.word.toLowerCase()]} onAdd={()=>addWord(w)}/>)}</div></div>}
