import {State,validateState,validNceKey} from './model';
export type LocalAudio={key:string,name:string,type:string,blob:Blob};
let connection:Promise<IDBDatabase>|undefined;
function database(){if(!connection)connection=new Promise<IDBDatabase>((resolve,reject)=>{if(!('indexedDB' in window)){reject(Error('此浏览器不支持本地资料库'));return}const r=indexedDB.open('english-studio-offline',1);r.onupgradeneeded=()=>{r.result.createObjectStore('state');r.result.createObjectStore('audio',{keyPath:'key'})};r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();connection=undefined};resolve(r.result)};r.onerror=()=>{connection=undefined;reject(r.error)};r.onblocked=()=>{connection=undefined;reject(Error('请关闭其他学习窗口后重试'))}});return connection}
export async function readState():Promise<State|undefined>{const db=await database();return new Promise((resolve,reject)=>{const t=db.transaction('state'),r=t.objectStore('state').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function writeState(state:State){const db=await database();return new Promise<void>((resolve,reject)=>{const t=db.transaction('state','readwrite');t.objectStore('state').put(state,'current');t.oncomplete=()=>resolve();t.onabort=()=>reject(t.error||Error('本机保存失败'));t.onerror=()=>{}})}
export async function readAudio(key:string):Promise<LocalAudio|undefined>{const db=await database();return new Promise((resolve,reject)=>{const r=db.transaction('audio').objectStore('audio').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function allAudio():Promise<LocalAudio[]>{const db=await database();return new Promise((resolve,reject)=>{const r=db.transaction('audio').objectStore('audio').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
export async function saveAudio(audio:LocalAudio){const db=await database();return new Promise<void>((resolve,reject)=>{const t=db.transaction('audio','readwrite');t.objectStore('audio').put(audio);t.oncomplete=()=>resolve();t.onabort=()=>reject(t.error||Error('音频保存失败'));t.onerror=()=>{}})}
export async function saveCollection(state:State,media:LocalAudio[],replace=false){const db=await database();return new Promise<void>((resolve,reject)=>{const t=db.transaction(['audio','state'],'readwrite');const a=t.objectStore('audio');if(replace)a.clear();for(const item of media)a.put(item);t.objectStore('state').put(state,'current');t.oncomplete=()=>resolve();t.onabort=()=>reject(t.error||Error('本地资料保存失败，原记录未改变'));t.onerror=()=>{}})}
const MAGIC='ENGLISH-STUDIO-PACK-1\n';
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
export async function makePack(state:State){const media=await allAudio();const manifest=JSON.stringify({version:1,state,media:media.map(({key,name,type,blob})=>({key,name,type,size:blob.size}))});const data=new TextEncoder().encode(manifest);return new Blob([MAGIC,String(data.length).padStart(12,'0')+'\n',data,...media.map(m=>m.blob)],{type:'application/octet-stream'})}
export async function parsePack(file:Blob):Promise<{state:State,media:LocalAudio[]}>{if(file.size>2*1024**3)throw Error('资料包超过 2 GB，请按册备份导入');const header=await file.slice(0,MAGIC.length+13).text();if(!header.startsWith(MAGIC)||!/^\d{12}\n$/.test(header.slice(MAGIC.length)))throw Error('请选择本网站导出的 .espack 资料包');const length=Number(header.slice(MAGIC.length).trim());let offset=MAGIC.length+13;if(length<=0||length>64*1024**2||offset+length>file.size)throw Error('资料包目录无效');const m=JSON.parse(await file.slice(offset,offset+length).text());offset+=length;if(m.version!==1||!validateState(m.state)||!Array.isArray(m.media)||m.media.length>348)throw Error('资料包内容无效');const seen=new Set<string>();const media:LocalAudio[]=[];for(const item of m.media){if(!validNceKey(item?.key||'')||seen.has(item.key)||typeof item.name!=='string'||item.name.length>300||!/^audio\/[a-zA-Z0-9.+-]+$/.test(item.type)||!Number.isInteger(item.size)||item.size<1||item.size>200*1024**2||offset+item.size>file.size)throw Error('资料包中的音频条目无效');seen.add(item.key);media.push({key:item.key,name:item.name,type:item.type,blob:file.slice(offset,offset+item.size,item.type)});offset+=item.size}if(offset!==file.size)throw Error('资料包长度不匹配');return {state:m.state,media}}
export const audioMime=(name:string)=>({mp3:'audio/mpeg',m4a:'audio/mp4',mp4:'audio/mp4',wav:'audio/wav',ogg:'audio/ogg',webm:'audio/webm',flac:'audio/flac',aac:'audio/aac'}[name.toLowerCase().split('.').pop()||'']||'audio/mpeg');
