'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {readMocks,readiness,overallBand,validMock,type MockResult} from './readiness';
import {navigate} from './navigation';
const skills=['听力','阅读','写作','口语'];
const blank=():MockResult=>({id:'',date:new Date().toLocaleDateString('en-CA'),paper:'',kind:'academic',scores:['','','',''],unseen:false,timed:false,reviewer:'',feedback:''});
export function Readiness({drafts,saveDraft}:{drafts:Record<string,string>;saveDraft:(id:string,text:string)=>void}){
 const record=readMocks(drafts['ielts-readiness']),[form,setForm]=useState(blank),[editing,setEditing]=useState(false);
 const ready=readiness(record.results,Number(record.minimum));
 const save=()=>{if(!validMock(form)){toast.error('请填写日期、试卷名称和四项 0–9 的成绩（每 0.5 分一档）');return}const entry={...form,id:form.id||String(Date.now())};const results=[...record.results.filter(r=>r.id!==entry.id),entry].slice(-20);saveDraft('ielts-readiness',JSON.stringify({...record,results}));setEditing(false);setForm(blank());toast.success('已保存本次模考记录')};
 return <section className="panel section-space readiness"><span className="eyebrow">用实际表现核对目标</span><h2>练完之后，怎样确认接近 6.5？</h2><p>新概念和短练习用于打基础。最后用没做过的完整试卷限时检查听说读写，口语、写作依据官方标准请有经验的老师或考试机构评价。</p><p className="small muted">本站的准备度参考：最近两次不同试卷都达到总分 6.5，并达到你设定的单项目标。以下为自己录入的成绩，本站无法核实评分，也不作为官方成绩证明。</p><label className="field">我的单项目标（总分目标为 6.5）<select value={record.minimum} onChange={e=>saveDraft('ielts-readiness',JSON.stringify({...record,minimum:e.target.value}))}><option value="0">仅检查总分</option><option value="5.5">每项至少 5.5</option><option value="6">每项至少 6.0</option><option value="6.5">每项至少 6.5</option><option value="7">每项至少 7.0</option></select></label><p className="notice" role="status">{ready?'最近两次录入的模考记录达到所设目标。请结合评分反馈继续确认稳定性。':'目前还没有两次满足条件的完整记录。先完成一次限时模考，找到最弱的一项。'}</p>
 <div className="readiness-skills">{skills.map((label,i)=><article key={label}><h3>{label}</h3><p className="small">{['用完整听力题检验主要信息和细节；按该套题的答案及换分说明记录成绩。','用完整阅读题检验定位、同义改写和推断；区分学术类与培训类换分标准。','完成两篇限时写作，获取任务完成、组织、词汇和语法四方面反馈。','完成三部分口语，获取流利连贯、词汇、语法和发音四方面反馈。'][i]}</p><button className="text-btn" onClick={()=>navigate({view:'ielts',tab:['listening','reading','writing','speaking'][i]})}>先补练{label}</button></article>)}</div>
 <div className="row wrap"><a className="text-btn" href="https://ielts.org/take-a-test/your-results/ielts-scoring-in-detail" target="_blank" rel="noreferrer">官方评分说明</a><a className="text-btn" href="https://ielts.org/take-a-test/preparation-resources/sample-test-questions" target="_blank" rel="noreferrer">官方练习资料</a><button className="btn secondary" onClick={()=>{setForm(blank());setEditing(true)}}>记录一次完整模考</button></div>
 {editing&&<div className="mock-form section-space"><h3>{form.id?'修正模考记录':'新增模考记录'}</h3><div className="two-col"><label className="field">完成日期<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label className="field">试卷名称 / 来源<input maxLength={200} value={form.paper} onChange={e=>setForm({...form,paper:e.target.value})} placeholder="填具体试卷，避免把同一套重复算作新题"/></label></div><label className="field">考试类型<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as MockResult['kind']})}><option value="academic">Academic · 学术类</option><option value="general">General Training · 培训类</option></select></label><div className="mock-scores">{skills.map((label,i)=><label className="field" key={label}>{label}成绩<input type="number" min="0" max="9" step="0.5" value={form.scores[i]} onChange={e=>{const scores=[...form.scores];scores[i]=e.target.value;setForm({...form,scores})}}/></label>)}</div><div className="checklist"><label><input type="checkbox" checked={form.unseen} onChange={e=>setForm({...form,unseen:e.target.checked})}/>此前未做过这套完整试卷</label><label><input type="checkbox" checked={form.timed} onChange={e=>setForm({...form,timed:e.target.checked})}/>按考试要求完成全部四项并限时</label></div><label className="field">口语、写作由谁依据标准评阅？<input maxLength={300} value={form.reviewer} onChange={e=>setForm({...form,reviewer:e.target.value})} placeholder="记录老师 / 机构 / 成绩报告来源；尚未评阅可留空"/></label><label className="field">收到的反馈，以及下一步要补练的具体问题<textarea maxLength={3000} rows={3} value={form.feedback} onChange={e=>setForm({...form,feedback:e.target.value})} placeholder="例如：论点缺少具体支持；先把每段的原因和例子对应起来"/></label><div className="row wrap"><button className="btn" onClick={save}>保存记录</button><button className="text-btn" onClick={()=>setEditing(false)}>取消</button></div></div>}
 {!!record.results.length&&<div className="mock-results">{[...record.results].sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id)).map(r=><article key={r.id}><div className="section-top"><strong>{r.paper} · {r.date}</strong><button className="text-btn" onClick={()=>{setForm(r);setEditing(true)}}>修正记录</button></div><p>{skills.map((s,i)=>`${s} ${r.scores[i]}`).join(' · ')} · 总分 {overallBand(r.scores.map(Number))??'待核对'}</p><p className="small muted">{r.kind==='academic'?'学术类':'培训类'} · {r.unseen?'新试卷':'复用试卷'} · {r.timed?'完整限时':'尚未完整限时'} · {r.reviewer&&r.feedback?'已记录评阅来源和反馈':'尚缺口语 / 写作评阅信息'}</p>{r.feedback&&<p>{r.feedback}</p>}</article>)}</div>}
 </section>;
}
