'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Volume2} from 'lucide-react';
import {WordText} from './word-lookup';
import {Recorder,speak} from './learning';
import {PlaybackSpeed} from './playback-speed';
import {Timer} from './timer';
import {navigate} from './navigation';
import {useRoute} from './use-route';
import {ONLINE} from './runtime-mode';
import {wordCount} from './model';

type Topic={id:string;part:number;title:string;questions:{en:string;zh:string;sourceRow:number}[]};
type Bank={version:number;notice:string;topics:Topic[]};
let pending:Promise<Bank>|undefined;
async function bank(){if(!pending)pending=fetch('/speaking/topics.json').then(async r=>{if(!r.ok)throw Error();const d=await r.json() as Bank;if(d.version!==1||!Array.isArray(d.topics)||d.topics.length!==66||d.topics.some(t=>!/^bank-[123]-\d+$/.test(t.id)||![1,2,3].includes(t.part)||!Array.isArray(t.questions)||!t.questions.length||!t.questions.every(q=>typeof q.en==='string'&&typeof q.zh==='string')))throw Error();return d}).catch(e=>{pending=undefined;throw e});return pending}
const models={
 1:{name:'直接回答 → 原因 → 一个细节',parts:['先回答题目','说一个原因','补一个具体细节'],help:['先决定自己的答案：人物、地点、活动，或 Yes / No。可以先写中文词。','问自己“为什么？”先想一个原因，不用凑复杂词。','选什么时候、和谁、多久一次中的一个，说明真实情况。'],sample:'I enjoy reading because it helps me relax. I usually read for ten minutes before bed.',zh:'我喜欢阅读，因为它帮助我放松。我通常在睡前读十分钟。',frame:'My answer … / because … / For example, …',focus:'这是练习用的三块结构，回答不必固定三句；根据问题自然展开。'},
 2:{name:'背景 → 事情 → 细节 → 意义',parts:['选一个人 / 事 / 物 / 地方','补时间、地点或背景','说一个具体细节','解释感受与原因'],help:['从题目找出要描述的对象，选一个你真正了解的。','选题卡里的第一两个提示，每个先写几个词。','讲一个看得见或发生过的细节，避免只说 good / interesting。','回答为什么记得、喜欢或重视它，并检查题卡每个提示都覆盖。'],sample:'I want to talk about a park near my home. I went there with a friend last Sunday. We walked by the lake and watched the birds. I enjoyed it because I could slow down after a busy week.',zh:'我想讲家附近的一个公园。上周日我和一个朋友去了那里。我们沿湖散步、看鸟。我很喜欢，因为忙碌一周后终于可以放慢脚步。',frame:'I want to talk about … / At that time, … / One detail I remember is … / It mattered to me because …',focus:'先讲清四块，再按题卡调整顺序。示范是短骨架，正式长答需要展开真实细节。'},
 3:{name:'观点 → 原因 → 例子 → 限制',parts:['先给出判断','解释为什么','用例子支持原因','补一个例外或另一面'],help:['先决定主要立场。题目问比较就先说差别，问原因就先给主要原因。','把因果说完整：这个原因怎样导致你说的结果？','举一个常见情境；不确定的数字不要编造。','补充“在什么情况下不一定如此”，有必要才加，不必强凑。'],sample:'Public parks can improve city life because they give people space to exercise. For example, families can walk together after dinner. However, parks need regular care to remain safe and pleasant.',zh:'公共公园能改善城市生活，因为它们给人们运动的空间。例如，家人可以在晚饭后一起散步。不过，公园需要定期维护，才能保持安全舒适。',frame:'I think … / This is because … / For example, … / However, …',focus:'先答问题再扩展；讲清因果比堆连接词重要。比较题要回应两边，原因题要解释机制。'}
};
type Plan={points:string[];answer:string;fix:string;retry:string;stage:number};
function readPlan(raw?:string):Plan{let d:any={};try{d=JSON.parse(raw||'{}')||{}}catch{}return {points:Array.isArray(d.points)?d.points.slice(0,4).map((v:any)=>typeof v==='string'?v.slice(0,1000):''):[],answer:typeof d.answer==='string'?d.answer.slice(0,6000):'',fix:typeof d.fix==='string'?d.fix.slice(0,1000):'',retry:typeof d.retry==='string'?d.retry.slice(0,6000):'',stage:Number.isInteger(d.stage)?Math.max(0,Math.min(3,d.stage)):0}}
function SpeakingCoach({topic,index,drafts,saveDraft}:{topic:Topic;index:number;drafts:Record<string,string>;saveDraft:(key:string,text:string)=>void}){
 const q=topic.questions[index],model=models[topic.part as 1|2|3],key=`speaking-plan-${topic.id}-${index}`,plan=readPlan(drafts[key]);
 const [hints,setHints]=useState(true),[showModel,setShowModel]=useState(false);
 const patch=(change:Partial<Plan>)=>saveDraft(key,JSON.stringify({...plan,...change}));
 return <section className="panel speaking-coach"><span className="pill">Part {topic.part} · {topic.title} · {index+1} / {topic.questions.length}</span><h2>先拆开，再连起来说</h2><div className="speaking-prompt"><p lang="en"><WordText text={q.en}/></p><p className="line-translation">{q.zh}</p><div className="row wrap"><button className="text-btn" onClick={()=>speak(q.en)}><Volume2 size={17}/>听题目</button><PlaybackSpeed ariaLabel="题库口语语速"/></div></div><nav className="guide-steps" aria-label="口语练习步骤">{['想内容','连成话','脱离提示','修一处'].map((label,i)=><button key={label} className={plan.stage===i?'active':''} onClick={()=>patch({stage:i})}>{i+1}<span>{label}</span></button>)}</nav>
 {plan.stage===0&&<><h3>{model.name}</h3><p className="small muted">{model.focus}</p><div className="speaking-plan-fields">{model.parts.map((label,i)=><label className="field" key={label}>{i+1}. {label}<span className="muted small">{model.help[i]}</span><textarea rows={2} maxLength={1000} value={plan.points[i]||''} onChange={e=>{const points=[...plan.points];points[i]=e.target.value;patch({points})}} placeholder="先写几个中文或英文关键词，再试着说一句"/></label>)}</div><button className="btn" disabled={!plan.points[0]?.trim()} onClick={()=>patch({stage:1})}>把关键词连成话 <ArrowRight size={16}/></button></>}
 {plan.stage===1&&<><h3>每一块先说一句</h3><p className="guide-keywords">{plan.points.filter(Boolean).join(' → ')||'回到第一步想几个关键词'}</p><p>先直接回答题目。需要解释时加 because，需要例子时加 for example。句子清楚后再加变化。</p><details open={showModel} onToggle={e=>setShowModel(e.currentTarget.open)}><summary>看一个结构示范（阅读 / 公园话题）</summary><blockquote><WordText text={model.sample}/><p className="line-translation">{model.zh}</p></blockquote><button className="text-btn" onClick={()=>speak(model.sample)}><Volume2 size={17}/>听结构示范</button><PlaybackSpeed ariaLabel="口语结构示范语速"/><p className="muted small">借用组织方法，用自己的内容回答上方题目。</p></details><label className="field">我的第一版回答<textarea maxLength={6000} rows={5} value={plan.answer} onChange={e=>patch({answer:e.target.value})} placeholder="把每块写成一句，再连起来。允许先用简单词。"/></label><button className="btn" disabled={wordCount(plan.answer)<3} onClick={()=>{patch({stage:2});setHints(false)}}>关掉句子，开始表达 <ArrowRight size={16}/></button></>}
 {plan.stage===2&&<><h3>用自己的话说，卡住也可以继续</h3><button className="text-btn" onClick={()=>setHints(!hints)}>{hints?'隐藏关键词':'需要时再看关键词'}</button>{hints&&<p className="guide-keywords">{plan.points.filter(Boolean).join(' → ')}</p>}{topic.part===2&&<Timer seconds={60} label="准备时间"/>}<Timer seconds={topic.part===2?120:topic.part===1?30:60} label={topic.part===2?'长答练习':'本站建议练习时长'}/><Recorder/><p className="small muted">先按自己的节奏讲清楚，再尝试限时。录音只在本次页面保留。</p><button className="btn" onClick={()=>patch({stage:3})}>回顾这次表达 <ArrowRight size={16}/></button></>}
 {plan.stage===3&&<><h3>只挑一处，改完再说</h3><p>内容：回答了题目吗？连贯：原因和例子连得上吗？语言：哪个时态或搭配不稳？发音：哪个词需要重听？</p><label className="field">这一遍最需要改的一处<input maxLength={1000} value={plan.fix} onChange={e=>patch({fix:e.target.value})} placeholder="例如：讲过去时忘记把 go 改成 went"/></label><label className="field">改过的版本<textarea rows={5} maxLength={6000} value={plan.retry} onChange={e=>patch({retry:e.target.value})} placeholder="保留原来的意思，只修这一个问题；再换一个细节试试"/></label><Recorder/><p className="notice">{plan.fix.trim()&&wordCount(plan.retry)>=3?'已保存这次修改。下次先只看题目再答，检查能否把改动用出来。':'写下一个问题和修改版，让下次练习有明确起点。'}</p><button className="text-btn" onClick={()=>{patch({stage:2});setHints(false)}}>再说一遍，验证这一处改好了</button></>}
 <p className="small muted">关键词、回答和修改版自动随学习备份保存；这些记录不自动评定雅思分数。</p></section>;
}

export function SpeakingBank({drafts,saveDraft}:{drafts:Record<string,string>;saveDraft:(key:string,text:string)=>void}){
 const route=useRoute();const [data,setData]=useState<Bank|null>(null),[error,setError]=useState(false);
 useEffect(()=>{let active=true;if(ONLINE)bank().then(d=>{if(active)setData(d)}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[]);
 if(!ONLINE)return <p className="notice">扩展口语题库在在线版提供；下方备用口语练习可离线使用。</p>;
 if(!data)return <p role="status" className="notice">{error?'口语题库暂时加载失败，请刷新重试。':'正在加载口语话题…'}</p>;
 const match=route.task?.match(/^(bank-[123]-\d+)-(\d)$/),topic=data.topics.find(t=>t.id===match?.[1])||data.topics[0],index=Math.min(Number(match?.[2]||0),topic.questions.length-1);
 const choose=(id:string,i=0)=>navigate({view:'ielts',tab:'speaking',task:`${id}-${i}`},{keepScroll:true});
 return <div className="speaking-bank"><div className="section-top section-space"><div><h2>把课本里的表达，用到真实话题</h2><p className="muted">66 组话题 · 238 道中英对照题</p></div></div><p className="small muted">{data.notice}</p><div className="bank-selectors"><label className="field">练到哪一步<select value={topic.part} onChange={e=>choose(data.topics.find(t=>t.part===Number(e.target.value))!.id)}><option value={1}>Part 1 · 回答日常问题</option><option value={2}>Part 2 · 讲清一段经历</option><option value={3}>Part 3 · 解释和讨论观点</option></select></label><label className="field">选择话题<select value={topic.id} onChange={e=>choose(e.target.value)}>{data.topics.filter(t=>t.part===topic.part).map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label><label className="field">选择问题<select value={index} onChange={e=>choose(topic.id,Number(e.target.value))}>{topic.questions.map((q,i)=><option key={i} value={i}>问题 {i+1} · {q.zh.split('\n')[0]}</option>)}</select></label></div><SpeakingCoach key={topic.id+'-'+index} topic={topic} index={index} drafts={drafts} saveDraft={saveDraft}/><div className="row spread section-space"><button className="btn secondary" disabled={index===0} onClick={()=>choose(topic.id,index-1)}>上一个问题</button><button className="btn secondary" disabled={index>=topic.questions.length-1} onClick={()=>choose(topic.id,index+1)}>下一个问题</button></div></div>;
}
