'use client';
import {TextbookGrammar} from './textbook-grammar-ui';
import {useState,useEffect,useMemo,useRef} from 'react';
import {BookOpen,LayoutDashboard,Layers,NotebookPen,GraduationCap,ChartNoAxesCombined,ArrowUpRight,ArrowRight,Play,Check,Volume2,Search,Headphones,Flame,Target,Clock3,ChevronRight,Plus,RotateCcw,FolderOpen,Info} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import lessonsData from './data/lessons.json';
import ieltsData from './data/ielts.json';
import {Lesson,Question,Word,State,NceBookId,initial,validateState,day} from './model';
import {LessonView,Grammar,Quiz,WordCard,speak,Recorder} from './learning';
import IELTS from './ielts';
import {ExpressionCollection} from './expression-guide-ui';
import NceStudio,{nceCompleted} from './nce';
import {TodayStudy} from './study-path-ui';
import {bookNames,studyUnit,recommendedStudy} from './study-path';
import {TextbookVocabulary} from './lesson-context';
import {loadLessonLanguage,rowsToText,type LessonLanguage} from './language';
import {readState,writeState} from './offline-store';
import {ProgressSave} from './progress-save';
import {ONLINE} from './runtime-mode';
import SiteMaterials from './site-materials';
import {WordLookupProvider} from './word-lookup';
import {PlaybackSpeed} from './playback-speed';
import {navigate} from './navigation';
import {useRoute,useRouteScroll} from './use-route';
import nceAttribution from './data/nce-attribution.json';
const lessons=lessonsData as Lesson[];
const courseWords=Array.from(new Map(lessons.flatMap(l=>l.vocab).map(w=>[w.word.toLowerCase(),w])).values());
const KEY='english-studio-v1';
const navs=[['today','今日学习',LayoutDashboard],['nce','新概念 · 四册',BookOpen],['words','单词复习',Layers],['grammar','语法与句型',NotebookPen],['ielts','雅思训练',GraduationCap],['progress','学习档案',ChartNoAxesCombined]] as const;
function SideNav({view,go,state}:{view:string,go:(v:string)=>void,state:State}){const {setOpenMobile}=useSidebar();return <Sidebar className="studio-sidebar"><SidebarHeader><a href="#/today" onClick={e=>{e.preventDefault();go('today');setOpenMobile(false)}} className="brand"><span className="brand-icon">E<span>.</span></span><span>句句有进步<small>ENGLISH STUDIO</small></span></a></SidebarHeader><SidebarContent><span className="nav-caption">你的英语学习空间</span><SidebarMenu>{navs.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id||(view==='cloud'&&id==='nce')} onClick={()=>{go(id);setOpenMobile(false)}}><Icon/><span>{label}</span>{id==='words'&&Object.keys(state.cards).length>0&&<span className="nav-count">{Object.values(state.cards).filter(c=>c.due<=Date.now()).length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-course"><span className="tiny-label">FOUNDATION → IELTS</span><p>把基础，变成底气。</p><Progress value={nceCompleted(state)/276*100}/><small>{nceCompleted(state)} / 276 组完成训练</small></div></SidebarContent><SidebarFooter><div className="profile"><span className="avatar">E</span><div><strong>我的学习空间</strong><small>一步一步，真正学会。</small></div></div></SidebarFooter></Sidebar>}
export default function StudyApp(){
 const route=useRoute();useRouteScroll();const view=route.view,lessonId=route.lesson||1;
 const materialStart=useMemo(()=>route.book&&route.lesson?{book:route.book,lesson:route.lesson}:null,[route.book,route.lesson]);
 const [persisted,setPersisted]=useState<State|null>(null);
 const [state,setState]=useState<State>(initial),[ready,setReady]=useState(false),[storageError,setStorageError]=useState(false),[storageBlocked,setStorageBlocked]=useState(false),[storageMode,setStorageMode]=useState('db'),[search,setSearch]=useState(''),[stage,setStage]=useState('all'),[customActive,setCustomActive]=useState(''),[flipped,setFlipped]=useState(false),[reviewClock,setReviewClock]=useState(0);const stateRef=useRef(state);stateRef.current=state;
 useEffect(()=>{let alive=true;(async()=>{try{let parsed:unknown;try{parsed=await readState()}catch{if(alive)setStorageMode('legacy')}if(parsed===undefined){const raw=localStorage.getItem(KEY);if(raw)parsed=JSON.parse(raw)}if(alive&&parsed!==undefined){if(validateState(parsed))setState(parsed);else{setStorageError(true);setStorageBlocked(true)}}}catch{if(alive){setStorageError(true);setStorageBlocked(true)}}finally{if(alive)setReady(true)}})();return()=>{alive=false}},[]);
 useEffect(()=>{if(!ready||storageBlocked)return;let alive=true;(async()=>{try{if(storageMode==='db')await writeState(state);else localStorage.setItem(KEY,JSON.stringify(state));if(alive){setStorageError(false);setPersisted(state)}}catch{if(alive)setStorageError(true)}})();return()=>{alive=false}},[state,ready,storageBlocked,storageMode]);
 useEffect(()=>{const tick=setInterval(()=>setReviewClock(Date.now()),30000);return()=>clearInterval(tick)},[]);
 async function restoreProgress(next:State){if(storageMode==='db')await writeState(next);else localStorage.setItem(KEY,JSON.stringify(next));setState(next);setPersisted(next);setStorageError(false);setStorageBlocked(false)}
 const saveStatus=!ready?'读取中':storageError||storageBlocked?'尚未自动保存':persisted===state?'本机已保存':'正在保存';
 function go(v:string){navigate({view:v});setSearch('');setStage('all')}
 function openLesson(id:number){setState(s=>({...s,lastLesson:id}));navigate({view:'lesson',lesson:id})}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const a=new AbortController();for(const t of [{name:'read_learning_progress',title:'读取学习进度',description:'Read locally saved completed units and mistake counts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({completed:stateRef.current.completed,lastLesson:stateRef.current.lastLesson,mistakes:Object.keys(stateRef.current.mistakes).length})},{name:'open_learning_unit',title:'打开课程',description:'Navigate to an original unit without marking it complete.',inputSchema:{type:'object',properties:{unit:{type:'integer',minimum:1,maximum:36}},required:['unit'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(x:any)=>{if(!Number.isInteger(x?.unit)||x.unit<1||x.unit>36)throw Error('unit must be 1–36');openLesson(x.unit);return {openedUnit:x.unit}}}]){try{Promise.resolve(ctx.registerTool(t,{signal:a.signal})).catch(()=>{})}catch{}}return()=>a.abort()},[]);
 function touch(s:State){return [...new Set([...s.days,day()])]}
 function addWord(w:Word){setState(s=>{const k=w.word.toLowerCase();if(s.cards[k])return s;return {...s,cards:{...s.cards,[k]:{box:0,due:Date.now()}},days:touch(s)}})}
 function addPersonalWord(w:Word){const k=w.word.toLowerCase();if(['__proto__','constructor','prototype'].includes(k)){toast.error('请将这个词连同常用短语一起加入');return}setState(s=>{const list=s.personalWords||[];if(list.length>=2000&&!list.some(x=>x.word.toLowerCase()===k)){toast.error('个人词库最多保留 2,000 个词');return s}return {...s,personalWords:[...list.filter(x=>x.word.toLowerCase()!==k),w],cards:{...s.cards,[k]:s.cards[k]||{box:0,due:Date.now()}},days:touch(s)}});toast.success('已加入个人词库和单词复习')}
 function answer(q:Question,ok:boolean){setState(s=>{const mistakes={...s.mistakes};if(ok)delete mistakes[q.id];else mistakes[q.id]=q;return {...s,mistakes,attempts:s.attempts+1,correct:s.correct+(ok?1:0),days:touch(s)}})}
 function finish(score:number,id?:number){setState(s=>({...s,scores:{...s.scores,[id?'unit-'+id:quizMode]:Math.max(s.scores[id?'unit-'+id:quizMode]||0,score)},completed:id&&score>=75?[...new Set([...s.completed,id])]:s.completed,days:touch(s)}));if(id&&score>=75)toast.success('本课已完成，继续保持！')}
 const quizMode=route.task==='mistakes'?'mistakes':'diagnostic',quizItems=quizMode==='mistakes'?Object.values(state.mistakes):lessons.filter((_,i)=>i%3===0).map(l=>l.exercises[1]);
 function startQuiz(mode:string){navigate({view:'quiz',task:mode})}
 const lesson=lessons.find(l=>l.id===lessonId)||lessons[0],last=state.nceLast||{book:'NCE1' as const,lesson:1};
 const personalWords=useMemo(()=>Array.from(new Map((state.personalWords||[]).map(w=>[w.word.toLowerCase(),w])).values()),[state.personalWords]);
 const personalKeys=useMemo(()=>new Set(personalWords.map(w=>w.word.toLowerCase())),[personalWords]);
 const reserveWords=useMemo(()=>courseWords.filter(w=>!personalKeys.has(w.word.toLowerCase())),[personalKeys]);
 const words=[...personalWords,...reserveWords];
 const due=words.filter(w=>state.cards[w.word.toLowerCase()]?.due<=Date.now());const card=due[0];
 useEffect(()=>setFlipped(false),[card?.word,view]);
 const studiedWords=Object.values(state.cards).filter(c=>c.box>=3).length;
 const filteredLessons=lessons.filter(l=>(stage==='all'||l.level===stage)&&`${l.id} ${l.title} ${l.subtitle} ${l.grammar.title}`.toLowerCase().includes(search.toLowerCase()));
 const streak=useMemo(()=>{let n=0;const d=new Date();if(!state.days.includes(d.toLocaleDateString('en-CA')))d.setDate(d.getDate()-1);while(state.days.includes(d.toLocaleDateString('en-CA'))){n++;d.setDate(d.getDate()-1)}return n},[state.days]);
 function rateCard(known:boolean){if(!card)return;const k=card.word.toLowerCase();setState(s=>{const box=known?Math.min(s.cards[k].box+1,5):0;const days=[0,1,3,7,14,30];return {...s,cards:{...s.cards,[k]:{box,due:Date.now()+(known?days[box]*86400000:600000)}},days:touch(s)}});setFlipped(false)}
 if(!lessons.length)return <main className="loading">正在准备课程…</main>;
 return <WordLookupProvider onAdd={addPersonalWord}><SidebarProvider><SideNav view={view} go={go} state={state}/><div className="main-shell"><header className="topbar"><div className="row"><SidebarTrigger className="mobile-menu" aria-label="打开导航菜单"/><span className="breadcrumb">学习空间 <ChevronRight size={14}/> {navs.find(n=>n[0]===view)?.[1]||({cloud:'新概念 · 整册资料',courses:'备用练习素材',lesson:'备用素材学习',quiz:'练习中心',materials:'我的课文'} as any)[view]}</span></div><div className="row"><span className="local-status" role="status"><span/>{saveStatus}</span><ProgressSave state={state} ready={ready} status={saveStatus} restore={restoreProgress}/></div></header><main className="workspace" id="main">{storageMode==='legacy'&&<div className="notice">此浏览器暂不支持大容量本地资料库，当前仅保存文字记录。需要持久音频时，请使用本地版压缩包里的启动器打开。</div>}{storageError&&<div role="alert" className="notice">本机存储不可用或原记录需要检查。当前学习仍可继续，请用顶部「保存进度」保留当前页面的学习记录；当前更改尚未自动保存。</div>}{!ready&&<div className="notice">正在读取本机学习记录…</div>}
 {ONLINE&&view==='cloud'&&<button className="text-btn nce-back" onClick={()=>go('nce')}>返回新概念四册目录</button>}
 {ONLINE&&<SiteMaterials startAt={materialStart} visible={view==='cloud'} state={state} restore={s=>{setState(s);setStorageError(false);setStorageBlocked(false)}} openLesson={(book,lesson)=>navigate({view:'nce',book,lesson,tab:'listen'})}/>}
 {view==='nce'&&<NceStudio goCloud={(book,lesson)=>navigate({view:'cloud',book,lesson})} state={state} update={setState} addWord={addPersonalWord} onAnswer={answer} goIELTS={()=>go('ielts')}/>}
 {view==='today'&&<>
  <PageTitle eyebrow="A LITTLE EVERY DAY" title="今天，也向前一步。" text="先完成一个小任务，再决定是否继续。"/>
  <div className="today-dashboard"><TodayStudy state={state}/><section className="panel study-shortcuts"><h2>继续与复习</h2><button onClick={()=>navigate({view:'nce',book:last.book,lesson:last.lesson,tab:ONLINE?'materials':'listen'})}><BookOpen size={21}/><span><strong>{state.nceLast?'继续上次课程':'从第一课开始'}</strong><small>{bookNames[last.book]} · 第 {last.lesson} 课</small></span><ChevronRight size={18}/></button><button onClick={()=>go('words')}><Layers size={21}/><span><strong>{due.length?`复习 ${due.length} 个到期词`:'收集本课生词'}</strong><small>{due.length?'先回想意思，再看答案':'从当前课程挑选不熟悉的词'}</small></span><ChevronRight size={18}/></button></section></div>
  <div className="stats-row"><div><span className="stat-icon blue"><BookOpen/></span><span><strong>{nceCompleted(state)}<small> / 276</small></strong><span>完成训练的课程组</span></span></div><div><span className="stat-icon purple"><Layers/></span><span><strong>{studiedWords}</strong><span>复习到第 3 级的词汇</span></span></div><div><span className="stat-icon orange"><Flame/></span><span><strong>{streak}<small> 天</small></strong><span>连续学习</span></span></div><div><span className="stat-icon green"><RotateCcw/></span><span><strong>{due.length}</strong><span>到期待复习词汇</span></span></div></div>
  <details className="panel reserve-materials"><summary>有 30 分钟时，怎样安排 <ChevronRight size={17}/></summary><div className="daily-plan"><button onClick={()=>go('words')}><span className="plan-num">01</span><span><strong>回想学过的词</strong><small>先复习到期词，再选本课生词</small></span><span className="plan-time">5 min</span><ChevronRight size={16}/></button><button onClick={()=>{const next=recommendedStudy(state);navigate({view:'nce',book:next.book,lesson:next.first,tab:ONLINE?'materials':'listen'})}}><span className="plan-num">02</span><span><strong>听清，再用自己的话说</strong><small>同一课程组可以分几天完成</small></span><span className="plan-time">20 min</span><ChevronRight size={16}/></button><button onClick={()=>{const next=recommendedStudy(state);navigate({view:'nce',book:next.book,lesson:next.first,tab:'notes'})}}><span className="plan-num">03</span><span><strong>自查与安排回顾</strong><small>试试能否听懂、理解和自己表达</small></span><span className="plan-time">5 min</span><ChevronRight size={16}/></button></div></details>
  <details className="panel reserve-materials"><summary>需要额外练习时 <ChevronRight size={17}/></summary><p className="muted small">36 个原创单元作为备用素材。先沿新概念学习，遇到具体问题时再选用；已有进度会保留。</p><div className="row wrap"><button className="text-btn" onClick={()=>go('courses')}>浏览备用素材 <ArrowRight size={17}/></button><button className="text-btn" onClick={()=>startQuiz('diagnostic')}>备用素材基础诊断 <ArrowUpRight size={17}/></button></div></details>
  <div className="ielts-strip"><span className="circle-icon"><GraduationCap/></span><div><h3>以雅思为方向，以基础为起点。</h3><p>按实际能力逐步加入听、说、读、写专项。</p></div><button className="text-btn" onClick={()=>go('ielts')}>进入雅思训练 <ArrowRight size={17}/></button></div>
 </>}

 {view==='courses'&&<><PageTitle eyebrow="EXTRA PRACTICE" title="需要时，再来练一练。" text="36 个原创单元作为备用素材，不需要另学一套课程。听读优先使用新概念原声；这里的语音为设备合成。"/><div className="filter-bar"><Tabs value={stage} onValueChange={setStage}><TabsList>{['all','基础起步','表达进阶','雅思衔接'].map(v=><TabsTrigger key={v} value={v}>{v==='all'?'全部课程':v}</TabsTrigger>)}</TabsList></Tabs><SearchField value={search} onChange={setSearch} placeholder="搜索课程或语法"/></div><div className="course-grid">{filteredLessons.map(l=><button className="course-card" key={l.id} onClick={()=>openLesson(l.id)}><div className="section-top"><span className="unit-label">UNIT {String(l.id).padStart(2,'0')}</span>{state.completed.includes(l.id)?<span className="completed"><Check size={14}/>已完成</span>:<span className="muted small">{l.level}</span>}</div><h3>{l.title}</h3><p className="course-sub" lang="en">{l.subtitle}</p><p className="muted small">{l.grammar.title}</p><div className="course-bottom"><span>8 个词汇 · 8 道练习</span><ArrowRight size={17}/></div></button>)}</div>{!filteredLessons.length&&<div className="empty">没有找到相关课程，换个关键词试试。</div>}<div className="notice row spread"><p>沿着新概念主线继续学习，遇到卡点时再回来。</p><button className="btn secondary" onClick={()=>go('nce')}>返回新概念</button></div></>}
 {view==='lesson'&&<LessonView key={lesson.id} lesson={lesson} state={state} addWord={addWord} onAnswer={answer} onFinish={score=>finish(score,lesson.id)} onNext={()=>lesson.id===36?go('courses'):openLesson(lesson.id+1)}/>}
 {view==='quiz'&&<><PageTitle eyebrow="PRACTICE ROOM" title={quizMode==='mistakes'?'把错题，变成会的题。':'12 题基础诊断'} text={quizMode==='mistakes'?'答对后移出错题本；记录保存在当前浏览器。':'覆盖三个阶段的语法要点，仅用于发现薄弱项，不是雅思估分。'}/><section className="panel narrow"><Quiz key={quizMode} questions={quizItems} onAnswer={answer} onFinish={score=>finish(score)}/></section></>}
 {view==='words'&&<>
  <PageTitle eyebrow="REMEMBER FOR LONGER" title="单词复习" text="优先复习个人生词，再从当前课程补充。记住后按 1、3、7、14、30 天复习；再练一次的词 10 分钟后回来。"/>
  <div className="review-grid"><section className="panel flashcard">{card?<>
   <div className="section-top"><div className="row wrap"><span className="pill">待复习 {due.length} 个</span><span className="muted small">{personalKeys.has(card.word.toLowerCase())?'个人生词':'备用素材词汇'}</span></div><button className="icon-btn" aria-label="朗读当前单词" onClick={()=>speak(card.word)}><Volume2/></button></div><PlaybackSpeed ariaLabel="复习单词语速"/>
   <div className="flash-content"><h2 lang="en">{card.word}</h2><p className="ipa">{card.ipa}</p>{flipped?<><p className="meaning">{card.meaning}</p><p className="example" lang="en">{card.example}</p></>:<p className="muted">试着说出意思，再造一个句子。</p>}</div>
   {!flipped?<button className="btn full" onClick={()=>setFlipped(true)}>翻开答案</button>:<div className="row"><button className="btn secondary grow" onClick={()=>rateCard(false)}>再练一次</button><button className="btn grow" onClick={()=>rateCard(true)}>记住了 <Check size={17}/></button></div>}
  </>:<div className="empty"><Layers size={40}/><h2>{Object.keys(state.cards).length?'本轮复习完成':'从本课生词开始'}</h2><p>{Object.keys(state.cards).length?'到期卡片会自动出现，也可以继续加入新单词。':ONLINE?'点开当前课词表中的词，选择需要记住的加入个人生词。':'从已保存课文中点词查义，或展开备用素材选择词汇。'}</p><button className="btn" onClick={()=>navigate({view:'nce',book:last.book,lesson:last.lesson,tab:ONLINE?'words':'listen'})}>{ONLINE?'到当前课程选词':'去课文中选词'} <ArrowRight size={17}/></button></div>}</section><CurrentCourseVocabulary state={state}/></div>
  <div className="section-top section-space"><div><h2>个人生词 · {personalWords.length}</h2><p className="muted">{Object.keys(state.cards).length} 个词已加入复习 · {due.length} 个到期</p></div><SearchField value={search} onChange={setSearch} placeholder="搜索个人生词或中文意思"/></div>
  {personalWords.length?<><div className="word-grid">{personalWords.filter(w=>(w.word+' '+w.meaning).toLowerCase().includes(search.toLowerCase())).map(w=><WordCard key={w.word} word={w} enrolled={!!state.cards[w.word.toLowerCase()]} onAdd={()=>addWord(w)}/>)}</div>{!personalWords.some(w=>(w.word+' '+w.meaning).toLowerCase().includes(search.toLowerCase()))&&<p className="empty">没有找到相关个人生词，换个关键词试试。</p>}</>:<p className="muted small">{ONLINE?'还没有个人生词。在课文或本课词表中点词，即可查看释义并加入复习。':'还没有个人生词。可在已保存的课文中点词，或展开备用素材选择词汇。'}</p>}
  <ReserveVocabulary words={reserveWords} cards={state.cards} addWord={addWord}/>
 </>}

 {view==='grammar'&&<TextbookGrammar/>}
 {view==='ielts'&&<IELTS data={ieltsData} drafts={state.drafts} saveDraft={(id,text)=>setState(s=>({...s,drafts:{...s.drafts,[id]:text}}))} onAnswer={answer} onFinish={(id,score)=>setState(s=>({...s,scores:{...s.scores,[id]:score},days:touch(s)}))}/>}
 {view==='progress'&&<><PageTitle eyebrow="YOUR LEARNING RECORD" title="每一步，都算数。" text={ONLINE?"教材由网站直接提供；学习进度保存在当前浏览器。":"全程本地运行。学习记录与已保存音频保存在当前浏览器。"}/><div className="panel nce-progress-summary"><div><h2>新概念四册进度</h2><p className="muted">{nceCompleted(state)} / 276 组完成训练 · {state.personalWords?.length||0} 个个人生词</p></div><button className="btn secondary" onClick={()=>go('nce')}>返回四册学习 <ArrowRight size={16}/></button></div><ExpressionCollection drafts={state.drafts}/><details className="panel progress-panel reserve-materials"><summary>备用素材进度 · {state.completed.length} / 36 <ChevronRight size={17}/></summary><Progress value={state.completed.length/36*100}/><div className="unit-dots">{lessons.map(l=><button key={l.id} className={state.completed.includes(l.id)?'done':''} onClick={()=>openLesson(l.id)} aria-label={`打开第${l.id}单元${state.completed.includes(l.id)?'，已完成':''}`}>{l.id}</button>)}</div><p className="muted">完成标准：本课练习至少答对 6 / 8 题。</p></details><div className="two-col section-space"><section className="panel"><h2>学习记录</h2><div className="record-row"><span>练习活跃天数</span><strong>{state.days.length} 天</strong></div><div className="record-row"><span>累计答题</span><strong>{state.attempts} 题</strong></div><div className="record-row"><span>累计答对</span><strong>{state.correct} 题</strong></div><div className="record-row"><span>待巩固错题</span><strong>{Object.keys(state.mistakes).length} 题</strong></div><button className="btn secondary full" onClick={()=>startQuiz('mistakes')}>重做错题 <ArrowRight size={17}/></button></section><section className="panel"><h2>本机学习记录</h2><p className="muted">进度、笔记和生词保存在当前浏览器，暂不自动跨设备同步。跟读录音仅在本次练习中保留。</p>{state.custom.length>0&&<button className="text-btn" onClick={()=>go('materials')}><FolderOpen size={17}/>查看已保存课文（{state.custom.length}）</button>}</section></div><section className="panel section-space"><h2>关于课程与考试</h2><p>「句句有进步」是独立英语学习工具，未获新概念英语或 IELTS 官方认证。{ONLINE?'网站教材按实际清单提供；扫描 PDF 未自动识别正文，逐句听读采用配套 LRC，英音缺项会明确显示。':'本地版未预装四册教材，可继续使用本机已有课文和音频。'}语法与句型按教材课次组织，讲解、例句与随手练习由本站编写；原书作为参考，分类名称是本站整理的检索标签。36 个备用单元为原创素材。已保存的个人课文仍可阅读与跟读。</p><p>基础课程与少量专项训练不等于完整雅思备考，也不能据此保证分数。朗读使用设备合成语音；口语录音与写作检查用于自评，不提供自动雅思评分。</p><details className="nce-license"><summary>来源与开源许可</summary><p>点读入口与目录配置来自 <span>finnlyu41-tech/nce</span>。本地版不请求原仓库中的远程资源；本机已有字幕请对照原书。</p><pre>{nceAttribution.license}</pre></details></section></>}
 {view==='materials'&&<><PageTitle eyebrow="YOUR OWN TEXTS" title="已保存的课文" text="继续阅读和跟读此前保存在当前浏览器的课文。"/><div className="materials-grid section-space"><div className="panel material-list">{state.custom.length?state.custom.map(c=><button key={c.id} className={customActive===c.id?'selected':''} onClick={()=>setCustomActive(c.id)}><BookOpen size={17}/>{c.title}<ChevronRight size={16}/></button>):<div className="empty"><BookOpen size={30}/><p>没有已保存的课文</p></div>}</div><div className="panel">{(()=>{const c=state.custom.find(x=>x.id===customActive)||state.custom[0];return c?<><div className="section-top"><h2>{c.title}</h2></div><div className="row wrap"><p className="muted">点击右侧听单句，再跟读。含中文的行会只朗读其中的英文。</p><PlaybackSpeed ariaLabel="自备课文语速"/></div>{c.text.split('\n').filter(x=>x.trim()).map((line,i)=><div className="custom-line" key={i}><p>{line}</p><button className="icon-btn" aria-label={'朗读自备课文第'+(i+1)+'行'} onClick={()=>speak(line.replace(/[^\x00-\x7F]/g,' ').trim())}><Volume2 size={18}/></button></div>)}<Recorder/></>:<div className="empty"><h3>从四册课程开始学习</h3><button className="btn" onClick={()=>go('nce')}>打开新概念课程 <ArrowRight size={16}/></button></div>})()}</div></div></>}
 <nav className={'phone-nav '+(view==='nce'&&route.lesson?'in-lesson':'')} aria-label="手机快捷导航">{[['today','今日',LayoutDashboard],['nce','新概念',BookOpen],['words','复习',Layers],['ielts','雅思',GraduationCap],['progress','记录',ChartNoAxesCombined]].map(([id,label,Icon])=>{const NavIcon=Icon as typeof BookOpen;return <button key={id as string} className={view===id?'active':''} aria-current={view===id?'page':undefined} onClick={()=>go(id as string)}><NavIcon size={20}/><span>{label as string}</span></button>})}</nav><footer className="footer"><span>句句有进步 · English Studio</span><span>{ONLINE?"独立在线版 · 原书听读 · 语法讲解":"完全本地运行 · 语法讲解 · 无云端上传"}</span></footer></main></div><Toaster position="top-center" richColors/></SidebarProvider></WordLookupProvider>
}
function PageTitle({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div></div>}
function SearchField({value,onChange,placeholder}:{value:string,onChange:(s:string)=>void,placeholder:string}){return <label className="search"><Search size={18}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>}

function CurrentCourseVocabulary({state}:{state:State}){
 const {book,lesson}=state.nceLast||{book:'NCE1' as const,lesson:1},unit=studyUnit(book,lesson);
 const [loaded,setLoaded]=useState<LessonLanguage|null>(null);
 useEffect(()=>{let active=true;setLoaded(null);void loadLessonLanguage(book,unit.first).then(data=>{if(active)setLoaded(data)});return()=>{active=false}},[book,unit.first]);
 const language=loaded?.book===book&&loaded.lesson===unit.first?loaded:null;
 const text=state.nce?.[unit.key]?.text||(language?rowsToText(language.rows):'');
 return <section className="panel current-course-vocabulary"><div className="section-top"><h2>{ONLINE?'当前课程词表':'当前课程词句'}</h2><BookOpen size={21}/></div><p className="muted">{bookNames[book]} · 第 {lesson} 课</p><TextbookVocabulary key={`${book}-${lesson}`} book={book} lesson={lesson} text={text}/><button className="text-btn" onClick={()=>navigate({view:'nce',book,lesson,tab:ONLINE?'words':'listen'})}>{ONLINE?'回到本课词句':'回到本课听读'} <ArrowRight size={17}/></button></section>;
}
function ReserveVocabulary({words,cards,addWord}:{words:Word[];cards:State['cards'];addWord:(w:Word)=>void}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState('');
 const filtered=words.filter(w=>(w.word+' '+w.meaning).toLowerCase().includes(query.toLowerCase()));
 return <details className="panel reserve-materials" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary>备用素材词汇 · {words.length} <ChevronRight size={17}/></summary><p className="muted small">来自 36 个原创备用单元；已加入的词卡继续按原计划复习。个人生词在上方单独显示。</p>{open&&<><div className="section-top section-space"><SearchField value={query} onChange={setQuery} placeholder="搜索备用素材词汇"/></div><div className="word-grid">{filtered.map(w=><WordCard key={w.word} word={w} enrolled={!!cards[w.word.toLowerCase()]} onAdd={()=>addWord(w)}/>)}</div>{!filtered.length&&<p className="empty">没有找到相关备用词汇，换个关键词试试。</p>}</>}</details>;
}
