import type {Bank,MiniItem,MiniTask} from '../content';
const banks:Bank[]=['guided','independent','repair','delayed-a','delayed-b'];
const make=(base:Omit<MiniTask,'items'|'calibration'|'level'>,rows:Omit<MiniItem,'id'|'bank'>[]):MiniTask=>({...base,level:'NCE1 第37–48课部分已教微目标；难度未校准',calibration:'uncalibrated',items:rows.map((row,i)=>({...row,id:`${base.id}:${banks[i]}`,bank:banks[i]}))});
export const batch04Tasks:readonly MiniTask[]=[
 make({"id": "mini-n1-37", "courseId": "nce1-37", "groupId": "NCE1-37", "lessons": [37, 38], "skill": "listening", "track": "common", "title": "听工作交接，分清现在与下一步", "teaching": "is/are + 动作-ing表示现在正在做；be going to + 动词原形表示已说明的下一步计划，不证明已经完成。先锁定指定人、物品或颜色，再区分当前和计划。wash洗，paint涂色，wait等待，blue蓝色，white白色，green绿色。只核对受控事实选择，答A/B/C，不评完整雅思听力。本机合成声未人工试听；播放记接触，文字稿记帮助。"},[
  {"material": "Jo: I am washing the cup. I am going to paint the box blue.", "prompt": "登记Jo现在的动作，只写A/B/C：A 洗杯子；B 给盒子涂蓝色；C 等公共汽车。", "hint": "am washing是当前动作；going to paint是下一步计划。", "reference": "A — washing the cup", "accepted": ["A"], "audio": new URL('./audio/mini-n1-37-guided.wav',import.meta.url).href},
  {"material": "Rae: I am washing the dishes. I am going to paint the bookcase white. Ben: I am painting the box green.", "prompt": "你要登记Rae的下一步计划，不是当前工作。只写A/B/C：A 洗碗；B 给盒子涂绿色；C 给书架涂白色。", "hint": "锁定Rae，再取going to后面的计划；Ben是另一个人。", "reference": "C — paint the bookcase white", "accepted": ["C"], "audio": new URL('./audio/mini-n1-37-independent.wav',import.meta.url).href},
  {"material": "Sam: I am painting the door blue. I am going to wash the cups. Jo: I am washing the dishes.", "prompt": "新交接中登记Sam的下一步计划。只写A/B/C：A 给门涂蓝色；B 洗杯子；C 洗碗。", "hint": "同样锁定指定人再分现在/下一步，不沿用上一题颜色计划。", "reference": "B — wash the cups", "accepted": ["B"], "audio": new URL('./audio/mini-n1-37-repair.wav',import.meta.url).href},
  {"material": "Ava: I am waiting for the bus. I am going to do my homework. Leo: I am doing my homework.", "prompt": "同伴问Ava现在在做什么。只写A/B/C：A 正在做作业；B 已完成作业；C 正在等公共汽车。", "hint": "Ava的going to不是Leo的当前动作，也不代表已完成。", "reference": "C — waiting for the bus", "accepted": ["C"], "audio": new URL('./audio/mini-n1-37-delayed-a.wav',import.meta.url).href},
  {"material": "Nora: I am painting the box white. Ben: Are you going to paint the bookcase blue? Nora: No. I am going to paint it green.", "prompt": "已明确it指bookcase。登记Nora确认的书架颜色计划，只写A/B/C：A white；B green；C blue。", "hint": "No否定了提问里的blue；white属于现在的box。", "reference": "B — green", "accepted": ["B"], "audio": new URL('./audio/mini-n1-37-delayed-b.wav',import.meta.url).href},
 ]),
 make({"id": "mini-n1-39", "courseId": "nce1-39", "groupId": "NCE1-39", "lessons": [39, 40], "skill": "reading", "track": "common", "title": "读处置便签，确认允许的对象与去向", "teaching": "What are you going to do with…询问处理计划。give给、show展示、send寄送、take带走；it接明确单件，them接明确多件。Don’t表示禁止动作，计划不是已送达。读最新明确指令，保留物品、接收人和禁令。shelf架子，window窗，daughter女儿，mother母亲，father父亲。只核对受控阅读事实，不自动证明指令执行或主动表达能力。"},[
  {"material": "整理便签\nI am going to put the vase on the shelf. Don’t put it near the window.", "prompt": "给接手人的处置确认哪条正确？只写A/B/C：A 花瓶放窗边；B 花瓶计划放架子上；C 花瓶已在架子上。", "hint": "it明确指vase；计划去向不能改成已经完成。", "reference": "B — planned shelf placement", "accepted": ["B"]},
  {"material": "交接卡\nThese books are for my daughter. I am going to give them to her. Don’t send them to my father.\nThe map is for my mother.", "prompt": "伙伴准备寄books给father。按卡片应怎样纠正？只写A/B/C：A books计划给daughter，不能寄father；B books已交给daughter；C books计划给mother。", "hint": "them紧接books；mother属于map。不要把计划变成已到达。", "reference": "A — books to daughter, not father", "accepted": ["A"]},
  {"material": "新交接卡\nThese pictures are for my mother. I am going to show them to her. Don’t take them to my daughter.\nThe book is for my father.", "prompt": "伙伴准备带pictures给daughter。按卡片应怎样纠正？只写A/B/C：A pictures已给mother；B pictures计划给father；C pictures计划给mother看，不能带给daughter。", "hint": "同样跟住指定复数物品与禁令；show不是已经交付。", "reference": "C — show pictures to mother, not take to daughter", "accepted": ["C"]},
  {"material": "换位留言\nBen: Are you going to put the box on the table?\nJo: No. I am going to put it in the cupboard. Don’t put the cups in it.", "prompt": "已明确it指box。哪条接手信息符合最新留言？只写A/B/C：A box计划放橱柜；cups不能放进box；B box计划放桌子；C cups已放进橱柜。", "hint": "No撤销提问的桌子方案；最后in it禁止把杯子放进盒子。", "reference": "A — box in cupboard; no cups in box", "accepted": ["A"]},
  {"material": "物品分流卡\nI am going to send the letter to my father. I am going to show the map to my sister. Don’t send the map.", "prompt": "只负责map的伙伴应该收到哪条计划？只写A/B/C：A 寄map给father；B 给sister看map，不能寄它；C map已给sister。", "hint": "分别匹配letter/send和map/show；不合并两条物品路线。", "reference": "B — show map to sister; do not send it", "accepted": ["B"]},
 ]),
 make({"id": "mini-n1-41", "courseId": "nce1-41", "groupId": "NCE1-41", "lessons": [41, 42], "skill": "speaking", "track": "common", "title": "口头核对袋中物品，问清尚未检查的存量", "teaching": "量词让不可数物能作为一件报告：a bottle of milk一瓶奶，a loaf of bread一条面包，a bar of soap一块肥皂，a piece of cheese一块奶酪。已核实的物品可报告；未检查不代表没有。Is there any milk/tea…?询问不可数物，Is there a cup…?询问单件。按情境向伙伴说明已知并询问未知，不从量词推断其他存量。录音仅本机本页回放，不上传、不持久保存，刷新需重选。文字备选不算独立口语；自然表达待人工，无自动口语分。"},[
  {"material": "你与伙伴核对购物袋。已核实：袋里有一瓶milk。tea是否在袋里尚未检查，伙伴能检查。", "prompt": "口头说2句：告诉伙伴袋中已核实的物品及单位，再问袋里有没有tea。不要把未知说成没有。", "hint": "There is a bottle of milk in the bag. Is there any tea in the bag?", "reference": "There is a bottle of milk in the bag. Is there any tea in the bag?", "accepted": []},
  {"material": "野餐分工：你已经检查盒子，里面有一条bread。另一个bag由伙伴负责；其中是否有cheese未检查。", "prompt": "向伙伴口头交接2句：报告box里已核实的物品与单位，再询问bag里有没有cheese。让对方分清两个容器，不猜未知存量。", "hint": "先报告a loaf of bread in the box，再问Is there any cheese in the bag?", "reference": "There is a loaf of bread in the box. Is there any cheese in the bag?", "accepted": []},
  {"material": "洗手用品交接：你已检查cupboard，里面有一块soap。另一个box由伙伴负责；其中是否有milk未检查。", "prompt": "换新情境口头说2句：报告cupboard里已核实的物品与单位，再询问box里有没有milk。不把不同容器混为一处。", "hint": "与前题一样分别保留已核实的单位/容器和未检查物品：a bar of soap；any milk。", "reference": "There is a bar of soap in the cupboard. Is there any milk in the box?", "accepted": []},
  {"material": "伙伴要清点餐具。你确认table上有一块cheese。cupboard里是否有一个cup还没检查。", "prompt": "口头说2句：报告table上的已知物品与单位，再向伙伴询问cupboard里有没有单只cup。别把cup当不可数物。", "hint": "There is a piece of cheese on the table. Is there a cup in the cupboard?", "reference": "There is a piece of cheese on the table. Is there a cup in the cupboard?", "accepted": []},
  {"material": "购物袋已由你核实，里面有一瓶milk。table是否有一条bread尚未检查，伙伴在桌边。", "prompt": "向伙伴口头说2句，保留milk单位和已知位置，再问table上有没有一条bread。不把提问当现有事实。", "hint": "a bottle of milk in the bag；Is there a loaf of bread on the table?", "reference": "There is a bottle of milk in the bag. Is there a loaf of bread on the table?", "accepted": []},
 ]),
 make({"id": "mini-n1-43", "courseId": "nce1-43", "groupId": "NCE1-43", "lessons": [43, 44], "skill": "writing", "track": "general-training", "title": "写库存联络短讯，区分有、没有与待查", "teaching": "日常GT起步短讯，不是完整Task1，也不是Academic图表，不给Band。There are some cups报告有若干杯子；There isn’t any tea/There aren’t any cups报告已经核实的零存量。未检查要问，不写成零；some不给精确数量。mass milk/tea/bread配is，复数cups/plates配are。给伙伴保留物品与位置，写自然短句待人工核对。"},[
  {"material": "当前库存：cupboard里有一些cups；cupboard里的tea已经检查，没有。伙伴问这两项现状。", "prompt": "写2句英文库存短讯，报告有cups和没有tea。some的数量未点清，不编数字。", "hint": "There are some cups in the cupboard. There isn’t any tea in the cupboard.", "reference": "There are some cups in the cupboard. There is not any tea in the cupboard.", "accepted": []},
  {"material": "当前核对：table上有一些bread；table上的plates已检查，没有。\n旧便签：table上有plates。", "prompt": "写2句英文更新短讯，以当前核对纠正旧便签。保留bread/plates单复与table位置，不猜bread的块数。", "hint": "按当前核对写some bread和not any plates；旧便签不是当前库存。", "reference": "There is some bread on the table. There are not any plates on the table.", "accepted": []},
  {"material": "当前核对：box里有一些cups；box里的milk已检查，没有。\n旧便签：box里有milk。", "prompt": "换新库存写2句英文更新短讯。保留物品与box位置，用当前信息纠正旧便签，不把不可数milk当复数。", "hint": "同样只写当前some cups和not any milk，不抄旧存量。", "reference": "There are some cups in the box. There is not any milk in the box.", "accepted": []},
  {"material": "你已核实：cupboard里有一些tea，数量没量。table上的plates未检查，伙伴可以查看。", "prompt": "给伙伴写2句短讯：报告已知tea，再问table上有没有plates。不要把未检查说成没有。", "hint": "There is some tea in the cupboard. Are there any plates on the table?", "reference": "There is some tea in the cupboard. Are there any plates on the table?", "accepted": []},
  {"material": "伙伴在box旁。你已核实table上没有bread；box里的cups尚未检查。伙伴需要知道已知缺项与要查哪处。", "prompt": "写2句英文联络短讯：先报告已核实的缺项，再询问box中是否有cups。不要猜有或精确杯数。", "hint": "There isn’t any bread on the table. Are there any cups in the box?", "reference": "There is not any bread on the table. Are there any cups in the box?", "accepted": []},
 ]),
 make({"id": "mini-n1-45", "courseId": "nce1-45", "groupId": "NCE1-45", "lessons": [45, 46], "skill": "listening", "track": "common", "title": "听能力确认，为具体任务安排合适帮助", "teaching": "Can…?询问能否完成；can/cannot说明给定具体任务的能力边界。能做一般动作不等于能处理这件物品；愿意或计划去做也不证明能做。type打字，read读，lift举起，chair椅子，table桌子，box盒子，hat帽子，coat外套。只核对已说出的事实，不评人的实际能力或完整听力；本机合成声未人工试听，文字稿记帮助。"},[
  {"material": "Jo: Can you lift this chair? Ben: Yes, I can. But I cannot lift this table.", "prompt": "伙伴要安排搬table。材料确认Ben能否举起这张table？只写A/B/C：A 能；B 不能；C 没有提到。", "hint": "不要把chair的can移给table的cannot。", "reference": "B — cannot lift this table", "accepted": ["B"], "audio": new URL('./audio/mini-n1-45-guided.wav',import.meta.url).href},
  {"material": "Rae: Can you type? Jo: Yes, I can. Rae: Can you type this letter? Jo: No, I cannot. I cannot read it.", "prompt": "要处理this letter，哪条交接有依据？只写A/B/C：A Jo能打这封信；B Jo一般能打字，但不能打这封信；C Jo不能打任何字。", "hint": "一般can type和this letter的cannot分开，别扩大能力边界。", "reference": "B — can type, cannot type this letter", "accepted": ["B"], "audio": new URL('./audio/mini-n1-45-independent.wav',import.meta.url).href},
  {"material": "Ben: Can you read? Sam: Yes, I can. Ben: Can you read this book? Sam: No, I cannot read this book.", "prompt": "新任务是this book，哪条有依据？只写A/B/C：A Sam一般能读，但不能读这本书；B Sam能读这本书；C Sam不能读任何东西。", "hint": "同样区分一般能力与指定物品，不沿用上题letter或推断所有物品。", "reference": "A — can read, cannot read this book", "accepted": ["A"], "audio": new URL('./audio/mini-n1-45-repair.wav',import.meta.url).href},
  {"material": "Ava: Can you make a hat? Nora: Yes, I can. Ava: Can you make a coat? Nora: I am going to ask Ben.", "prompt": "登记Nora能否make a coat。只写A/B/C：A 已确认能；B 已确认不能；C 本段没有确认能否。", "hint": "ask Ben是下一步计划；它没有直接回答coat的能力问题。", "reference": "C — coat ability unconfirmed", "accepted": ["C"], "audio": new URL('./audio/mini-n1-45-delayed-a.wav',import.meta.url).href},
  {"material": "Leo: Can you lift this box? Mia: No, I cannot. Leo: Can you lift this chair? Mia: Yes, I can.", "prompt": "把可以交给Mia的已确认动作写进任务表，选A/B/C：A lift this box；B lift this chair；C lift this table。", "hint": "只选明确can的具体物品；table未提及，不从chair推广。", "reference": "B — lift this chair", "accepted": ["B"], "audio": new URL('./audio/mini-n1-45-delayed-b.wav',import.meta.url).href},
 ]),
 make({"id": "mini-n1-47", "courseId": "nce1-47", "groupId": "NCE1-47", "lessons": [47, 48], "skill": "reading", "track": "common", "title": "读点单回复，区分通常喜好与这次需求", "teaching": "Do you like…问通常喜好；Do you want…问本次是否要。喜欢不必这次要，不喜欢也不自动推断本次回答。按当前明确答复传递订单，不把通常偏好或旧订单覆盖本次要求。coffee咖啡，milk牛奶，sugar糖，biscuits饼干，eggs鸡蛋，bread面包，apples苹果。只核对受控阅读信息，不评完整雅思阅读或真实点单完成。"},[
  {"material": "点单回复\nDo you like coffee? Yes, I do.\nDo you want coffee now? No, thank you.", "prompt": "这次应记录哪条？只写A/B/C：A 喜欢coffee，这次不要；B 不喜欢coffee；C 这次要coffee。", "hint": "like的Yes和want now的No分别登记。", "reference": "A — likes coffee, does not want it now", "accepted": ["A"]},
  {"material": "早餐回复卡\nJo: I like eggs. I don’t want eggs now. I want bread.\nRae: I want eggs.", "prompt": "只替Jo传递本次需求，应选A/B/C：A eggs；B bread；C eggs和bread。", "hint": "跟Jo的want，不把通常like或Rae的订单合并。", "reference": "B — Jo wants bread now", "accepted": ["B"]},
  {"material": "茶歇回复卡\nSam: I like biscuits. I don’t want biscuits now. I want apples.\nBen: I want biscuits.", "prompt": "只替Sam传递本次需求，应选A/B/C：A biscuits和apples；B biscuits；C apples。", "hint": "与前题同样分开本人通常喜好、本次want和另一人订单。", "reference": "C — Sam wants apples now", "accepted": ["C"]},
  {"material": "当前答复\nDo you want milk in your coffee? No, thank you.\nDo you want sugar? Yes, please.\n旧订单：coffee with milk.", "prompt": "这次咖啡应怎样记录？只写A/B/C：A 加milk、不加sugar；B 不加milk、加sugar；C 加milk和sugar。", "hint": "当前两个明确答复分别管milk与sugar，旧订单被本次信息更新。", "reference": "B — no milk, sugar requested", "accepted": ["B"]},
  {"material": "伙伴当前回复\nI like apples. I don’t like milk. I want bread now.\n尚未问伙伴这次是否要apples。", "prompt": "哪条只用已知事实，不替伙伴补答案？只写A/B/C：A 这次要bread；本次apples需求未确认；B 这次要apples；C 这次不需要任何食物。", "hint": "usually like apples不回答本次want；bread是明确本次需求。", "reference": "A — bread requested; apples not confirmed", "accepted": ["A"]},
 ]),
];
