// Native Chrome against actual final packages; synthetic owned profile only.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdir,readdir,rename} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=new URL('../../',import.meta.url),run=new URL(`work/mini-batch04/browser-${Date.now()}/`,root),origin='http://127.0.0.1:5200';
await mkdir(new URL('downloads/',run),{recursive:true});const profile=fileURLToPath(new URL('chrome-profile/',run));
const chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--autoplay-policy=no-user-gesture-required','--mute-audio','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});
const checks=[],errors=[],requests=[];let page,browser,missing;
class CDP{
 constructor(socket){this.socket=socket;this.seq=0;this.navSeq=0;this.pending=new Map();socket.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=this.pending.get(m.id);if(p){this.pending.delete(m.id);clearTimeout(p.timer);if(m.error)p.reject(Error(JSON.stringify(m.error)));else p.resolve(m.result)}}if(m.method==='Page.frameNavigated'&&!m.params.frame.parentId)this.navSeq++;if(m.method==='Page.javascriptDialogOpening')void this.send('Page.handleJavaScriptDialog',{accept:true});if(m.method==='Runtime.exceptionThrown')errors.push(m.params);if(m.method==='Network.requestWillBeSent')requests.push(m.params.request.url)})}
 static async connect(url){const socket=new WebSocket(url);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true})});return new CDP(socket)}
 send(method,params={}){const id=++this.seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('CDP timeout '+method)),12000);this.pending.set(id,{resolve,reject,timer});this.socket.send(JSON.stringify({id,method,params}))})}
 async eval(fn,arg){const r=await this.send('Runtime.evaluate',{expression:`(${fn.toString()})(${JSON.stringify(arg)})`,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
 async wait(fn,arg,label){for(let i=0;i<120;i++){if((await this.send('Runtime.evaluate',{expression:`!!((${fn.toString()})(${JSON.stringify(arg)}))`,returnByValue:true})).result.value)return;await new Promise(r=>setTimeout(r,100))}throw Error('Timeout '+label)}
 async click(text){await this.wait(text=>{const b=[...document.querySelectorAll('button,a[href]')].find(b=>b.textContent===text);return b&&!b.disabled},text,text);const point=await this.eval(text=>{const b=[...document.querySelectorAll('button,a[href]')].find(b=>b.textContent===text);b.scrollIntoView({block:'center'});const r=b.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}},text);await this.send('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',clickCount:1});await this.send('Input.dispatchMouseEvent',{type:'mouseReleased',...point,button:'left',clickCount:1})}
}
try{
 let active;for(let i=0;i<100;i++){try{active=(await readFile(profile+'/DevToolsActivePort','utf8')).trim().split('\n');break}catch{await new Promise(r=>setTimeout(r,100))}}assert(active);browser=await CDP.connect(`ws://127.0.0.1:${active[0]}${active[1]}`);await browser.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:fileURLToPath(new URL('downloads/',run)),eventsEnabled:true});const {targetId}=await browser.send('Target.createTarget',{url:origin+'/map/'});const list=await fetch(`http://127.0.0.1:${active[0]}/json/list`).then(r=>r.json());page=await CDP.connect(list.find(t=>t.id===targetId).webSocketDebuggerUrl);await page.send('Page.enable');await page.send('Runtime.enable');await page.send('Network.enable');await page.send('Network.setCacheDisabled',{cacheDisabled:true});await page.wait(()=>document.readyState==='complete'&&document.querySelector('main'),null,'normal map');
 const fixtures=JSON.parse(await readFile(new URL('work/mini-batch04/fixtures.json',root),'utf8')),m=await import(new URL('work/mini-batch04/model.mjs',root)),oldKey=m.miniDraftKey('mini-n1-01'),oldRaw=JSON.stringify(fixtures.finalSnapshots['mini-n1-01']),records={};
 async function seed(state,map){await page.eval(async({state,map})=>{localStorage.setItem('english-studio-v1',JSON.stringify(state));if(map)localStorage.setItem('wayfinder-ielts-map:v2',JSON.stringify(map));await new Promise((resolve,reject)=>{const r=indexedDB.open('english-studio-offline',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('state'))r.result.createObjectStore('state')};r.onsuccess=()=>{const d=r.result,t=d.transaction('state','readwrite');t.objectStore('state').put(state,'current');t.oncomplete=()=>{d.close();resolve()};t.onerror=()=>reject(t.error)};r.onerror=()=>reject(r.error)})},{state,map})}
 const saved=()=>page.eval(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('english-studio-offline',1);r.onsuccess=()=>{const d=r.result,t=d.transaction('state'),g=t.objectStore('state').get('current');g.onsuccess=()=>resolve(g.result);g.onerror=()=>reject(g.error);t.oncomplete=()=>d.close()};r.onerror=()=>reject(r.error)}));
 const phase=p=>page.wait(p=>document.querySelector('.mini-task[data-task]')?.dataset.phase===p&&!document.querySelector('.mini-task[data-task] [role=status]')?.textContent.includes('正在'),p,p);
 async function reload(){const n=page.navSeq;await page.send('Page.reload');for(let i=0;i<120&&page.navSeq===n;i++)await new Promise(r=>setTimeout(r,100));assert(page.navSeq>n);await page.wait(()=>document.readyState==='complete',null,'reload')}
 async function fill(value,index=0){await page.eval(i=>{const e=document.querySelectorAll('.mini-task[data-task] textarea')[i];e.focus();e.select()},index);await page.send('Input.insertText',{text:value});await page.wait(()=>!document.querySelector('.mini-task[data-task] [role=status]').textContent.includes('正在'),null,'input write finished')}
 async function clickSelector(selector){await page.wait(s=>!!document.querySelector(s),selector,selector);const pt=await page.eval(s=>{const e=document.querySelector(s);e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}},selector);await page.send('Input.dispatchMouseEvent',{type:'mousePressed',...pt,button:'left',clickCount:1});await page.send('Input.dispatchMouseEvent',{type:'mouseReleased',...pt,button:'left',clickCount:1})}
 async function played(){await page.eval(()=>document.querySelector('.mini-task[data-task] audio').play());await page.wait(()=>document.querySelector('.mini-task[data-task] audio')?.ended,null,'packaged playback ended');await page.wait(()=>!document.querySelector('.mini-task[data-task] [role=status]').textContent.includes('正在'),null,'play saved')}
 async function speech(){const doc=await page.send('DOM.getDocument'),node=await page.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'.mini-task[data-task] input[type=file]'});await page.send('DOM.setFileInputFiles',{nodeId:node.nodeId,files:[fileURLToPath(new URL('mini-task/batch-04/audio/mini-n1-37-guided.wav',root))]});await page.wait(()=>!!document.querySelector('.mini-task[data-task] audio'),null,'synthetic QA local file selected');await page.wait(()=>!document.querySelector('.mini-task[data-task] [role=status]').textContent.includes('正在'),null,'local metadata saved')}
 const map={...m.emptyProgress(),access:{all:true,nodes:[]},lastNode:'nce1-37'};let lastState;
 for(const t of m.batch04Tasks){
  const binding=m.courseLoopBindings.find(b=>b.id===t.courseId),finished=binding.model.transition(fixtures.loops[t.courseId],{type:'finish'},Date.now()-1000);assert(finished.ok);const state=m.enrollFlashcard(structuredClone(m.initial),{word:'qa-example',meaning:'合成QA词',example:'This is a cup.'},[],Date.now()-100);state.drafts[binding.key]=JSON.stringify(finished.state);state.drafts[oldKey]=oldRaw;state.drafts['batch04-qa-unrelated']='synthetic old note';state.cards['qa-card']={box:2,due:Date.now()+864000000};state.scores['1']=4;const key=m.miniDraftKey(t.id);map.lastNode=t.courseId;
  await page.send('Page.navigate',{url:origin+'/map/'});await page.wait(()=>document.querySelector('main'),null,'map seed');await seed(state,map);await reload();await page.wait(id=>document.querySelector('.today-start')?.getAttribute('href')==='/#/mini-task/'+id,t.id,'one eligible Today');assert.equal(await page.eval(id=>[...document.querySelectorAll('.today-practice a[href]')].filter(a=>a.getAttribute('href')==='/#/mini-task/'+id).length,t.id),1);await clickSelector('.today-start');await phase('teaching');await page.click('开始有提示练习');await phase('guided');
  if(t.skill==='speaking')await speech();else{if(t.skill==='listening')await played();await fill(t.items[0].accepted[0]||t.items[0].reference)}
  await page.click('保留首答，提交本题');await phase('feedback');const original=m.restoreMini((await saved()).drafts[key]).view.attempts[0];await fill('修订草稿');await fill('原因草稿',1);await reload();await phase('feedback');assert.equal(await page.eval(()=>document.querySelectorAll('.mini-task[data-task] textarea')[0].value),'修订草稿');await page.click('收起示范，换新材料');await phase('independent');
  if(t.id==='mini-n1-37'){
   const before=(await saved()).drafts[key];await page.eval(()=>{window.qaPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='state'&&args[1]==='current')throw new DOMException('Synthetic batch04 quota','QuotaExceededError');return window.qaPut.apply(this,args)}});await fill(t.items[1].accepted[0]);await page.wait(()=>document.querySelector('.mini-task[data-task] [role=alert]'),null,'failed real writer');for(const label of ['查看今天安排','回到本组课程','打开现有学习记录与备份']){await page.click(label);await page.wait(()=>document.querySelector('.mini-task-host [role=alert]'),null,'leave blocked');assert.equal(await page.eval(()=>location.hash),'#/mini-task/mini-n1-37');assert.equal((await saved()).drafts[key],before)}await page.eval(()=>{location.hash='#/progress'});await page.wait(()=>location.hash==='#/mini-task/mini-n1-37',null,'hash blocked');await page.eval(()=>{IDBObjectStore.prototype.put=window.qaPut});await page.click('重试保存');await phase('independent');await reload();await phase('independent');assert.equal(await page.eval(()=>document.querySelector('.mini-task[data-task] textarea').value),t.items[1].accepted[0]);await page.click('回到本组课程');await page.wait(id=>document.querySelector('.course-loop')?.dataset.course===id,t.courseId,'original course');await page.click('本组适级雅思式小任务');await phase('independent');await page.click('查看今天安排');await page.wait(id=>document.querySelector('.today-start')?.getAttribute('href')==='/#/mini-task/'+id,t.id,'Today resume');await clickSelector('.today-start');await phase('independent');checks.push('37 quota failure/route guard/retry/refresh/paired CL callback/Today resume');
  }
  if(t.skill==='speaking'){
   await speech();await reload();await phase('independent');assert(await page.eval(()=>document.querySelector('.mini-task[data-task]').innerText.includes('请重新选择原录音')));assert.equal(await page.eval(()=>[...document.querySelectorAll('.mini-task[data-task] button')].find(b=>b.textContent==='保留首答，提交本题').disabled),true);await speech();
  }else{if(t.skill==='listening')await played();await fill(t.items[1].accepted[0]||t.items[1].reference)}
  await page.click('保留首答，提交本题');await phase('feedback');const current=await saved(),p=m.restoreMini(current.drafts[key]);assert(p.ok);assert.deepEqual(p.view.attempts[0],original);assert.equal(p.view.attempts.length,2);assert.equal(p.view.attempts[1].independent,true);if(['speaking','writing'].includes(t.skill))assert(p.view.attempts.every(a=>a.status==='awaiting-external-review'&&a.matched===null));assert.equal(current.drafts[binding.key],state.drafts[binding.key]);assert.equal(current.drafts[oldKey],oldRaw);assert.equal(current.drafts['batch04-qa-unrelated'],state.drafts['batch04-qa-unrelated']);for(const f of ['cards','scores','completed','mistakes','attempts','correct','flashcards'])assert.deepEqual(current[f],state[f]);assert.deepEqual(JSON.parse(await page.eval(()=>localStorage.getItem('wayfinder-ielts-map:v2'))).records,map.records);records[key]=current.drafts[key];lastState=current;checks.push(t.id+' normal host real first attempt/feedback/new material/refresh originals isolated');console.log('PASS native '+t.id);
  if(['mini-n1-37','mini-n1-41','mini-n1-43','mini-n1-47'].includes(t.id))for(const width of [390,320]){await page.send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});const size=await page.eval(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));assert(size.scroll<=size.w);const shot=await page.send('Page.captureScreenshot',{format:'png'});await writeFile(new URL(t.id+'-'+width+'.png',run),Buffer.from(shot.data,'base64'))}
 }
 // Actual existing backup download and native file restore, no alternate store.
 Object.assign(lastState.drafts,records);await seed(lastState,map);await page.send('Page.navigate',{url:origin+'/#/progress'});await page.wait(()=>document.querySelector('.progress-save-button:not([disabled])'),null,'actual records backup');await clickSelector('.progress-save-button');let downloaded;for(let i=0;i<120;i++){const files=await readdir(new URL('downloads/',run));downloaded=files.find(n=>n.endsWith('.json'));if(downloaded)break;await new Promise(r=>setTimeout(r,100))}assert(downloaded,'native backup download completed');const backupPath=fileURLToPath(new URL('downloads/'+downloaded,run)),backup=JSON.parse(await readFile(backupPath,'utf8'));assert.deepEqual(backup.state.drafts,lastState.drafts);assert(!JSON.stringify(backup).includes('data:audio'));assert(!JSON.stringify(backup).includes('blob:'));await seed(m.initial,map);await reload();await clickSelector('.progress-save-more');await page.wait(()=>document.querySelector('input[type=file][accept=".json,application/json"]'),null,'existing restore dialog');const doc=await page.send('DOM.getDocument'),node=await page.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'input[type=file][accept=".json,application/json"]'});await page.send('DOM.setFileInputFiles',{nodeId:node.nodeId,files:[backupPath]});await page.click('确认替换并恢复');await page.wait(()=>document.querySelector('.progress-save-receipt')?.textContent.includes('已恢复'),null,'native restore settled');const restored=await saved();for(const [key,raw] of Object.entries(lastState.drafts))assert.equal(restored.drafts[key],raw);assert.deepEqual(restored.cards,lastState.cards);assert.deepEqual(restored.flashcards,lastState.flashcards);await page.send('Page.navigate',{url:origin+'/#/mini-task/mini-n1-37'});await phase('feedback');checks.push('actual existing JSON backup download/file preview/confirmed native restore preserves all mini and CL originals plus cards');
 // Exhaustion is visible and never silently re-enrolled by the real Today.
 const exhaustedTask=m.batch04Tasks.at(-1).skill==='reading'?m.batch04Tasks.at(-1).id:'mini-n1-39',exhaustedState=await saved(),exhaustedKey=m.miniDraftKey(exhaustedTask);exhaustedState.drafts[exhaustedKey]=JSON.stringify(fixtures.finalSnapshots[exhaustedTask]);await seed(exhaustedState,map);await page.send('Page.navigate',{url:origin+'/#/mini-task/'+exhaustedTask});await phase('exhausted');assert(await page.eval(()=>document.querySelector('.mini-task[data-task]').innerText.includes('不会把旧题重复当成新的迁移或达标证明')));const exhaustedRaw=(await saved()).drafts[exhaustedKey];await page.click('查看今天安排');await page.wait(()=>document.querySelector('.today-practice'),null,'Today after finite exhaustion');assert.equal(await page.eval(id=>[...document.querySelectorAll('.today-practice a[href]')].filter(a=>a.getAttribute('href')==='/#/mini-task/'+id).length,exhaustedTask),0);assert.equal((await saved()).drafts[exhaustedKey],exhaustedRaw);checks.push('47 actual finite pool warning/Today omission/original exhausted raw retained');
 // Every root and map audio HTTP URL, including the original frozen ten.
 const version=JSON.parse(await readFile(new URL('dist-online/version.json',root),'utf8')),media=[];for(const [p,sha] of Object.entries(version.mini_audio_assets)){for(const urlPath of [p,'map/'+p]){const r=await fetch(origin+'/'+urlPath),b=Buffer.from(await r.arrayBuffer());assert.equal(r.status,200);assert(/audio\/(?:x-)?wav/.test(r.headers.get('content-type')));assert.equal(createHash('sha256').update(b).digest('hex'),sha);media.push({path:urlPath,status:r.status,mime:r.headers.get('content-type'),sha256:sha})}}
 const due=structuredClone(fixtures.finalSnapshots['mini-n1-37']);due.events=due.events.slice(0,due.events.findIndex(e=>e.type==='review'));const dueState=await saved();dueState.drafts[m.miniDraftKey('mini-n1-37')]=JSON.stringify(due);await seed(dueState,map);await page.send('Page.navigate',{url:origin+'/#/mini-task/mini-n1-37'});await phase('waiting');await page.click('开始到期的新题');await phase('delayed-a');const url=await page.eval(()=>document.querySelector('.mini-task[data-task] audio').src),from=fileURLToPath(new URL('dist-online'+new URL(url).pathname,root));missing={from,to:from+'.qa-missing'};await rename(missing.from,missing.to);await page.eval(async()=>{const a=document.querySelector('.mini-task[data-task] audio');a.load();try{await a.play()}catch{}});await page.wait(()=>document.querySelector('.mini-task[data-task]').innerText.includes('声音暂不可用'),null,'missing media honest');assert.equal(m.restoreMini((await saved()).drafts[m.miniDraftKey('mini-n1-37')]).view.audioPlays,0);await rename(missing.to,missing.from);missing=null;await page.eval(()=>document.querySelector('.mini-task[data-task] audio').load());await played();checks.push('root/map all finite WAV HTTP200/MIME/hash; actual404 earns no exposure; restored real playback; synthetic due route');
 for(const t of m.batch04Tasks.filter(t=>t.skill==='listening')){const state=structuredClone(m.initial),b=m.courseLoopBindings.find(b=>b.id===t.courseId);state.drafts[b.key]=JSON.stringify(fixtures.loops[t.courseId]);await page.send('Page.navigate',{url:new URL('dist/index.html',root).href+'#/mini-task/'+t.id});await page.wait(()=>document.querySelector('[data-mini-host]'),null,'actual file package');await seed(state);await reload();await phase('teaching');await page.click('开始有提示练习');await phase('guided');assert((await page.eval(()=>document.querySelector('.mini-task[data-task] audio').src)).startsWith('data:audio/wav;base64,'));await played();await fill(t.items[0].accepted[0]);await reload();await phase('guided');assert.equal(await page.eval(()=>document.querySelector('.mini-task[data-task] textarea').value),t.items[0].accepted[0]);await page.click('保留首答，提交本题');await phase('feedback');checks.push(t.id+' actual file offline embedded real play/ended+save/refresh/submit')}
 assert.equal(errors.length,0);const external=requests.filter(u=>/^https?:/.test(u)&&!u.startsWith(origin));assert.deepEqual(external,[]);const receipt={checks,media,exceptions:errors.length,externalHTTP:external,profile:'fresh synthetic QA, no user records/profile or natural lesson13 archive read',actualPackages:true,realLearnerSpeech:false,humanAcousticAudit:false,naturalDelayVerified:false,offlineTested:'Chrome desktop file direct mini route',backup:'actual existing UI download and file restore; no audio bytes persisted'};await writeFile(new URL('receipt.json',run),JSON.stringify(receipt,null,2)+'\n');console.log('PASS '+checks.length+' actual packaged batch04 groups. Evidence '+fileURLToPath(run));
}finally{if(missing)await rename(missing.to,missing.from);if(browser)try{await browser.send('Browser.close')}catch{}page?.socket.close();browser?.socket.close();chrome.kill()}
