import fs from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const {entries}=JSON.parse(await fs.readFile(new URL('app/data/textbook-grammar.json',root),'utf8'));
const batches=[];
const add=(id,scope,members,status)=>batches.push({id,scope,groups:members.map(e=>e.id),status,acceptance:['each group: authored diagnostic, targeted study, unseen same-level response, preserved first answer/correction, two delayed banks','source text/audio/comic kept available with explicit help/exposure handling','single next action; no open draft or help converted to independent mastery','model failure/restoration/exposure tests; exact build UI and actual source media checks by owner','content reviewer checks task ambiguity and difficulty; natural delay remains separate learner evidence']});
const nce1=entries.filter(e=>e.book==='NCE1'),nce2=entries.filter(e=>e.book==='NCE2');
add('CL-00','one pilot',nce1.slice(0,1),'content/model/preview tested locally; host integration pending');
add('CL-01','finish first 4 groups',nce1.slice(1,4),'queued; no authored tasks');
add('CL-02','next 4 groups',nce1.slice(4,8),'queued; no authored tasks');
add('CL-03','finish chapter 1',nce1.slice(8,12),'queued; no authored tasks');
for(let i=1;i<6;i++)add(`CL-N1-${i+1}`,'next existing chapter',nce1.slice(i*12,(i+1)*12),'queued; no authored tasks');
for(let i=0;i<8;i++)add(`CL-N2-${i+1}`,'next existing chapter',nce2.slice(i*12,(i+1)*12),'queued; no authored tasks');
for(const book of ['NCE3','NCE4']){const e=entries.filter(e=>e.book===book);for(let i=0;i<e.length;i+=12)add(`CL-${book}-${i/12+1}`,'supplemental material, selected only for demonstrated need',e.slice(i,i+12),'queue inventory; not a required route or authored tasks')}
const proposal={status:'execution proposal; no user-confirmed total duration, lesson cap or workload',basis:'276 existing teaching groups; each listed once; no new invented lesson total',batches,routeProposal:{oneRecommendation:['resume unsaved/incomplete step without replacing input','repair an actual failed attempt','oldest due lesson with unused new material','next scheduled course/micro-task','checkpoint when its explicit evidence is ready'],ieltsRotation:{cadence:'one suitably graded mini-task after each 3 completed teaching groups',order:['listening','reading','speaking','writing'],status:'proposed insertion contract, NOT registered or authored here',existingReusable:'8 registered lessons per exam category; reuse only after prerequisites and media QA. No duplicate work on other author batches.',firstChapter:'After groups 3/6/9/12, build or choose a genuinely beginner-sized task; do not silently send a beginner to the harder hub/course material.'},checkpoint:'after each existing 12-group chapter: new same-level integrated task + separate delayed evidence; reuse existing project record but do not call a task instruction an authored test',supplements:'NCE3/4 remain accessible; choose targeted remediation through same route, never require all four books before IELTS'}};
const file=new URL('docs/course-loop-batches.json',root),text=JSON.stringify(proposal,null,2)+'\n';if(process.argv.includes('--check')){if(await fs.readFile(file,'utf8')!==text)throw Error('Stale batch inventory')}else await fs.writeFile(file,text);
console.log(`${batches.length} bounded batch records, ${batches.flatMap(b=>b.groups).length} groups; only CL-00 authored.`);
