import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile,mkdtemp} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const root=fileURLToPath(new URL('./',import.meta.url));
const proof=fileURLToPath(new URL('../work/course-loop-qa/',import.meta.url));await mkdir(proof,{recursive:true});
const profile=await mkdtemp(join(proof,'profile-'));
const server=createServer(async(req,res)=>{const pathname=new URL(req.url,'http://local').pathname;const name=pathname==='/'?'preview.html':pathname.slice(1);if(!['preview.html','preview.mjs','model.mjs','lesson-nce1-001.mjs'].includes(name)){res.writeHead(404).end();return}res.setHeader('content-type',name.endsWith('.mjs')?'text/javascript':'text/html');res.end(await readFile(join(root,name)))});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const chrome=spawn(process.env.COURSE_LOOP_BROWSER||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-first-run','--no-default-browser-check',`--user-data-dir=${profile}`,'--remote-debugging-port=0',origin],{stdio:['ignore','ignore','pipe']});
let browserWS='';chrome.stderr.on('data',x=>{browserWS+=(x.toString())});
const until=async(fn)=>{const end=Date.now()+15000;while(Date.now()<end){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,50))}throw Error('Timed out')};
let socket;const errors=[],checks=[];let sequence=0;const pending=new Map();
try{
 await until(()=>browserWS.match(/DevTools listening on (ws:\/\/[^\s]+)/));const address=new URL(browserWS.match(/DevTools listening on (ws:\/\/[^\s]+)/)[1]);
 const pages=await fetch(`http://${address.host}/json/list`).then(r=>r.json());const page=pages.find(p=>p.url.startsWith(origin));assert(page);
 socket=new WebSocket(page.webSocketDebuggerUrl);socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}};
 await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject});
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence,timer=setTimeout(()=>reject(Error(method+' timeout')),10000);pending.set(id,{resolve,reject,timer});socket.send(JSON.stringify({id,method,params}))});
 const evaluate=async(fn,arg)=>{const r=await send('Runtime.evaluate',{expression:`(${fn.toString()})(${JSON.stringify(arg)})`,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description);return r.result.value};
 await send('Runtime.enable');await send('Page.enable');await until(()=>evaluate(()=>document.querySelector('#root h2')));
 const text=()=>evaluate(()=>document.querySelector('#root').innerText);
 const click=async(label)=>{const p=await evaluate(label=>{const n=[...document.querySelectorAll('button')].find(n=>n.textContent===label);if(!n)throw Error('No button '+label);n.scrollIntoView({block:'center'});const r=n.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}},label);await send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});};
 const fill=async(value,index=0)=>{await evaluate(index=>{const n=document.querySelectorAll('input,textarea')[index];n.focus();n.select()},index);await send('Input.insertText',{text:value})};
 const answer=async(value)=>{if(value==='Pardon?')await click(value);else await fill(value);await click('提交本题')};
 const check=async(label,fn)=>{await fn();checks.push(label);console.log('PASS '+label)};
 await check('initial independent preview hides all model/answer/review text',async()=>{assert.doesNotMatch(await text(),/Is this your book\?|Yes, it is|phone|工作坊分发/);assert.equal(await evaluate(()=>localStorage.length),0)});
 await check('explicit beginner not-yet response can advance without an invented answer',async()=>{await click('暂时不会，先记下');assert.match(await text(),/首答已留在本页/);await click('下一题');assert.match(await text(),/刚才掉的笔/);await send('Page.reload');await until(()=>evaluate(()=>document.querySelector('#root h2')?.textContent.includes('这是你的书')))});
 await answer('wrong');await click('下一题');await answer('Yes, it is.');await click('下一题');await answer('Pardon?');await click('看针对性讲解');
 await check('diagnostic leads to targeted explanation and explicit host-only media',async()=>{assert.match(await text(),/问“是不是”/);assert.match(await text(),/当前预览只提供宿主接口说明/)});
 await click('跟着换一句');await answer('Is this your bag?');await click('下一题');await answer('Yes, it is.');await click('下一题');await answer('Pardon?');await click('收起示范，自己试');
 await check('new independent question conceals study answer, later tasks and future banks',async()=>{assert.doesNotMatch(await text(),/Is this your bag\?|Is this your coat\?|电话接通|手机/);assert.match(await text(),/衣帽间/)});
 await answer('This is your coat?');await click('下一题');await answer('Yes, it is.');await click('下一题');await answer('Pardon?');await click('看首答与反馈');
 await check('feedback retains original wrong sentence; missing correction cannot skip',async()=>{assert.match(await text(),/你的首答：This is your coat\?/);await click('换三个情境，再试一次');assert.match(await evaluate(()=>document.querySelector('#error').textContent),/订正/)});
 await fill('Is this your coat?',0);await fill('Is 要放在问句开头。',1);await click('保留这条订正');await click('换三个情境，再试一次');
 await answer('wrong');await click('对照后重试');await answer('Is this your key?');await click('下一题');await answer('Yes, it is.');await click('下一题');await answer('Pardon?');await click('换成自己的问答');
 await fill('Is this your pen? Yes, it is.');await click('保留本次记录，安排复习');
 await check('end shows real future due, unassessed draft and no fake save or early review',async()=>{assert.match(await text(),/当前未到期/);assert.match(await text(),/待人工核对/);assert.equal(await evaluate(()=>[...document.querySelectorAll('button')].some(n=>n.textContent==='开始到期的新题')),false);assert.equal(await evaluate(()=>localStorage.length),0)});
 await send('Emulation.setDeviceMetricsOverride',{width:360,height:780,deviceScaleFactor:1,mobile:false});
 await check('local preview 360px fits; no runtime errors',async()=>{assert.equal(await evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[])});
 const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(join(proof,'preview-complete-360.png'),Buffer.from(shot.data,'base64'));
 await send('Page.reload');await until(()=>evaluate(()=>document.querySelector('#root')?.innerText.includes('先尝试')));
 await check('preview accurately discloses non-persistence; refresh returns to first attempt',async()=>{assert.match(await evaluate(()=>document.body.innerText),/刷新会清空/);assert.doesNotMatch(await text(),/你的首答：This is your coat/)});
 await writeFile(join(proof,'receipt.json'),JSON.stringify({source:'local unintegrated course-loop preview',browser:(await send('Browser.getVersion')).product,checks,errors,scope:'Native CDP clicks/insertText in fresh task-owned Chrome. No production access, injected clock, user records or audio. Model tests separately simulate delayed time.',screenshot:'preview-complete-360.png'},null,2)+'\n');
}finally{socket?.close();chrome.kill('SIGTERM');await new Promise(r=>server.close(r));}
