import test from 'node:test';
import assert from 'node:assert/strict';
import {lesson,questions,byId,matches} from './lesson-nce1-001.mjs';
import {initialState,transition,inspect,currentQuestion,teachingFor,receipt,recommendation,restore} from './model.mjs';
const START=1790900000000;
function run(){let state=initialState(START),now=START;return {get state(){return state},get now(){return now},get view(){return inspect(state,now).view},at(n){now=n},do(action){const r=transition(state,action,++now);assert.equal(r.ok,true,r.message);state=r.state;return r},reject(action){const before=JSON.stringify(state),r=transition(state,action,++now);assert.equal(r.ok,false);assert.equal(JSON.stringify(r.state),before);return r},answer(value){const q=currentQuestion(this.view);this.do({type:'draft',value:value??q.accepted[0]});this.do({type:'submit'});},stage(){const phase=this.view.phase;while(this.view.phase===phase){this.answer();this.do({type:'next'})}},toIndependent(){this.stage();this.do({type:'next'});this.stage()},finish(){this.toIndependent();this.stage();this.do({type:'next'});this.stage();this.do({type:'own-draft',value:'My own draft, still unassessed.'});this.do({type:'finish'})}}}
test('content: 18 unique complete tasks; six disjoint contexts; source-bound first lesson',()=>{
 assert.equal(questions.length,18);assert.equal(new Set(questions.map(q=>q.id)).size,18);assert.equal(new Set(questions.map(q=>q.context)).size,18);
 assert.deepEqual(lesson.lessons,[1,2]);assert.equal(lesson.source.clips.length,3);
 for(const q of questions){assert.ok(q.accepted.length&&q.why&&q.context&&q.prompt);assert.ok(q.accepted.every(a=>matches(q,a)));if(q.options)assert.ok(q.accepted.every(a=>q.options.includes(a)))}
});
test('bounded matcher accepts case, whitespace and terminal Chinese punctuation; rejects wrong grammar and extra claims',()=>{
 const q=byId.get('independent-ask');for(const a of ['IS THIS YOUR COAT？',' Is  this your coat. ','Is this your coat?'])assert.equal(matches(q,a),true);
 for(const a of ['This is your coat?','Is your this coat?','Is this my coat?','Is this your coats?','Is this your coat? Yes.','coat'])assert.equal(matches(q,a),false);
 assert.equal(matches(byId.get('independent-confirm'),'Yes, I am.'),false);
});
test('initial route exposes only first test item and cannot finish or bypass first attempts',()=>{const r=run();assert.deepEqual(r.view.exposures.map(x=>x.id),['diagnostic-ask']);assert.deepEqual(r.view.learning,[]);for(const type of ['next','submit','finish','review'])r.reject({type});assert.equal(receipt(r.view).mastery,'not-assessed')});
test('diagnostic wrong answer selects targeted teaching first; original persists',()=>{const r=run();r.answer();r.do({type:'next'});r.answer('Yes, I am.');r.do({type:'next'});r.answer();r.do({type:'next'});assert.equal(teachingFor(r.view)[0].target,'confirm');assert.equal(r.view.attempts[1].answer,'Yes, I am.');assert.equal(r.view.learning.length,3)});
test('reading/audio/comic access recorded separately; active answer becomes assisted',()=>{for(const source of ['text','audio','comic']){const r=run();r.do({type:'source',source});r.answer();assert.equal(r.view.attempts[0].hinted,true);assert.equal(r.view.learning[0].id,`nce1-1:${source}`);assert.equal(r.view.exposures.length,1);assert.equal(receipt(r.view).listening,'not-tested')}});
test('study materials do not pre-expose independent or delayed banks',()=>{const r=run();r.toIndependent();assert.equal(r.view.exposures.some(x=>x.id.startsWith('review-')),false);assert.deepEqual(r.view.exposures.filter(x=>x.id.startsWith('independent')).map(x=>x.id),['independent-ask']);assert.equal(r.view.hinted,false)});
test('first answer cannot be overwritten; duplicate submit rejected',()=>{const r=run();r.answer('bad');r.reject({type:'draft',value:'correct'});r.reject({type:'submit'});r.reject({type:'retry'});assert.equal(r.view.attempts[0].answer,'bad')});
test('guided failure: feedback then retry preserves wrong original and is not fresh independent evidence',()=>{const r=run();r.stage();r.do({type:'next'});r.answer('wrong');r.reject({type:'next'});r.do({type:'retry'});r.answer();const [wrong,right]=r.view.attempts.slice(-2);assert.equal(wrong.answer,'wrong');assert.equal(right.correct,true);assert.equal(right.fresh,false);assert.equal(right.hinted,true);r.do({type:'next'})});
test('wrong independent answer requires correct separate correction plus note',()=>{const r=run();r.toIndependent();r.answer('This is your coat?');r.do({type:'next'});r.answer();r.do({type:'next'});r.answer();r.do({type:'next'});r.reject({type:'next'});r.reject({type:'correct',id:'independent-ask',answer:'Is this your coat?',note:''});r.reject({type:'correct',id:'independent-ask',answer:'bad',note:'Is first'});r.do({type:'correct',id:'independent-ask',answer:'Is this your coat?',note:'把 Is 移到问句开头。'});r.do({type:'next'});assert.equal(r.view.attempts.find(a=>a.id==='independent-ask').answer,'This is your coat?');assert.equal(r.view.corrections['independent-ask'].answer,'Is this your coat?')});
test('hinted correct answer remains assisted and requires correction note',()=>{const r=run();r.toIndependent();r.do({type:'help'});r.stage();r.reject({type:'next'});r.do({type:'correct',id:'independent-ask',answer:'Is this your coat?',note:'看过语序提示，需要撤掉再试。'});r.do({type:'next'});assert.equal(receipt(r.view).independent[0].assisted,true)});
test('repair failure must retry; later pass keeps both attempts and makes no mastery claim',()=>{const r=run();r.toIndependent();r.stage();r.do({type:'next'});r.answer('bad');r.reject({type:'next'});r.do({type:'retry'});r.answer();r.do({type:'next'});r.stage();r.do({type:'finish'});assert.equal(r.view.ownFinal.status,'not-recorded');assert.equal(receipt(r.view).band,null)});
test('one route returns resume then continue-route and only real due review',()=>{const r=run();assert.equal(recommendation(r.view,r.now).kind,'resume');r.finish();const due=r.view.dueAt;assert.equal(due,r.now+lesson.intervals.first);assert.equal(recommendation(r.view,due-1).kind,'continue-route');assert.equal(recommendation(r.view,due).kind,'review');r.reject({type:'review'});r.at(due);r.do({type:'review'});assert.equal(r.view.phase,'review-a')});
test('review entry/view alone does not create results or postpone due',()=>{const r=run();r.finish();const due=r.view.dueAt;r.at(due);r.do({type:'review'});assert.equal(r.view.dueAt,due);assert.equal(r.view.reviewResults.length,0);assert.equal(recommendation(r.view,r.now).kind,'resume')});
test('actual complete unassisted new review schedules seven days from completion, not original due',()=>{const r=run();r.finish();r.at(r.view.dueAt+3*86400000);r.do({type:'review'});r.stage();assert.equal(r.view.reviewResults[0].independent,true);assert.equal(r.view.dueAt,r.now+7*86400000);r.do({type:'next'});assert.equal(r.view.reviewResults.length,1)});
test('failed or helped review schedules one day, even with otherwise correct answers',()=>{for(const help of [true,false]){const r=run();r.finish();r.at(r.view.dueAt);r.do({type:'review'});if(help)r.do({type:'source',source:'comic'});r.answer(help?undefined:'wrong');r.do({type:'next'});r.stage();assert.equal(r.view.reviewResults[0].independent,false);assert.equal(r.view.dueAt,r.now+86400000)}});
test('two review banks exhaust honestly; opening prior material never replenishes bank',()=>{const r=run();r.finish();for(let i=0;i<2;i++){r.at(r.view.dueAt);r.do({type:'review'});r.stage();r.do({type:'next'})}r.at(r.view.dueAt);assert.equal(recommendation(r.view,r.now).kind,'needs-new-material');r.reject({type:'review'});assert.equal(r.view.reviewResults.length,2)});
test('UTC elapsed interval unaffected by display timezone or missed days',()=>{const r=run();r.finish();const due=r.view.dueAt;for(const tz of ['UTC','Asia/Shanghai','America/New_York']){new Intl.DateTimeFormat('en',{timeZone:tz}).format(due);assert.equal(receipt(r.view,due-1).due,false);assert.equal(receipt(r.view,due).due,true)}assert.equal(r.view.reviewResults.length,0)});
test('JSON replays all originals, corrections, drafts, hints, exposures, position and due without migration',()=>{const r=run();r.finish();r.at(r.view.dueAt);r.do({type:'review'});r.do({type:'help'});r.do({type:'draft',value:'unfinished'});const restored=restore(JSON.stringify(r.state),r.now);assert.equal(restored.ok,true);assert.deepEqual(restored.view,r.view);assert.equal(restored.view.draft,'unfinished');assert.equal(restored.view.hinted,true);assert.equal(restored.view.ownFinal.status,'awaiting-human-review')});
test('corrupt/future/unsupported snapshots preserve raw instead of resetting',()=>{for(const raw of ['{',JSON.stringify({...initialState(START),version:2}),JSON.stringify(initialState(START+100))]){const r=restore(raw,START);assert.equal(r.ok,false);assert.equal(r.raw,raw)}});
test('out-of-order or injected future action rejected and state immutable',()=>{const r=run(),old=JSON.stringify(r.state);const next=transition(r.state,{type:'draft',value:'a'},START-1);assert.equal(next.ok,false);assert.equal(JSON.stringify(r.state),old);r.reject({type:'draft',value:'b',at:START+999});r.reject({type:'bogus'});r.reject({type:'source',source:'external'})});
test('host may acknowledge persistence separately: pure model does not touch storage, navigation, audio, or map',async()=>{const {readFile}=await import('node:fs/promises');const s=await readFile(new URL('./model.mjs',import.meta.url),'utf8');assert.doesNotMatch(s,/localStorage|indexedDB|navigator\.|window\.|fetch\(/)});

test('typing drafts coalesce without dropping submitted originals or help events',()=>{const r=run();for(let i=1;i<=2500;i++)r.do({type:'draft',value:'x'.repeat(i%500+1)});assert.equal(r.state.events.length,1);r.do({type:'help'});r.do({type:'draft',value:'Is this your book?'});r.do({type:'submit'});assert.equal(r.view.attempts[0].hinted,true);assert.equal(r.view.attempts[0].answer,'Is this your book?');assert.equal(restore(JSON.stringify(r.state),r.now).ok,true)});

test('explicit not-yet response lets a beginner reach teaching without fabricating success or silently skipping',()=>{const r=run();for(let i=0;i<3;i++){r.do({type:'not-yet'});r.reject({type:'submit'});r.do({type:'next'})}assert.equal(r.view.phase,'learn');assert.ok(r.view.attempts.every(a=>a.responseKind==='not-yet'&&!a.correct));assert.equal(receipt(r.view).dueAt,null)});
