import React, {useState} from 'react';
import {ArrowRight, BookOpen, Check, ChevronDown, Lock, Search} from 'lucide-react';
import {nodes, nodeById, originalSite, type MapNode} from './content';
import {achieved, learningLabel, manuallyUnlocked, statusMap, type Progress} from './model';
import {catalogueGroups, catalogueItems, catalogueTitle, type CatalogueGroup} from './navigation';

export function CourseCatalogue({group,query,state,current,browse,search,open}:{group:CatalogueGroup;query:string;state:Progress;current:string;browse:(group:CatalogueGroup)=>void;search:(query:string)=>void;open:(id:string)=>void}) {
  const chapters=nodes.filter(n=>n.kind==='course' && n.stage===(group==='NCE1'?'foundation':'bridge'));
  const [expanded,setExpanded]=useState<string|undefined>(chapters.some(n=>n.id===nodeById(current)?.parent)?nodeById(current)?.parent:chapters[0]?.id);
  const statuses=statusMap(state),results=catalogueItems(group,query);
  function row(node:MapNode) {
    return <button key={node.id} className={`catalogue-lesson ${statuses[node.id]}`} onClick={()=>open(node.id)}>
      <span className="catalogue-status" aria-hidden="true">{achieved(node,state)?<Check size={18}/>:statuses[node.id]==='locked'?<Lock size={17}/>:<BookOpen size={18}/>}</span>
      <span><strong>{catalogueTitle(node)}</strong><small>{node.kind==='unit'?node.subtitle:node.kind==='starter'?'零基础起步':node.stage==='summit'?'模考与成绩':'雅思专项'}{node.kind==='unit'&&<> · <span lang="en">{node.title}</span></>}</small><small>{manuallyUnlocked(node,state)?'手动解锁 · ':''}{learningLabel(node,state)}{statuses[node.id]==='locked'?' · 待解锁':''}</small></span><ArrowRight size={16}/>
    </button>;
  }
  return <section className="course-catalogue" aria-label="在学习路线中找课">
    <div className="catalogue-tools"><label className="catalogue-search"><Search size={18}/><input aria-label="搜索学习课程" placeholder="搜索目标、课号或英文标题" value={query} onChange={e=>search(e.target.value)}/>{query&&<button aria-label="清除课程搜索" onClick={()=>search('')}>清除</button>}</label><label className="catalogue-filter"><span>范围</span><select aria-label="选择课程范围" value={group} onChange={e=>browse(e.target.value as CatalogueGroup)}>{catalogueGroups.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label></div>
    {query.trim()?<><p className="catalogue-count" role="status">{results.length} 个匹配的学习内容</p><div className="catalogue-list">{results.map(row)}</div>{!results.length&&<div className="catalogue-empty"><h2>没有找到相关课程</h2><p>可以试试“物品”“第 1 课”或英文课文名，也可以扩大检索范围。</p><button className="secondary" onClick={()=>{location.hash='#/courses'}}>查看全部课程</button></div>}</>:group==='all'?<div className="catalogue-groups">{catalogueGroups.filter(g=>g.id!=='all').map(g=>{const items=catalogueItems(g.id,'');return <button key={g.id} onClick={()=>browse(g.id)}><span className="mini-label">{g.caption}</span><h2>{g.title}</h2><p>{g.description}</p><span className="catalogue-group-foot">{items.length?`${items.filter(n=>achieved(n,state)).length} / ${items.length} ${g.id.startsWith('NCE')?'组初次通过':'项完成'}`:'新概念第三、四册 · 按需选读'}<ArrowRight size={18}/></span></button>})}</div>:group==='NCE1'||group==='NCE2'?<div className="catalogue-chapters">{chapters.map(chapter=>{const items=chapter.members!.map(id=>nodeById(id)!);return <section key={chapter.id} className="catalogue-chapter"><h2><button aria-expanded={expanded===chapter.id} aria-controls={`catalogue-${chapter.id}`} onClick={()=>setExpanded(expanded===chapter.id?undefined:chapter.id)}><span><small>第 {group==='NCE1'?chapter.chapter!+1:chapter.chapter!-5} 章</small><strong>{chapter.title}</strong></span><span>{items.filter(n=>achieved(n,state)).length} / {items.length}<ChevronDown size={18}/></span></button></h2>{expanded===chapter.id&&<div id={`catalogue-${chapter.id}`}><div className="catalogue-list">{items.map(row)}</div><button className="text-button catalogue-project" onClick={()=>open(chapter.id)}>本章作品与解锁条件 <ArrowRight size={15}/></button></div>}</section>})}</div>:group==='extra'?<div className="catalogue-groups">{[{book:'NCE3',title:'第三册',description:'长句理解、篇章阅读和复述补强。'},{book:'NCE4',title:'第四册',description:'较深入的篇章与表达，按需要选读。'}].map(b=><a key={b.book} href={`${originalSite}#/nce/${b.book}`}><span className="mini-label">补充选读</span><h2>新概念{b.title}</h2><p>{b.description}</p><span className="catalogue-group-foot">查看课文、原声与已有笔记 <ArrowRight size={18}/></span></a>)}</div>:<div className="catalogue-list">{results.map(row)}</div>}
    <details className="catalogue-resources"><summary>其他学习资料</summary><div><a href={`${originalSite}#/ielts`}>雅思专项资料</a><a href={`${originalSite}#/cloud`}>整册资料与下载</a><a href={`${originalSite}#/courses`}>备用练习素材</a></div></details>
  </section>;
}
