import React, {useEffect, useState} from 'react';
import {ArrowRight, Check, Lock, RotateCcw, BookOpen, Lightbulb} from 'lucide-react';
import {nodeById, courseUrl, type MapNode} from './content';
import {unitById, guidesFor, firstChapterFocus, sourceLabel, starters, type Unit, type MapQuestion} from './curriculum';
import {achieved, learningLabel, manuallyUnlocked, emptyRecord, updateDraft, chapterProgress, statusMap, stable, due, nextReviewAt, projectErrors, type Project, type Progress} from './model';
import {ClipButton, Recorder, StopAudio} from './media';
import {loadLessonLanguage, loadDictionary, findWord, type LessonLanguage, type DictionaryEntry} from '../app/language';
import {readJsonResource} from '../app/network';
import {splitLesson} from '../app/lesson-structure';
import {grammarEntryFor, grammarSourceHash} from '../app/textbook-grammar';
import type {PageIndex} from '../app/lesson-context';
import type {Save} from './learning';
import {GuidedExpression} from './expression';
import {lessonPlan} from './lesson-plan';

export function StarterTeaching({node,state,save,ready}:{node:MapNode;state:Progress;save:Save;ready:()=>void}){
  const starter=starters.find(s=>s.id===node.id)!;
  const [choice,setChoice]=useState('');
  const index=Math.min(state.records[node.id]?.exampleIndex||0,starter.lines.length),row=starter.lines[index];
  const move=(exampleIndex:number)=>{setChoice('');save(s=>({...s,records:{...s.records,[node.id]:{...(s.records[node.id]||emptyRecord()),exampleIndex}}}));};
  return <section className="focus-starter"><StopAudio key={index}/>{row?<><div className="quiz-position"><span>示范 {index+1} / {starter.lines.length}</span><span>听一句，跟着说</span></div><article className="starter-one"><p lang="en">{row.en}</p><p>{row.zh}</p>{'clip' in row&&<ClipButton clip={row.clip} label="听这一句"/>}</article><div className="quiz-actions"><button className="text-button" disabled={index===0} onClick={()=>move(index-1)}>上一句</button><button className="primary" onClick={()=>move(index+1)}>{index===starter.lines.length-1?'跟着试一次':'下一句'}<ArrowRight size={17}/></button></div><details className="starter-tip"><summary>怎么学这一小步？</summary><p>{starter.tip}</p></details></>:<><span className="mini-label">跟着试 · 这一步可以看示范</span><h2>{starter.question}</h2><div className="choices">{starter.options.map(o=><button key={o} aria-pressed={choice===o} className={choice===o?'picked':''} onClick={()=>setChoice(o)}>{o}</button>)}</div>{choice&&<p role="status">{choice===starter.answer?'选对了。接下来收起示范，独立试一次。':'还不太对，可以回听上一句再选。'}</p>}<div className="quiz-actions"><button className="text-button" onClick={()=>move(starter.lines.length-1)}>回看示范</button><button className="primary" onClick={ready}>自己试<ArrowRight size={17}/></button></div></>}</section>;
}

const beginnerMeanings:Record<string,string>={'excuse':'Excuse me 连起来表示“请问／劳驾”','me':'我（放在动作后面）','yes':'是的；表示肯定','is':'是（与 this、it 等搭配）','this':'这；这个','your':'你的；你们的','handbag':'手提包','pardon':'Pardon? 表示“请再说一遍”','it':'它；这件东西','thank you':'谢谢','very much':'非常'};
const shortMeaning=(word:string,meaning:string,first:boolean)=>first&&beginnerMeanings[word]||meaning.replace(/\[[^\]]+\].*$/,'').replace(/\b(?:pron|adv|adj|vt|vi|n|a|v)\.\s*/g,'').split(/[;；,，]/).slice(0,2).join('，').slice(0,45)||'结合原句和原书理解';
let sourcePages:Promise<PageIndex>|undefined;
function loadSources(){if(!sourcePages)sourcePages=readJsonResource<PageIndex>('/lesson-pages/index.json').then(p=>{if(p.version!==1||!p.lessons||p.sources.NCE1!==grammarSourceHash('NCE1')||p.sources.NCE2!==grammarSourceHash('NCE2'))throw Error('原书版本需要核对。');return p}).catch(e=>{sourcePages=undefined;throw e});return sourcePages;}
export function UnitTeaching({unit,state,save,step,next}:{unit:Unit;state:Progress;save:Save;step:number;next:()=>void}){
  const [language,setLanguage]=useState<LessonLanguage|null>(null),[pages,setPages]=useState<PageIndex|null>(null),[dictionary,setDictionary]=useState<Record<string,DictionaryEntry>>({});
  const [error,setError]=useState(''),[resourceError,setResourceError]=useState(''),[retry,setRetry]=useState(0),[resource,setResource]=useState<'words'|'source'|null>(null);
  const [showText,setShowText]=useState(false),[guideIndex,setGuideIndex]=useState(0),[guided,setGuided]=useState(false),[focusShown,setFocusShown]=useState(false);
  useEffect(()=>{let alive=true;setError('');loadLessonLanguage(unit.book,unit.lesson).then(l=>{if(!alive)return;if(!l||l.sourceSha256!==unit.sourceSha256)throw Error('课文版本不一致，请重新加载。');setLanguage(l)}).catch(e=>{if(alive)setError(e.message||'课文暂时无法读取。')});return()=>{alive=false}},[unit.id,retry]);
  useEffect(()=>{if(!resource)return;let alive=true;setResourceError('');Promise.all([loadSources(),resource==='words'?loadDictionary():Promise.resolve({})]).then(([p,d])=>{if(alive){setPages(p);if(resource==='words')setDictionary(d)}}).catch(e=>{if(alive)setResourceError(e.message||'资料暂时无法读取。')});return()=>{alive=false}},[resource,unit.id,retry]);
  useEffect(()=>{setResource(null)},[step]);
  const source=pages?.lessons[`${unit.book}-${unit.lesson}`],body=language?splitLesson(language.rows,unit.book,true).body:[],guides=guidesFor(unit),guide=guides[guideIndex];
  const focus=unit.book==='NCE1'?firstChapterFocus[unit.lesson]:undefined;
  if(resource)return <section className="focus-resource" aria-label="本课参考资料"><button className="text-button" onClick={()=>setResource(null)}>← 回到当前步骤</button><h2>{resource==='words'?'本课词语':'原书与以前的笔记'}</h2><p className="muted">{sourceLabel(unit)}</p>{resourceError?<p role="alert">{resourceError}<button onClick={()=>setRetry(retry+1)}>重新加载</button></p>:!pages?<p role="status">正在读取原书资料…</p>:resource==='words'?<div className="source-vocabulary">{source?.vocabulary?.words.map(({word,forms})=>{const item=findWord(dictionary,word),row=body.find(r=>[word,...forms].some(w=>w.length>1&&r.en.toLowerCase().includes(w.toLowerCase())));return <details key={word}><summary><strong>{word}</strong><span>{shortMeaning(word,item?.meaning||'',unit.book==='NCE1'&&unit.lesson===1)}</span></summary><p>{item?.ipa} {item?.meaning}</p>{row&&<><p lang="en">{row.en}</p><p>{row.zh}</p><ClipButton clip={{book:unit.book,lesson:unit.lesson,start:row.time!,end:body[body.indexOf(row)+1]?.time??99999}} label="听词语所在原句"/></>}</details>})}</div>:<><p>按需核对原书。以前保存的笔记和练习仍在原处。</p><a className="text-button" href={courseUrl(nodeById(unit.id)!).replace('tab=grammar','tab=notes')}>查看以前的笔记与练习 →</a>{[unit.lesson,...unit.lastLesson!==unit.lesson?[unit.lastLesson]:[]].map(lesson=><details className="source-pages" key={lesson}><summary>第 {lesson} 课 · 原书页</summary>{pages.lessons[`${unit.book}-${lesson}`]?.pages.map(page=><a key={page.page} href={page.src} target="_blank" rel="noreferrer"><img loading="lazy" src={page.src} alt={`原书第 ${lesson} 课 · PDF 第 ${page.page} 页`}/><small>PDF 第 {page.page} 页 · 点图放大</small></a>)}</details>)}</>}</section>;
  return <><section className="focus-task" aria-label={['听懂课文','理解句子','自己的表达'][step]}>
    {step===0?<><span className="mini-label">先抓住大意</span><h2>听听这段对话在说什么</h2><p>先听一遍，试着用中文说出发生了什么。听不清可以重听。</p><div className="focus-listen"><ClipButton clip={{book:unit.book,lesson:unit.lesson,start:unit.rows[0].start,end:99999}} label="听完整课文"/></div><a className="text-button speaking-entry" href={`#/learn/${unit.id}?speaking=practice`}>跟读一句，练清楚发音 →</a>{error?<p role="alert">{error}<button className="text-button" onClick={()=>setRetry(retry+1)}>重新加载课文</button></p>:!language?<p role="status">正在读取逐句课文…</p>:<><button className="text-button" onClick={()=>setShowText(!showText)}>{showText?'收起课文':'需要帮助？逐句听与看中文'}</button>{showText&&<div className="transcript">{body.map((row,i)=><div key={i}><ClipButton label={`听第 ${i+1} 句`} clip={{book:unit.book,lesson:unit.lesson,start:row.time!,end:body[i+1]?.time??99999}}/><p lang="en">{row.en}</p><p>{row.zh}</p></div>)}</div>}</>}</>:step===1?<><span className="mini-label">看懂，再跟着说</span>{focus?<div className="beginner-focus"><h2>先用好这一句</h2><p>{focus.idea}</p><div className="bilingual-example"><strong lang="en">{focus.en}</strong><p>{focus.zh}</p></div><h3>{focus.prompt}</h3><button className="secondary" onClick={()=>setFocusShown(!focusShown)}>{focusShown?'收起示范':'我试过了，看示范'}</button>{focusShown&&<p role="status">{focus.answer}</p>}</div>:<h2>理解本课的句子</h2>}<details className="grammar-depth" open={focus?undefined:true}><summary>{focus?'展开完整语法讲解':'本课用法与跟练'}</summary>{guides.length>1&&<label className="form-field">选择本课用法<select value={guideIndex} onChange={e=>{setGuideIndex(Number(e.target.value));setGuided(false)}}>{guides.map((g,i)=><option key={g.id} value={i}>{g.title}</option>)}</select></label>}<h3>{guide.title}</h3><p>{guide.idea}</p><div className="pattern">{guide.pattern}</div>{guide.explain.map(t=><p key={t}>{t}</p>)}{guide.examples.map(example=><div className="bilingual-example" key={example.en}><strong lang="en">{example.en}</strong><p>{example.zh}</p><small>{example.note}</small></div>)}<p className="teaching-note">容易混淆：{guide.pitfall}</p><div className="practice-block"><h3>{guide.practice.prompt}</h3><p>先自己试，再看示范。</p><button className="secondary" onClick={()=>setGuided(!guided)}>{guided?'收起示范答案':'我试过了，看示范答案'}</button>{guided&&<p role="status">{guide.practice.answer}<br/>{guide.practice.explanation}</p>}</div></details></>:<GuidedExpression unit={unit} state={state} save={save} next={next}/>}
  </section>{step<2&&<div className="focus-next"><button className="primary" onClick={next}>{['听过了，看看怎么说','试过了，换成自己的话','收起资料，开始检验'][step]}<ArrowRight size={17}/></button></div>}<div className="focus-tools" aria-label="按需查看本课资料"><button onClick={()=>setResource('words')}>查本课词语</button><span>·</span><button onClick={()=>setResource('source')}>原书与旧笔记</button></div></>;
}

export function QuestionAnswer({q,index,round,value,disabled,set,heard}:{q:MapQuestion;index:number;round:number;value:string;disabled:boolean;set:(s:string)=>void;heard:()=>void}){
  const words=q.options||[],used=value?value.split(' '):[];
  const available=words.map((word,i)=>({word,i}));
  for(const word of used){const found=available.find(x=>x.word===word);if(found)available.splice(available.indexOf(found),1);}
  const ordered=words.map((word,i)=>({word,i})).sort((a,b)=>((a.i*17+round*7)%23)-((b.i*17+round*7)%23)).reverse();
  return <>{q.clip&&<ClipButton clip={q.clip} done={heard} label="听题目原声"/>}{q.type==='choice'?<div className="answer-choices" role="group" aria-label={`第 ${index+1} 题选项`}>{q.options?.map(option=><button type="button" key={option} disabled={disabled} aria-pressed={value===option} className={value===option?'picked':''} onClick={()=>set(option)}>{option}</button>)}</div>:q.mode==='order'?<><output className="sentence-answer" aria-label={`第 ${index+1} 题已组成句子`}>{value||'按顺序点词，组成句子'}</output><div className="word-tiles">{ordered.map(({word,i})=><button type="button" key={i} disabled={disabled||!available.some(x=>x.i===i)} onClick={()=>set(value?`${value} ${word}`:word)}>{word}</button>)}</div><button type="button" className="text-button" disabled={disabled||!value} onClick={()=>set(used.slice(0,-1).join(' '))}>撤回一个词</button><button type="button" className="text-button" disabled={disabled||!value} onClick={()=>set('')}>重新组句</button></>:<input id={`answer-${index}`} aria-label={q.prompt} autoComplete="off" spellCheck={false} required maxLength={1000} readOnly={disabled} value={value} placeholder="输入你的答案" onChange={e=>set(e.target.value)}/>}</>;
}

export function CourseRoom({node,state,save,select}:{node:MapNode;state:Progress;save:Save;select:(id:string)=>void}){
  const progress=chapterProgress(node,state),statuses=statusMap(state),record=state.records[node.id]||emptyRecord();
  const members=(node.members||[]).map(id=>nodeById(id)!);
  const next=members.find(n=>due(n,state))||members.find(n=>statuses[n.id]==='available')||members.find(n=>!stable(n,state));
  const base:Project={text:'',recording:'',reviewer:'',feedback:'',criteria:[false,false,false,false],at:Date.now(),...record.project,...record.draft} as Project;
  const [errors,setErrors]=useState<string[]>([]),[saved,setSaved]=useState(false),[section,setSection]=useState(progress.learned===progress.total&&!achieved(node,state)?'project':'lessons');
  const change=(key:string,value:string|boolean[])=>{setSaved(false);save(s=>updateDraft(s,node.id,{[key]:value},base))};
  return <><nav className="chapter-tabs" aria-label="章节内容"><button aria-current={section==='lessons'?'page':undefined} onClick={()=>setSection('lessons')}>课次目录</button><button aria-current={section==='project'?'page':undefined} onClick={()=>setSection('project')}>章节作品与评阅</button></nav>{section==='lessons'?<><div className="chapter-summary"><strong>{progress.learned} / {progress.total} 初次通过</strong><span>{progress.stable} / {progress.total} 隔日巩固</span></div><p>一组一次学不完，可以拆成“听懂”和“自己用”两次。每组首次独立通过，就能学本章下一组；至少隔 24 小时换题通过，才记为巩固。全章巩固并完成作品评阅后解锁下一章。</p>{next&&<button className="primary full" onClick={()=>select(next.id)}>{due(next,state)?'先复习':statuses[next.id]==='available'?'继续学习':'查看复习安排'}：{lessonPlan(unitById(next.id)!).goal}<ArrowRight size={16}/></button>}<div className="unit-list">{members.map(n=>{const u=unitById(n.id)!,s=statuses[n.id],ready=stable(n,state),time=nextReviewAt(n,state);return <button key={n.id} onClick={()=>select(n.id)} className={s} aria-label={`${sourceLabel(u)} ${n.title}，${`${manuallyUnlocked(n,state)?'手动解锁，':''}${learningLabel(n,state)}${s==='locked'?'，待解锁':''}`}`}><span className="unit-icon">{s==='locked'?<Lock size={17}/>:ready?<Check size={17}/>:<BookOpen size={17}/>}</span><span><small>{sourceLabel(u)}</small><strong>{lessonPlan(u).goal}</strong><small lang="en">{n.title}</small><small className={manuallyUnlocked(n,state)?"manual-note":""}>{manuallyUnlocked(n,state)?'手动解锁 · ':''}{learningLabel(n,state)}</small><small>{s==='locked'?'前一组初次通过后解锁':ready?due(n,state)?'到了巩固时间':'已隔日独立通过':s==='passed'?due(n,state)?'现在可以换题复习':`复习从 ${new Date(time!).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} 开始`:'听懂 → 讲解 → 自己用 → 独立检验'}</small></span><ArrowRight size={16}/></button>})}</div>
    </>:<section className="chapter-project"><span className="mini-label">把本章变成自己的表达</span><h2>章节作品与评阅</h2><p>{node.project}</p><p className="muted">练习时可以看笔记；正式留下作品时收起课文。请能判断本章表达的老师或伙伴听读，指出具体问题，修订后再确认。系统检查记录完整性，不能代替真实评阅。</p><form onSubmit={e=>{e.preventDefault();const project={...base,at:Date.now()},issues=projectErrors(node,project);save(s=>({...s,records:{...s.records,[node.id]:{...(s.records[node.id]||emptyRecord()),project,draft:undefined}}}));setErrors(issues);setSaved(!issues.length)}}><label className="form-field">自己的英文原稿<textarea required rows={7} maxLength={10000} value={base.text} onChange={e=>change('text',e.target.value)} placeholder="写自己的内容，保留修订后的稿件。"/></label><Recorder id={node.id} onSaved={name=>change('recording',name)}/><label className="form-field">录音文件名或保存位置<input required maxLength={1000} value={base.recording} onChange={e=>change('recording',e.target.value)} placeholder="可用本站录音，也可填写另存录音的位置。"/></label><label className="form-field">评阅者<input required maxLength={200} value={base.reviewer} onChange={e=>change('reviewer',e.target.value)} placeholder="听读过作品的老师或伙伴"/></label><label className="form-field">具体反馈与修订<textarea required rows={4} maxLength={10000} value={base.feedback} onChange={e=>change('feedback',e.target.value)} placeholder="原来的问题是什么，评阅者怎样建议，现在如何修改？"/></label><fieldset className="criteria"><legend>由评阅反馈确认</legend>{['表达覆盖本章任务，内容是自己的','意思清楚，主要句型能独立使用','录音可理解，能回应对方的简单追问','具体问题已修订并重新表达'].map((text,i)=><label key={text}><input type="checkbox" checked={base.criteria[i]} onChange={e=>{const criteria=[...base.criteria];criteria[i]=e.target.checked;change('criteria',criteria)}}/>{text}</label>)}</fieldset>{errors.length>0&&<div className="form-errors" role="alert"><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}{saved&&<p role="status">作品记录已保存。{progress.stable===progress.total?'本章已达本站通关条件。':'还需完成本章所有单元的隔日巩固。'}</p>}<button className="primary full">保存作品，检查章节通关条件<Check size={17}/></button></form></section>}
    {section==='lessons'&&node.chapter!>=6&&<details className="source-pages"><summary>按薄弱项补充新概念三册</summary><p>三册用于补强长句、篇章和复述，不按册数换算雅思分数。四册是拓展阅读，不是本路线的必修门槛。</p><a className="text-button" href={`${courseUrl(node).split('#')[0]}#/nce/NCE3/1?tab=grammar`} >三册：长句与篇章讲解 →</a></details>}
  </>;
}
