import React, {useEffect, useState} from 'react';
import {ArrowRight, Check, Lock, RotateCcw, BookOpen, Lightbulb} from 'lucide-react';
import {nodeById, courseUrl, type MapNode} from './content';
import {unitById, guidesFor, firstChapterFocus, sourceLabel, starters, type Unit, type MapQuestion} from './curriculum';
import {learningLabel, manuallyUnlocked, emptyRecord, updateDraft, chapterProgress, statusMap, stable, due, nextReviewAt, projectErrors, type Project, type Progress} from './model';
import {ClipButton, Recorder} from './media';
import {loadLessonLanguage, loadDictionary, findWord, type LessonLanguage, type DictionaryEntry} from '../app/language';
import {readJsonResource} from '../app/network';
import {splitLesson} from '../app/lesson-structure';
import {grammarEntryFor, grammarSourceHash} from '../app/textbook-grammar';
import type {PageIndex} from '../app/lesson-context';
import type {Save} from './learning';

export function StarterTeaching({node}:{node:MapNode}){
  const starter=starters.find(s=>s.id===node.id)!;
  const [choice,setChoice]=useState('');
  return <><div className="teaching-note"><Lightbulb size={21}/><p>{starter.tip}</p></div><div className="starter-cards">{starter.lines.map(row=><article key={row.en}><p lang="en">{row.en}</p><p>{row.zh}</p>{'clip' in row&&<ClipButton clip={row.clip}/>}</article>)}</div><div className="practice-block"><span className="mini-label">跟着练 · 可以看上面的示范</span><h3>{starter.question}</h3><div className="choices">{starter.options.map(o=><button key={o} className={choice===o?'picked':''} onClick={()=>setChoice(o)}>{o}</button>)}</div>{choice&&<p role="status">{choice===starter.answer?'选对了。现在读一遍，再盖住示范自己试。':'回到上面的声音和解释，再选一次。'}</p>}</div></>;
}

const beginnerMeanings:Record<string,string>={'excuse':'Excuse me 连起来表示“请问／劳驾”','me':'我（放在动作后面）','yes':'是的；表示肯定','is':'是（与 this、it 等搭配）','this':'这；这个','your':'你的；你们的','handbag':'手提包','pardon':'Pardon? 表示“请再说一遍”','it':'它；这件东西','thank you':'谢谢','very much':'非常'};
const shortMeaning=(word:string,meaning:string,first:boolean)=>first&&beginnerMeanings[word]||meaning.replace(/\[[^\]]+\].*$/,'').replace(/\b(?:pron|adv|adj|vt|vi|n|a|v)\.\s*/g,'').split(/[;；,，]/).slice(0,2).join('，').slice(0,45)||'结合原句和原书理解';
let sourcePages:Promise<PageIndex>|undefined;
function loadSources(){if(!sourcePages)sourcePages=readJsonResource<PageIndex>('/lesson-pages/index.json').then(p=>{if(p.version!==1||!p.lessons||p.sources.NCE1!==grammarSourceHash('NCE1')||p.sources.NCE2!==grammarSourceHash('NCE2'))throw Error('原书版本需要核对。');return p}).catch(e=>{sourcePages=undefined;throw e});return sourcePages;}
export function UnitTeaching({unit,state,save}:{unit:Unit;state:Progress;save:Save}){
  const [language,setLanguage]=useState<LessonLanguage|null>(null),[pages,setPages]=useState<PageIndex|null>(null),[dictionary,setDictionary]=useState<Record<string,DictionaryEntry>>({});
  const [error,setError]=useState(''),[retry,setRetry]=useState(0),[sourceOpen,setSourceOpen]=useState(false),[showText,setShowText]=useState(false),[guideIndex,setGuideIndex]=useState(0),[guided,setGuided]=useState(false),[focusShown,setFocusShown]=useState(false);
  useEffect(()=>{let alive=true;setError('');Promise.all([loadLessonLanguage(unit.book,unit.lesson),loadSources(),loadDictionary()]).then(([l,p,d])=>{if(!alive)return;if(!l||l.sourceSha256!==unit.sourceSha256)throw Error('课文版本不一致，请重新加载。');setLanguage(l);setPages(p);setDictionary(d)}).catch(e=>{if(alive)setError(e.message||'教材暂时无法读取。')});return()=>{alive=false}},[unit.id,retry]);
  const source=pages?.lessons[`${unit.book}-${unit.lesson}`],body=language?splitLesson(language.rows,unit.book,true).body:[],guides=guidesFor(unit),guide=guides[guideIndex];
  const focus=unit.book==='NCE1'?firstChapterFocus[unit.lesson]:undefined;
  const record=state.records[unit.id]||emptyRecord();
  const note=String(record.draft?.note||'');
  return <><div className="source-tag"><BookOpen size={15}/>{sourceLabel(unit)}<span>{grammarEntryFor(unit.book,unit.lesson)?.title}</span></div>
    <section className="lesson-step"><span className="mini-label">01 先听懂 · 声音与意思</span><p>先听一遍，试着说出发生了什么，中文也可以。再展开对照，逐句听、模仿，最后盖住文字。</p><ClipButton clip={{book:unit.book,lesson:unit.lesson,start:unit.rows[0].start,end:99999}} label="听完整课文"/>{error?<p role="alert">{error}<button className="text-button" onClick={()=>setRetry(retry+1)}>重新加载教材</button></p>:!language?<p role="status">正在读取逐句课文、原书词表与释义…</p>:<><button className="text-button" onClick={()=>setShowText(!showText)}>{showText?'盖住课文和中文':'展开逐句中英对照'}</button>{showText&&<div className="transcript">{body.map((row,i)=><div key={i}><ClipButton label={`听第 ${i+1} 句`} clip={{book:unit.book,lesson:unit.lesson,start:row.time!,end:body[i+1]?.time??99999}}/><p lang="en">{row.en}</p><p>{row.zh}</p></div>)}</div>}</>}
    </section>
    <section className="lesson-step"><span className="mini-label">02 看懂本课词语</span><p>先看常见义，再结合原句里的中文理解；完整释义可以展开。</p><div className="source-vocabulary">{source?.vocabulary?.words.map(({word,forms})=>{const item=findWord(dictionary,word),row=body.find(r=>[word,...forms].some(w=>w.length>1&&r.en.toLowerCase().includes(w.toLowerCase())));return <details key={word}><summary><strong>{word}</strong><span>{shortMeaning(word,item?.meaning||'',unit.book==='NCE1'&&unit.lesson===1)}</span></summary><p>{item?.ipa} {item?.meaning}</p>{row&&<><p lang="en">{row.en}</p><p>{row.zh}</p><ClipButton clip={{book:unit.book,lesson:unit.lesson,start:row.time!,end:body[body.indexOf(row)+1]?.time??99999}} label="听词语所在原句"/></>}</details>})}</div></section>
    <section className="lesson-step"><span className="mini-label">03 理解句子 · 跟着用</span>{focus&&<div className="beginner-focus"><h2>先用好这一句</h2><p>{focus.idea}</p><div className="bilingual-example"><strong lang="en">{focus.en}</strong><p>{focus.zh}</p></div><h3>{focus.prompt}</h3><p>先自己说，再看示范。</p><button className="secondary" onClick={()=>setFocusShown(!focusShown)}>{focusShown?'收起示范':'我试过了，看示范'}</button>{focusShown&&<p role="status">{focus.answer}</p>}</div>}<details className="grammar-depth" open={focus?undefined:true}><summary>{focus?'准备好后，看完整语法讲解':'本课语法讲解与跟练'}</summary>{guides.length>1&&<label className="form-field">本课用法<select value={guideIndex} onChange={e=>{setGuideIndex(Number(e.target.value));setGuided(false)}}>{guides.map((g,i)=><option key={g.id} value={i}>{g.title}</option>)}</select></label>}<h2>{guide.title}</h2><p>{guide.idea}</p><div className="pattern">{guide.pattern}</div>{guide.explain.map(t=><p key={t}>{t}</p>)}{guide.examples.map(example=><div className="bilingual-example" key={example.en}><strong lang="en">{example.en}</strong><p>{example.zh}</p><small>{example.note}</small></div>)}<p className="teaching-note">容易混淆：{guide.pitfall}</p><div className="practice-block"><h3>{guide.practice.prompt}</h3><p>先自己说出或写出，再看示范；这是跟练，后面还有独立检验。</p><button className="secondary" onClick={()=>setGuided(!guided)}>{guided?'收起示范答案':'我试过了，看示范'}</button>{guided&&<p role="status">{guide.practice.answer}<br/>{guide.practice.explanation}</p>}</div></details></section>
    <section className="lesson-step"><span className="mini-label">04 换成自己的内容</span><p>{unit.book==='NCE1'&&unit.lesson<25?'把课文里的人名或物品换成你身边的，自己说一个小问答。可以先口头说，再试写 2–3 句。':'不看课文，用本课句型说自己的经历或情况，再写 3–5 句。二册还需口头概括课文中的人物、事件、原因与结果。'}</p><label className="form-field">我的表达 / 需要解决的问题<textarea rows={4} maxLength={10000} value={note} onChange={e=>save(s=>({...s,records:{...s.records,[unit.id]:{...(s.records[unit.id]||emptyRecord()),draft:{...s.records[unit.id]?.draft,note:e.target.value}}}}))} placeholder="这里保留自己的尝试；不会的词先用中文记下来。"/></label><Recorder id={unit.id}/><p className="footnote">这份草稿用于积累作品，不由关键词匹配判断表达正确。章节末由老师或伙伴听读、反馈，再修订。</p></section>
    <details className="source-pages" open={sourceOpen} onToggle={e=>setSourceOpen(e.currentTarget.open)}><summary>{sourceLabel(unit)} · 原书与配套练习</summary><p>先按本页讲解学习；在原书中完成对应书面练习，答案在教材练习中按需查看。{unit.book==='NCE1'?'奇数课的原声与偶数课的句型、书面练习配对学习；偶数课没有被当作独立录音。':''}</p>{sourceOpen&&[unit.lesson,...unit.lastLesson!==unit.lesson?[unit.lastLesson]:[]].map(lesson=><div key={lesson}><h3>第 {lesson} 课</h3>{pages?.lessons[`${unit.book}-${lesson}`]?.pages.map(page=><a key={page.page} href={page.src} target="_blank" rel="noreferrer"><img loading="lazy" src={page.src} alt={`原书第 ${lesson} 课 · PDF 第 ${page.page} 页`}/><small>PDF 第 {page.page} 页 · 点图放大</small></a>)}</div>)}<a className="text-button" href={courseUrl(nodeById(unit.id)!)}>继续本课教材讲解与练习 →</a></details>
  </>;
}

export function QuestionAnswer({q,index,round,value,disabled,set,heard}:{q:MapQuestion;index:number;round:number;value:string;disabled:boolean;set:(s:string)=>void;heard:()=>void}){
  const words=q.options||[],used=value?value.split(' '):[];
  const available=words.map((word,i)=>({word,i}));
  for(const word of used){const found=available.find(x=>x.word===word);if(found)available.splice(available.indexOf(found),1);}
  const ordered=words.map((word,i)=>({word,i})).sort((a,b)=>((a.i*17+round*7)%23)-((b.i*17+round*7)%23)).reverse();
  return <>{q.clip&&<ClipButton clip={q.clip} done={heard} label="听题目原声"/>}{q.type==='choice'?<div className="answer-choices" role="group" aria-label={`第 ${index+1} 题选项`}>{q.options?.map(option=><button type="button" key={option} disabled={disabled} aria-pressed={value===option} className={value===option?'picked':''} onClick={()=>set(option)}>{option}</button>)}</div>:q.mode==='order'?<><output className="sentence-answer" aria-label={`第 ${index+1} 题已组成句子`}>{value||'按顺序点词，组成句子'}</output><div className="word-tiles">{ordered.map(({word,i})=><button type="button" key={i} disabled={disabled||!available.some(x=>x.i===i)} onClick={()=>set(value?`${value} ${word}`:word)}>{word}</button>)}</div><button type="button" className="text-button" disabled={disabled||!value} onClick={()=>set(used.slice(0,-1).join(' '))}>撤回一个词</button><button type="button" className="text-button" disabled={disabled||!value} onClick={()=>set('')}>重新组句</button></>:<input id={`answer-${index}`} autoComplete="off" spellCheck={false} required maxLength={1000} readOnly={disabled} value={value} placeholder="输入你的答案" onChange={e=>set(e.target.value)}/>}</>;
}

export function CourseRoom({node,state,save,select}:{node:MapNode;state:Progress;save:Save;select:(id:string)=>void}){
  const progress=chapterProgress(node,state),statuses=statusMap(state),record=state.records[node.id]||emptyRecord();
  const members=(node.members||[]).map(id=>nodeById(id)!);
  const next=members.find(n=>due(n,state))||members.find(n=>statuses[n.id]==='available')||members.find(n=>!stable(n,state));
  const base:Project={text:'',recording:'',reviewer:'',feedback:'',criteria:[false,false,false,false],at:Date.now(),...record.project,...record.draft} as Project;
  const [errors,setErrors]=useState<string[]>([]),[saved,setSaved]=useState(false);
  const change=(key:string,value:string|boolean[])=>{setSaved(false);save(s=>updateDraft(s,node.id,{[key]:value},base))};
  return <><div className="chapter-summary"><strong>{progress.learned} / {progress.total} 初次通过</strong><span>{progress.stable} / {progress.total} 隔日巩固</span></div><p>一组一次学不完，可以拆成“听懂”和“自己用”两次。每组首次独立通过，就能学本章下一组；至少隔 24 小时换题通过，才记为巩固。全章巩固并完成作品评阅后解锁下一章。</p>{next&&<button className="primary full" onClick={()=>select(next.id)}>{due(next,state)?'先复习':statuses[next.id]==='available'?'继续学习':'查看复习安排'}：{next.title}<ArrowRight size={16}/></button>}<div className="unit-list">{members.map(n=>{const u=unitById(n.id)!,s=statuses[n.id],ready=stable(n,state),time=nextReviewAt(n,state);return <button key={n.id} onClick={()=>select(n.id)} className={s} aria-label={`${sourceLabel(u)} ${n.title}，${`${manuallyUnlocked(n,state)?'手动解锁，':''}${learningLabel(n,state)}${s==='locked'?'，待解锁':''}`}`}><span className="unit-icon">{s==='locked'?<Lock size={17}/>:ready?<Check size={17}/>:<BookOpen size={17}/>}</span><span><small>{sourceLabel(u)}</small><strong>{n.title}</strong><small className={manuallyUnlocked(n,state)?"manual-note":""}>{manuallyUnlocked(n,state)?'手动解锁 · ':''}{learningLabel(n,state)}</small><small>{s==='locked'?'前一组初次通过后解锁':ready?due(n,state)?'到了巩固时间':'已隔日独立通过':s==='passed'?due(n,state)?'现在可以换题复习':`复习从 ${new Date(time!).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} 开始`:'听懂 → 讲解 → 自己用 → 独立检验'}</small></span><ArrowRight size={16}/></button>})}</div>
    <section className="chapter-project"><span className="mini-label">把本章变成自己的表达</span><h2>章节作品与评阅</h2><p>{node.project}</p><p className="muted">练习时可以看笔记；正式留下作品时收起课文。请能判断本章表达的老师或伙伴听读，指出具体问题，修订后再确认。系统检查记录完整性，不能代替真实评阅。</p><form onSubmit={e=>{e.preventDefault();const project={...base,at:Date.now()},issues=projectErrors(node,project);save(s=>({...s,records:{...s.records,[node.id]:{...(s.records[node.id]||emptyRecord()),project,draft:undefined}}}));setErrors(issues);setSaved(!issues.length)}}><label className="form-field">自己的英文原稿<textarea required rows={7} maxLength={10000} value={base.text} onChange={e=>change('text',e.target.value)} placeholder="写自己的内容，保留修订后的稿件。"/></label><Recorder id={node.id} onSaved={name=>change('recording',name)}/><label className="form-field">录音文件名或保存位置<input required maxLength={1000} value={base.recording} onChange={e=>change('recording',e.target.value)} placeholder="可用本站录音，也可填写另存录音的位置。"/></label><label className="form-field">评阅者<input required maxLength={200} value={base.reviewer} onChange={e=>change('reviewer',e.target.value)} placeholder="听读过作品的老师或伙伴"/></label><label className="form-field">具体反馈与修订<textarea required rows={4} maxLength={10000} value={base.feedback} onChange={e=>change('feedback',e.target.value)} placeholder="原来的问题是什么，评阅者怎样建议，现在如何修改？"/></label><fieldset className="criteria"><legend>由评阅反馈确认</legend>{['表达覆盖本章任务，内容是自己的','意思清楚，主要句型能独立使用','录音可理解，能回应对方的简单追问','具体问题已修订并重新表达'].map((text,i)=><label key={text}><input type="checkbox" checked={base.criteria[i]} onChange={e=>{const criteria=[...base.criteria];criteria[i]=e.target.checked;change('criteria',criteria)}}/>{text}</label>)}</fieldset>{errors.length>0&&<div className="form-errors" role="alert"><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}{saved&&<p role="status">作品记录已保存。{progress.stable===progress.total?'本章已达本站通关条件。':'还需完成本章所有单元的隔日巩固。'}</p>}<button className="primary full">保存作品，检查章节通关条件<Check size={17}/></button></form></section>
    {node.chapter!>=6&&<details className="source-pages"><summary>按薄弱项补充新概念三册</summary><p>三册用于补强长句、篇章和复述，不按册数换算雅思分数。四册是拓展阅读，不是本路线的必修门槛。</p><a className="text-button" href={`${courseUrl(node).split('#')[0]}#/nce/NCE3/1?tab=grammar`} >三册：长句与篇章讲解 →</a></details>}
  </>;
}
