import type {Dimension} from './manifest';
export type PlacementQuestion={id:string;pool:'a'|'b';dimension:Dimension;context:string;prompt:string;options?:string[];accepted:readonly string[];hint:string;explanation:string;repair:string;repairHref:string};
/** Original finite items. These are withheld from teaching until submitted/skipped. */
export const placementQuestions:readonly PlacementQuestion[]=[
 {id:'a-1',pool:'a',dimension:'basic',context:'Rina says, “This is my bag. Your bag is on the chair.”',prompt:'谁的包在椅子上？',options:['Rina 的','听 Rina 说话的人的','两个人的'],accepted:['听 Rina 说话的人的'],hint:'留意 my 和 your 指向的人。',explanation:'your 指向听话的人；Rina 的包是 my bag。',repair:'先练 my / your 和物品归属，再换一句核对。',repairHref:'/#/nce/NCE1/1?tab=grammar'},
 {id:'a-2',pool:'a',dimension:'basic',context:'情境：Kai 现在在家。他的几位朋友现在在车站。',prompt:'用 be 动词的现在时，只填一个词：His friends ___ at the station.',accepted:['are'],hint:'先判断主语是一人还是多人。',explanation:'friends 是复数，这句用 are。',repair:'补 is / are 与单复数对应。',repairHref:'/#/nce/NCE1/25?tab=grammar'},
 {id:'a-3',pool:'a',dimension:'narrative',context:'情境：Sora 昨天步行去市场。请保留昨天发生的时间意义。',prompt:'只填一个词：Yesterday, Sora ___ to the market.（walk 的适当形式）',accepted:['walked'],hint:'Yesterday 指已过去的时间。',explanation:'这件事发生在昨天，walk 的过去式是 walked。',repair:'用明确过去时间练一般过去式，再独立换题。',repairHref:'/#/nce/NCE2/1?tab=grammar'},
 {id:'a-4',pool:'a',dimension:'narrative',context:'Leo carried an umbrella because heavy rain was expected. It did not rain in the end.',prompt:'Leo 带伞的原因是什么？',options:['已经淋湿了','预计会有大雨','最后真的下雨了'],accepted:['预计会有大雨'],hint:'because 后面说明带伞时的原因。',explanation:'was expected 表示预计；结尾说明最后没下雨。',repair:'区分原因、预期和实际结果，用 because 连接。',repairHref:'/#/nce/NCE2/1?tab=grammar'},
 {id:'a-5',pool:'a',dimension:'reading',context:'The museum opens at 9 a.m. every day except Tuesday. On Tuesday it opens at noon. Its café opens at 10 a.m. every day.',prompt:'判断：On Tuesday, the café opens before the museum.',options:['True（有证据支持）','False（与原文矛盾）','Not given（原文未给）'],accepted:['True（有证据支持）'],hint:'分别比较 Tuesday 的两个开门时间。',explanation:'周二 café 10 点开，museum 12 点开，因此 café 更早。',repair:'先圈时间与例外，再判断支持或矛盾。',repairHref:'/#/ielts?tab=course&task=sample-academic-reading'},
 {id:'a-6',pool:'a',dimension:'reading',context:'Twenty volunteers planted trees by the river on Saturday. Each volunteer received a bottle of water. The report does not describe any other supplies.',prompt:'判断：Every volunteer received a free lunch.',options:['True（有证据支持）','False（与原文矛盾）','Not given（原文未给）'],accepted:['Not given（原文未给）'],hint:'没有提到，不代表一定没有发生。',explanation:'只明确给了水，没有午餐信息，不能推出有或没有午餐。',repair:'练“未给信息”与“明确矛盾”的区别。',repairHref:'/#/ielts?tab=course&task=sample-academic-reading'},
 {id:'b-1',pool:'b',dimension:'basic',context:'Milo says, “My cup is blue. Your cup is green.”',prompt:'听 Milo 说话的人的杯子是什么颜色？',options:['蓝色','绿色','没有给出'],accepted:['绿色'],hint:'your 指向听话的人。',explanation:'Your cup is green 指听话者的杯子是绿色。',repair:'先练 my / your 和物品归属，再换一句核对。',repairHref:'/#/nce/NCE1/1?tab=grammar'},
 {id:'b-2',pool:'b',dimension:'basic',context:'情境：Nia 和妹妹现在在厨房。她们的父亲现在在屋外。',prompt:'用 be 动词的现在时，只填一个词：Their father ___ outside.',accepted:['is'],hint:'先判断 father 是一人还是多人。',explanation:'father 是单数，这句用 is。',repair:'补 is / are 与单复数对应。',repairHref:'/#/nce/NCE1/25?tab=grammar'},
 {id:'b-3',pool:'b',dimension:'narrative',context:'情境：Jo 昨晚清理了书桌。请保留昨晚发生的时间意义。',prompt:'只填一个词：Last night, Jo ___ her desk.（clean 的适当形式）',accepted:['cleaned'],hint:'Last night 指已过去的时间。',explanation:'昨晚已经发生的动作，clean 用过去式 cleaned。',repair:'用明确过去时间练一般过去式，再独立换题。',repairHref:'/#/nce/NCE2/1?tab=grammar'},
 {id:'b-4',pool:'b',dimension:'narrative',context:'Ada left early because she expected heavy traffic. The roads were quiet, so she arrived before everyone else.',prompt:'Ada 提前出门的原因是什么？',options:['预计堵车','路上已经很空','其他人已到了'],accepted:['预计堵车'],hint:'区分出门时的理由和之后的结果。',explanation:'because she expected heavy traffic 是原因；roads were quiet 是实际结果。',repair:'区分原因、预期和实际结果，用 because 连接。',repairHref:'/#/nce/NCE2/1?tab=grammar'},
 {id:'b-5',pool:'b',dimension:'reading',context:'On weekdays, the library closes at 7 p.m. On Saturday it closes at 4 p.m. The study room closes at 6 p.m. every day.',prompt:'判断：On Saturday, the library closes after the study room.',options:['True（有证据支持）','False（与原文矛盾）','Not given（原文未给）'],accepted:['False（与原文矛盾）'],hint:'只比较 Saturday 的两个关门时间。',explanation:'周六 library 16 点关，study room 18 点关，library 更早，原判断与原文矛盾。',repair:'先圈时间与例外，再判断支持或矛盾。',repairHref:'/#/ielts?tab=course&task=sample-academic-reading'},
 {id:'b-6',pool:'b',dimension:'reading',context:'Six students visited a farm on Friday. They travelled there by train. The report gives no details about their journey home.',prompt:'判断：The students returned home by bus.',options:['True（有证据支持）','False（与原文矛盾）','Not given（原文未给）'],accepted:['Not given（原文未给）'],hint:'去程和回程是两件事。',explanation:'只说明去时坐火车，回程交通方式未给，不能凭去程判断回程。',repair:'练“未给信息”与“明确矛盾”的区别。',repairHref:'/#/ielts?tab=course&task=sample-academic-reading'},
];
export const questionById=(id:string)=>placementQuestions.find(q=>q.id===id);
