import type {Bank,MiniItem,MiniTask} from '../content';
const banks:Bank[]=['guided','independent','repair','delayed-a','delayed-b'];
const make=(base:Omit<MiniTask,'items'|'calibration'|'level'>,rows:Omit<MiniItem,'id'|'bank'>[]):MiniTask=>({...base,level:'NCE1 第25–36课部分已教微目标；难度未校准',calibration:'uncalibrated',items:rows.map((row,i)=>({...row,id:`${base.id}:${banks[i]}`,bank:banks[i]}))});
// Different original communicative materials; closed factual selections and open production stay distinct.
export const batch03Tasks:readonly MiniTask[]=[
 make({id:'mini-n1-25',courseId:'nce1-25',groupId:'NCE1-25',lessons:[25,26],skill:'listening',track:'common',title:'听物品位置，为取物确认选一条',teaching:'先确认要找的是哪一件，再听它的位置。There is首次介绍单件；the/it继续指同一件。in=内部，on=表面，under=下方，near=附近；lamp=灯，camera=相机，cupboard=橱柜。物品所在容器的位置不等于物品直接在该表面上。这里是受控位置语义选择，答A/B/C，只核对材料支持的事实，不评完整雅思听力或真实取物成功。本机合成声未人工试听；播放仅记接触，文字稿记帮助。'},[
  {material:'There is a lamp in the room. The lamp is under the table. There is a cup on the table.',prompt:'你要找lamp。听完选一条位置确认，只写A/B/C：A on the table；B under the table；C in the cup。',hint:'先跟住lamp的第二句，别把cup的位置当成灯的位置。',reference:'B — under the table',accepted:['B'],audio:new URL('./audio/mini-n1-25-guided.wav',import.meta.url).href},
  {material:'There is a box under the desk. There is a camera in the box. The lamp is on the desk.',prompt:'相机应从哪里找？按材料选直接位置，只写A/B/C：A on the desk；B in the box；C on the lamp。',hint:'camera在box内部；box在desk下面，是容器的位置，不是相机直接在桌面上。',reference:'B — in the box',accepted:['B'],audio:new URL('./audio/mini-n1-25-independent.wav',import.meta.url).href},
  {material:'There is a cupboard near the door. There is a knife in the cupboard. The clean cup is on the table.',prompt:'要取knife，应确认哪个直接位置？只写A/B/C：A on the table；B near the cup；C in the cupboard。',hint:'与前题一样先找单件所在的容器；near the door说的是cupboard，不是桌上的cup。',reference:'C — in the cupboard',accepted:['C'],audio:new URL('./audio/mini-n1-25-repair.wav',import.meta.url).href},
  {material:'Jo: Is the bottle on the table? Rae: No. It is in the cupboard. The cup is on the table.',prompt:'已明确it指bottle。核对留言中的瓶子位置，只写A/B/C：A in the cupboard；B on the table；C under the table。',hint:'No拒绝了提问中的位置；it继续指瓶子，不是后来的杯子。',reference:'A — in the cupboard',accepted:['A'],audio:new URL('./audio/mini-n1-25-delayed-a.wav',import.meta.url).href},
  {material:'There is a large box on the shelf. There is a clean cup in the box. The dirty cup is under the table.',prompt:'你需要clean cup。按材料选它的直接位置，不选容器所在位置，只写A/B/C：A under the table；B on the shelf；C in the box。',hint:'选clean那只杯子的直接容器；shelf是box的位置，table下是另一只杯子。',reference:'C — in the box',accepted:['C'],audio:new URL('./audio/mini-n1-25-delayed-b.wav',import.meta.url).href},
 ]),
 make({id:'mini-n1-27',courseId:'nce1-27',groupId:'NCE1-27',lessons:[27,28],skill:'reading',track:'common',title:'读领物便签，把需求和一组物品对上',teaching:'这些是原创领物便签。There are some介绍若干件；The…are或They are继续指已明确的一组。每个they紧接的物品组由上一句明说。先看要取的类别/用途，再把组和位置对应到领物条，不照抄邻组。some不说明精确数量。maps=地图，tools=工具，plates=盘子，bottles=瓶子，shelf=架子，cupboard=橱柜，wall=墙，window=窗。这里是受控独立语义选择，不评主动构句或完整雅思阅读。'},[
  {material:'餐具便签\nThere are some plates on the table. They are clean.\nThere are some cups in the cupboard. They are dirty.',prompt:'要取干净的餐具，应选哪条领物信息？只写A/B/C：A dirty cups in the cupboard；B clean plates on the table；C clean cups on the table。',hint:'第二句They指plates；不要把clean移到后面的cups组。',reference:'B — clean plates on the table',accepted:['B']},
  {material:'工具间便签\nThere are some maps on the wall.\nThere are some boxes near the door. The tools are in the boxes. They are clean.',prompt:'伙伴需要tools，不是外面的boxes或墙上的maps。哪条确认与便签一致？只写A/B/C：A tools on the wall；B tools near the window；C tools in the boxes。',hint:'最后They明确接上一句tools；容器boxes在门边，工具在这些boxes内部。',reference:'C — tools in the boxes',accepted:['C']},
  {material:'展览准备便签\nThere are some bottles on the shelf.\nThere are some boxes near the window. The maps are in the boxes. They are old.',prompt:'伙伴需要maps，不是bottles或外面的boxes。哪条确认与便签一致？只写A/B/C：A maps in the boxes；B maps on the shelf；C maps on the window。',hint:'与前题一样找实际类别所在的容器；最后They是maps，别把别组的shelf移过来。',reference:'A — maps in the boxes',accepted:['A']},
  {material:'数量未点清的库存便签\nThere are some cups in the cupboard. They are clean.\nThere are some bottles on the table.',prompt:'不能猜未写的数量。哪条库存说明被便签直接支持？只写A/B/C：A exactly two clean cups in the cupboard（恰好两个）；B some clean cups in the cupboard（若干）；C some clean bottles in the cupboard。',hint:'some只说明若干；没有精确两只的证据。clean与cupboard属于cups组。',reference:'B — some clean cups in the cupboard',accepted:['B']},
  {material:'等候区便签\nThere are some chairs near the window.\nThe boxes are under the table. The tickets are in the boxes. They are green.',prompt:'为了领green tickets，哪条位置确认正确？只写A/B/C：A tickets near the window；B tickets on the table；C tickets in the boxes。',hint:'最后They是tickets；chairs属于窗边另一组，under the table说明外部boxes的位置。',reference:'C — tickets in the boxes',accepted:['C']},
 ]),
 make({id:'mini-n1-29',courseId:'nce1-29',groupId:'NCE1-29',lessons:[29,30],skill:'speaking',track:'common',title:'口头交接任务，保留规则、对象与顺序',teaching:'有明确任务规则才转述must，不替别人猜义务。must后动词原形；直接指令用动作词起句，then=然后，保留实际先后。open/shut=打开/关闭；take off=脱下；put…in=放进；sweep the floor=扫地；clean the table=清理桌子；read this letter=读这封信。面对接手人说明需做什么，或按任务表区分两位执行者；自然表达待人工核对，不按模板给口语分。录音仅本页本机回放，无上传；声音不持久保存，刷新需重选。文字备选不记独立口语。'},[
  {material:'你把一个装书任务交给面前的伙伴。明确规则是先打开空盒子，再把书放进这个盒子。没有其他规定。',prompt:'口头说2句，先说明伙伴必须做的第一步，再给出第二步指令。让对方听清对象和先后，可以礼貌表达。',hint:'You must open the box. Then put the books in the box, please.',reference:'You must open the box. Then put the books in the box, please.',accepted:[]},
  {material:'你在入口向接手整理工作的伙伴说明规则：他/她先脱下自己的外套，再把同一件外套放进橱柜。橱柜不是装地图的盒子；不用关窗。',prompt:'口头说2句交接：第一句说明必须先做的动作；第二句指明同一件物品的下一步与正确位置。不要增加无关任务。',hint:'对面前伙伴用You must；第二步可用it明确指coat，保留then和in the cupboard。',reference:'You must take off your coat. Then put it in the cupboard, please.',accepted:[]},
  {material:'你在收件台向接手整理工作的伙伴说明规则：他/她先读这封信（letter），再把同一封信放进盒子。信不放进橱柜；不用清理桌子。',prompt:'换一个情境口头说2句交接：说明必须先做的动作，再指明同一件物品的下一步与正确容器，不增加无关任务。',hint:'与前题一样跟踪第一步处理的同一件物品：it明确指letter；保留then和in the box。',reference:'You must read this letter. Then put it in the box, please.',accepted:[]},
  {material:'你向清理房间的接手人交接已确认规则：先关窗，再扫地。盒子可以保持原样，任务没有要求打开它。',prompt:'口头说2句，让接手人听清必须先完成什么，再给下一步指令。不要把没规定的盒子任务加进去。',hint:'You must shut/close the window. Then sweep the floor, please. 不替规则增加第三个动作。',reference:'You must shut the window. Then sweep the floor, please.',accepted:[]},
  {material:'任务表：Ava负责打开窗；Ben负责清理桌子。你向协调员报告分工，然后当面对Ben给出他自己的指令。题设没有规定两人的先后，也没有性别信息。',prompt:'口头说3句：先明确每人的必须任务，再向Ben给出直接指令。别交换分工或编造先后。',hint:'Ava must…和Ben must…区分姓名；最后向Ben说Clean the table, please，不推断he/she。',reference:'Ava must open the window. Ben must clean the table. Clean the table, please.',accepted:[]},
 ]),
];
