import type {Bank,MiniItem,MiniTask} from '../content';
const banks:Bank[]=['guided','independent','repair','delayed-a','delayed-b'];
const make=(base:Omit<MiniTask,'items'|'calibration'|'level'>,rows:Omit<MiniItem,'id'|'bank'>[]):MiniTask=>({...base,level:'NCE1 第25–36课部分已教微目标；难度未校准',calibration:'uncalibrated',items:rows.map((row,i)=>({...row,id:`${base.id}:${banks[i]}`,bank:banks[i]}))});
// Different original communicative materials; closed factual selections and open production stay distinct.
export const batch03Tasks:readonly MiniTask[]=[
 make({id:'mini-n1-25',courseId:'nce1-25',groupId:'NCE1-25',lessons:[25,26],skill:'listening',track:'common',title:'听物品位置，为取物确认选一条',teaching:'先确认要找的是哪一件，再听它的位置。There is首次介绍单件；the/it继续指同一件。in=内部，on=表面，under=下方，near=附近；lamp=灯，camera=相机，cupboard=橱柜。物品所在容器的位置不等于物品直接在该表面上。这里是受控位置语义选择，答A/B/C，只核对材料支持的事实，不评完整雅思听力或真实取物成功。本机合成声未人工试听；播放仅记接触，文字稿记帮助。'},[
  {material:'There is a lamp in the room. The lamp is under the table. There is a cup on the table.',prompt:'你要找lamp。听完选一条位置确认，只写A/B/C：A on the table；B under the table；C in the cup。',hint:'先跟住lamp的第二句，别把cup的位置当成灯的位置。',reference:'B — under the table',accepted:['B'],audio:new URL('./audio/mini-n1-25-guided.wav',import.meta.url).href},
  {material:'There is a box under the desk. There is a camera in the box. The lamp is on the desk.',prompt:'相机应从哪里找？按材料选直接位置，只写A/B/C：A on the desk；B in the box；C on the lamp。',hint:'camera在box内部；box在desk下面，是容器的位置，不是相机直接在桌面上。',reference:'B — in the box',accepted:['B'],audio:new URL('./audio/mini-n1-25-independent.wav',import.meta.url).href},
  {material:'There is a cupboard near the door. There is a knife in the cupboard. The clean cup is on the table.',prompt:'要取knife，应确认哪个直接位置？只写A/B/C：A on the table；B near the cup；C in the cupboard。',hint:'与前题一样先找单件所在的容器；near the door说的是cupboard，不是桌上的cup。',reference:'C — in the cupboard',accepted:['C'],audio:new URL('./audio/mini-n1-25-repair.wav',import.meta.url).href},
  {material:'Jo: Is the bottle on the table? Rae: No. It is in the cupboard. The cup is on the table.',prompt:'已明确it指bottle。核对留言中的瓶子位置，只写A/B/C：A in the cupboard；B on the table；C under the table。',hint:'No拒绝了提问中的位置；it继续指瓶子，不是后来的杯子。',reference:'A — in the cupboard',accepted:['A'],audio:new URL('./audio/mini-n1-25-delayed-a.wav',import.meta.url).href},
  {material:'There is a large box on the shelf. There is a clean cup in the box. The dirty cup is under the table.',prompt:'你需要clean cup。按材料选它的直接位置，不选容器所在位置，只写A/B/C：A under the table；B on the shelf；C in the box。',hint:'选clean那只杯子的直接容器；shelf是box的位置，table下是另一只杯子。',reference:'C — in the box',accepted:['C'],audio:new URL('./audio/mini-n1-25-delayed-b.wav',import.meta.url).href},
 ]),
 make({id:'mini-n1-27',courseId:'nce1-27',groupId:'NCE1-27',lessons:[27,28],skill:'reading',track:'common',title:'读领物便签，把需求和一组物品对上',teaching:'这些是原创领物便签。There are some介绍若干件；The…are或They are继续指已明确的一组。每个they紧接的物品组由上一句明说。先看要取的类别/用途，再把组和位置对应到领物条，不照抄邻组。some不说明精确数量。maps=地图，tools=工具，plates=盘子，bottles=瓶子，shelf=架子，cupboard=橱柜，wall=墙，window=窗。这里是受控独立语义选择，不评主动构句或完整雅思阅读。'},[
  {material:'餐具便签\nThere are some plates on the table. They are clean.\nThere are some cups in the cupboard. They are dirty.',prompt:'要取干净的餐具，应选哪条领物信息？只写A/B/C：A dirty cups in the cupboard；B clean plates on the table；C clean cups on the table。',hint:'第二句They指plates；不要把clean移到后面的cups组。',reference:'B — clean plates on the table',accepted:['B']},
  {material:'工具间便签\nThere are some maps on the wall.\nThere are some boxes near the door. The tools are in the boxes. They are clean.',prompt:'伙伴需要tools，不是外面的boxes或墙上的maps。哪条确认与便签一致？只写A/B/C：A tools on the wall；B tools near the window；C tools in the boxes。',hint:'最后They明确接上一句tools；容器boxes在门边，工具在这些boxes内部。',reference:'C — tools in the boxes',accepted:['C']},
  {material:'展览准备便签\nThere are some bottles on the shelf.\nThere are some boxes near the window. The maps are in the boxes. They are old.',prompt:'伙伴需要maps，不是bottles或外面的boxes。哪条确认与便签一致？只写A/B/C：A maps in the boxes；B maps on the shelf；C maps on the window。',hint:'与前题一样找实际类别所在的容器；最后They是maps，别把别组的shelf移过来。',reference:'A — maps in the boxes',accepted:['A']},
  {material:'数量未点清的库存便签\nThere are some cups in the cupboard. They are clean.\nThere are some bottles on the table.',prompt:'不能猜未写的数量。哪条库存说明被便签直接支持？只写A/B/C：A exactly two clean cups in the cupboard（恰好两个）；B some clean cups in the cupboard（若干）；C some clean bottles in the cupboard。',hint:'some只说明若干；没有精确两只的证据。clean与cupboard属于cups组。',reference:'B — some clean cups in the cupboard',accepted:['B']},
  {material:'等候区便签\nThere are some chairs near the window.\nThe boxes are under the table. The tickets are in the boxes. They are green.',prompt:'为了领green tickets，哪条位置确认正确？只写A/B/C：A tickets near the window；B tickets on the table；C tickets in the boxes。',hint:'最后They是tickets；chairs属于窗边另一组，under the table说明外部boxes的位置。',reference:'C — tickets in the boxes',accepted:['C']},
 ]),
 make({id:'mini-n1-29',courseId:'nce1-29',groupId:'NCE1-29',lessons:[29,30],skill:'speaking',track:'common',title:'口头交接任务，保留规则、对象与顺序',teaching:'有明确任务规则才转述must，不替别人猜义务。must后动词原形；直接指令用动作词起句，then=然后，保留实际先后。open/shut=打开/关闭；take off=脱下；put…in=放进；sweep the floor=扫地；clean the table=清理桌子；read this letter=读这封信。面对接手人说明需做什么，或按任务表区分两位执行者；自然表达待人工核对，不按模板给口语分。录音仅本页本机回放，无上传；声音不持久保存，刷新需重选。文字备选不记独立口语。'},[
  {material:'你把一个装书任务交给面前的伙伴。明确规则是先打开空盒子，再把书放进这个盒子。没有其他规定。',prompt:'口头说2句，先说明伙伴必须做的第一步，再给出第二步指令。让对方听清对象和先后，可以礼貌表达。',hint:'You must open the box. Then put the books in the box, please.',reference:'You must open the box. Then put the books in the box, please.',accepted:[]},
  {material:'你在入口向接手整理工作的伙伴说明规则：他/她先脱下自己的外套，再把同一件外套放进橱柜。橱柜不是装地图的盒子；不用关窗。',prompt:'口头说2句交接：第一句说明必须先做的动作；第二句指明同一件物品的下一步与正确位置。不要增加无关任务。',hint:'对面前伙伴用You must；第二步可用it明确指coat，保留then和in the cupboard。',reference:'You must take off your coat. Then put it in the cupboard, please.',accepted:[]},
  {material:'你在收件台向接手整理工作的伙伴说明规则：他/她先读这封信（letter），再把同一封信放进盒子。信不放进橱柜；不用清理桌子。',prompt:'换一个情境口头说2句交接：说明必须先做的动作，再指明同一件物品的下一步与正确容器，不增加无关任务。',hint:'与前题一样跟踪第一步处理的同一件物品：it明确指letter；保留then和in the box。',reference:'You must read this letter. Then put it in the box, please.',accepted:[]},
  {material:'你向清理房间的接手人交接已确认规则：先关窗，再扫地。盒子可以保持原样，任务没有要求打开它。',prompt:'口头说2句，让接手人听清必须先完成什么，再给下一步指令。不要把没规定的盒子任务加进去。',hint:'You must shut/close the window. Then sweep the floor, please. 不替规则增加第三个动作。',reference:'You must shut the window. Then sweep the floor, please.',accepted:[]},
  {material:'任务表：Ava负责打开窗；Ben负责清理桌子。你向协调员报告分工，然后当面对Ben给出他自己的指令。题设没有规定两人的先后，也没有性别信息。',prompt:'口头说3句：先明确每人的必须任务，再向Ben给出直接指令。别交换分工或编造先后。',hint:'Ava must…和Ben must…区分姓名；最后向Ben说Clean the table, please，不推断he/she。',reference:'Ava must open the window. Ben must clean the table. Clean the table, please.',accepted:[]},
 ]),
 make({id:'mini-n1-31',courseId:'nce1-31',groupId:'NCE1-31',lessons:[31,32],skill:'writing',track:'general-training',title:'写现场短讯，区分当前观察与旧便签',teaching:'这是日常联络短讯的GT起步任务，不是完整Task1，不做Academic图表，也不给Band。只报告给定的当前观察，旧便签不当作现在事实；未看到的动作可用What is he/she doing?询问，不猜测。单个人He/She或单只动物It配is+动作-ing，保留动作的物品和路线：washing a cup洗杯子；cutting paper剪纸；jumping over a box越过盒子；running across the grass横穿草地；drinking water喝水；swimming across the river横游河流。自然等义短讯留待人工核对，不自动评内容或写作质量。'},[
  {material:'给不在场伙伴的当前观察便签：Ben明确用he，现在 cutting paper（剪纸）；cat明确用it，现在 sleeping（睡觉）。伙伴只需要知道这两者现在的活动，没有原因或过去信息。',prompt:'写2句英文短讯，把两条当前观察传给伙伴。让他分清谁在做什么；不编造原因。',hint:'He is cutting paper. The cat is sleeping. 可用明确名称或题设代词；自然表达待人工。',reference:'He is cutting paper. The cat is sleeping.',accepted:[]},
  {material:'当前观察／Current note\nJo (she): washing a cup.\nDog (it): jumping over a box.\n旧便签／Old note: Dog — sleeping.\n只需向不在场伙伴传达当前两条观察。',prompt:'写2句英文联络短讯，以当前观察更新旧便签。保留两位主体、动作物品和动物路线，不把sleeping当现在事实。',hint:'当前she在洗杯子，it在越过盒子；报告当前，不复述旧便签。',reference:'She is washing a cup. The dog is jumping over a box.',accepted:[]},
  {material:'当前观察／Current note\nSam (he): opening a box.\nCat (it): running across the grass.\n旧便签／Old note: Cat — sleeping.\n只需向不在场伙伴传达当前两条观察。',prompt:'换新观察写2句英文短讯，以当前信息更新旧便签。保留动作物品和动物路线，不复述旧状态。',hint:'与前题一样区分当前和旧便签，保留两位主体；across不是along，猫现在没有sleeping。',reference:'He is opening a box. The cat is running across the grass.',accepted:[]},
  {material:'伙伴刚问起Ben（明确he）。你没有看到Ben当前在做什么；你只看到一只cat（it）现在 drinking water。伙伴知道he指Ben，不需要你猜Ben的活动。',prompt:'写2句英文回复：先询问Ben现在做什么，再说明你确实看到的猫的动作。不要替未知动作编答案。',hint:'What is he doing? The cat is drinking water. 把未知问题和已知观察分开。',reference:'What is he doing? The cat is drinking water.',accepted:[]},
  {material:'当前观察便签：Nora（明确she）现在 swimming across the river；一只dog（it）现在 sleeping。旧便签写Nora在河边walking，但当前观察已不同。',prompt:'给伙伴写2句更新短讯，分别报告当前人物和动物活动。保留横穿河流的路线，不把旧的沿岸走路当当前事实。',hint:'She is swimming across the river. The dog is sleeping. 只报告新的当前观察。',reference:'She is swimming across the river. The dog is sleeping.',accepted:[]},
 ]),
 make({id:'mini-n1-33',courseId:'nce1-33',groupId:'NCE1-33',lessons:[33,34],skill:'listening',track:'common',title:'听多人活动口播，补联络表的一条事实',teaching:'多人当前活动用are+动作-ing。先按问题找到指定组或指定活动，再提取联络表需要的事实；别混入相邻组。两人搬一个box仍可用are，人数不决定物品数量；按口播保留物品形式，不猜精确数量。students学生，nurses护士；carrying搬运，checking a map核对地图，drawing a picture画画，washing cups洗杯子，walking along a path沿小路走。只核对受控事实提取，不评完整听力或主动构句。本机合成声未人工试听；播放只记接触，文字稿记帮助。'},[
  {material:'The students are carrying a box. They are near the door. The nurses are checking a map.',prompt:'联络表登记students正在搬的物品：____。只写一个英文单数物品词，不填别组在核对的物品。',hint:'先找到students的carrying，再取a后的物品；map属于nurses。',reference:'box',accepted:['box'],audio:new URL('./audio/mini-n1-33-guided.wav',import.meta.url).href},
  {material:'The nurses are checking a map. The students are carrying a box. Mia and Leo are drawing a picture.',prompt:'要联络正在checking a map的那一组。联络表的复数身份词是____。只写一个英文词；不要填另一组或姓名。',hint:'把指定活动checking a map反向对应到它的主语组，而非取相邻活动的人。',reference:'nurses',accepted:['nurses'],audio:new URL('./audio/mini-n1-33-independent.wav',import.meta.url).href},
  {material:'The nurses are washing cups. The students are checking a map. Nora and Sam are carrying a box.',prompt:'新口播中要联络正在checking a map的那一组。复数身份词是____。只写一个英文词，不沿用上题组别。',hint:'同样按当前活动反向找主语；熟悉的nurses这次在wash cups，不是核对地图。',reference:'students',accepted:['students'],audio:new URL('./audio/mini-n1-33-repair.wav',import.meta.url).href},
  {material:'Mia and Leo are walking along a path. The students are running across the grass. The nurses are sitting near the door.',prompt:'路线记录：Mia和Leo正沿着哪个对象走？只写一个英文名词：____。不填其他组横穿的对象。',hint:'目标是并列姓名的一组；along a path不同于另一组across the grass。',reference:'path',accepted:['path'],audio:new URL('./audio/mini-n1-33-delayed-a.wav',import.meta.url).href},
  {material:'The nurses are carrying a box. The students are checking maps. Jo and Rae are washing cups.',prompt:'记录students正在核对的物品。只写一个英文名词，保留口播中的复数；不猜精确数量：____。',hint:'学生组checking maps；另一组a box不能证明学生也只有一个物品。',reference:'maps',accepted:['maps'],audio:new URL('./audio/mini-n1-33-delayed-b.wav',import.meta.url).href},
 ]),
 make({id:'mini-n1-35',courseId:'nce1-35',groupId:'NCE1-35',lessons:[35,36],skill:'reading',track:'common',title:'读来访留言，分清所在位置与移动方向',teaching:'原创来访留言给出足够位置和动向事实。is/are in说明所在内部；going into正在由外进入；coming out of正在由内向外，不能改成已到达或已完成。along沿着，across横穿；beside旁边，between在两个对象之间。hall大厅，gym体育馆，library图书馆，museum博物馆，cafe咖啡馆，station车站，river bank河岸，square广场。选A/B/C只核对受控阅读语义；不是实际导航成功、完整雅思地图题或主动表达达标。'},[
  {material:'来访说明\nThe library is beside the museum.\nThe visitors are going into the library.\nThe guides are in the museum.',prompt:'哪条理解有材料支持？只写A/B/C：A 图书馆在博物馆内部；B visitors正在进入图书馆；C guides正在走出博物馆。',hint:'beside不是in；going into是正在进入，guides的in只是位置。',reference:'B — visitors正在进入图书馆',accepted:['B']},
  {material:'碰面留言\nThe students are coming out of the hall.\nThe teachers are going into the hall.\nThe hall is beside the park.',prompt:'同伴要辨认students当前动向，哪条对应留言？只写A/B/C：A 正在进入hall；B 已在park内部；C 正在从hall内向外移动。不要把过程改为已到达。',hint:'按students找到coming out of；另一组teachers才是going into。',reference:'C — students正在从hall内向外移动',accepted:['C']},
  {material:'出口联络便签\nThe nurses are coming out of the gym.\nThe visitors are going into the gym.\nThe gym is beside the station.',prompt:'新便签里nurses当前动向是哪条？只写A/B/C：A 正在从gym内向外移动；B 正在进入gym；C 已到station内部。不要猜到达状态。',hint:'与前题一样跟指定组的当前移动；visitors的进入方向不能移给nurses。',reference:'A — nurses正在从gym内向外移动',accepted:['A']},
  {material:'沿河观察留言\nJo and Rae are walking along the river bank.\nThe dogs are swimming across the river.\nThe cafe is beside the station.',prompt:'哪条保留两组的路线事实？只写A/B/C：A 两人横穿河流，狗沿岸游；B 两人已在station内部；C 两人沿岸走，狗横游河流。',hint:'along river bank与across river不能交换；station只是另一条静态位置关系。',reference:'C — 两人沿岸走，狗横游河流',accepted:['C']},
  {material:'访客信息卡\nThe museum is between the library and the cafe.\nThe students are in the cafe.\nThe guide is walking across the square.',prompt:'哪条解释与卡上的明确事实相符？只写A/B/C：A museum在cafe内部；B museum在library与cafe之间；C guide正在沿square边缘走。',hint:'between给两个参照物；across是横穿，不是沿边缘，in the cafe的主体是students。',reference:'B — museum在library与cafe之间',accepted:['B']},
 ]),
];
