// Unchanged production workspace in a fresh isolated QA Chrome profile. Temporary
// test-only registration; this does not prove production integration or retention.
import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdir,mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {fileURLToPath} from 'node:url';import {createCourseLoopModel} from '../model.mjs';import {startPreview} from './preview-server.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),proof=join(root,'docs/parallel-nce1-085-095'),work=join(root,'work/parallel-nce1-085-095-browser');await mkdir(work,{recursive:true});const profile=await mkdtemp(join(work,'qa-')),checks=[],errors=[];let chrome,browser,tab,server;
const delay=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,label){for(let i=0;i<200;i++){try{if(await fn())return}catch{}await delay(30)}throw Error('Timeout '+label)}
async function connect(url){const ws=new WebSocket(url),pending=new Map();let id=0;await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.j(Error(JSON.stringify(m.error))):p.r(m.result)}};return {close:()=>ws.close(),send:(method,params={})=>new Promise((r,j)=>{const n=++id;const timer=setTimeout(()=>{pending.delete(n);j(Error('CDP timeout '+method))},15000);pending.set(n,{r:v=>{clearTimeout(timer);r(v)},j:e=>{clearTimeout(timer);j(e)}});ws.send(JSON.stringify({id:n,method,params}))})}}
async function evaluate(expression){const r=await tab.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result.value}
const expr=(selector,text)=>`[...document.querySelectorAll(${JSON.stringify(selector)})].find(e=>${text?`e.textContent.trim()===${JSON.stringify(text)}`:'true'})`;
async function click(selector,text){const x=expr(selector,text);await until(()=>evaluate(`(()=>{const e=${x};return !!e&&!e.disabled&&e.getClientRects().length>0})()`),text||selector);await evaluate(`(${x}).scrollIntoView({block:'center'})`);await delay(100);const pos=await evaluate(`(()=>{const r=(${x}).getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await tab.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...pos});await tab.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...pos})}
async function type(selector,value){await click(selector);await delay(70);await tab.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:4,commands:['selectAll']});await tab.send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:4});await tab.send('Input.insertText',{text:value});await until(()=>evaluate(`document.querySelector(${JSON.stringify(selector)})?.value===${JSON.stringify(value)}`),'native text')}
async function qa(){return evaluate(`new Promise((resolve,reject)=>{const q=indexedDB.open('english-studio-offline',1);q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result;if(!db.objectStoreNames.contains('state')){db.close();reject(Error('QA store not ready'));return}const r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>{resolve(r.result);db.close()};r.onerror=()=>reject(r.error)}})`)}
async function snapshot(id){const s=await qa(),c=await import('./lesson-nce1-'+id.slice(5).padStart(3,'0')+'.mjs'),model=createCourseLoopModel(c),raw=s?.drafts?.['nce-course-loop-v1:'+c.lesson.source.groupId];if(!raw)return null;const r=model.restore(raw);assert.ok(r.ok,r.message);return {s,c,model,view:r.view,raw}}
async function saved(id,fn){await until(()=>evaluate(`!!document.querySelector('.course-loop[data-course="${id}"]')&&!document.querySelector('.course-loop[data-phase="loading"]')`),'workspace mounted');await until(async()=>{const r=await snapshot(id);return r&&fn(r.view)},'confirmed '+id);await until(()=>evaluate(`document.querySelector('.course-loop-status')?.textContent==='本次课程记录已保存'`),'saved status')}
async function screenshot(name){const r=await tab.send('Page.captureScreenshot',{format:'png'});await writeFile(join(proof,name),Buffer.from(r.data,'base64'))}
try{
 const preview=await startPreview();server=preview.server;chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','ignore']});await until(async()=>{try{return !!await readFile(join(profile,'DevToolsActivePort'),'utf8')}catch{return false}},'isolated Chrome');const [port,path]=(await readFile(join(profile,'DevToolsActivePort'),'utf8')).trim().split('\n');browser=await connect('ws://127.0.0.1:'+port+path);const {targetId}=await browser.send('Target.createTarget',{url:'about:blank'});const entry=(await fetch('http://127.0.0.1:'+port+'/json/list').then(r=>r.json())).find(x=>x.id===targetId);tab=await connect(entry.webSocketDebuggerUrl);await tab.send('Runtime.enable');await tab.send('Page.enable');await tab.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
 const chosen=process.env.NCE_PREVIEW_IDS?process.env.NCE_PREVIEW_IDS.split(',').map(Number):preview.numbers;
 for(const n of chosen){const id='nce1-'+n;await tab.send('Page.navigate',{url:preview.origin+'/?course='+id});await saved(id,v=>v.phase==='diagnostic');console.log(id+' mounted');const c=(await snapshot(id)).c;
  await click('button','看原文');await until(()=>evaluate(`document.querySelectorAll('.course-loop-text article').length>0`),'real SourcePanel text');const txt=await evaluate(`document.querySelector('.course-loop-text').innerText`),language=JSON.parse(await readFile(join(root,'dist-online/language/NCE1/'+n+'.json')));assert.ok(txt.includes(language.rows[4].en));await saved(id,v=>v.hinted);await evaluate(`document.querySelector('.course-loop-sources').scrollIntoView({block:'start'})`);await screenshot('source-'+n+'.png');await click('button','收起教材');
  await click('button','看本课漫画');await until(()=>evaluate(`!![...document.images].find(i=>i.complete&&i.naturalWidth>0)`),'actual source comic');await evaluate(`document.querySelector('.course-loop-sources').scrollIntoView({block:'start'})`);await screenshot('comic-'+n+'.png');await click('button','收起教材');
  await click('button','听本课原声');await until(()=>evaluate(`[...document.querySelectorAll('.clip-button')].some(b=>b.textContent.trim()===${JSON.stringify(c.lesson.source.clips[0].label)})`),'actual clip labels');await click('.clip-button',c.lesson.source.clips[0].label);await until(()=>evaluate(`[...document.querySelectorAll('audio')].some(a=>a.readyState>=1&&a.currentTime>0&&a.src.startsWith('blob:'))`),'packaged original audio loaded and seeked');const audio=await evaluate(`[...document.querySelectorAll('audio')].filter(a=>a.src.startsWith('blob:')).map(a=>({currentTime:a.currentTime,duration:a.duration,readyState:a.readyState,paused:a.paused}))`);await click('button[aria-label="停止或取消原声"]');await click('button','收起教材');
  let wrongId,original;for(let i=0;i<3;i++){const {model,view}=await snapshot(id),q=model.currentQuestion(view);await type('.course-loop-card input',q.accepted[0]);await click('.course-loop-card button.primary');await saved(id,v=>v.attempts.some(a=>a.id===q.id));await click('.course-loop-card button.primary');}
  await saved(id,v=>v.phase==='learn');await screenshot('teaching-'+n+'.png');await click('.course-loop-card button.primary');
  while((await snapshot(id)).view.phase!=='own'){const {model,view}=await snapshot(id),q=model.currentQuestion(view);
   if(q){const wrong=view.phase==='independent'&&view.index===0,answer=wrong?q.counterexamples[0].answer:q.accepted.at(-1);if(wrong){wrongId=q.id;original=answer}await type('.course-loop-card input',answer);await click('.course-loop-card button.primary');await saved(id,v=>v.attempts.some(a=>a.id===q.id));await click('.course-loop-card button.primary');}
   else if(view.phase==='feedback'){if(wrongId){await type('.course-loop-card input',c.byId.get(wrongId).accepted[0]);await type('.course-loop-card textarea','核对人称、时间与事实，首答保留。');await click('button','保留这条订正');await saved(id,v=>!!v.corrections[wrongId]);await screenshot('correction-'+n+'.png')}await click('.course-loop-card button.primary');}
   else if(view.phase==='own')break;else assert.fail(view.phase)
  }
  await type('.course-loop-card textarea','这是隔离QA虚构表达，需伙伴核对。');await click('.course-loop-card button.primary');await saved(id,v=>v.phase==='waiting');let r=await snapshot(id);assert.equal(r.view.attempts.find(a=>a.id===wrongId).answer,original);assert.equal(r.model.receipt(r.view).openExpression,'awaiting-human-review');assert.equal(r.model.receipt(r.view).listening,'not-tested');assert.equal(r.view.dueAt-r.view.ownFinal.at,86400000);assert.equal(r.model.receipt(r.view).band,null);await evaluate('window.scrollTo(0,0)');await screenshot('waiting-'+n+'.png');await tab.send('Emulation.setDeviceMetricsOverride',{width:320,height:844,deviceScaleFactor:1,mobile:false});const mobile320=await evaluate(`({width:innerWidth,scroll:document.documentElement.scrollWidth})`);assert.ok(mobile320.scroll<=mobile320.width+1,JSON.stringify(mobile320));await screenshot('waiting-320-'+n+'.png');await tab.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
  const overflow=await evaluate(`({width:innerWidth,scroll:document.documentElement.scrollWidth})`);assert.ok(overflow.scroll<=overflow.width+1,JSON.stringify(overflow));await tab.send('Page.reload');await saved(id,v=>v.phase==='waiting');r=await snapshot(id);assert.equal(r.view.attempts.find(a=>a.id===wrongId).answer,original);checks.push({id,sourcePanel:'real JSON accepted by unchanged production guard',comic:'real packaged image rendered',factory:'unchanged production factory with exported matcher',registration:'test-only bundler override',mapProps:'QA map nce1-85; unchanged nextCourse lacks new successors and preserves current route; production wiring remains owner work',nativeQA:'diagnostic, learn, guided, independent wrong answer, original-preserving correction, repair, own, waiting, reload',viewport:overflow,viewport320:mobile320,retention:'natural 24h/7d not run',audioPlayback:audio,audibility:'not audited'});console.log(id+' production QA passed');
 }
 assert.equal(errors.length,0,JSON.stringify(errors));await writeFile(join(proof,'browser-evidence'+(process.env.NCE_PROOF_SUFFIX||'')+'.json'),JSON.stringify({baseline:'6b1faad2840bee06f9b824e72d5c551bb9acd273',checks,runtimeErrors:errors,profile:'fresh QA; no user profile/data; removed after test',productionRegistration:'not modified',naturalRetention:'not run'},null,2)+'\n');
}catch(error){await writeFile(join(proof,'browser-failure.json'),JSON.stringify({error:String(error),runtimeErrors:errors},null,2));if(tab)await screenshot('browser-failure.png').catch(()=>{});throw error}finally{tab?.close();browser?.close();chrome?.kill('SIGTERM');server?.close();await delay(500);await rm(profile,{recursive:true,force:true})}
