/** Actual built map/course entry with fresh synthetic Chrome profile and native input.
 * Only QA-origin records are read; no real user profile, recording or clock changes. */
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {mkdir,mkdtemp,readFile,readdir,writeFile,stat,rm} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {join,resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {getCourseBinding} from '../../course-loop/registry.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
const work=join(root,'work/course-video-browser');await mkdir(work,{recursive:true});
const proof=await mkdtemp(join(work,'native-')),profile=join(proof,'profile'),downloads=join(proof,'downloads');await mkdir(downloads);
const assetRoot=join(root,'dist-online'),checks=[],errors=[],requests=[],retries=[];let chrome,server,browser,tabs=[],origin,debugPort;
const sha=data=>createHash('sha256').update(data).digest('hex'),delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(predicate,label,limit=200){for(let i=0;i<limit;i++){try{if(await predicate())return}catch(error){if(!/Inspected target navigated|Execution context was destroyed|Cannot find context/.test(String(error)))throw error;retries.push({kind:'navigation context readiness',label,error:String(error)})}await delay(30)}throw Error('Timeout: '+label)}
async function connect(url){const ws=new WebSocket(url),pending=new Map();let sequence=0;await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});ws.onmessage=e=>{const m=JSON.parse(String(e.data));if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}};return {close:()=>ws.close(),send:(method,params={})=>new Promise((r,j)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);j(Error('CDP timeout '+method))},15000);pending.set(id,{resolve:r,reject:j,timer});ws.send(JSON.stringify({id,method,params}))})}}
async function evaluate(tab,expression){const r=await tab.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
async function newTab(url){const {targetId}=await browser.send('Target.createTarget',{url:'about:blank'});const list=await fetch(`http://127.0.0.1:${debugPort}/json/list`).then(r=>r.json()),entry=list.find(x=>x.id===targetId);const tab=await connect(entry.webSocketDebuggerUrl);tab.targetId=targetId;tabs.push(tab);await tab.send('Runtime.enable');await tab.send('Page.enable');await tab.send('DOM.enable');await tab.send('Emulation.setDeviceMetricsOverride',{width:1100,height:850,deviceScaleFactor:1,mobile:false});await navigate(tab,url);return tab}
async function navigate(tab,path){const url=path.startsWith('http')?path:origin+path,current=new URL(await evaluate(tab,'location.href')),target=new URL(url);if(current.href!==url){if(current.origin===target.origin&&current.pathname===target.pathname&&current.search===target.search)await evaluate(tab,`location.hash=${JSON.stringify(target.hash)}`);else await tab.send('Page.navigate',{url})}await until(()=>evaluate(tab,`document.readyState==='complete'&&!!document.querySelector('#root')`),'page ready')}
const selectorExpression=(selector,text)=>`[...document.querySelectorAll(${JSON.stringify(selector)})].find(e=>${text===undefined?'true':`e.textContent.trim()===${JSON.stringify(text)}`})`;
async function click(tab,selector,text){await browser.send('Target.activateTarget',{targetId:tab.targetId});const expression=selectorExpression(selector,text);await until(()=>evaluate(tab,`(()=>{const e=${expression};return !!e&&!e.disabled&&!!e.getClientRects().length})()`),'enabled control '+(text||selector));await evaluate(tab,`(${expression}).scrollIntoView({block:'center'})`);let point,previous,stable=0;for(let frame=0;frame<30;frame++){await delay(30);point=await evaluate(tab,`(()=>{const e=${expression},r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);stable=previous&&Math.abs(previous.x-point.x)<0.2&&Math.abs(previous.y-point.y)<0.2?stable+1:0;previous=point;if(stable>=2)break}await tab.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await tab.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point})}
async function type(tab,selector,value){for(let attempt=0;attempt<5;attempt++){await click(tab,selector);await delay(90);if(await evaluate(tab,`document.activeElement===document.querySelector(${JSON.stringify(selector)})`))break;retries.push({kind:'await native field focus after heading readiness',selector,attempt});if(attempt===4)throw Error('Native field focus did not settle')}await tab.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:process.platform==='darwin'?4:2,commands:['selectAll']});await tab.send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:process.platform==='darwin'?4:2});await tab.send('Input.insertText',{text:value});try{await until(()=>evaluate(tab,`document.querySelector(${JSON.stringify(selector)})?.value===${JSON.stringify(value)}`),'native input value')}catch(error){await writeFile(join(proof,'typing-failure.json'),JSON.stringify({selector,expected:value,actual:await evaluate(tab,`({value:document.querySelector(${JSON.stringify(selector)})?.value,active:document.activeElement?.outerHTML,hasFocus:document.hasFocus(),phase:document.querySelector('.course-loop')?.dataset.phase,course:document.querySelector('.course-loop')?.dataset.course,errors:[...document.querySelectorAll('[role=alert]')].map(e=>e.innerText)})`),state:await qaState(tab)},null,2));throw error}}
async function qaState(tab){return evaluate(tab,`new Promise((resolve,reject)=>{const q=indexedDB.open('english-studio-offline',1);q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result,r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>{resolve(r.result);db.close()};r.onerror=()=>{reject(r.error);db.close()}}})`)}
async function saved(tab,id,predicate){const key=getCourseBinding(id).key;await until(async()=>{const s=await qaState(tab);if(!s?.drafts?.[key])return false;const parsed=getCourseBinding(id).model.restore(s.drafts[key],Date.now());return parsed.ok&&predicate(parsed.view,s)},'confirmed selected save '+id)}
async function course(tab,id){await navigate(tab,`/map/#/learn/${id}?access=1`);await until(()=>evaluate(tab,`document.querySelector('.course-loop')?.dataset.course===${JSON.stringify(id)}&&!document.querySelector('.course-loop-error')&&!!document.querySelector('.course-loop-card')`),'course '+id)}
async function screenshot(tab,name){const shot=await tab.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(join(proof,name),Buffer.from(shot.data,'base64'))}
async function check(name,run){const started=Date.now();try{const detail=await run();checks.push({name,ok:true,elapsedMs:Date.now()-started,...(detail?{detail}:{})});console.log('PASS '+name)}catch(error){checks.push({name,ok:false,error:String(error),elapsedMs:Date.now()-started});throw error}}
async function backup(tab,label){await navigate(tab,'/#/progress');await until(()=>evaluate(tab,`!!document.querySelector('button[aria-label="进度备份与恢复"]')&&!document.querySelector('button[aria-label="进度备份与恢复"]').disabled`),'backup ready');const before=new Set(await readdir(downloads));await click(tab,'button[aria-label="进度备份与恢复"]');await click(tab,'[role="dialog"] button','保存进度到本地');let filename;await until(async()=>{filename=(await readdir(downloads)).find(n=>!before.has(n)&&n.endsWith('.json'));return !!filename},'native download');const bytes=await readFile(join(downloads,filename));const copy=join(proof,label+'.json');await writeFile(copy,bytes);await closeDialog(tab);return {file:copy,value:JSON.parse(bytes),sha256:sha(bytes)}}
async function closeDialog(tab){if(await evaluate(tab,`!!document.querySelector('[role="dialog"]')`)){await tab.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await tab.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await until(()=>evaluate(tab,`!document.querySelector('[role="dialog"]')`),'dialog close')}}
async function restore(tab,file){await navigate(tab,'/#/progress');await until(()=>evaluate(tab,`!!document.querySelector('button[aria-label="进度备份与恢复"]')&&!document.querySelector('button[aria-label="进度备份与恢复"]').disabled`),'restore ready');await click(tab,'button[aria-label="进度备份与恢复"]');await click(tab,'[role="dialog"] button','从文件恢复进度');const {root:doc}=await tab.send('DOM.getDocument',{depth:-1,pierce:true}),{nodeId}=await tab.send('DOM.querySelector',{nodeId:doc.nodeId,selector:'[role="dialog"] input[type="file"]'});assert.ok(nodeId);await tab.send('DOM.setFileInputFiles',{nodeId,files:[file]});await click(tab,'[role="dialog"] button','确认替换并恢复');await until(()=>evaluate(tab,`document.querySelector('[role="dialog"] .progress-save-receipt')?.textContent.includes('已恢复')&&[...document.querySelectorAll('[role="dialog"] button')].some(b=>b.textContent.trim()==='保存进度到本地'&&!b.disabled)`),'restore receipt');await closeDialog(tab)}
async function key(tab,key,code=key){const windowsVirtualKeyCode={Home:36,ArrowDown:40,ArrowUp:38,Enter:13,Escape:27}[key];await tab.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key,code,windowsVirtualKeyCode});await tab.send('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode})}
async function part(tab,index){const selector='.course-video-segments button:nth-child('+(index+1)+')';await click(tab,selector);await until(()=>evaluate(tab,`document.querySelector(${JSON.stringify(selector)})?.getAttribute('aria-pressed')==='true'`),'native selected part');await until(()=>evaluate(tab,`document.querySelector('.course-video-note textarea')&&!document.querySelector('.course-video-note textarea').disabled`),'note ready')}
async function toLearn(tab,id){await course(tab,id);if(await evaluate(tab,`document.querySelector('.course-loop')?.dataset.phase==='diagnostic'`))for(let i=0;i<3;i++){await click(tab,'.course-loop button','暂时不会，先记下');await click(tab,'.course-loop button',i===2?'看针对性讲解':'下一题')}await until(()=>evaluate(tab,`document.querySelector('.course-loop')?.dataset.phase==='learn'&&!!document.querySelector('.course-video-note textarea')&&!document.querySelector('.course-video-note textarea').disabled`),'learning help '+id)}
const nk=(course,p,lesson)=>`course-video-notes-v1:${course}:NCE1:${lesson}:BV1xa411J7jJ:${p}`;
async function prepareOriginal(tab){if(await evaluate(tab,`!!document.querySelector('.course-video [data-prepare-original]')`))await click(tab,'.course-video [data-prepare-original]');await until(()=>evaluate(tab,`!!document.querySelector('.course-video-note a[href*="/video/"]')`),'confirmed original link')}
async function noteSaved(tab,key,text){await until(async()=>{const s=await qaState(tab);return s?.drafts?.[key]&&JSON.parse(s.drafts[key]).text===text},'real persisted video note')}
try{
 server=createServer(async(req,res)=>{try{const path=decodeURIComponent(new URL(req.url,'http://localhost').pathname);let file;if(path==='/map/'||path==='/map/index.html')file=join(root,'map/dist/index.html');else if(path.startsWith('/map/assets/'))file=join(root,'map/dist',path.slice(5));else if(path==='/'||path==='/index.html'||path==='/standalone.html')file=join(root,'static-export/standalone.html');else if(path.startsWith('/assets/'))file=join(root,'static-export',path.slice(1));else if(/^\/(language|materials|illustrations|comics|lesson-pages)\//.test(path)||path==='/favicon.svg')file=join(assetRoot,path.slice(1));else{res.writeHead(404);res.end();return}const roots=[join(root,'map/dist'),join(root,'static-export'),assetRoot];assert.ok(roots.some(r=>resolve(file).startsWith(r+'/')));const s=await stat(file);requests.push({path,size:s.size});const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.bin':'application/octet-stream'}[extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':mime,'Content-Length':s.size,'Cache-Control':'no-store'});createReadStream(file).pipe(res)}catch(error){res.writeHead(404);res.end(String(error))}});await new Promise((r,j)=>{server.once('error',j);server.listen(0,'127.0.0.1',r)});origin=`http://127.0.0.1:${server.address().port}`;
 chrome=spawn(process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let chromeError;chrome.once('error',e=>chromeError=e);await until(async()=>{if(chromeError)throw chromeError;try{return !!(await readFile(join(profile,'DevToolsActivePort'),'utf8'))}catch{return false}},'isolated Chrome endpoint');const [port,path]=(await readFile(join(profile,'DevToolsActivePort'),'utf8')).trim().split('\n');debugPort=port;browser=await connect(`ws://127.0.0.1:${port}${path}`);await browser.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads,eventsEnabled:true});const tab=await newTab('/map/');

 await check('real normal course diagnostic hides video/notes and loads no third-party player',async()=>{await course(tab,'nce1-1');assert.equal(await evaluate(tab,`document.querySelectorAll('.course-video textarea,iframe[src*="player.bilibili.com"]').length`),0);await screenshot(tab,'diagnostic-hidden.png')});
 await check('native learn entry exposes exact multi-part links with no automatic iframe or summary',async()=>{await toLearn(tab,'nce1-1');assert.equal(await evaluate(tab,`document.querySelectorAll('.course-video-segments button').length`),3);await prepareOriginal(tab);assert.equal(await evaluate(tab,`document.querySelector('.course-video-note a[href*="/video/"]')?.href`),'https://www.bilibili.com/video/BV1xa411J7jJ/?p=3');assert.equal(await evaluate(tab,`document.querySelectorAll('iframe').length`),0);assert.equal(await evaluate(tab,`document.body.innerText.includes('视频内容要点')`),false)});
 const firstText='合成笔记 P3：记录自己的疑问，不是视频总结。';
 await check('actual production IDB writer saves personal text and refresh restores it',async()=>{await type(tab,'.course-video textarea',firstText);await noteSaved(tab,nk('nce1-1',3,1),firstText);await tab.send('Page.reload',{ignoreCache:true});await toLearn(tab,'nce1-1');assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),firstText);await screenshot(tab,'learn-notes-desktop.png')});
 await check('native part selection isolates P4 and P5 then restores P3',async()=>{await part(tab,1);assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),'');await type(tab,'.course-video textarea','合成 P4 独立笔记');await noteSaved(tab,nk('nce1-1',4,1),'合成 P4 独立笔记');await part(tab,2);assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),'');await prepareOriginal(tab);assert.equal(await evaluate(tab,`document.querySelector('.course-video-note a[href*="/video/"]')?.href`),'https://www.bilibili.com/video/BV1xa411J7jJ/?p=5');await part(tab,0);assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),firstText)});
 await check('click loads official non-autoplay iframe only after saved video assistance/provenance; fallback survives',async()=>{await tab.send('Network.enable');await tab.send('Network.setBlockedURLs',{urls:['*://player.bilibili.com/*']});await click(tab,'.course-video button','在本页播放');await until(()=>evaluate(tab,`!!document.querySelector('iframe[src*="player.bilibili.com"]')`),'click iframe');const src=await evaluate(tab,`document.querySelector('iframe').src`);assert.equal(new URL(src).searchParams.get('autoplay'),'0');const s=await qaState(tab),notes=JSON.parse(s.drafts[nk('nce1-1',3,1)]);assert.equal(notes.access.at(-1).kind,'load-player');assert.equal(notes.access.at(-1).sourceUrl,'https://www.bilibili.com/video/BV1xa411J7jJ/?p=3');const loop=getCourseBinding('nce1-1').model.restore(s.drafts[getCourseBinding('nce1-1').key]);assert(loop.ok);assert(loop.state.events.some(e=>e.type==='source'&&e.source==='video'));assert.equal(loop.view.attempts.length,3);assert.equal(s.attempts,0);assert.equal(s.correct,0);assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),firstText);assert(await evaluate(tab,`document.body.innerText.includes('未显示或不能播放时可打开原视频')`));await type(tab,'.course-video textarea',firstText+' 阻断播放仍可编辑');await noteSaved(tab,nk('nce1-1',3,1),firstText+' 阻断播放仍可编辑');await click(tab,'.course-video button','收起播放器');return {iframeSrc:src,network:'intentionally blocked public player URL; no playback claim'}});
 await check('course notes are isolated by actual course and later course restores independently',async()=>{await toLearn(tab,'nce1-3');assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),'');await prepareOriginal(tab);assert.equal(await evaluate(tab,`document.querySelector('.course-video-note a[href*="/video/"]')?.href`),'https://www.bilibili.com/video/BV1xa411J7jJ/?p=6');await type(tab,'.course-video textarea','合成第3课笔记');await noteSaved(tab,nk('nce1-3',6,3),'合成第3课笔记');await toLearn(tab,'nce1-1');assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),firstText+' 阻断播放仍可编辑')});
 await check('real two-tab CAS refuses stale same-video note and leaves losing text visible',async()=>{const other=await newTab('/map/#/learn/nce1-1?access=1');await toLearn(other,'nce1-1');await click(other,'.course-video textarea');await type(tab,'.course-video textarea','合成旧标签页输方文本仍保留');await browser.send('Target.activateTarget',{targetId:other.targetId});await other.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:process.platform==='darwin'?4:2,commands:['selectAll']});await other.send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:process.platform==='darwin'?4:2});await other.send('Input.insertText',{text:'合成新标签页胜方笔记'});await click(other,'.course-video button','保存笔记');await noteSaved(other,nk('nce1-1',3,1),'合成新标签页胜方笔记');await until(()=>evaluate(tab,`document.querySelector('.course-video [role="alert"]')?.innerText.includes('另一页面')`),'stale tab refused');assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),'合成旧标签页输方文本仍保留');assert.equal(JSON.parse((await qaState(tab)).drafts[nk('nce1-1',3,1)]).text,'合成新标签页胜方笔记');await screenshot(tab,'two-tab-conflict.png');await browser.send('Target.closeTarget',{targetId:other.targetId})});
 await check('failed note blocks host next until explicit backup/reload; original text is downloadable',async()=>{await click(tab,'.course-loop button','跟着换一句');assert.equal(await evaluate(tab,`document.querySelector('.course-loop').dataset.phase`),'learn');const before=new Set(await readdir(downloads));await click(tab,'.course-video button','下载未保存笔记');let name;await until(async()=>{name=(await readdir(downloads)).find(n=>!before.has(n)&&n.endsWith('.json'));return !!name},'unsaved note native download');const bytes=await readFile(join(downloads,name));assert.equal(JSON.parse(bytes).pending.text,'合成旧标签页输方文本仍保留');await writeFile(join(proof,'unsaved-note.json'),bytes);await click(tab,'.course-video button','已备份，读取最新笔记');await until(()=>evaluate(tab,`document.querySelector('.course-video textarea').value==='合成新标签页胜方笔记'&&!document.querySelector('.course-video [role="alert"]')`),'explicit newest reload')});
 const savedBackup=await backup(tab,'actual-progress-backup');
 await check('native full progress download includes exact note text, access and course source events',async()=>{assert.equal(JSON.parse(savedBackup.value.state.drafts[nk('nce1-1',3,1)]).text,'合成新标签页胜方笔记');assert.equal(JSON.parse(savedBackup.value.state.drafts[nk('nce1-3',6,3)]).text,'合成第3课笔记');assert(JSON.parse(savedBackup.value.state.drafts[nk('nce1-1',3,1)]).access.some(e=>e.kind==='load-player'));return {sha256:savedBackup.sha256,bytes:(await stat(savedBackup.file)).size}});
 await check('native unchanged actual backup restore retains notes/access and refreshed normal course',async()=>{await restore(tab,savedBackup.file);await toLearn(tab,'nce1-1');const s=await qaState(tab);for(const key of [nk('nce1-1',3,1),nk('nce1-1',4,1),nk('nce1-3',6,3)])assert.equal(s.drafts[key],savedBackup.value.state.drafts[key]);assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),'合成新标签页胜方笔记')});
 await check('native guided-to-independent transition flushes note and removes player/notes from assessment',async()=>{await click(tab,'.course-loop button','跟着换一句');const content=await import('../../course-loop/lesson-nce1-001.mjs');for(const [i,q] of content.questionsFor('guided').entries()){if(q.kind==='input')await type(tab,'.course-loop-card input',q.accepted[0]);else await click(tab,'.course-loop-choices button',q.accepted[0]);await click(tab,'.course-loop button','提交本题');if(i===2){await type(tab,'.course-video textarea','合成进入独立检验前的最后笔记');await click(tab,'.course-loop button','收起示范，自己试')}else await click(tab,'.course-loop button','下一题')};await until(()=>evaluate(tab,`document.querySelector('.course-loop').dataset.phase==='independent'`),'independent entry');assert.equal(await evaluate(tab,`document.querySelectorAll('.course-video textarea,.course-video iframe').length`),0);assert.equal(JSON.parse((await qaState(tab)).drafts[nk('nce1-1',3,1)]).text,'合成进入独立检验前的最后笔记');await screenshot(tab,'independent-hidden.png')});
 await restore(tab,savedBackup.file);await toLearn(tab,'nce1-1');
 await check('320/390 CSS viewports have readable note/link layout without horizontal page overflow',async()=>{const sizes=[];for(const width of [320,390]){await tab.send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:false});const size=await evaluate(tab,`({width:innerWidth,scroll:document.documentElement.scrollWidth,textarea:document.querySelector('.course-video textarea').getBoundingClientRect().width})`);assert(size.scroll<=width+1,JSON.stringify(size));sizes.push(size);await screenshot(tab,'viewport-'+width+'.png')}return {sizes,scope:'desktop CSS emulation; physical-phone playback unverified'}});
 assert.equal(errors.length,0,'main application Runtime exceptions');
}catch(error){console.error(error);process.exitCode=1;const tab=tabs.at(-1);if(tab){await screenshot(tab,'failure.png').catch(()=>{});await writeFile(join(proof,'failure-dom.txt'),await evaluate(tab,`document.body.innerText`).catch(()=>''))}}
finally{const sourceFiles=['course-video/ui.tsx','course-video/controller.ts','course-video/adapter.ts','course-video/manifest.ts','course-video/notes.ts','course-video/sources.json','app/course-loop-ui.tsx','course-loop/model.mjs','course-loop/host-contract.d.ts','app/offline-store.ts'];const hashes=Object.fromEntries(await Promise.all(sourceFiles.map(async p=>[p,sha(await readFile(join(root,p)))])));const report={scope:'actual built map/classic normal course + existing IDB guarded writer; native input/download/file restore; fresh synthetic isolated Chrome profile',base:'424efc1869e98cd7b19afd2c1ab7cab0e8380b4b',origin,checks,passed:checks.filter(c=>c.ok).length,failed:checks.filter(c=>!c.ok).length,driverExitedWithError:!!process.exitCode,RuntimeExceptions:errors,requests,sourceSha256:hashes,unverified:['published origin','natural retention','physical phone','actual Bilibili playback/audio','video summaries','learning gain'],retries};await writeFile(join(proof,'browser-report.json'),JSON.stringify(report,null,2)+'\n');await writeFile(join(root,'course-video/qa/browser-report.json'),JSON.stringify(report,null,2)+'\n');await writeFile(join(work,'latest-proof.txt'),proof+'\n');for(const tab of tabs)tab.close();browser?.close();if(chrome){const exited=new Promise(r=>{if(chrome.exitCode!==null)r();else chrome.once('exit',r)});chrome.kill('SIGTERM');await exited}if(server)await new Promise(r=>server.close(r));await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100});console.log(JSON.stringify({proof,passed:report.passed,failed:report.failed,exceptions:errors.length,driverExitedWithError:report.driverExitedWithError}))}
