/** Actual built map/course entry with fresh synthetic Chrome profile and native input.
 * Only QA-origin records are read; no real user profile, recording or clock changes. */
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {mkdir,mkdtemp,readFile,readdir,writeFile,stat,rm} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {join,resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {getCourseBinding} from '../../course-loop/registry.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url));
const work=join(root,'work/course-video-browser');await mkdir(work,{recursive:true});
const proof=await mkdtemp(join(work,'native-')),profile=join(proof,'profile'),downloads=join(proof,'downloads');await mkdir(downloads);
const assetRoot=join(root,'dist-online'),checks=[],errors=[],requests=[],retries=[];let chrome,server,browser,tabs=[],origin,debugPort;
const sha=data=>createHash('sha256').update(data).digest('hex'),delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(predicate,label,limit=200){for(let i=0;i<limit;i++){try{if(await predicate())return}catch(error){if(!/Inspected target navigated|Execution context was destroyed|Cannot find context/.test(String(error)))throw error;retries.push({kind:'navigation context readiness',label,error:String(error)})}await delay(30)}throw Error('Timeout: '+label)}
async function connect(url){const ws=new WebSocket(url),pending=new Map();let sequence=0;await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j});ws.onmessage=e=>{const m=JSON.parse(String(e.data));if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}};return {close:()=>ws.close(),send:(method,params={})=>new Promise((r,j)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);j(Error('CDP timeout '+method))},15000);pending.set(id,{resolve:r,reject:j,timer});ws.send(JSON.stringify({id,method,params}))})}}
async function evaluate(tab,expression){const r=await tab.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value}
async function newTab(url){const {targetId}=await browser.send('Target.createTarget',{url:'about:blank'});const list=await fetch(`http://127.0.0.1:${debugPort}/json/list`).then(r=>r.json()),entry=list.find(x=>x.id===targetId);const tab=await connect(entry.webSocketDebuggerUrl);tab.targetId=targetId;tabs.push(tab);await tab.send('Runtime.enable');await tab.send('Page.enable');await tab.send('DOM.enable');await tab.send('Emulation.setDeviceMetricsOverride',{width:1100,height:850,deviceScaleFactor:1,mobile:false});await navigate(tab,url);return tab}
async function navigate(tab,path){const url=path.startsWith('http')?path:origin+path,current=new URL(await evaluate(tab,'location.href')),target=new URL(url);if(current.href!==url){if(current.origin===target.origin&&current.pathname===target.pathname&&current.search===target.search)await evaluate(tab,`location.hash=${JSON.stringify(target.hash)}`);else await tab.send('Page.navigate',{url})}await until(()=>evaluate(tab,`document.readyState==='complete'&&!!document.querySelector('#root')`),'page ready')}
const selectorExpression=(selector,text)=>`[...document.querySelectorAll(${JSON.stringify(selector)})].find(e=>${text===undefined?'true':`e.textContent.trim()===${JSON.stringify(text)}`})`;
async function click(tab,selector,text){await browser.send('Target.activateTarget',{targetId:tab.targetId});const expression=selectorExpression(selector,text);await until(()=>evaluate(tab,`(()=>{const e=${expression};return !!e&&!e.disabled&&!!e.getClientRects().length})()`),'enabled control '+(text||selector));await evaluate(tab,`(${expression}).scrollIntoView({block:'center'})`);let point,previous,stable=0;for(let frame=0;frame<30;frame++){await delay(30);point=await evaluate(tab,`(()=>{const e=${expression},r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);stable=previous&&Math.abs(previous.x-point.x)<0.2&&Math.abs(previous.y-point.y)<0.2?stable+1:0;previous=point;if(stable>=2)break}await tab.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await tab.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point})}
async function type(tab,selector,value){for(let attempt=0;attempt<5;attempt++){await click(tab,selector);await delay(90);if(await evaluate(tab,`document.activeElement===document.querySelector(${JSON.stringify(selector)})`))break;retries.push({kind:'await native field focus after heading readiness',selector,attempt});if(attempt===4)throw Error('Native field focus did not settle')}await tab.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:process.platform==='darwin'?4:2,commands:['selectAll']});await tab.send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:process.platform==='darwin'?4:2});await tab.send('Input.insertText',{text:value});try{await until(()=>evaluate(tab,`document.querySelector(${JSON.stringify(selector)})?.value===${JSON.stringify(value)}`),'native input value')}catch(error){await writeFile(join(proof,'typing-failure.json'),JSON.stringify({selector,expected:value,actual:await evaluate(tab,`({value:document.querySelector(${JSON.stringify(selector)})?.value,active:document.activeElement?.outerHTML,hasFocus:document.hasFocus(),phase:document.querySelector('.course-loop')?.dataset.phase,course:document.querySelector('.course-loop')?.dataset.course,errors:[...document.querySelectorAll('[role=alert]')].map(e=>e.innerText)})`),state:await qaState(tab)},null,2));throw error}}
async function qaState(tab){return evaluate(tab,`new Promise((resolve,reject)=>{const q=indexedDB.open('english-studio-offline',1);q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result,r=db.transaction('state').objectStore('state').get('current');r.onsuccess=()=>{resolve(r.result);db.close()};r.onerror=()=>{reject(r.error);db.close()}}})`)}
async function saved(tab,id,predicate){const key=getCourseBinding(id).key;await until(async()=>{const s=await qaState(tab);if(!s?.drafts?.[key])return false;const parsed=getCourseBinding(id).model.restore(s.drafts[key],Date.now());return parsed.ok&&predicate(parsed.view,s)},'confirmed selected save '+id)}
async function course(tab,id){await navigate(tab,`/map/#/learn/${id}?access=1`);await until(()=>evaluate(tab,`document.querySelector('.course-loop')?.dataset.course===${JSON.stringify(id)}&&!document.querySelector('.course-loop-error')&&!!document.querySelector('.course-loop-card')`),'course '+id)}
async function screenshot(tab,name){const shot=await tab.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(join(proof,name),Buffer.from(shot.data,'base64'))}
async function check(name,run){const started=Date.now();try{const detail=await run();checks.push({name,ok:true,elapsedMs:Date.now()-started,...(detail?{detail}:{})});console.log('PASS '+name)}catch(error){checks.push({name,ok:false,error:String(error),elapsedMs:Date.now()-started});throw error}}
async function backup(tab,label){await navigate(tab,'/#/progress');await until(()=>evaluate(tab,`!!document.querySelector('button[aria-label="进度备份与恢复"]')&&!document.querySelector('button[aria-label="进度备份与恢复"]').disabled`),'backup ready');const before=new Set(await readdir(downloads));await click(tab,'button[aria-label="进度备份与恢复"]');await click(tab,'[role="dialog"] button','保存进度到本地');let filename;await until(async()=>{filename=(await readdir(downloads)).find(n=>!before.has(n)&&n.endsWith('.json'));return !!filename},'native download');const bytes=await readFile(join(downloads,filename));const copy=join(proof,label+'.json');await writeFile(copy,bytes);await closeDialog(tab);return {file:copy,value:JSON.parse(bytes),sha256:sha(bytes)}}
async function closeDialog(tab){if(await evaluate(tab,`!!document.querySelector('[role="dialog"]')`)){await tab.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await tab.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await until(()=>evaluate(tab,`!document.querySelector('[role="dialog"]')`),'dialog close')}}
async function restore(tab,file){await navigate(tab,'/#/progress');await until(()=>evaluate(tab,`!!document.querySelector('button[aria-label="进度备份与恢复"]')&&!document.querySelector('button[aria-label="进度备份与恢复"]').disabled`),'restore ready');await click(tab,'button[aria-label="进度备份与恢复"]');await click(tab,'[role="dialog"] button','从文件恢复进度');const {root:doc}=await tab.send('DOM.getDocument',{depth:-1,pierce:true}),{nodeId}=await tab.send('DOM.querySelector',{nodeId:doc.nodeId,selector:'[role="dialog"] input[type="file"]'});assert.ok(nodeId);await tab.send('DOM.setFileInputFiles',{nodeId,files:[file]});await click(tab,'[role="dialog"] button','确认替换并恢复');await until(()=>evaluate(tab,`document.querySelector('[role="dialog"] .progress-save-receipt')?.textContent.includes('已恢复')&&[...document.querySelectorAll('[role="dialog"] button')].some(b=>b.textContent.trim()==='保存进度到本地'&&!b.disabled)`),'restore receipt');await closeDialog(tab)}
async function key(tab,key,code=key){const windowsVirtualKeyCode={Home:36,ArrowDown:40,ArrowUp:38,Enter:13,Escape:27}[key];await tab.send('Input.dispatchKeyEvent',{type:'rawKeyDown',key,code,windowsVirtualKeyCode});await tab.send('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode})}
async function part(tab,index){const selector='.course-video-segments button:nth-child('+(index+1)+')';await click(tab,selector);await until(()=>evaluate(tab,`document.querySelector(${JSON.stringify(selector)})?.getAttribute('aria-pressed')==='true'`),'native selected part');await until(()=>evaluate(tab,`document.querySelector('.course-video-note textarea')&&!document.querySelector('.course-video-note textarea').disabled`),'note ready')}
async function toLearn(tab,id){await course(tab,id);if(await evaluate(tab,`document.querySelector('.course-loop')?.dataset.phase==='diagnostic'`))for(let i=0;i<3;i++){await click(tab,'.course-loop button','暂时不会，先记下');await click(tab,'.course-loop button',i===2?'看针对性讲解':'下一题')}await until(()=>evaluate(tab,`document.querySelector('.course-loop')?.dataset.phase==='learn'&&!!document.querySelector('.course-video-note textarea')&&!document.querySelector('.course-video-note textarea').disabled`),'learning help '+id)}
const nk=(course,p,lesson)=>`course-video-notes-v1:${course}:NCE1:${lesson}:BV1xa411J7jJ:${p}`;
async function prepareOriginal(tab){if(await evaluate(tab,`!!document.querySelector('.course-video [data-prepare-original]')`))await click(tab,'.course-video [data-prepare-original]');await until(()=>evaluate(tab,`!!document.querySelector('.course-video-note a[href*="/video/"]')`),'confirmed original link')}
async function noteSaved(tab,key,text){await until(async()=>{const s=await qaState(tab);return s?.drafts?.[key]&&JSON.parse(s.drafts[key]).text===text},'real persisted video note')}
try{
 server=createServer(async(req,res)=>{try{const path=decodeURIComponent(new URL(req.url,'http://localhost').pathname);let file;if(path==='/map/'||path==='/map/index.html')file=join(root,'map/dist/index.html');else if(path.startsWith('/map/assets/'))file=join(root,'map/dist',path.slice(5));else if(path==='/'||path==='/index.html'||path==='/standalone.html')file=join(root,'static-export/standalone.html');else if(path.startsWith('/assets/'))file=join(root,'static-export',path.slice(1));else if(/^\/(language|materials|illustrations|comics|lesson-pages)\//.test(path)||path==='/favicon.svg')file=join(assetRoot,path.slice(1));else{res.writeHead(404);res.end();return}const roots=[join(root,'map/dist'),join(root,'static-export'),assetRoot];assert.ok(roots.some(r=>resolve(file).startsWith(r+'/')));const s=await stat(file);requests.push({path,size:s.size});const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.bin':'application/octet-stream'}[extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':mime,'Content-Length':s.size,'Cache-Control':'no-store'});createReadStream(file).pipe(res)}catch(error){res.writeHead(404);res.end(String(error))}});await new Promise((r,j)=>{server.once('error',j);server.listen(0,'127.0.0.1',r)});origin=`http://127.0.0.1:${server.address().port}`;
 chrome=spawn(process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','pipe']});let chromeError;chrome.once('error',e=>chromeError=e);await until(async()=>{if(chromeError)throw chromeError;try{return !!(await readFile(join(profile,'DevToolsActivePort'),'utf8'))}catch{return false}},'isolated Chrome endpoint');const [port,path]=(await readFile(join(profile,'DevToolsActivePort'),'utf8')).trim().split('\n');debugPort=port;browser=await connect(`ws://127.0.0.1:${port}${path}`);await browser.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads,eventsEnabled:true});const tab=await newTab('/map/');


 async function classic(tab,book,lesson){await navigate(tab,`/#/nce/${book}/${lesson}?tab=grammar`);await until(()=>evaluate(tab,`!!document.querySelector('.course-video textarea')&&!document.querySelector('.course-video textarea').disabled`),'classic teaching note ready '+book+lesson)}
 const thirdKey='course-video-notes-v1:nce3-1:NCE3:1:BV1zY4y187cK:2',secondKey='course-video-notes-v1:nce2-1:NCE2:1:BV1cu411r7pw:3';
 await check('actual older NCE2 map teaching and classic NCE3 grammar receive exact verified source and independent notes',async()=>{await navigate(tab,'/map/#/learn/nce2-1?access=1');await until(()=>evaluate(tab,`!!document.querySelector('.course-video textarea')&&!document.querySelector('.course-video textarea').disabled`),'old NCE2 map note');await prepareOriginal(tab);assert.equal(await evaluate(tab,`document.querySelector('.course-video-note a[href*="/video/"]').href`),'https://www.bilibili.com/video/BV1cu411r7pw/?p=3');await type(tab,'.course-video textarea','合成第二册真实入口笔记');await noteSaved(tab,secondKey,'合成第二册真实入口笔记');await classic(tab,'NCE3',1);await prepareOriginal(tab);assert.equal(await evaluate(tab,`document.querySelector('.course-video-note a[href*="/video/"]').href`),'https://www.bilibili.com/video/BV1zY4y187cK/?p=2');await type(tab,'.course-video textarea','合成第三册真实入口笔记');await noteSaved(tab,thirdKey,'合成第三册真实入口笔记');await screenshot(tab,'classic-third-book.png')});
 await check('native classic recall draft survives interleaved video note writes and remains in same-page backup',async()=>{await click(tab,'button[role="tab"]','3 练习');await until(()=>evaluate(tab,`!!document.querySelector('.learning-practice')`),'practice for unrelated recall draft');await click(tab,'details > summary','再用课文原句做填空（可选）');await type(tab,'.lesson-recall input[aria-label="第 1 题填空"]','synthetic-recall');await until(async()=>{const state=await qaState(tab);return state?.drafts?.['nce-recall-NCE3-1']?.includes('synthetic-recall')},'native unrelated recall saved');await classic(tab,'NCE3',1);await type(tab,'.course-video textarea','合成第三册交错保存笔记');await noteSaved(tab,thirdKey,'合成第三册交错保存笔记');assert.ok((await qaState(tab)).drafts['nce-recall-NCE3-1'].includes('synthetic-recall'))});
 await check('same-page actual ProgressSave downloads confirmed video draft alongside unrelated second-course note',async()=>{const before=new Set(await readdir(downloads));await click(tab,'button[aria-label="进度备份与恢复"]');await click(tab,'[role="dialog"] button','保存进度到本地');let filename;await until(async()=>{filename=(await readdir(downloads)).find(n=>!before.has(n)&&n.endsWith('.json'));return !!filename},'same page native backup');const bytes=await readFile(join(downloads,filename)),backup=JSON.parse(bytes);assert.equal(JSON.parse(backup.state.drafts[thirdKey]).text,'合成第三册交错保存笔记');assert.ok(backup.state.drafts['nce-recall-NCE3-1'].includes('synthetic-recall'));assert.equal(JSON.parse(backup.state.drafts[secondKey]).text,'合成第二册真实入口笔记');await writeFile(join(proof,'same-page-progress.json'),bytes);await closeDialog(tab);return {bytes:bytes.length,sha256:sha(bytes)}});
 await check('normal classic tab switch waits for unsaved note, practice renders no video notes',async()=>{await type(tab,'.course-video textarea','合成切到练习前最后一稿');await click(tab,'button[role="tab"]','3 练习');await until(()=>evaluate(tab,`location.hash.includes('tab=practice')&&!!document.querySelector('.learning-practice')`),'practice tab');assert.equal(await evaluate(tab,`document.querySelectorAll('.course-video textarea').length`),0);assert.equal(JSON.parse((await qaState(tab)).drafts[thirdKey]).text,'合成切到练习前最后一稿');await classic(tab,'NCE3',1)});
 const miniHash='#/mini-task/mini-n1-03';
 await check('video notes to actual mini and placement routes save before leaving; module guards remain active',async()=>{await type(tab,'.course-video textarea','合成切到mini前的笔记');await evaluate(tab,`location.hash=${JSON.stringify(miniHash)}`);await until(()=>evaluate(tab,`!!document.querySelector('[data-mini-host]')`),'actual mini host');assert.equal(JSON.parse((await qaState(tab)).drafts[thirdKey]).text,'合成切到mini前的笔记');await evaluate(tab,`location.hash='#/placement'`);await until(()=>evaluate(tab,`!!document.querySelector('[data-placement-host] .placement')`),'actual placement host');await classic(tab,'NCE3',1);await type(tab,'.course-video textarea','合成切到placement前的笔记');await evaluate(tab,`location.hash='#/placement'`);await until(()=>evaluate(tab,`!!document.querySelector('[data-placement-host] .placement')`),'actual placement host after video');assert.equal(JSON.parse((await qaState(tab)).drafts[thirdKey]).text,'合成切到placement前的笔记');await classic(tab,'NCE3',1)});
 await check('synthetic writer failure blocks actual mini/placement and native Back while keeping current text/hash',async()=>{await evaluate(tab,`window.__videoQAOriginalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='state')throw new DOMException('Synthetic note writer failure','QuotaExceededError');return window.__videoQAOriginalPut.apply(this,args)}`);await type(tab,'.course-video textarea','合成保存失败的私有笔记');await until(()=>evaluate(tab,`document.querySelector('.course-video [role="alert"]')?.innerText.includes('Synthetic')`),'actual writer injected failure');for(const target of [miniHash,'#/placement']){await evaluate(tab,`location.hash=${JSON.stringify(target)}`);await until(()=>evaluate(tab,`location.hash==='#/nce/NCE3/1?tab=grammar'`),'refused module route '+target);assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),'合成保存失败的私有笔记');assert.equal(await evaluate(tab,`document.querySelectorAll('[data-mini-host],[data-placement-host]').length`),0)}const historyEntries=await tab.send('Page.getNavigationHistory');if(historyEntries.currentIndex>0){await tab.send('Page.navigateToHistoryEntry',{entryId:historyEntries.entries[historyEntries.currentIndex-1].id});await until(()=>evaluate(tab,`location.hash==='#/nce/NCE3/1?tab=grammar'&&!!document.querySelector('.course-video textarea')`),'native Back refusal')}await screenshot(tab,'classic-failed-save-retained.png');await evaluate(tab,`IDBObjectStore.prototype.put=window.__videoQAOriginalPut;delete window.__videoQAOriginalPut`);await click(tab,'.course-video button','重试保存笔记');await noteSaved(tab,thirdKey,'合成保存失败的私有笔记');return {failure:'injected only into isolated synthetic QA IDB put; not a real quota claim'}});
 await check('successful native Back and next lesson preserve saved notes and isolate course identity',async()=>{await type(tab,'.course-video textarea','合成自然Back前保存');await click(tab,'.nce-lesson-footer button','下一课');await until(()=>evaluate(tab,`location.hash.includes('/NCE3/2')&&document.querySelectorAll('.course-video textarea').length===0`),'next course default listening');await click(tab,'button[role="tab"]','2 讲解');await until(()=>evaluate(tab,`document.querySelector('.course-video-byline')?.innerText.includes('第 2 课')&&!document.querySelector('.course-video textarea')?.disabled`),'second course teaching');assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),'');const historyEntries=await tab.send('Page.getNavigationHistory');await tab.send('Page.navigateToHistoryEntry',{entryId:historyEntries.entries.slice(0,historyEntries.currentIndex).filter(e=>e.url.includes('/NCE3/1?tab=grammar')).at(-1).id});await until(()=>evaluate(tab,`location.hash.includes('/NCE3/1')&&document.querySelector('.course-video-byline')?.innerText.includes('第 1 课')&&!document.querySelector('.course-video textarea')?.disabled`),'native Back accepted');assert.equal(await evaluate(tab,`document.querySelector('.course-video textarea').value`),'合成自然Back前保存')});
 await check('no verified videos for NCE3 lesson48 or NCE4; original teaching continues',async()=>{for(const [book,lesson] of [['NCE3',48],['NCE4',1]]){await navigate(tab,`/#/nce/${book}/${lesson}?tab=grammar`);await until(()=>evaluate(tab,`!!document.querySelector('.nce-studio.is-lesson')&&document.querySelectorAll('.course-video textarea').length===0`),'unmapped course');assert.equal(await evaluate(tab,`document.querySelectorAll('.course-video-note a[href*="bilibili"],.course-video textarea').length`),0)}});
 assert.equal(errors.length,0,'main application Runtime exceptions');
}catch(error){console.error(error);process.exitCode=1;const tab=tabs.at(-1);if(tab){await screenshot(tab,'failure.png').catch(()=>{});await writeFile(join(proof,'failure-dom.txt'),await evaluate(tab,`document.body.innerText`).catch(()=>''))}}
finally{const sourceFiles=['course-video/ui.tsx','course-video/controller.ts','course-video/adapter.ts','course-video/manifest.ts','course-video/notes.ts','course-video/sources.json','app/course-loop-ui.tsx','course-loop/model.mjs','course-loop/host-contract.d.ts','app/offline-store.ts'];const hashes=Object.fromEntries(await Promise.all(sourceFiles.map(async p=>[p,sha(await readFile(join(root,p)))])));const report={scope:'actual built map/classic normal course + existing IDB guarded writer; native input/download/file restore; fresh synthetic isolated Chrome profile',base:'bd5d1f731dc4c2d7e1cf213485c75af903d47fa1',origin,checks,passed:checks.filter(c=>c.ok).length,failed:checks.filter(c=>!c.ok).length,driverExitedWithError:!!process.exitCode,RuntimeExceptions:errors,requests,sourceSha256:hashes,unverified:['published origin','natural retention','physical phone','actual Bilibili playback/audio','video summaries','learning gain'],retries};await writeFile(join(proof,'browser-report.json'),JSON.stringify(report,null,2)+'\n');await writeFile(join(root,'course-video/qa/integrated-browser-report.json'),JSON.stringify(report,null,2)+'\n');await writeFile(join(work,'latest-proof.txt'),proof+'\n');for(const tab of tabs)tab.close();browser?.close();if(chrome){const exited=new Promise(r=>{if(chrome.exitCode!==null)r();else chrome.once('exit',r)});chrome.kill('SIGTERM');await exited}if(server)await new Promise(r=>server.close(r));await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100});console.log(JSON.stringify({proof,passed:report.passed,failed:report.failed,exceptions:errors.length,driverExitedWithError:report.driverExitedWithError}))}
