import type { CodeEvidence } from './types';
const both = ['academic', 'general-training'] as const;
const a = ['academic'] as const;
const g = ['general-training'] as const;
const numbered = (prefix: string, numbers: number[]) => numbers.map(n => `${prefix}${n}`);
const allWriting = ['W-TA-A', 'W-TA-GT', 'W-TR-A', 'W-TR-GT', 'W-CC-A', 'W-CC-GT', 'W-LR-A', 'W-LR-GT', 'W-GRA-A', 'W-GRA-GT'];

/** Audited against e2efbd3. WIP in other worktrees is intentionally absent. */
export const codeEvidence: readonly CodeEvidence[] = [
  { id: 'l-bank', path: 'app/data/ielts.json', symbol: 'listening.questions', anchor: '"id":"ielts-l1"', scope: 'local-practice', stages: ['explain', 'independent', 'feedback', 'review'], variants: both, supports: ['L01'], rights: 'original-declared', artifactIds: numbered('ielts-l', [1,2,3,4,5,6,7,8]), limitation: '同一段TTS对话8道单选；说明/答案解释已有，没有解题示范、引导或鲜题库；重播/原文/先看反馈不记录；复做缺音频上下文。' },
  { id: 'r-mc-bank', path: 'app/data/ielts.json', symbol: 'reading.questions (MC)', anchor: '"id":"ielts-r1"', scope: 'local-practice', stages: ['explain', 'independent', 'timed', 'feedback', 'review'], variants: a, supports: ['R01-A'], rights: 'original-declared', artifactIds: numbered('ielts-r', [1,3,5,8]), limitation: '同一短篇4道单选；只有建议12分钟计时，中文提示/逐题答案开放；错题复做无原文。短篇只是Academic衔接，非完整考试语境。' },
  { id: 'r-tfng-bank', path: 'app/data/ielts.json', symbol: 'reading.questions (TFNG)', anchor: '"id":"ielts-r2"', scope: 'local-practice', stages: ['explain', 'independent', 'timed', 'feedback', 'review'], variants: a, supports: ['R03-A'], rights: 'original-declared', artifactIds: numbered('ielts-r', [2,4,6,7]), limitation: '单篇4道TFNG；无独立新套/完整卷/有效延迟迁移；不能把重复已知题认定为保持。' },
  { id: 'l-mini', path: 'app/ielts-journey-content.ts', symbol: 'hear-correction', anchor: "mini('hear-correction'", scope: 'foundation', stages: ['explain', 'model', 'guided', 'independent', 'feedback', 'review'], variants: both, supports: ['L01'], rights: 'original-declared', artifactIds: ['hear-correction'], limitation: '旧经典路线：1示范/1引导选择/3文本短核对；主地图没有该节点。只是改口桥接，3文本回忆题不是音频听力题。' },
  { id: 'r-mini', path: 'app/ielts-journey-content.ts', symbol: 'read-evidence', anchor: "mini('read-evidence'", scope: 'foundation', stages: ['explain', 'model', 'guided', 'independent', 'feedback', 'review'], variants: both, supports: ['R03-A', 'R03-GT'], rights: 'original-declared', artifactIds: ['read-evidence'], limitation: '旧经典路线1示范/1引导/3短句核对；主地图未接。基础证据/矛盾/缺失识别，不能证明两种正式文本或评分覆盖。' },
  { id: 'w1', path: 'app/data/ielts.json', symbol: 'writing.ielts-w1', anchor: '"id":"ielts-w1"', scope: 'local-practice', stages: ['explain', 'model', 'independent', 'timed', 'feedback'], variants: a, supports: ['W-TA-A','W-CC-A','W-LR-A','W-GRA-A','WA-TABLE','W-FORMAT-A'], rights: 'original-declared', artifactIds: ['ielts-w1'], limitation: '1静态表格/1原创未评分参考/草稿/自查；无带注解示范、逐步产出、真人评分或新题复验。计时可暂停重置。' },
  { id: 'w2', path: 'app/data/ielts.json', symbol: 'writing.ielts-w2', anchor: '"id":"ielts-w2"', scope: 'local-practice', stages: ['explain', 'model', 'independent', 'timed', 'feedback'], variants: g, supports: ['W-TA-GT','W-CC-GT','W-LR-GT','W-GRA-GT','WG-FORMAL','WG-REQUEST','WG-INFORM','W-FORMAT-GT'], rights: 'original-declared', artifactIds: ['ielts-w2'], limitation: '1正式情境请求信/1原创未评分参考；地图未接，缺半正式/个人场景、完整书信练习链及延迟鲜题。' },
  { id: 'w3', path: 'app/data/ielts.json', symbol: 'writing.ielts-w3', anchor: '"id":"ielts-w3"', scope: 'local-practice', stages: ['explain', 'model', 'independent', 'timed', 'feedback'], variants: both, supports: ['W-TR-A','W-TR-GT','W-CC-A','W-CC-GT','W-LR-A','W-LR-GT','W-GRA-A','W-GRA-GT','WT-DISCUSS','WT-OPINION','W-FORMAT-A','W-FORMAT-GT'], rights: 'original-declared', artifactIds: ['ielts-w3'], limitation: '1双边讨论+个人观点题/1原创未评分参考；适用两种essay准备，但不能覆盖所有题目命令、语体或混合题。' },
  { id: 'w-mini-overview', path: 'app/ielts-journey-content.ts', symbol: 'write-overview', anchor: "mini('write-overview'", scope: 'foundation', stages: ['explain','model','guided','independent','feedback','review'], variants: a, supports: ['W-TA-A'], rights: 'original-declared', artifactIds: ['write-overview'], limitation: '1示范/1选择跟练/3词语核对；只有文字数据，无真实线图/表格视觉，不能作为这些题型的专门素材。' },
  { id: 'w-mini-reason', path: 'app/ielts-journey-content.ts', symbol: 'write-reason', anchor: "mini('write-reason'", scope: 'foundation', stages: ['explain','model','guided','independent','feedback','review'], variants: both, supports: ['W-TR-A','W-TR-GT','WT-OPINION','WT-DISCUSS'], rights: 'original-declared', artifactIds: ['write-reason'], limitation: '原因/例子桥接，1示范/1引导/3填词；不能作为议论文展开或独立写作成功。' },
  { id: 's1', path: 'app/data/ielts.json', symbol: 'speaking Part 1 fallback', anchor: '"id":"ielts-s1"', scope: 'local-practice', stages: ['explain','independent','timed','feedback'], variants: both, supports: ['S-P1','S-FC','S-LR','S-GRA','S-P'], rights: 'original-declared', artifactIds: ['ielts-s1','ielts-s2'], limitation: '2原创短问、提示、录音/单题训练计时、自查；没有陌生互动或四维真实评阅。' },
  { id: 's2', path: 'app/data/ielts.json', symbol: 'speaking Part 2 fallback', anchor: '"id":"ielts-s3"', scope: 'local-practice', stages: ['explain','independent','timed','feedback'], variants: both, supports: ['S-P2','S-FC','S-LR','S-GRA','S-P'], rights: 'original-declared', artifactIds: ['ielts-s3','ielts-s4'], limitation: '2原创长答题、1分钟准备/2分钟练习和录音；无完整3–4分钟part含追问、维度反馈或新题延迟复验。' },
  { id: 's3', path: 'app/data/ielts.json', symbol: 'speaking Part 3 fallback', anchor: '"id":"ielts-s5"', scope: 'local-practice', stages: ['explain','independent','timed','feedback'], variants: both, supports: ['S-P3','S-FC','S-LR','S-GRA','S-P'], rights: 'original-declared', artifactIds: ['ielts-s5','ielts-s6'], limitation: '2原创讨论问；单题75秒是教学建议，不是Part3完整互动；缺意外追问。' },
  { id: 's-coach', path: 'app/speaking-bank.tsx', symbol: 'SpeakingCoach / models', anchor: 'function SpeakingCoach(', scope: 'local-practice', stages: ['explain','model','guided','independent','timed','feedback','review'], variants: both, supports: ['S-P1','S-P2','S-P3','S-FC','S-LR','S-GRA'], rights: 'original-declared', artifactIds:['speaking-model-1','speaking-model-2','speaking-model-3'], limitation: '3本站通用组织骨架及四阶段UI已编写，不是带完整评分注解的口头表现模型。历史题库单列待核，不计鲜题数量。文本反馈不评发音/语流，手动再说没有延迟迁移记录。' },
  { id: 's-history', path: 'scripts/package-speaking.py', symbol: 'historical bank packaging', anchor: '按学习者提供的 Part 1–3 题库整理', scope: 'local-practice', stages: [], variants: both, supports: [], rights: 'learner-provided-unverified', limitation: '66组/238题是脚本声明；当前基线无已打包payload，来源权利待核，不用其数量认证新题覆盖。' },
  { id: 's-mini', path: 'app/ielts-journey-content.ts', symbol: 'speak-detail', anchor: "mini('speak-detail'", scope: 'foundation', stages: ['explain','model','guided','independent','feedback','review'], variants: both, supports: ['S-P1','S-FC'], rights: 'original-declared', artifactIds: ['speak-detail'], limitation: '旧经典路线1结构示范/1跟练/3短词核对；不是自发口语或语流证据。' },
  { id: 'rubric-overview', path: 'app/data/ielts.json', symbol: 'facts: scoring', anchor: '"title":"口语：四个评分维度"', scope: 'local-practice', stages: ['explain'], variants: both, supports: ['S-FC','S-LR','S-GRA','S-P',...allWriting,'L-MARKING','R-MARKING-A','R-MARKING-GT'], rights: 'not-a-content-bank', limitation: '简短维度/换分说明，未有各维度的行为示范、评分演练或全面band导读。' },
  { id: 'format-overview', path: 'app/data/ielts.json', symbol: 'facts: overview / skill formats', anchor: '"title":"先选对考试类别"', scope: 'local-practice', stages: ['explain'], variants: both, supports: ['L-FORMAT','R-FORMAT-A','R-FORMAT-GT','S-FULL','W-FORMAT-A','W-FORMAT-GT'], rights: 'not-a-content-bank', limitation: '概览文字存在，默认地图仍为Academic；没有验证用户目标、完整练习条件或新模式交付教学。' },
  { id: 'map-handoff', path: 'map/learning.tsx', symbol: 'EvidenceForm', anchor: 'function EvidenceForm(', scope: 'external-handoff', stages: ['independent','timed','feedback','review'], variants: a, supports: ['L-FORMAT','R-FORMAT-A','S-FULL','S-FC','S-LR','S-GRA','S-P','W-FORMAT-A','W-TA-A','W-TR-A','W-CC-A','W-LR-A','W-GRA-A'], rights: 'link-only', limitation: '外部作答/评阅/复验自录表单，无法核验实际素材或评价；不是站内内容或真实学习效果。当前模考限定Academic。' },
  { id: 'map-navigation', path: 'map/content.ts', symbol: 'nodes / questionsFor', anchor: 'const exits: string[] = [];', scope: 'navigation', stages: [], variants: a, supports: [], rights: 'not-a-content-bank', limitation: '32overview节点含12四科task、两模考与终点；位置真实存在，task的questionsFor为空。' },
  { id: 'nce-foundation', path: 'map/lesson-plan.ts', symbol: 'lessonPlan', anchor: 'export function lessonPlan(', scope: 'foundation', stages: [], variants: both, supports: [], rights: 'not-a-content-bank', limitation: '168NCE单元可补词句；没有逐单元核实IELTS依赖，不批量贴满官方覆盖标签。' },
  { id: 'ielts-ui', path: 'app/ielts.tsx', symbol: 'IELTS / Writing / Speaking', anchor: 'export default function IELTS(', scope: 'local-practice', stages:['explain','model','independent','timed','feedback'], variants:both, supports:[], rights:'not-a-content-bank', limitation:'实际数据展示、浏览器TTS、阅读/写作/备用口语工具；可见提示和反复计时不形成考试证据。' },
  { id: 'quiz-ui', path: 'app/learning.tsx', symbol: 'Quiz', anchor:'export function Quiz(', scope:'local-practice', stages:['independent','feedback','review'], variants:both, supports:[], rights:'not-a-content-bank', limitation:'逐题答案解释与同题重练，没有材料上下文传递或新套保持。' },
  { id: 'mistakes-ui', path:'app/study-app.tsx', symbol:'quizItems / review', anchor:'quizItems', scope:'local-practice', stages:['review'], variants:both, supports:[], rights:'not-a-content-bank', limitation:'共用Question复做不携带passage/audio引用，不能当听读有效复验。' },
  { id:'timer-ui', path:'app/timer.tsx', symbol:'Timer', anchor:'export function Timer(', scope:'local-practice', stages:['timed'], variants:both, supports:[], rights:'not-a-content-bank', limitation:'可暂停/重置，到时提醒；不锁卷或保存实际时长。' },
];

// Runtime dependencies are also code evidence; data alone does not prove a runnable activity.
for (const e of codeEvidence) {
  if (['l-bank','r-mc-bank','r-tfng-bank'].includes(e.id)) e.runtimeRefs=['ielts-ui','quiz-ui','mistakes-ui',...(e.id==='l-bank'?[]:['timer-ui'])];
  if (['w1','w2','w3','s1','s2','s3'].includes(e.id)) e.runtimeRefs=['ielts-ui','timer-ui'];
}

export const baselineInventory = {
  listening: { itemIds: numbered('ielts-l', [1,2,3,4,5,6,7,8]), contexts: 1, prerecordedAudioFilesVerified: 0, delivery: 'device-tts-repeatable' },
  reading: { multipleChoiceItemIds: numbered('ielts-r', [1,3,5,8]), identifyingInformationItemIds: numbered('ielts-r', [2,4,6,7]), passages: 1, dedicatedGeneralTrainingPassages: 0 },
  writing: { promptIds: ['ielts-w1','ielts-w2','ielts-w3'], referenceModels: 3, examinerRatedModels: 0 },
  speaking: { originalFallbackPromptIds: numbered('ielts-s', [1,2,3,4,5,6]), organisationModels: 3, prerecordedPerformanceModelsVerified: 0, declaredHistoricalBankPrompts: 238, verifiedPackagedHistoricalBankPrompts: null, historicalRights: 'learner-provided-unverified' },
  map: { overviewStations: 32, nceUnits: 168, skillAssignmentStations: 12, completeMockHandoffs: 2, officialResultRecord: 1, inlineIeltsQuestionItems: 0 },
  evidenceBoundary: '数量是已编写素材/工具盘点，重叠引用不可相加；未运行真人项目QA的量为未知，未验证任何用户的新题迁移/延迟保持。',
} as const;
